### PR TITLE
Preparing release version 5.3.4

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
> Not really a hotfix release since it includes other changes from master, but those hopefully cause not any other problems.

Indeed, but none of them were really user facing, but no worries, I won't call it a hotfix release then.

> (I would have branched off e1298fa (the merge of 544b4a1 (5.3.3)) for this)

I prefer to make the release off the current master, to keep history concise, but thanks for the suggestion.

**Comment by blueyed** [comment]
@nicoddemus 
> I prefer to make the release off the current master, to keep history concise

Why would the history be not concise?
Your argument would make sense in case we would just tag current master, but since you are going through a branch for the release anyway I cannot follow.

**Comment by nicoddemus** [comment]
Oh I misunderstood your suggestion earlier, I thought you meant to make a branch reverting the original merge, and throw away that branch after the release.

But reading it again I see you meant to create a branch right after 5.3.3, revert the merge commit there, and then merge it into `master`. Yeah I agree that would have been cleaner, my apologies.

**Comment by blueyed** [comment]
@nicoddemus please merge master into features.

**Comment by nicoddemus** [comment]
Sure, done, thanks for the remainder.

**Pull request merged**
