### PR TITLE
[WIP] TerminalReporter.section: start on new line

### PR DESCRIPTION
**Pull request by blueyed**
TODO:

- [ ] https://github.com/blueyed/pytest/pull/185

### CODE REVIEW

**Comment by blueyed** [comment]
I've updated it according to the idea:

> Note that there is `ensure_newline`, which uses `currentfspath` though
only.  It might make sense to use and fix/improve this instead.

**Comment by nicoddemus** [comment]
Looks good to me as is, anything else missing here?

**Comment by blueyed** [comment]
@nicoddemus see the title and TODO.. ;)

**Comment by nicoddemus** [comment]
OK, sorry, thought this might have slipped through the cracks.

**Comment by nicoddemus** [comment]
Closing for now

**Pull request closed without merging**
