### PR TITLE
Force terminal width when running tests

### PR DESCRIPTION
**Pull request by nicoddemus**
Fixes #11423

### CODE REVIEW

**Review by RonnyPfannschmidt — APPROVED** [review]
This might be slightly overboard,I wonder if that may hide possible issues

**Comment by nicoddemus** [comment]
> This might be slightly overboard

You mean this being an autouse fixture, so you would prefer to only apply it to the tests which fail?

**Comment by RonnyPfannschmidt** [comment]
I'm not sure where to draw the line here, it's a very "it depends" choice

Lets perhaps log down a tasks too investigate The results

**Comment by nicoddemus** [comment]
> Lets perhaps log down a tasks too investigate The results

Sounds good, can you do it? It would be useful to list some ideas as well.

**Pull request merged**
