### PR TITLE
Use tomllib on Python 3.11

### PR DESCRIPTION
**Pull request by hauntsaninja**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks @hauntsaninja! 

We are getting an import error, I guess it is not available in the current 3.11 from GitHub Actions?

**Comment by hukkin** [comment]
`tomllib` will be available in Python v3.11a7 (expected release date 2022-04-05) so CI should be failing until then, plus maybe a couple extra days for GitHub Actions to point `3.11-dev` to the latest alpha.

**Comment by hukkin** [comment]
With https://github.com/actions/python-versions/pull/157 merged tests should pass now!

**Comment by hauntsaninja** [comment]
Looks like Github Actions is still using alpha 5 here

**Comment by hukkin** [comment]
Interesting, I have no idea why... I did have GitHub Actions pull alpha7 in another repo [earlier today](https://github.com/executablebooks/mdformat/runs/6038468933?check_suite_focus=true). And `import tomllib` of course worked fine there.

**Comment by hauntsaninja** [comment]
It looks like merging in main fixed it 🤷

**Comment by hauntsaninja** [comment]
Let me know if I should add some pragma ignores or whatever for coverage

**Review by bluetech — APPROVED** [review]
This is great, thanks!

**Pull request merged**
