### PR TITLE
Fixed handling of invalid regex pattern

### LINKED ISSUE #12505: `pytest.raises` with invalid regex in match kwarg fails with internal `re.error`
Using an invalid regex in `pytest.raises` fails in a messy way. 

```py
with pytest.raises(ValueError, match="invalid regex character ["):
    raise ValueError()
```

```shell
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\user\Documents\Projects\external\pytest\src\_pytest\python_api.py", line 1011, in __exit__
    self.excinfo.match(self.match_expr)
  File "C:\Users\user\Documents\Projects\external\pytest\src\_pytest\_code\code.py", line 733, in match
    assert re.search(regexp, value), msg
  File "C:\Python38\lib\re.py", line 201, in search
    return _compile(pattern, flags).search(string)
  File "C:\Python38\lib\re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Python38\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Python38\lib\sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Python38\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Python38\lib\sre_parse.py", line 549, in _parse
    raise source.error("unterminated character set",
re.error: unterminated character set at position 24
```

Proposal would be to handle regex failures within `pytest.raises` and fail nicely for the user (`UsageError`).

- [ ] a detailed description of the bug or problem you are having
- [ ] output of `pip list` from the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] minimal example if possible

### PR DESCRIPTION
**Pull request by virendrapatil24**
closes #12505 

- Updated the `RaisesContext` class in `src/_pytest/python_api.py` to catch `re.error` and call `pytest.fail` with a clear error message.
- Added a test case in `testing/python/raises.py` to validate the new behavior.
- Created a changelog fragment to document this improvement.

### CODE REVIEW

**Comment by The-Compiler** [comment]
This definitely makes things a bit nicer:

```pytb
test_raises.py:3: in <module>
    raise ValueError()
E   ValueError

During handling of the above exception, another exception occurred:
/usr/lib/python3.12/re/__init__.py:177: in search
    return _compile(pattern, flags).search(string)
/usr/lib/python3.12/re/__init__.py:307: in _compile
    p = _compiler.compile(pattern, flags)
/usr/lib/python3.12/re/_compiler.py:745: in compile
    p = _parser.parse(p, flags)
/usr/lib/python3.12/re/_parser.py:979: in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
/usr/lib/python3.12/re/_parser.py:460: in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
/usr/lib/python3.12/re/_parser.py:568: in _parse
    raise source.error("unterminated character set",
E   re.error: unterminated character set at position 24

During handling of the above exception, another exception occurred:
test_raises.py:2: in <module>
    with pytest.raises(ValueError, match="invalid regex character ["):
E   Failed: Invalid regex pattern provided to 'match': unterminated character set at position 24
```

This could be improved by using `raise fail.Exception(...) from None`:

```pytb
test_raises.py:2: in <module>
    with pytest.raises(ValueError, match="invalid regex character ["):
E   Failed: Invalid regex pattern provided to 'match': unterminated character set at position 24
```

though we don't really do this kind of thing elsewhere so far. I'd wait to see what others think before proceeding with that.

**Review by bluetech — CHANGES_REQUESTED** [review]
Thanks for the improvement.

The proposed solution of catching the exception in `__exit__` has the disadvantage that the `fail` is raised from the `__exit__` (and is thus chained to the exception under test), and is not checked at all in the "did not raise" case. I therefore think it'd be better to check it eagerly in the `__init__`.

I also agree with @The-Compiler. We can use `fail.Exception`, but another way is to just make sure to call `fail` outside of the `except` block, something like:

```py
re_error = None
try:
    self.excinfo.match(self.match_expr)
except re.error as e:
    re_error = e
if re_error is not None:               
    fail(f"Invalid regex pattern provided to 'match': {e}")
```

a little verbose, but OK.

**Comment by virendrapatil24** [comment]
I have added the changes you asked for, please let me know if anything else needs to be done. Thanks for the input!

**Comment by bluetech** [comment]
@virendrapatil24 The proposed solution of catching the exception in `__exit__` has the disadvantage that the `fail` is raised from the `__exit__` (and is thus chained to the exception under test), and is not checked at all in the "did not raise" case. I therefore think it'd be better to check it eagerly in the `__init__`.

**Comment by virendrapatil24** [comment]
@bluetech So I need to compile the regex pattern in the `__init__` itself to check it for the valid pattern. Let me know if I have gotten this right.

**Comment by bluetech** [comment]
Right, that would be a good way to do it.

**Review by bluetech — APPROVED** [review]
Thanks, looks good to me!

**Pull request merged**
