### PR TITLE
Add rtd-bot configuration file

### PR DESCRIPTION
**Pull request by nicoddemus**
Part of the configuration necessary for https://github.com/apps/rtd-helper

### CODE REVIEW

**Comment by blueyed** [comment]
I do not like the following from https://github.com/KengoTODA/rtd-bot/ for security reasons:

> Invite rtd-bot user to your RTD project as maintainer.

**Comment by blueyed** [comment]
Ah, that's for the RTD project, but still..

**Comment by nicoddemus** [comment]
I think it is alright, tox has been using the same service too.

**Comment by KengoTODA** [comment]
Hi, thanks for your consideration regarding rtd-bot!

If it's necessary for security reason, you can [deploy your bot by own](https://github.com/KengoTODA/rtd-bot/#deployment). What you need is just a heroku dyno and a GitHub probot. :)

**Comment by blueyed** [comment]
I also think it is fine, especially since we do not have own infrastructure for this.

**Pull request merged**
