### PR TITLE
Fixes Issue 1549

### PR DESCRIPTION
**Pull request by fushi**
Fixes https://github.com/pytest-dev/pytest/issues/1549

test_junitxml.py has been updated to ensure test counting tests pass

### CODE REVIEW

**Comment by fushi** [comment]
Looks like appveyor config is messed up, and passing an invalid filename:

FileNotFoundError: [Errno 2] No such file or directory: 'c:usersappveyorappdatalocaltemp1pytest-of-appveyorpytest-28testdirtest_absolute_win32_path0custom.cfg'

**Comment by RonnyPfannschmidt** [comment]
thanks for the fix!

**Comment by fushi** [comment]
Thanks for picking it up! What's the release schedule like for this to hit pypi?

**Comment by RonnyPfannschmidt** [comment]
currently irregular, the plan to release patches asap needs more work on automation

**Pull request merged**
