### PR TITLE
Add warning about implementing pytest_addoption in conftest files

### PR DESCRIPTION
**Pull request by nicoddemus**
As discussed in #906

### CODE REVIEW

**Comment by nicoddemus** [comment]
cc @flub

**Comment by RonnyPfannschmidt** [comment]
We can hook into contest consideration

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt could you give me some pointers? Also, would it work for cases like this:

```python
# content of conftest.py
pytest_plugins = 'project.fixtures'

# content of project.fixtures
def pytest_addoption(parser):
    ...
```

?

**Comment by RonnyPfannschmidt** [comment]
bascially we should set up the plugin_registred hook in sich a way, that we track when direct plugin consideration is done and conftest consideration is started

at that place we can also warn about initial conftests and later conftests

then any other plugin that is registred, can be checked against and warned as well

the flow if the warning modes is

* nowarn from initial plugins
* warn first conftest for the conftest and any plugin considerations it causes
* warn later considered conftest in the collection phases

**Comment by nicoddemus** [comment]
> warn first conftest for the conftest and any plugin considerations it causes

The topic of this PR is to warn about `pytest_addoption` hooks implemented in `conftest` files... so I'm thinking we would have to record which hooks are being executed and at which point, no?

**Comment by RonnyPfannschmidt** [comment]
Plugin_registered should be sufficient to test if a plugin has a hook

**Comment by nicoddemus** [comment]
Hmm OK, thanks for the suggestion! :smile:

I will wait on #986 before tackling this again.

**Comment by flub** [comment]
I'm not sure if I like to change this to an actual warning at runtime.  And regardless the change here seems useful already so I'm tempted to merge this.

**Pull request merged**
