### PR TITLE
Cleanup MockAwareDocTestFinder.

### LINKED ISSUE #12430: MockAwareDocTestFinder._find_lineno is stale
In doctest, the comment for _find_lineno is stale:

https://github.com/pytest-dev/pytest/blob/043ff9abc657124db3504d3604e16ddebfe6e28f/src/_pytest/doctest.py#L514-L520

issue17446 resolves to python/cpython#61648, the fix which was released in Python 3.11. #8796 links to 0191563fd605a839e9e9c299605c52725b4da17a, which indicates that the method has two purposes, one to work around the aforementioned cpython issue and another "to be reported upstream," though I don't see that it was reported upstream. Does it still need to be reported upstream?

Doing a bit of testing, the doctests all pass on Python 3.11 and later with that method removed, so I'm inclined to say there's no outstanding work to be done except to suppress the use of this workaround after Python 3.11.

### LINKED ISSUE #12432: MockAwareDocTestFinder._find is stale
The implementation of _find has no comments:

https://github.com/pytest-dev/pytest/blob/043ff9abc657124db3504d3604e16ddebfe6e28f/src/_pytest/doctest.py#L534-L543

Perhaps the comments in the class are related. Indeed, looking at where that method was introduced (a6988aa0b92c93bfd397d6b788249488b8f5d300), it's associated with the docstring in the class.

It appears that the tests all pass with the method removed on Python 3.10 and later.

### PR DESCRIPTION
**Pull request by jaraco**
Closes #12430 
Closes #12432

### CODE REVIEW

**Comment by jaraco** [comment]
I don't trust the codecov analysis. I think I may have borked it by pushing another commit that I later force-pushed without. A previous check only showed one line uncovered that I addressed in b989a74.

**Comment by nicoddemus** [comment]
Thanks @jaraco! 

I didn't look too deeply into the issues, but I trust @jaraco's assessment and the fact that all tests pass. 👍

**Review by nicoddemus — APPROVED** [review]

**Review by bluetech — APPROVED** [review]

**Review by RonnyPfannschmidt — COMMENTED** [review]
I noted that this was backported from 3.13

Are there affected versions of 3.11 and 3.12 we ought to include in the condition?

**Comment by jaraco** [comment]
> I noted that this was backported from 3.13
>
> Are there affected versions of 3.11 and 3.12 we ought to include in the condition?

I'm guessing by "this", you mean the `_find_lineno`, since that's the one that only runs on Python 3.10 and earlier now. Looking at my analysis in #12430, I tracked that change to a Python 3.11 release and moreover confirmed that the behavior is required on Python 3.10 and earlier for tests to pass.

Maybe you mean `_from_module`, but that one already includes 3.11 and 3.12, and moreover, that logic is unchanged in this PR.

Can you perhaps restate the question?

**Comment by webknjaz** [comment]
> Are there affected versions of 3.11 and 3.12 we ought to include in the condition?

@RonnyPfannschmidt yes, there are such versions that got overlooked: https://github.com/pytest-dev/pytest/issues/12430#issuecomment-2173542291. The regression fix is here: https://github.com/pytest-dev/pytest/pull/12471.

**Pull request merged**
