### PR TITLE
Revert invocation-fixtures code

### PR DESCRIPTION
**Pull request by nicoddemus**
Due to a serious regression found in #1794, it was decided to pull off invocation features from 3.0 so it can be (hopefully) re-introduced in 3.1

### CODE REVIEW

**Comment by nicoddemus** [comment]
Opened The-Compiler/qutebrowser#1865 to make sure this fixes the test suite.

**Comment by The-Compiler** [comment]
Some remaining bits I found:

- `doc/en/builtin.rst` still says "This fixture is ``invocation``-scoped." for `monkeypatch`. 
- `_pytest/python.py` has a comment about invocation-scoped fixtures in `_showfixtures_main`
-` testing/python/fixture.py` still has some invocation-scoped fixture bits in `test_funcarg_lookup_error` and `test_show_invocation_fixtures`.

**Comment by nicoddemus** [comment]
Thanks! Did all except for the first one because that's automatically generated by `regendocs` so it will be updated automatically the next time it runs.

**Comment by nicoddemus** [comment]
Anything else? Can we merge this?

**Comment by The-Compiler** [comment]
Merged, thanks and sorry for the delay! :wink:

**Comment by nicoddemus** [comment]
No worries, thanks! :grin:

**Pull request merged**
