### PR TITLE
Cherry-pick release 5.4.2

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
(I don't think we need approval to merge the release cherry-picking right?)

**Comment by RonnyPfannschmidt** [comment]
@bluetech what was the rationale for cherry pick instead of merge, i no longer recall

**Comment by bluetech** [comment]
@RonnyPfannschmidt The idea was to do away with the confusing merges and have a clean history.

**Comment by RonnyPfannschmidt** [comment]
Ah right, git history Metadata shortcomings

**Pull request merged**
