### PR TITLE
doc: Reformat/Modernize some code

### PR DESCRIPTION
**Pull request by The-Compiler**
Found because I was curious what https://pypi.org/project/shed/ does with pytest.

### CODE REVIEW

**Review by nicoddemus — APPROVED** [review]
LGTM!

Congratz @Zac-HD for the nice tool! 😁

**Comment by RonnyPfannschmidt** [comment]
@The-Compiler looks awesome

@asottile aware of something similar to just pyupgrade on the docs? (out of interest)

**Review by RonnyPfannschmidt — APPROVED** [review]

**Comment by RonnyPfannschmidt** [comment]
@Zac-HD i presume Integration of reorder-imports is not intended as of now (it looks like shed could be a nice all for one)

**Comment by asottile** [comment]
not to mention it uses intentionally private apis to do work

**Comment by The-Compiler** [comment]
> LGTM - we might try `shed --refactor` as a follow up?

Gave it a try - it mostly changes `assert False` to `raise AssertionError` which seems weird in the context of test functions.

It also throws two internal errors at me :wink: - opened https://github.com/Zac-HD/shed/issues/35.

**Pull request merged**
