### PR TITLE
remove the py.path.local() and replace it with os.getcwd()

### PR DESCRIPTION
**Pull request by srinivasreddy**

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
Please discuss before attempting stuff like that

**Comment by nicoddemus** [comment]
Thanks @srinivasreddy, but what's the purpose of this change?

**Comment by srinivasreddy** [comment]
@nicoddemus  To remove `py` lib dependency.

**Comment by The-Compiler** [comment]
This won't work. `os.getcwd()` is a string, while `py.path.local` is a `py.path` object.

**Comment by nicoddemus** [comment]
@srinivasreddy thanks for trying, but unfortunately this is not so simple to do because we need to keep the same `py.path` interface for backward compatibility; #2230 is a step in this direction.

Closing because we can't merge this as it is. Thanks again.

**Pull request closed without merging**
