### PR TITLE
Merge master into features

### PR DESCRIPTION
**Pull request by blueyed**
Sorry, again for https://github.com/pytest-dev/pytest/pull/5306.

### CODE REVIEW

**Comment by blueyed** [comment]
Hmm, pypy3 did not fail here - restarted it.  /cc @nicoddemus

**Comment by nicoddemus** [comment]
Working again... do we see those failures on `features` by any chance?

**Comment by blueyed** [comment]
> Working again... do we see those failures on features by any chance?

What do you mean?

Can we merge this?

**Comment by nicoddemus** [comment]
> > Working again... do we see those failures on features by any chance?
>  What do you mean?

I mean't pypy3, sorry.

> Can we merge this?

Oops sure

**Comment by blueyed** [comment]
Re pypy3: it's been an issue on features, not master.

**Pull request merged**
