### PR TITLE
Update talks.rst

### PR DESCRIPTION
**Pull request by avallbona**
Added the slides of a PyconES 2017 talk about pytest and its plugins ecosystem.

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks @avallbona!

I just moved the talk to the top of the list as it is more recent. 👍

**Comment by nicoddemus** [comment]
(I'm cancelling AppVeyor)

**Comment by avallbona** [comment]
Thanks @nicoddemus !!

**Comment by blueyed** [comment]
Failure:

> /home/travis/build/pytest-dev/pytest/doc/en/talks.rst:3:Duplicate explicit target name: "slides".

**Comment by nicoddemus** [comment]
Fine to leave this as is, just for the record: using `__` as suffix (instead of a single `_`) then doesn't generate target names. 😁

**Comment by avallbona** [comment]
Ok, understood. Thanks @blueyed and @nicoddemus !!

**Pull request merged**
