### PR TITLE
[WIP][deferred] minimal example experiment for a toml based configuration and legacy mapping

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
ref #1556

in this pr im aiming to make a mockup ap exaplei for supporting toml files as input for pytest configuration/options as well as mapping both cli and ini options to the new tool

it will evolve at a slow pace as i tap into it when i find time/motivation

### CODE REVIEW

**Comment by nicoddemus** [comment]
Nice, thanks for the follow up

**Comment by RonnyPfannschmidt** [comment]
i finished the actual method names, next steps would be to put them into actual use in some manner

**Comment by nicoddemus** [comment]
I suggest translating one of the existing plugins to the new configuration to see how it would like.

One question: to support `pyproject.toml`, plugins *need* to implement the new hook, or will they be mapped automatically in the legacy manner?

**Comment by RonnyPfannschmidt** [comment]
no automatic mapping, the plugins will have to port, unless some proposes a actually viable porting scheme,  im going to be -10 on it

**Comment by JAMMFam** [comment]
Testing pull request

**Comment by JAMMFam** [comment]
Testing

**Comment by JAMMFam** [comment]
Testing Pull access

**Comment by nicoddemus** [comment]
Giving that we are following a different approach (https://github.com/pytest-dev/pytest/issues/1556#issuecomment-572267167) I believe we can close this.

**Pull request closed without merging**
