### PR TITLE
code/source: some cleanups

### PR DESCRIPTION
**Pull request by bluetech**
These commits clean up the  `_pytest._code.source` module, particularly removing a bunch of code we don't need.

I think it's a good idea to remove stuff we don't use because it reduces the amount of code we need to maintain and understand.

### CODE REVIEW

**Comment by bluetech** [comment]
Thanks for taking a look @RonnyPfannschmidt!

> We might have to pick a breaking change for this one, but I like the drop

Do you think we expose `Source` anywhere?

I guess one path is `ExceptionInfo` (from raises or some hooks) -> `traceback` attribute (type `_pytest._code.Traceback`)  -> `__getitem__` (type `_pytest._code.TracebackEntry`) -> `statement` attribute (type `Source`). And then using one of the removed functions on that.

I think this probably deserves a changelog but since it's not a documented API maybe not a deprecation cycle...

**Comment by RonnyPfannschmidt** [comment]
I agree that a deprecation cycle seems unnecessary, i still believe this is to be classified as breaking change in the changelog

**Comment by bluetech** [comment]
OK, I'll add a `breaking` changelog documenting all of the changes here, a bit later.

**Comment by bluetech** [comment]
Thanks for the reviews. I added the changelog, and got the coverage to 100% by ignoring some unreachable code.

**Pull request merged**
