### PR TITLE
Fix #1981, improve ini-options help text

### LINKED ISSUE #1981: ini-options help text improve phraseology
This help text is slightly bad English:

> [pytest] ini-options in the next pytest.ini|tox.ini|setup.cfg file:

I propose we replace it with:

> [pytest] ini-options in the first pytest.ini|tox.ini|setup.cfg file found:

### PR DESCRIPTION
**Pull request by tomviner**
Fix for https://github.com/pytest-dev/pytest/issues/1981

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
@tomviner please check your git setup, you accidentally pushed your topic branch to the main repo

should we add a few lines for the workflow setup to the documentation (i recall making the same mistake a few weeks back)

**Comment by nicoddemus** [comment]
> please check your git setup, you accidentally pushed your topic branch to the main repo

Yes, it is recommended to open PRs from branches in your fork. FWIW the only drawback of opening PRs from branches in the main repository is that the CI services run twice. Other than that, there's really no long term drawback though.

> should we add a few lines for the workflow setup to the documentation (i recall making the same mistake a few weeks back)

I believe [the documentation](https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst#preparing-pull-requests-on-github) is explicit about the recommendation of opening PRs from forks already... do you have something in mind @RonnyPfannschmidt?

I'm merging this, the py35-trial failure on Linux is not related, hopefully I'll be able to investigate it in #1979.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i believe we should propose a configuration workflow,

recently i started to always clone from the pristine repos, and setting my fork as the push url for origin
perhaps a discussion on the ml makes sense

**Comment by nicoddemus** [comment]
> i believe we should propose a configuration workflow,

I see, I usually:

1. Fork on GH, and clone my fork (this automatically sets my fork as `origin`).
2. Use `git remote add upstream <official repo url>` to add a `upstream` remote pointing to the original repository, usually just to update my fork with upstream commits.

I think that's the recommended workflow in general when working on GH, although I don't really remember reading it specifically anywhere.

**Comment by tomviner** [comment]
> @tomviner please check your git setup, you accidentally pushed your topic branch to the main repo
> 
> should we add a few lines for the workflow setup to the documentation (i recall making the same mistake a few weeks back)

@RonnyPfannschmidt very sorry about that! The only reason it happened is because I made the change using the github web interface.

I would never normally create a branch on pytest-dev otherwise. And of course, it's only possible because I'm a pytest plugin maintainer, otherwise I'd have no rights to create branches here anyway.

@nicoddemus for what it's worth, my usual workflow for open source contributions is:

1. Clone original repo, to look round / run the code base on my laptop. Assuming I need to make change:
1. Click *Fork* on github
1. Run a little shell function I have, called `git-forked` which moves the original repo to `upstream` and adds a new `origin` under my github username:

```bash
function git-forked {
    git remote rename origin upstream
    git remote add origin $(git remote -v | grep upstream | cut -d$'\t' -f2 | cut -d' ' -f1 | sed s/":[A-Za-z0-9-]\+\/"/":tomviner\/"/ | head -1)
    git fetch --all
    git branch master -u origin/master
}
```

I'm sure that could be simplified though!

**Comment by nicoddemus** [comment]
Hey @tomviner!

>  The only reason it happened is because I made the change using the github web interface.

Absolutely, I've done so in the past myself. 😁

**Comment by tomviner** [comment]
> image

 @nicoddemus thanks for the clean up!

**Pull request merged**
