### PR TITLE
Modifying doc for run tests by nodeid section

### PR DESCRIPTION
**Pull request by udaymankena**
Creating this PR for https://github.com/pytest-dev/pytest/issues/11107

### CODE REVIEW

**Comment by nicoddemus** [comment]
Assigning @bluetech explicitly as requested in https://github.com/pytest-dev/pytest/issues/11107#issuecomment-1650884152

**Comment by bluetech** [comment]
Hi @udaymankena, I've merged my change but I like your suggested change of "nodeids" to "collection arguments", that should clarify away the confusion entirely, and also happens to match how we call them internally. Please rebase the PR on the latest main, then we can merge it.

**Comment by udaymankena** [comment]
thank you @bluetech. I've rebased my PR onto main.

**Review by bluetech — APPROVED** [review]
Thanks! (I made a few edits)

**Pull request merged**
