### PR TITLE
Colon-pair keywords

### PR DESCRIPTION
**Pull request by pakal**
Here is the port to GitHub of that previous pull request : https://bitbucket.org/pytest-dev/pytest/pull-request/305/allow-selection-with-myfilepy-myfile/diff#comment-7531336

### CODE REVIEW

**Comment by pakal** [comment]
OK my bad, python2.6 doesn't accept re.sub(..., flags=xxx) argument.
I'll change it to "re.sub("(?i)mr", "", "Mr Bean")" notation asap and update the PR.

**Comment by nicoddemus** [comment]
Related to #765

**Comment by flub** [comment]
So continuing the conversation from the original bitbucket PR, does it help if -k understands the node-id?  The whole point of the node-id was that it could be copy-pasted, partially copy-pasting it seems like a weird use-case and increases the backwards-compatibility someone who'd like to tackle the python keywords issue with -k would have to worry about.

**Comment by RonnyPfannschmidt** [comment]
I'm -1 on this one, test ids can be passed without -k

**Comment by RonnyPfannschmidt** [comment]
Imho We should support exact full name prefix matching and regex matching via the planned keyword expressions

**Comment by nicoddemus** [comment]
I was +1 on the PR until I found out that you can actually copy/paste ids directly, but now I must say I'm +0 on it as I agree with @flub's points.

**Comment by RonnyPfannschmidt** [comment]
we should take a look at partial test id's for the following use-case:

-> run all parametrizations of a test functions

**Comment by flub** [comment]
But as part of -k? I think that should be part of the normal test id
parameter so remain -1 on this

**Comment by RonnyPfannschmidt** [comment]
yes, it should be part of the test id selection

i suspect a reorganization of collection<>parametrisation will do some good,
but thats potentially for pytest 3.0

**Comment by flub** [comment]
So it seems like the consensus is that selection by ID is already suitably covered and should not be done by -k.  Thanks for submitting the pull requests anyway!

**Pull request closed without merging**
