### PR TITLE
[wip] detangle Config init

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
currently config initialization is bound to the namespace hooks nad technically broken since years

the fix requires removing the pytest_namespace hook

### CODE REVIEW

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt unfortunately it is hard/impossible for me to review this because you split the `config.py` module *and* made some changes at the same time so I can't differentiate between what was moved and what was changed. 😞

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i see, i will separate them this week then

**Comment by nicoddemus** [comment]
Thanks!

**Comment by RonnyPfannschmidt** [comment]
closing this one will restart fresh bit by bit

**Pull request closed without merging**
