### PR TITLE
added a check if denominator is zero

### LINKED ISSUE #10533: `assert a == approx(b)` when `b` is dict containing zero value results in ZeroDivisionError
Pytest behaves differently when comparing dictionaries containing zero values compared to lists containing same values

pytest==7.2.0
Ubuntu 22.04

```python
import pytest

def test_foo_dict():
    a = {'foo': 42.0}
    b = {'foo': 0.0}
    assert a == pytest.approx(b) # ZeroDivisionError in pytest/python_api.py

def test_foo_list():
    a = [42.0]
    b = [0.0]
    assert a == pytest.approx(b) # OK
```

```python
_____________________ test_foo_dict

    def test_foo_dict():
        a = {'foo': 42.0}
        b = {'foo': 0.0}
>       assert a == pytest.approx(b)
E       AssertionError: assert {'foo': 42.0} == approx({'foo': 0.0 ± 1.0e-12})
E         (pytest_assertion plugin: representation of details failed: /home/arkanoid/test/venv/lib/python3.10/site-packages/_pytest/python_api.py:274: ZeroDivisionError: float division by zero.
E          Probably an object has a faulty __repr__.)

extra/test_pytest_issue.py:9: AssertionError

_____________________ test_foo_list

    def test_foo_list():
        a = [42.0]
        b = [0.0]
>       assert a == pytest.approx(b)
E       assert [42.0] == approx([0.0 ± 1.0e-12])
E         comparison failed. Mismatched elements: 1 / 1:
E         Max absolute difference: 42.0
E         Max relative difference: 1.0
E         Index | Obtained | Expected     
E         0     | 42.0     | 0.0 ± 1.0e-12

extra/test_pytest_issue.py:15: AssertionError
```

### PR DESCRIPTION
**Pull request by jayendra-patil33**
closes #10533

### CODE REVIEW

**Review by nicoddemus — CHANGES_REQUESTED** [review]
Thanks @jayendra-patil33!

Could you please:

1. Add a test to avoid future regressions?
2. Add a changelog entry, as a new file `changelog/10533.bugfix.rst` describing the fix, like:

    ```
    Fix :func:`pytest.approx` handling of dictionaries containing one or more values of `0.0`.
    ```

**Comment by jayendra-patil33** [comment]
Done

**Comment by nicoddemus** [comment]
Hi @jayendra-patil33,

I don't see the requested changes, did you forget to push perhaps?

**Comment by jayendra-patil33** [comment]
Sorry, it seems that was indeed the case, now I have pushed the code.

**Review by nicoddemus — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
