### PR TITLE
[WIP] typing for getcfg and determine_setup

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by bluetech** [comment]
Somehow some comments seem to have been lost...

Did we get a conclusion on using an empty `SectionWrapper` instead of the `Dict`? If a dict is necessary, can it be typed as `Dict[str, str]` instead?

**Comment by blueyed** [comment]
> Somehow some comments seem to have been lost...

I've pulled this out of https://github.com/pytest-dev/pytest/pull/6447.

> Did we get a conclusion on using an empty `SectionWrapper` instead of the `Dict`? If a dict is necessary, can it be typed as `Dict[str, str]` instead?

Given that SectionWrapper is not importable I've found this to be less useful / possible.

**Comment by bluetech** [comment]
Do the `py` stubs change things for this PR?

In the `py` stubs we made `SectionWrapper` hidden - `_SectionWrapper` - because it isn't exposed in the public API (not importable).

**Comment by blueyed** [comment]
@bluetech py stubs are helpful / change things.
I've worked a bit more on this in https://github.com/blueyed/pytest/pull/251, but IIRC used the `_vendored` import also for instance checks there.

**Comment by bluetech** [comment]
OK, feel free to ping me once this is ready.

**Comment by nicoddemus** [comment]
Closing for now.

**Pull request closed without merging**
