### PR TITLE
Use temporary directory for cx_freeze testing

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus missing  .local in there?

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt what do you mean?

**Comment by hpk42** [comment]
the build fails -- py.path.local.make_numbered_dir instead of py.path.make_numbered_dir :)

**Comment by nicoddemus** [comment]
Oops, fixed. :sweat_smile:

**Pull request merged**
