### PR TITLE
add script to generate a example folder for collecting many files

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Not sure if this is a good idea, that many files does incur an overhead for checkout doesn't it?

**Comment by RonnyPfannschmidt** [comment]
we totally need some tooling around manual testing support (this would be a manual test where we want to drop into a optional manual interaction point with a ipython shell or a system shell in the testdir

then we could jsut start some tests in "interactive mode, and mess around

**Comment by blueyed** [comment]
@RonnyPfannschmidt 
Sure.  But it is fast to generate those files locally, and would be trivial through a Makefile (using the script that was provided already).

**Comment by RonnyPfannschmidt** [comment]
@blueyed i dislike incomplete error prone tooling because ^^ - and i absolutely refuse makefiles - those things should die already

**Comment by nicoddemus** [comment]
I concur with @RonnyPfannschmidt that Makefiles are not the way to go. 😁 

I propose we commit a Python script which can generate the files; this way we don't incur the overhead of 1000s files on each checkout, plus the script can be configurable (how many files to generate, and depth of folders, etc) which will make it even more useful in the future (say we want to test with 10k or 100k files, 6 directories deep).

I think the script can reside inside the examples folder, say in `testing/example_scripts/perf_examples/collect_stats/generate_files.py`, and contain a `.gitignore` file which ignores all the files generated by it to avoid accidental commits.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus good thinking

**Comment by blueyed** [comment]
@nicoddemus 
That's what I've meant basically.

And a Makefile would just call the script then, preparing the files needed for the perf tests, but it would not be required to be used of course.  I am not talking about autoconf or something similar, but just something basic as (in collect_stats):
```Makefile
100x10:
  python generate_files.py 100 10 $@

test: 100x10
  cd 100x10 && pytest -k doesnotmatch
```

Then CI / perf generation could use `make -C …/collect_stats test`.

Anyway, this was just an idea for the future, but the main point is that files should be generated dynamically, not being committed, and I am glad you agree.

Closing this PR then.

**Comment by nicoddemus** [comment]
Nice work! 👍

**Pull request merged**
