### PR TITLE
 Doctest: hack in handling mock style objects

### LINKED ISSUE #3456: `--doctest-modules` causes `py.test` to consume all memory and then crash
WARNING: Please don't run code sample from below, it can block / crash your machine. Instead, use Vagrant machine for testing it. 

So, on Ubuntu 17.10 , Python 3.6:

~~~sh
mkdir foobar
cd foobar
mkdir src
mkdir tests
mkdir docs
python3 -mvenv .venv
source .venv/bin/activate
pip install -U pip wheel
pip install "pytest>=3.0.0"

cat <<EOT > setup.cfg
[tool:pytest]
norecursedirs = .git tmp* .hg .venv .tox .eggs
testpaths = tests docs src
addopts =
    -r=xEfsw
    --strict
    --ignore=docs/conf.py
    --ignore=setup.py
    --ignore=.eggs
    --doctest-modules
    --doctest-glob=*.rst
    --tb=short
    --color=auto
EOT

echo "from unittest.mock import Mock, call" > tests/test_with_mock_package.py
~~~

Running `py.test` will cause it to consume all RAM it can get and then either kernel will kill it or system will start swapping wildly until it blocks completely.

To make above thing work:

~~~diff
--- setup.cfg   2018-05-08 13:03:47.058679203 +0000
+++ setup.cfg.new       2018-05-08 13:09:46.650678324 +0000
@@ -7,7 +7,7 @@
     --ignore=docs/conf.py
     --ignore=setup.py
     --ignore=.eggs
-    --doctest-modules
+    # --doctest-modules
     --doctest-glob=*.rst
     --tb=short
     --color=auto
~~~

After which:

~~~
$ py.test
============================================================ test session starts ============================================================
platform linux -- Python 3.6.3, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /home/vagrant/foobar, inifile: setup.cfg
collected 0 items

======================================================= no tests ran in 0.01 seconds ========================================================
~~~

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
Resolves #3456

### CODE REVIEW

**Comment by nicoddemus** [comment]
Just FYI: GitHub is facing some issues so webhooks are disabled for the moment: https://status.github.com/messages

**Comment by RonnyPfannschmidt** [comment]
i am aware ^^

**Comment by nicoddemus** [comment]
great, thanks

**Comment by thisch** [comment]
@RonnyPfannschmidt Thx for this hack! I have applied it in pytest-sphinx as well.

**Comment by RonnyPfannschmidt** [comment]
@thisch im glad it could help, i was repulsed as i made it ^^

**Pull request merged**
