### PR TITLE
Replace deprecated logging.warn with logging.warning

### PR DESCRIPTION
**Pull request by hugovk**
Replace `logging.warn` (deprecated in [Python 2.7, 2011](https://github.com/python/cpython/commit/04d5bc00a219860c69ea17eaa633d3ab9917409f)) with `logging.warning` (added in [Python 2.3, 2003](https://github.com/python/cpython/commit/6fa635df7aa88ae9fd8b41ae42743341316c90f7)).

* https://docs.python.org/3/library/logging.html#logging.Logger.warning
* https://github.com/python/cpython/issues/57444

### CODE REVIEW

**Review by RonnyPfannschmidt — APPROVED** [review]
Thanks

**Comment by The-Compiler** [comment]
Looks good, thanks! Wonder if we need a changelog entry for this?

**Comment by RonnyPfannschmidt** [comment]
reopen cycled in the hope that pre-commit.ci works this time

**Comment by RonnyPfannschmidt** [comment]
btw, no changelog needed, as this is a minor test cleanup thats practically not user-facing

**Comment by hugovk** [comment]
pre-commit.ci isn't running on other PRs either, for example https://github.com/pytest-dev/pytest/pull/10061.

The last pre-commit.ci run was on 2022-06-06: https://results.pre-commit.ci/repo/github/37489525

ping @asottile

**Comment by asottile** [comment]
someone turned it off -- not really sure who -- https://results.pre-commit.ci/install/github/13658824

**Comment by asottile** [comment]
pre-commit.ci run

**Comment by asottile** [comment]
I re-added it to pytest-dev/pytest

**Pull request merged**
