### PR TITLE
Make minor grammar changes in doctest.rst

### PR DESCRIPTION
**Pull request by mvoitko**

### CODE REVIEW

**Comment by Zac-HD** [comment]
"adding commas" is not "fixing typos", and while we welcome Hacktoberfest contributions this is not actually helpful.

**Comment by The-Compiler** [comment]
@Zac-HD This seems unnecessarily dismissive, IMHO. While Hacktoberfest-spam is a problem, I view this PR as a net-positive.

Also, it's coming from a GitHub account which exists for a long time already, so this doesn't seem like someone just trying to game the system for getting a t-shirt. It really doesn't sit well with me to outright dismiss well-intended contributions just because they're a minor change and it happens to be October. This is how you drive new contributors away.

Note that "typos" vs. "grammar changes" is a subtle distinction, even more so for someone who (presumably) isn't a native English speaker.

Taking the freedom to reopen and merge this.

**Review by The-Compiler — APPROVED** [review]

**Comment by Zac-HD** [comment]
Apologies @mvoitko, I guess I'm a little over-sensitised :confused: 

(and thanks for catching it, @The-Compiler)

**Comment by mvoitko** [comment]
@The-Compiler @Zac-HD Thanks a lot. I was searching for a starting point to contribute to pytest since I have been using it for a very long time and notices these very minor grammar issues. (I am not a native English speaker) I would appreciate it if you could suggest a good first PR issue in pytest.

**Comment by Zac-HD** [comment]
Checking [issues labelled `easy`](https://github.com/pytest-dev/pytest/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+easy%22), https://github.com/pytest-dev/pytest/issues/3141 might be good :slightly_smiling_face:

**Comment by The-Compiler** [comment]
Thank you!

**Pull request merged**
