### PR TITLE
fix markup typo that breaks rendering

### PR DESCRIPTION
**Pull request by merwok**

### CODE REVIEW

**Review by nicoddemus — APPROVED** [review]
Thanks!

**Comment by bluetech** [comment]
(I changed the base branch and marked for backport)

**Comment by The-Compiler** [comment]
@merwok thank you!

@bluetech so I assume you are going to take care of the backporting?

**Comment by The-Compiler** [comment]
I did the backport as I backported two other PRs too anyways: #9397

**Pull request merged**
