### PR TITLE
Custom reason support for "importorskip"

### PR DESCRIPTION
**Pull request by s0undt3ch**
- [ ] Create a new changelog file in the `changelog` folder, with a name like `<ISSUE NUMBER>.<TYPE>.rst`. See [changelog/README.rst](https://github.com/pytest-dev/pytest/blob/master/changelog/README.rst) for details.
- [x] Target the `features` branch for new features and removals/deprecations.
- [ ] Include documentation when adding new features.
- [x] Include new tests or update existing tests when applicable.

Unless your change is trivial or a small documentation fix (e.g.,  a typo or reword of a small section) please:

- [x] Add yourself to `AUTHORS` in alphabetical order;

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Will do!

**Comment by nicoddemus** [comment]
Took the liberty of doing the requested changes myself as I would like to include this in the 4.1 release, hope @s0undt3ch doesn't mind. 😁

**Comment by nicoddemus** [comment]
docs, doctesting and linting passed so I'm going ahead and merge this.

**Comment by s0undt3ch** [comment]
Of course I don't mind. Thank You!

**Pull request merged**
