### PR TITLE
Upgrade pyupgrade for crlf fixes (again)

### PR DESCRIPTION
**Pull request by asottile**
I promise I commit things to pytest other than changing this yaml file :sob:

### CODE REVIEW

**Comment by nicoddemus** [comment]
Hahaha thanks for the lightning quick fix @asottile! 🙇

**Comment by RonnyPfannschmidt** [comment]
personally i appreciate having someone that's not me dedicated to the pain of yaml ^^

**Comment by asottile** [comment]
@RonnyPfannschmidt I feel ya, yaml is my biggest regret w/ pre-commit

**Comment by nicoddemus** [comment]
> yaml is my biggest regret w/ pre-commit

Oh really? I'm curious why you feel that way. Also, which alternatives would you use instead of yaml for pre-commit configuration?

**Comment by asottile** [comment]
> > yaml is my biggest regret w/ pre-commit
> 
> Oh really? I'm curious why you feel that way. Also, which alternatives would you use instead of yaml for pre-commit configuration?

The biggest being that it can't be programmatically rewritten.  [`autoupdate` (though glorious) is a giant hack](https://github.com/pre-commit/pre-commit/blob/1f1cd2bc394271540955794b3d2d3e6d8f4e65bb/pre_commit/commands/autoupdate.py#L70-L106) -- it used to be one of the biggest [sources of frustration](https://github.com/pre-commit/pre-commit/issues/210).

There's also the sheer complexity (and slowness) of yaml -- the spec for json fits on a postcard, but yaml's is [84 pages](http://yaml.org/spec/1.2/spec.pdf).  The default implementation of yaml has some famous [security problems](https://www.youtube.com/watch?v=ATY_R6qEa3s) and unless you've got `libyaml-dev` at install time (and the appropriate code to [_opt into the fast path_](https://anthonywritescode.github.io/episodes-wat/02-pyyaml/#/6), you're stuck in the pure-python slow path.  Even the fast path is orders of magnitude slower than the equivalent `json` calls.

To be honest, I haven't found a better alternative.  What I really want is some high level configuration that's fast, readable, and machine rewritable.  [json5](https://json5.org/) seems so close to what I want, but the parsers for python are an awful pile of pure python + regex and aren't round trippable.  I even [tried to invent my own config language](https://github.com/asottile/dumbconf) and while it worked, it wasn't ever really production worthy (a fun exercise though, I learned a ton and wrote some cool toys).

Maybe one day I'll have enough time to make `json5` functional in python... but until then I'll continue shouting to the wind :sob:

**Comment by nicoddemus** [comment]
Thanks for the detailed write up!

And what about toml?

**Comment by asottile** [comment]
Also doesn't have a round-trip parser :(

**Comment by nicoddemus** [comment]
Hmm.

About the roundtrip parser, conda uses [ruamel.yaml](https://yaml.readthedocs.io/en/latest/). 👍

**Comment by asottile** [comment]
Yeah, I tried it it didn't quite cut it.  Kinda funny though, from [their overview page](https://yaml.readthedocs.io/en/latest/overview.html):

> flow style sequences ( ‘a: b, c, d’) (based on request and test by Anthony Sottile)

**Pull request merged**
