### PR TITLE
Some setup.cfg cleanups

### PR DESCRIPTION
**Pull request by bluetech**
Remove some no longer needed sections, and move the mypy config to pyproject.toml.

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
Looks great. Is something blocking moving to ``pyproject.toml`` entirely and removing the setup.cfg ?

**Comment by bluetech** [comment]
> Is something blocking moving to pyproject.toml entirely and removing the setup.cfg ?

I've done this in pytest-django and haven't received any complaints. In pytest 8.0 we also removed setup.py and no complaints. So it probably would be fine. It requires newer setuptools.

**Comment by Pierre-Sassoulas** [comment]
Do you want to do it yourself or can I have a go at it ?

**Comment by bluetech** [comment]
Please do! I'll merge this so you have a clean base to work with.

**Pull request merged**
