### PR TITLE
Pickup addition positional args passed to _parse_parametrize_args

### PR DESCRIPTION
**Pull request by kevinjfoley**
Fix for #5482.

### CODE REVIEW

**Comment by kevinjfoley** [comment]
Will do, will also change the arg names which is causing the tests to fail currently.

Any input on where the test should be added?

**Comment by nicoddemus** [comment]
I think `testing/python/metafunc.py` should do it, thanks.

**Comment by nicoddemus** [comment]
Hmmm I wonder though, since this is already broken, we should make everything except `argnames` and `argvalues` keyword only in 5.0? 🤔 

@asottile @blueyed @Zac-HD what do you think?

**Comment by nicoddemus** [comment]
(@kevinjfoley perhaps hold on to your patch for a bit, wouldn't want you to waste your time)

**Comment by Zac-HD** [comment]
I'm a big fan of keyword-only arguments... but we broke this in 4.6, so I'd prefer to accept the PR (thanks @kevinjfoley!) and then have a follow-up issue to work out what and how to convert to keyword-only arguments.

**Comment by kevinjfoley** [comment]
> thanks @kevinjfoley

No problem!

Pushed a squashed commit with the fix and a test demonstrating the problem, let me know if anything else is needed.

**Comment by nicoddemus** [comment]
>  but we broke this in 4.6, so I'd prefer to accept the PR (thanks @kevinjfoley!) and then have a follow-up issue to work out what and how to convert to keyword-only arguments.

Yeah, I agree, thanks for putting me in check. 👍

**Comment by kevinjfoley** [comment]
> Thanks again @kevinjfoley, appreciate it!

Happy to be able to contribute!

**Comment by asottile** [comment]
Hmmm i don't think this should be merged, it was a bug that parametrize swallowed extra arguments (the test is asserting that a bug exists)

**Comment by asottile** [comment]
Oh already merged :thinking:

**Comment by nicoddemus** [comment]
> Hmmm i don't think this should be merged, it was a bug that parametrize swallowed extra arguments (the test is asserting that a bug exists)

Not really, the extra arguments are valid, here's the signature:

https://github.com/pytest-dev/pytest/blob/37fce6c6e54bc276ca639343344b80b3e3838520/src/_pytest/python.py#L947

So it is in fact a regression, I'm afraid.

**Comment by asottile** [comment]
Yikes, always assumed those were kwargonly, and it's probably too late to do that for 5.0

**Comment by nicoddemus** [comment]
I guess we should open an issue then to discuss how to change that so it emits a warning in 5.X so we can turn it into keyword-only in 6.0 at least.

**Pull request merged**
