### PR TITLE
Replace custom flask theme by the official one

### PR DESCRIPTION
**Pull request by nicoddemus**
Ref: #6402

### CODE REVIEW

**Comment by nicoddemus** [comment]
The pages can be seen here: https://docs.pytest.org/en/use-standard-flask-theme/

**Comment by RonnyPfannschmidt** [comment]
not "perfect", but my first impression is a lot better
thanks for setting it up

**Comment by nicoddemus** [comment]
Since we didn't get traction in other fronts, I suggest we go ahead with this style: it is an updated flask theme at least, and already an improvement IMHO. We can always apply another theme later if we decide on a better one.

What do you guys think?

**Comment by The-Compiler** [comment]
Sounds good - thanks @nicoddemus! :+1:

**Pull request merged**
