### PR TITLE
mypy: no_implicit_optional = False

### PR DESCRIPTION
**Pull request by blueyed**
This allows for easier signatures.

doc: https://mypy.readthedocs.io/en/latest/command_line.html#none-and-optional-handling

### CODE REVIEW

**Comment by bluetech** [comment]
I personally prefer it to be True, I find a signature like `exprinfo: str = None` to be inconsistent and surprising. But I don't feel strongly about it.

**Comment by blueyed** [comment]
Me neither, but I can see no benefit in the boilerplate overhead.
It is a nice shortcut IMHO, and mypy default to it IIRC.

**Comment by bluetech** [comment]
> mypy default to it IIRC.

The consensus seems to be that this was a bad default:

- https://github.com/python/typing/issues/275
- https://github.com/python/peps/pull/689

**Comment by asottile** [comment]
:-1: strongly prefer being explicit here

**Pull request closed without merging**
