### PR TITLE
Preparing release version 4.1.2

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Weird, @asottile we are getting an error during doc generation:

```
Warning, treated as error:
/home/travis/build/pytest-dev/pytest/doc/en/example/parametrize.rst:539:Could not lex literal_block as "pytest". Highlighting skipped.
ERROR: InvocationError for command '/home/travis/build/pytest-dev/pytest/.tox/docs/bin/sphinx-build -W -b html . _build' (exited with code 2)
```

Here's the relevant code:

```
.. code-block:: pytest

    $ pytest -v -m basic
    =========================== test session starts ============================
    platform linux -- Python 3.x.y, pytest-4.x.y, py-1.x.y, pluggy-0.x.y -- $PYTHON_PREFIX/bin/python3.6
    cachedir: .pytest_cache
    rootdir: $REGENDOC_TMPDIR, inifile:
    collecting ... collected 17 items / 14 deselected

    test_pytest_param_example.py::test_eval[1+7-8] PASSED                [ 33%]
    test_pytest_param_example.py::test_eval[basic_2+4] PASSED            [ 66%]
    test_pytest_param_example.py::test_eval[basic_6*9] XFAIL             [100%]

    ============ 2 passed, 14 deselected, 1 xfailed in 0.12 seconds ============
```

This is not new and just now started to fail... any ideas?

**Comment by asottile** [comment]
interesting, let me take a look

**Comment by asottile** [comment]
there's a difference in output between pytest 4.1.1 and master -- I suspect we should fix that and not release:

```python
import pytest


@pytest.mark.xfail
def test_xfail():
    raise AssertionError()


@pytest.mark.xfail
def test_xpass():
    pass
```

```bash
pytest t.py -vv > 4_1_1
pip install git+https://github.com/pytest-dev/pytest --upgrade
pytest t.py -vv > 4_1_2
```

```diff
$ diff -u 4_1_1 4_1_2 
--- 4_1_1	2019-01-28 13:38:03.004458708 -0800
+++ 4_1_2	2019-01-28 13:38:18.108019589 -0800
@@ -1,10 +1,10 @@
 ============================= test session starts ==============================
-platform linux -- Python 3.6.7, pytest-4.1.1, py-1.7.0, pluggy-0.8.1 -- /tmp/pygments-pytest/venv/bin/python3
+platform linux -- Python 3.6.7, pytest-4.1.2.dev39+g5119abe4, py-1.7.0, pluggy-0.8.1 -- /tmp/pygments-pytest/venv/bin/python3
 cachedir: .pytest_cache
 rootdir: /tmp/pygments-pytest, inifile:
 collecting ... collected 2 items
 
-t.py::test_xfail xfail                                                   [ 50%]
+t.py::test_xfail XFAIL                                                   [ 50%]
 t.py::test_xpass XPASS                                                   [100%]
 
 ===================== 1 xfailed, 1 xpassed in 0.02 seconds =====================
```

The original behaviour seems more correct to me, for xfail we used `x` / `xfail` for "failed and expected to fail" and `X` / `XPASS` for "passed but expected to fail"

**Comment by nicoddemus** [comment]
Hmm right, this was changed in https://github.com/pytest-dev/pytest/pull/4668. I disagree, I think `XFAIL` is more consistent with all the other statuses we display: `PASSED`, `FAILED`, `XPASS`, `SKIPPED`. It is odd that only `xfail` was not in caps.

**Comment by asottile** [comment]
:man_shrugging: 1a8b2838fa3ca3abc864d490cb25210535198aef changed `xpass` to `XPASS` without changing `XFAIL` making me think it was intentional to match the case of the short status.

It's entirely cosmetic though I guess -- I can update pygments-pytest to recognize `XFAIL` as well -- let me know how you'd like to proceed :)

**Comment by nicoddemus** [comment]
> I can update pygments-pytest to recognize XFAIL as well -- let me know how you'd like to proceed :)

Yes please. ☺️

**Comment by asottile** [comment]
the other question is should this change land in 4.1.2 or in 4.2.0

**Comment by asottile** [comment]
here's the patch for `XFAIL`: https://github.com/asottile/pygments-pytest/pull/11

**Comment by nicoddemus** [comment]
> the other question is should this change land in 4.1.2 or in 4.2.0

Hmmm I guess this small change is OK to go into `4.1.2`. @RonnyPfannschmidt what's your opinion on this?

**Comment by nicoddemus** [comment]
Awesome, thanks @asottile! 🙇

**Comment by nicoddemus** [comment]
Yeah, I agree, so I'm closing this.

**Comment by nicoddemus** [comment]
We have only 3 issues left on the [4.2 milestone](https://github.com/pytest-dev/pytest/milestone/23), seems reasonable that we can get 4.2 out by the end of the week?

**Comment by blueyed** [comment]
I do not have much time myself, but https://github.com/pytest-dev/pytest/pull/4280 should be fine - no real review though still.

**Comment by nicoddemus** [comment]
@blueyed I will take it for a spin later and merge it, unless I encounter some problem. 👍

**Comment by wimglenn** [comment]
The https://github.com/pytest-dev/pytest/commit/1a8b2838fa3ca3abc864d490cb25210535198aef might be the historical reason I was searching for in https://github.com/pytest-dev/pytest/pull/4668#discussion_r250384798 
This change should certainly not go in a micro release bump (it's very likely some users are parsing those test report output statuses with case sensitivity greps or whatever).

**Pull request closed without merging**
