### PR TITLE
Specify paramterized node in command line - Issue #649

### PR DESCRIPTION
**Pull request by palaviv**
This PR solves the problem specified in Issue #649.
I added the test to test_mark but i am not so sure that is the right place.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
good work, its mergable as is

as for nitpicking, could you please add a todo comment to remove the workaround once collection structure properly contains parameterization

in any case i'll merge after work

**Comment by nicoddemus** [comment]
(I gave a :+1: to the PR, does anyone receive a notification for that?

**Comment by The-Compiler** [comment]
@nicoddemus  No, I think that's the whole point of those reactions - I think they got added because for bigger projects, dozens of :+1: comments were too noisy

**Comment by palaviv** [comment]
Thanks for the good reviews :).
I will not be infront a computer until tommorow evening. I can add the TODO commnet then if you wish to wait.
Is there a PR or Issue that regard the planned change in the collection structure?

**Comment by RonnyPfannschmidt** [comment]
no pr or issue, i have it on my personal agenda for the sprint

**Comment by palaviv** [comment]
I added the TODO comment

**Comment by RonnyPfannschmidt** [comment]
well done, thanks

**Comment by david-fliguer-ws** [comment]
Hi, how do I use this ?

I have parametrized tests which name are WST_6,WST_7,WST_61,WST_62 and I want a way to run specifically test WST_6, if I use the -k parameter then it will run also WST_61 and WST_62.

How can I solve this ?

**Comment by RonnyPfannschmidt** [comment]
@david-fliguer-ws based on the test names you provided they cant be based on pytest parametrization, so this doesn't apply to you

**Pull request merged**
