### PR TITLE
pre-commit: add zizmor hook

### PR DESCRIPTION
**Pull request by bluetech**
Ensure we don't regress.

### CODE REVIEW

**Comment by webknjaz** [comment]
@bluetech how fast is the check compared to others? I tend to sort checks in pre-commit taking into account responsiveness and what files they mutate for best DX... You can see timings with `-vv`.

**Comment by webknjaz** [comment]
Looks like there's a race condition on RTD. I'll re-open the PR to trigger a rebuild.

**Review by nicoddemus — APPROVED** [review]

**Comment by nicoddemus** [comment]
> @bluetech how fast is the check compared to others? 

I would assume it is a local check only, so reasonably fast -- also it only runs in [changed files under `.github/workflows`](https://github.com/woodruffw/zizmor-pre-commit/blob/453c316a0ca6efdd7cc1449366b5464371e32f1c/.pre-commit-hooks.yaml#L6), so the hook will be skipped in most cases.

**Review by Pierre-Sassoulas — APPROVED** [review]
Great, I was waiting for something like this to run it, because I didn't want to install it myself !

> It is very fast locally. I'm not sure if you mean I should put it early or late?

Personally I sort them from fastest to slowest (with autofixxer first) so I have faster feedback if the fast one fail and no warning if something is autofixxable.

**Review by webknjaz — APPROVED** [review]
Yep, I also order them from fast to slow, except when there's dependencies between checks (like a formatter would run before a check targeting the same files).

**Pull request merged**
