### PR TITLE
doc: plugin link on readme.rst fixed

### PR DESCRIPTION
**Pull request by freelancing-solutions**
Close https://github.com/pytest-dev/pytest/issues/8619.

### CODE REVIEW

**Comment by freelancing-solutions** [comment]
document fix , 
Plugin list link is broken
a working link has been relocated to :
[plugin list ](https://docs.pytest.org/en/latest/reference/plugin_list.html)

**Comment by nicoddemus** [comment]
Thanks @freelancing-solutions. 

While usually we point to the `stable` docs, I think it makes sense here to point to `latest` instead.

**Review by The-Compiler — COMMENTED** [review]
Agreed that it makes more sense to point to `latest` here, especially because that page doesn't exist in `stable` at all.

However, I guess the version switch is a bit worrying though (if a user clicks through to the plugin list and then uses the docs menu, they'll end up with potentially "wrong" (i.e. too new) documentation, without noticing.

Not sure what to do here.

**Comment by nicoddemus** [comment]
> However, I guess the version switch is a bit worrying though (if a user clicks through to the plugin list and then uses the docs menu, they'll end up with potentially "wrong" (i.e. too new) documentation, without noticing.

But we don't include the `README.rst` file in the docs, so the only way for the user to use this link is through GitHub, unless I'm missing something. 🤔

**Comment by The-Compiler** [comment]
Ah, right, I missed that! Let's merge this then.

**Review by The-Compiler — APPROVED** [review]

**Pull request merged**
