### PR TITLE
WIP/RFC: remove pytest.python.Instance  [ci skip]

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/pytest-dev/pytest/issues/4127

### CODE REVIEW

**Comment by nicoddemus** [comment]
Just to note that this is breaking change as `pytest.Instance` is part of the API. We should figure out a way to deprecate its access somehow if we are to delete it in the future.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus this is one of the changes where i want to do a breaking release without the ramp ups

**Comment by nicoddemus** [comment]
Without the ramp ups because there's no sane way to generate a warning for this, correct? I agree, I can't think of a portable way to issue that warning either.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus correct

**Pull request closed without merging**
