### PR TITLE
pdb: try to import --pdbcls in pytest_configure only

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/pytest-dev/pytest/issues/5039.

### CODE REVIEW

**Comment by JBKahn** [comment]
Thanks for getting on this 😀

**Comment by blueyed** [comment]
@JBKahn 
Sure, I always like to fix regression I've caused.. ;)

Can you review / test it, please?

**Comment by nicoddemus** [comment]
> Can you review / test it, please?

Oh sorry, I might have merged this too soon. 😬

**Comment by blueyed** [comment]
@nicoddemus 
No worries, I've added tests.. :)

Thanks for merging!

**Pull request merged**
