### PR TITLE
Add Python 3.11 compatibility to 4.6.x

### PR DESCRIPTION
**Pull request by cielavenir**
This adds Python 3.11 compatibility to 2.7-compatible version.

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks @cielavenir,

Unless I'm mistaken, we do not plan to have any more 4.6.x releases. Can somebody else from the core team confirm?

**Comment by The-Compiler** [comment]
Agreed. The last 4.6.x release was over 3.5 years ago, and Python 2 has been EOL for just as long.

As per our [contribution guide](https://docs.pytest.org/en/7.4.x/contributing.html#backporting-bug-fixes-for-the-next-patch-release) (emphasis mine):

> Pytest makes a feature release every few weeks or months. In between, patch releases are made to the **previous feature release**, containing bug fixes only. The bug fixes usually fix regressions, but may be any change that should reach users before the next feature release.

**Comment by cielavenir** [comment]
our company just started Py3 migration and 1.16.x has to be used to maintain the transitional code base.

we can just build my branch internally, so this MR is like record, thanks

**Comment by The-Compiler** [comment]
Sorry to be blunt here, but I feel like this needs to be said: You're at least 4 years late with that migration, and I'd expect many other projects to not be willing to spend any sort of resources on this.

**Pull request closed without merging**
