### PR TITLE
Reference docs

### PR DESCRIPTION
**Pull request by nicoddemus**
This is an initial work to have a "Reference" page destined for users already familiar with pytest but want to quickly see the signature of an object or how to use a fixture.

Some notes:

- This also enables the [sphinxcontrib-trio](https://sphinxcontrib-trio.readthedocs.io/en/latest/) extension so we can have better representation of context managers and decorators (although the extension is named "trio", it is not specific to async or trio at all). Examples: [fixture signature](https://docs.pytest.org/en/ref-docs/reference.html#fixture-decorator-signature) and [capsys.disabled](https://docs.pytest.org/en/ref-docs/reference.html#_pytest.capture.CaptureFixture.disabled).
- Exceptionally I pushed this to the official repository instead of my fork so the docs can be built automatically for easier reviewing.

~~What are your thoughts and should I continue working on this?~~ Since I got a +1000, I've continued this effort. 

**Review link**: https://docs.pytest.org/en/ref-docs/reference.html

**TODO**

- [x] Marks
- [x] Objects (`Item`, `Module`, etc)
- [x] Functions (`pytest.fail`, `pytest.skip`, etc)
- [x] Parametrize
- [x] Hooks
- [ ] ~~Command-line options~~ (I've decided to leave this out for now)
- [x] Environment variables
- [x] `ini` options
- [x] Special variables (`pytest_plugins`, ...)

### CODE REVIEW

**Comment by nicoddemus** [comment]
Guys, just to be clear, while this is marked as WIP I still would like a quick review of the approach and a "go ahead" signal (or not). 👍

**Comment by flub** [comment]
+1000

**Comment by flub** [comment]
The approach seems fine as well, this would be a great addition.

**Comment by nicoddemus** [comment]
Thanks @flub for the feedback.

I worked a little more on it today.

**Comment by nicoddemus** [comment]
OK I think this is ready to be merged. 😅 This was much more work than I expected TBH.

The reference docs are not perfect, but I think they ares a step in the right direction, we can improve them over the course of more iterations in the future.

I plan to merge this in the next few days unless someone wants more time to take a look, in which case just leave a comment please. 👍

**Comment by nicoddemus** [comment]
This fixes: #1713 and #3229

**Pull request merged**
