### PR TITLE
infra: Temporary pin setup-python GH action to v2.1.4

### PR DESCRIPTION
**Pull request by antonblr**
Fix for  #8170 to address CI builds failure (will revert it once underlying issue is fixed)

*EDIT:* `setup-python` fix is out -  https://github.com/actions/setup-python/pull/172 (perhaps, we could update to new syntax too)

### CODE REVIEW

**Review by nicoddemus — APPROVED** [review]
Thanks @antonblr!

What's the new syntax you mention? I did glance quickly at the README but didn't notice anything different. 😁

**Comment by antonblr** [comment]
@nicoddemus - it was mentioned on the issue https://github.com/actions/setup-python/issues/171#issuecomment-747917974
Seems like there should be a dash followed by python major.minor version, like `pypy-3.7` or `pypy-3.8` (vs `pypy3` we have right now)

**Comment by nicoddemus** [comment]
Ahh I see, thanks! Sure, no problem in using the new syntax.

**Comment by asottile** [comment]
looks like https://github.com/actions/setup-python/issues/171 is fixed now -- I've opened #8172 with a revert + update

**Pull request merged**
