### PR TITLE
add rerun support to junitxml

### PR DESCRIPTION
**Pull request by n0npax**
Add support for rerunfailures to junitxml

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
@The-Compiler since we also do similar hacks for xdist, we should put some thought into this and either also move xdist handling out into xdist or consider letting people contribute detail handling for plugins we cant properly support with an api

**Comment by The-Compiler** [comment]
Why wouldn't we be able to add hooks for this instead? I can kind of see the point with xdist, I presume it just goes into pytest internals too deep, and IIRC it used to be part of pytest?

**Comment by RonnyPfannschmidt** [comment]
@The-Compiler well, xdist shouldn't be that special then - from my pov we should either allow such contributions, or work torwards getting xdist specials out of pytest, else we just hand externals a double standard, which sucks

after all this is working code and it solves a problem

**Comment by nicoddemus** [comment]
I agree with @The-Compiler, we should avoid adding special handling of plugins inside the core, but should strive instead to expose the functionality through hooks or an API so plugins can extend existing behavior. Adding special handling for plugins in the core does not scale and is a maintenance burden to the core in the long run.

The fact that xdist has special treatment should be considered a "wart", and not justification to further add special cases to the core IMHO.

As for the patch itself, I don't think `rerun` is a valid according to the junitxml schema, so this further hints to me that it shouldn't go into the core.

Unless I'm mistaken though, it should be a matter of thinking about one or two hooks to expose the ability to extend what's produced in the xml report. This should be simple to implement and then pytest-rerunfailures can benefit from it in 3.2 onwards.

@n0npax thanks for the patch, I know this debate is not what you expected but we as maintainers have to strive to make the correct decisions regarding future maintenance and extensibility.

**Comment by flub** [comment]
Hey @n0npax,

Would you mind adding the hook to _pytest/junitxml.py which would allow you to do this work in the rerunfailures plugin?  If you'd like some pointers please say and we can try point you in the right direction.

**Comment by n0npax** [comment]
@flub I'll try to implement it during this/next week.

**Comment by nicoddemus** [comment]
@n0npax awesome. As @flub said, please don't hesitate to ask for pointers.

Closing this for now then.

**Pull request closed without merging**
