### PR TITLE
[DEBUG/WIP] ci: Travis: remove most jobs running on GitHub now

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Will probably be superseded by https://github.com/pytest-dev/pytest/pull/6470 👍

**Comment by blueyed** [comment]
Flaky coverage due to py38-windows upload failure:
```
 Codecov upload22s
##[warning]Codecov warning: The process 'bash' failed with exit code 127
Run codecov/codecov-action@v1
##[warning]Codecov warning: connect ETIMEDOUT 35.199.43.247:443
bash codecov.sh -f ./coverage.xml -n windows-py38 -F GHA -y ""
codecov.sh: line 1: undefined: command not found
##[warning]Codecov warning: The process 'bash' failed with exit code 127
```
This is the only job that accidentally covered https://github.com/pytest-dev/pytest/pull/6529.

**Comment by nicoddemus** [comment]
It seems the coverage is fine now at 96.27%, awesome. 

I see the only one job running in Travis is to cover the 3.5.0/1 support code. We have two options:

1. Keep Travis running that job only.
2. Keep the 3.5.0/1 code uncovered.

**Comment by blueyed** [comment]
Yeah, keeping Travis for that job should be good.

Haven't checked this PR lately, but can clean it up / finish it later.

**Comment by nicoddemus** [comment]
Sounds good!

**Comment by blueyed** [comment]
@nicoddemus please take over.
FWIW 3.5.1 works for whatever reason in my fork.
You might want to remove it (Travis) here completely.

**Comment by hugovk** [comment]
One thing Travis might be useful for:

`3.9-dev` to test Python 3.9 alpha, ahead of it's full release in October, to avoid any surprises.

**Pull request closed without merging**
