### PR TITLE
[WIP] ci: tox/Travis: use pexpect for dep only

### PR DESCRIPTION
**Pull request by blueyed**
For https://github.com/pytest-dev/pytest/pull/5306 I would have to add
`testing/test_pytester.py` to the default pos args, but that would run
all other tests therein additionally.

This also adds pexpect tests to the MacOS job, which appears to have
caused trouble at least in the past, and likely needs fixing here before
this works.

TODO:

- [ ] might hang on py37-linux job

### CODE REVIEW

**Comment by jaraco** [comment]
@blueyed What are you looking for in my review? There's a whole chain of tickets leading to this one, enough that it'll take me awhile to try to understand what's going on here. Can you direct me to how I can help?

**Comment by blueyed** [comment]
@jaraco 
You were suggested as reviewer.
Please try if `tox -e py37-pexpect` works for you on MacOS with this branch.

**Comment by blueyed** [comment]
@jaraco 
Sorry for not being clear: it is mainly for this commit: https://github.com/pytest-dev/pytest/pull/5313/commits/2832e628267599398a7dc3d0692b524fc7c7684c.

**Comment by blueyed** [comment]
Pulled out the actual fixes into https://github.com/pytest-dev/pytest/pull/5336 - in case you want to test it, @jaraco.

**Comment by blueyed** [comment]
Moved into / closing in favor of https://github.com/pytest-dev/pytest/pull/5336.

**Pull request closed without merging**
