### PR TITLE
Use stanford theme

### PR DESCRIPTION
**Pull request by nicoddemus**
Use stanford theme for evaluation (#6402)

### CODE REVIEW

**Comment by The-Compiler** [comment]
Looking at https://github.com/LinxiFan/Sphinx-theme stanford mostly seems to be an outdated version of rtd:

> This branch is 25 commits ahead, 649 commits behind readthedocs:master.

Last update was over three years ago, so the chances of maintenance happening when needed for some reason (e.g. Sphinx upgrades?) are pretty slim. Also I don't think the colors really fit well for pytest.

**Comment by nicoddemus** [comment]
😞 shame, I liked it for some reason.

**Comment by blueyed** [comment]
Let's drop it from the options to chose from?

**Comment by nicoddemus** [comment]
Sure, done. 👍

**Pull request closed without merging**
