### PR TITLE
Consider session fixtures for doctest docstrings in modules

### LINKED ISSUE #768: doctests appear to run before session scope fixtures
Originally reported by: **Jason R. Coombs (BitBucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

----------------------------------------

I've created a session scoped fixture in ./conftest.py:

```
@pytest.fixture(autouse=True, scope='session')
def myfixture():
  raise ValueError()
```

Then, I create a module to be doctested:

```
def foo():
  """
  >>> assert True
  """
```

Then, I run pytest with `--doctest-modules`.

It completes one test on "mod.py" and it passes. Furthermore, if anything in the session scope is required by the doctest, it won't yet be setup. It seems that doctests are run outside of the test session.

I understand that session scope fixtures [are meant to serve as test setup and teardown](http://stackoverflow.com/a/12600154/70170). However, they seem not to be available for doctests.

Is there any way to set up the context for doctests? I'd like to incorporate another fixture from a plugin during setup as well.

----------------------------------------
- Bitbucket: https://bitbucket.org/pytest-dev/pytest/issue/768

### PR DESCRIPTION
**Pull request by nicoddemus**
Fixes #768

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
+1

**Comment by nicoddemus** [comment]
Triggered a new build manually now that devpi is back on.

**Comment by nicoddemus** [comment]
Fixed unused import and rebased it on `master`.

**Comment by hpk42** [comment]
Thanks, Bruno!

**Pull request merged**
