### PR TITLE
Add `FutureWarning` to `deprecated_call`

### LINKED ISSUE #11447: Add `FutureWarning` to `deprecated_call()`
#### What's the problem this feature will solve?

When implementing deprecated features, we are regularly expected to use the [`DeprecationWarning`][DeprecationWarning] and [`PendingDeprecationWarning`][PendingDeprecationWarning] warnings. However, there is another one: [`FutureWarning`][FutureWarning]. This particular warning is used by packages such as [`pydeprecate`][pydeprecate] as the default warning for any functions that will be removed in the future.

However, when I write a function that raises the [`FutureWarning`][FutureWarning] (or use the [`@deprecated`][pydeprecate] decorator), then [`deprecated_call()`][deprecated_call] currently does not catch the test successfully.

#### Describe the solution you'd like

I'd like to add [`FutureWarning`][FutureWarning] to the list of warnings which are captured by [`deprecated_call()`][deprecated_call].

This is the current behaviour:

```py
from warnings import warn
from pytest import deprecated_call

def deprecated_func():
    warn("This function is deprecated", DeprecationWarning)
    pass

def future_deprecation_func():
    warn("This function will be deprecated in the future", FutureWarning)
    pass

def test_deprecated():
    """Expected to pass"""
    with deprecated_call():
        deprecated_func()

def test_futures():
    """Expected to fail"""
    with deprecated_call():
        future_deprecation_func()
```

The expected behaviour would be for both of these two test cases to pass successfully.

#### Alternative Solutions

N/A

#### Additional context

N/A

[DeprecationWarning]: https://docs.python.org/3/library/exceptions.html#DeprecationWarning
[PendingDeprecationWarning]: https://docs.python.org/3/library/exceptions.html#PendingDeprecationWarning
[FutureWarning]: https://docs.python.org/3/library/exceptions.html#FutureWarning
[pydeprecate]: https://borda.github.io/pyDeprecate/
[deprecated_call]: https://docs.pytest.org/en/7.4.x/reference/reference.html#pytest.deprecated_call

### PR DESCRIPTION
**Pull request by chrimaho**
- [x] Updated documentation to include updated features.
- [x] Include new tests or update existing tests when applicable.
- [x] Allow maintainers to push and squash when merging my commits.
- [x] Closes #11447
- [x] Create a new changelog file in the `changelog` folder. 
- [x] Added yourself to `AUTHORS` in alphabetical order.
- [ ] 

Close #11447

### CODE REVIEW

**Review by RonnyPfannschmidt — CHANGES_REQUESTED** [review]
As futurewarning doesn't relate to deprecation,its wrong to add it there

**Comment by The-Compiler** [comment]
@RonnyPfannschmidt I've mentioned this over in #11447 already, but the [Python docs](https://docs.python.org/3/library/exceptions.html#FutureWarning) clearly disagree with you:

> Base class for warnings **about deprecated features** when those warnings are intended for end users of applications that are written in Python.

**Review by RonnyPfannschmidt — COMMENTED** [review]
changing back to comment after reading up on the details probided by @The-Compiler

**Comment by RonnyPfannschmidt** [comment]
@The-Compiler after crosschecking the documentation text used, i`m under the strong impression that 

`FutureWarning` is supposed to be end user facing, not programmer facing - as such the usage in the programmer-facing library is incorrect

the documentation text is 
```
Base class for warnings about deprecated features when those warnings are intended for end users of applications that are written in Python.
```

the linked library is clearly targeted at programmers and to my understanding it is using the wrong warning type here

IMHO we should not mix user facing warnings and programmer facing warnings without a way to control the choice

**Comment by The-Compiler** [comment]
People test end-user facing applications with pytest (that's my primary usage of pytest, FWIW). We do already have a way to control which warning is emitted if you want to be specific: `pytest.warns`.

`pytest.deprecated_call` is already a rather "fuzzy" convenience alias because it doesn't discern `DeprecationWarning` and `PendingDeprecationWarning`. IMHO we shouldn't have it at all, yet here we are — and including two out of three deprecation-related stdlib warnings with an API with a generic name seems like a major footgun.

**Comment by RonnyPfannschmidt** [comment]
thank you for elaborating, consider me convinced

**Review by RonnyPfannschmidt — APPROVED** [review]

**Review by nicoddemus — APPROVED** [review]

**Comment by nicoddemus** [comment]
Thanks a lot everyone for the discussion and @chrimaho for the contribution!

**Pull request merged**
