### PR TITLE
Use inspect to properly detect generators. Fixes #2129

### LINKED ISSUE #2129: _pytest.compat.is_generator incorrectly identifies coroutine functions
https://gist.github.com/malinoff/148507bf51ff8b9a0a947c178aa0ac3a

I don't know what exactly, but something magical definitely happens during `_pytest._code` import.

### PR DESCRIPTION
**Pull request by malinoff**
- [x] Make sure to include one or more tests for your change;
- [ ] Add yourself to `AUTHORS`;
- [ ] Add a new entry to `CHANGELOG.rst`
  * Choose any open position to avoid merge conflicts with other PRs.
  * Add a link to the issue you are fixing (if any) using RST syntax.
  * The pytest team likes to have people to acknowledged in the `CHANGELOG`, so please add a thank note to yourself ("Thanks @user for the PR") and a link to your GitHub profile. It may sound weird thanking yourself, but otherwise a maintainer would have to do it manually before or after merging instead of just using GitHub's merge button. This makes it easier on the maintainers to merge PRs.

### CODE REVIEW

**Comment by malinoff** [comment]
With this fix, gist (https://gist.github.com/malinoff/148507bf51ff8b9a0a947c178aa0ac3a) output is
```
$ python example.py
False
False
False
False
True
```

**Comment by malinoff** [comment]
Errors do not seem to be related to my change.

**Comment by nicoddemus** [comment]
Thanks @malinoff and @RonnyPfannschmidt, I will take a more detailed look at the PR and the CI errors but probably will only have time for it later in the week though.

**Comment by nicoddemus** [comment]
I pushed some commits to the PR:

* The errors were related to the new `asyncio` import, which in turn imports `logging` which breaks an acceptance test for #8. I had to resort to copy the relevant 2-lines function to circumvent that. It is simple enough so IMHO it shouldn't be a problem.
* Updated the CHANGELOG;
* Moved the "compat" tests to a single module and used `testdir` on the tests with newer Python syntax. While I usually prefer unit-tests instead of integration tests when possible, I think it is acceptable in this case to avoid importing `asyncio` into pytest's process and the flake8 errors.

Thanks again to @malinoff for pursuing this. 👍

**Comment by nicoddemus** [comment]
Hmmm now `py27-trial` is also breaking. Perhaps it is related to #1989?

**Comment by malinoff** [comment]
@nicoddemus could you please merge this?

**Comment by nicoddemus** [comment]
@malinoff I would like to take a look at the trial failures first. While they seem unrelated, I'm not sure.

Are you using pytest in development mode?

**Comment by nicoddemus** [comment]
The trial failures are certainly unrelated since they are happening on `master` as well and this PR has been open long enough, so I'm merging this.

Thanks @malinoff for the patience! 🙇

**Comment by dmalinovsky-issart** [comment]
Yay! Thanks @nicoddemus

**Comment by malinoff** [comment]
Yay! Thanks @nicoddemus

**Pull request merged**
