### PR TITLE
Revert "fixtures register finalizers with all fixtures before them in the stack"

### PR DESCRIPTION
**Pull request by nicoddemus**
This PR reverts #6438 due the problems shown in #6492.

I plan to make a hotfix release after this as I suspect this will break many test suites.

---

This reverts commit 99180939febb6ca4b3ff788cf336b065046653f2 (cc @SalmonMode)

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks. 👍 

I will hold on a bit to merge/releasing 5.3.4 depending on #6492's progress.

**Comment by nicoddemus** [comment]
#6492 is still in progress... should we wait some more or cut a new release?

@SalmonMode what's your feeling? Do you believe you are advancing in a solution?

@RonnyPfannschmidt @asottile @blueyed @bluetech what are your thoughts? 

If @SalmonMode feels we are getting closer to a resolution I would rather wait a bit more instead of causing more noise with a hotfix release.

**Comment by RonnyPfannschmidt** [comment]
i would propose that we set out for a release at he end of the day  unless we get  new information,
while its indeed better to ship the good fixes that are in preparation - its a pain for the users to have a latest release that breaks some things, and the longer we wait, the  more pins will have to be undone for our users.

**Comment by blueyed** [comment]
+1 for reverting it (the earlier the better).
It is totally unclear how many different issues this is causing still, and we do not even have a single test for any of them.

(JFI: I would do this via some searate release branch though, since we plan to keep this (on master) after all (and plan to "revert the revert", i.e. causing diff churn) - but I also know that it's not "how it works here").

**Comment by nicoddemus** [comment]
Pushed a changelog entry; will merge and prepare a new release afterwards.

**Comment by bavedarnow** [comment]
Are there any tests that can be added to ensure this break doesn't happen in the future?

**Comment by nicoddemus** [comment]
@bavedarnow 

> Are there any tests that can be added to ensure this break doesn't happen in the future?

We don't have any at the moment, but definitely as part of the fix for this issue we will need to add new tests.

**Comment by SalmonMode** [comment]
@bavedarnow @nicoddemus the change this reverted solved a pretty core issue that some things depended on (usually without having any idea that they were). The issues popping up seem to be in the plugins used, rather than this change itself.

E.g. #6492 was actually an issue with `pytest-django` and how it determined what the suffix should be for a given worker's DB should be. It assumed something wasn't being cleaned up, which is why it didn't keep adding more suffixes on before the fix. After the fix, it had to run through that logic again, and the name kept getting longer.

I'm not sure what tests _could_ be added to check for such things. Maybe a successfully built pytest job could kick off builds of the builds for all the official pytest plugins to see if they had any regressions?

**Comment by blueyed** [comment]
> I'm not sure what tests _could_ be added to check for such things.

We should add tests for issues found with it, e.g. reproducing what you've described with pytest-django.

> Maybe a successfully built pytest job could kick off builds of the builds for all the official pytest plugins to see if they had any regressions?

It would make sense to run test suites of e.g. pytest-django when doing a release, yes.

**Comment by SalmonMode** [comment]
> We should add tests for issues found with it, e.g. reproducing what you've described with pytest-django.

@blueyed I might be able to do it if I involve `django`, `pytest-django`, and `pytest-xdist`, by having a bunch of tests, each one effectively asserting the database name is `"test_thing_<worker_id>"`

**Comment by blueyed** [comment]
@SalmonMode that's a test pytest-django has already.  We should be able to reproduce what is happening there.  Also with regard to the other thing you've addressed, where it appears that fixtures are not used in the correct order anymore (tox/xdist vs xdist/tox suffix).

**Comment by SalmonMode** [comment]
@blueyed ah, yes. it seems pytest-django almost has tests for that as well, as there were tests dependent on the order of them, but didn't check everything they should. I'll update them to make sure it's absolutely covered.

**Comment by nicoddemus** [comment]
@SalmonMode 

> @bavedarnow @nicoddemus the change this reverted solved a pretty core issue that some things depended on (usually without having any idea that they were). The issues popping up seem to be in the plugins used, rather than this change itself.

**Comment by SalmonMode** [comment]
@nicoddemus I have a fix ready for pytest-django here https://github.com/pytest-dev/pytest-django/pull/807

I was able to run it against the branch linked here https://github.com/pytest-dev/pytest/issues/6492#issuecomment-576057075 for that issue, and it was resolved.

As for #6512, I don't believe that's actually a bug.

I expected a lot of folks would have issues because they never saw failures as a result of things not tearing down when they should have, so now that they are, more operations are being performed, and resources may no longer be available when they were previously. I added a pretty large test to make sure the order of setup/teardown is as it should be, and it's passing. So unless someone can produce an example (of any size or complexity) to the contrary, there's nothing to investigate.

> Oh and BTW, in case it is not clear, we greatly appreciate all the effort you are putting into this (both in the initial patch as well as trying to fix regressions); we know this is a very complex part of the code base, very tricky to get right (we also made a very breaking release when I tried to implement "invocation-scoped" fixtures a while back).

It's been one heck of a week :joy:. But I've enjoyed it and it's given me a much greater understanding of pytest's inner workings as well as a few of its plugins :slightly_smiling_face:. And, if I hadn't been in meetings this morning, I would have also recommended pulling my change out. I can always make a duplicate branch and PR later

**Pull request merged**
