### PR TITLE
pytest-dev#7942 test_runner_xunit.py

### PR DESCRIPTION
**Pull request by pillemer**
migrating test_runner_xunit.py from testdir to pytester.
I'm new to contributing and am eager to learn so please let me know if I've done anything wrong (or right).

### CODE REVIEW

**Review by bluetech — APPROVED** [review]
Hi @pillemer, you did everything correctly, so it's ready to merge!

Since you asked for feedback, the only comment I have is to write the issue number in the PR body instead of the title, and write it as just `#7942` instead of `pytest-dev#7942`. This is so that GitHub properly links it. This is extremely minor and I wouldn't mention it unless you asked :)

You can add yourself to `AUTHORS` file if you'd like, and mark the PR as ready, and then I'll merge it.

**Comment by pillemer** [comment]
Hi @bluetech, thanks for the feedback! I've added myself to the `AUTHORS` and marked this as `Ready for review`.

**Review by nicoddemus — CHANGES_REQUESTED** [review]
@pillemer you've created https://github.com/pytest-dev/pytest/pull/7973 instead of adding yourself to AUTHORS here. 😁 

Please just update this PR adding yourself to AUTHORS then we can merge it. 👍

**Comment by pillemer** [comment]
Sorry @nicoddemus!
I see now what I've done wrong. I need to make the changes in the same branch otherwise it will create a brand new pull request. I think  I did it right this time.
Thank you for your patience.

**Pull request merged**
