### PR TITLE
Release 3.9.0

### PR DESCRIPTION
**Pull request by nicoddemus**
.

### CODE REVIEW

**Comment by nicoddemus** [comment]
Sadly deployment failed:

```
HTTPError: 400 Client Error: '"https://docs.pytest.org/en/latest/"' is an invalid value for Home-Page. Error: Invalid URI See https://packaging.python.org/specifications/core-metadata for url: https://upload.pypi.org/legacy/
```

@RonnyPfannschmidt I suspect the problem is this line:

https://github.com/pytest-dev/pytest/blob/e4e4fd1e521c3a6235adedb179915c9c74bd08d4/setup.cfg#L6

Should this be done without quotes?

**Comment by RonnyPfannschmidt** [comment]
i think so, i missed the mistake when inspecting the wheels

**Comment by nicoddemus** [comment]
Bummer. We will have to release `3.9.1` then and mark `3.9.0` on the CHANGELOG as never-released.

**Comment by nicoddemus** [comment]
Is there some command we can run that inspect the generated wheels to detect this kind of problem in the future? If there is, I would like to run that command as part of our normal testing.

**Comment by RonnyPfannschmidt** [comment]
im not aware of a tool off-hand - we should consult pypa ^^

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus dont we need to merge the branch to sort out the release process correctly?
please restore it, then we can add a commit with the note and merge it as starting point for 3.9.1

**Comment by nicoddemus** [comment]
I would rather not, because we did not in fact released the package.

I think the protocol now should be to open a new release PR, fix the metadata, and manually adjust the changelog to mention that 3.9.0 was never released.

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt do you have the time to open the PR fixing the metadata and the new release, or would you like me to do it?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i still haven't resolved my massive issues with regendoc

**Comment by nicoddemus** [comment]
I think it is fine to just start from my last commit on this branch and then:

1. Fix the metadata;
2. Update the CHANGELOG manually by changing the `3.9.0` release to `3.9.1`, and add a new `3.9.0` release below that.

I would do it myself, but I'm not sure if just removing the quotes from the home page URL is enough to fix 1).

**Pull request closed without merging**
