### PR TITLE
Allow for "pdb" module to be rewritten

### PR DESCRIPTION
**Pull request by blueyed**
Noticed this with tests for pdb++.

### CODE REVIEW

**Comment by blueyed** [comment]
Note that it still tries to rewrite it (https://github.com/pytest-dev/pytest/blob/c1361b48f83911aa721b21a4515a5446515642e2/src/_pytest/assertion/rewrite.py#L233-L234), and might succeed (likely due to the "pdb" module being re-imported explicitly in the tests).

**Comment by nicoddemus** [comment]
Needs rebase once https://github.com/pytest-dev/pytest/pull/5923 is merged

**Comment by blueyed** [comment]
> Missing changelog, otherwise LGTM. ￼

Isn't that just noise?  (quite internal isn't it?).

**Comment by nicoddemus** [comment]
> Isn't that just noise? (quite internal isn't it?)

Fair enough. 👍

**Pull request merged**
