### PR TITLE
Refactored old style classes to new style classes

### PR DESCRIPTION
**Pull request by mandeep**
Added (object) to the end of class names as discussed in #2147. I searched the pytest package folder with the regex "class [A-Z]\w*(?<!\():" and added (object) before the colon of each class. The tests passed as expected. Thoughts?

### CODE REVIEW

**Comment by mandeep** [comment]
Thanks @RonnyPfannschmidt. Let me know if I need to edit AUTHORS and the CHANGELOG.

**Comment by RonnyPfannschmidt** [comment]
@mandeep oh, that would make sense, it is a slight behaviour change after all

**Comment by nicoddemus** [comment]
I agree that an entry to the CHANGELOG is in order. 👍 

Thanks @mandeep for the PR, appreciate it.

**Comment by RonnyPfannschmidt** [comment]
yay - kudos @mandeep  🎉

**Comment by mandeep** [comment]
Thanks! @RonnyPfannschmidt @nicoddemus

**Pull request merged**
