### PR TITLE
Discourage users from using unittest support somewhat

### PR DESCRIPTION
**Pull request by ionelmc**
After some discussion @nedbat on IRC - he simply don't believe TestCase are bad :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks @ionelmc! 

I like the change, but I'm curious about what the discussion entailed. Also, the title talks about discouraging users from using `unittest`, while your comment indicates that @nedbat actually thinks it is OK to keep `TestCase` subclasses around. 

Would love to understand better what was the discussion about. 😁

**Comment by ionelmc** [comment]
Well, @nedbat, what do you think of it now?

**Comment by RonnyPfannschmidt** [comment]
personally i think we should put it even more harsh and ourtight say that some of us would be happy to fix those details as part of a consulting gig, but its certainly neither easy nor fun work

**Comment by ionelmc** [comment]
@nicoddemus the discussion was basically me saying mean things about @nedbat's testcases and bragging about converting around 40k sloc worth of testcase code to fixtures. It only took a week - what's the big deal 😁

**Comment by nicoddemus** [comment]
@ionelmc thanks for the summary! 👍 

Could you please take a look at the failure on the `docs` env?

**Comment by nicoddemus** [comment]
Thanks @ionelmc!

(Just a small heads up, prefer to open PRs from your own fork, even if you have write access to the repository like you do here, otherwise CI services will run twice: once for your branch and another for the PR).

**Pull request merged**
