### PR TITLE
Fix `MonkeyPatch.context`

### PR DESCRIPTION
**Pull request by harupy**
Fix https://docs.pytest.org/en/latest/reference/reference.html#pytest.MonkeyPatch.context

image

### CODE REVIEW

**Comment by harupy** [comment]
It looks like pre-commit reverted my change

**Comment by Pierre-Sassoulas** [comment]
It seems due to something in ruff / pydocstyle, Do you care to investigate (You need to remove the ``--fix`` option to see what message is causing problem).  There's a chance it introduced this issue in more place than just this file.

**Comment by harupy** [comment]
Is https://docs.astral.sh/ruff/rules/blank-lines-between-header-and-content the cause?

**Comment by Pierre-Sassoulas** [comment]
You can revert [53e9aa4](https://github.com/pytest-dev/pytest/pull/12375/commits/53e9aa46045d7b81f43fbdd303ff698dedf6f45c) and disable D412 to be sure, here:

https://github.com/pytest-dev/pytest/blob/24abe4eb03f64bfed301e6d70dfcf4f0c6a8cc0e/pyproject.toml#L135-L136

Reverting the problems introduced without tracking them all, could get technical. I guess reverting and reapplying then squashing could work. Let me know if I should take over.

**Pull request closed without merging**
