### PR TITLE
Move python api code to own file

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
Thanks for submitting a PR, your contribution is really appreciated!

Here's a quick checklist that should be present in PRs:

- [x] Add a new news fragment into the changelog folder
  * name it `$issue_id.$type` for example (588.bug)
  * if you don't have an issue_id change it to the pr id after creating the pr
  * ensure type is one of `removal`, `feature`, `bugfix`, `vendor`, `doc` or `trivial`
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."
- [x] Target: for `bugfix`, `vendor`, `doc` or `trivial` fixes, target `master`; for removals or features target `features`;
- [x] Make sure to include reasonable tests for your change if necessary

### CODE REVIEW

**Comment by nicoddemus** [comment]
Also what's the intent for moving those classes?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus cutting down the file sizes before introducing `FunctionDefinition?`

**Comment by nicoddemus** [comment]
OK, was just wondering. `python_api` sounds like something we want to make public, that's why I asked.

**Comment by RonnyPfannschmidt** [comment]
wrt the filename - api.py seems a bit short and non-saying - same for python api

i do wonder about splitting logical bits into more files

**Comment by RonnyPfannschmidt** [comment]
but yeah, this can be merged ^^

**Pull request merged**
