### PR TITLE
doctest: unset RUNNER_CLASS in pytest_unconfigure

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by blueyed** [comment]
Ok, that was nasty.. - see the commit message.

**Comment by blueyed** [comment]
To reproduce: `pytest testing/acceptance_test.py -k test_doctest_id`

**Comment by RonnyPfannschmidt** [comment]
this one is most confusing - this is just caching a lazy import/codegen, does that surround inprocess sys.modules cleanup?

**Comment by blueyed** [comment]
Yes.

**Comment by RonnyPfannschmidt** [comment]
lets adda followup to put this into a per config storage then, or ensure we import doctest in the testsuite instead

**Comment by blueyed** [comment]
https://github.com/pytest-dev/pytest/pull/5847/files#diff-df80246215438974e5e2656c15531696 changes it already a bit - might at least be affected then still (since the class appears to be cached there also/additionally) /cc @bluetech

**Comment by blueyed** [comment]
Should we take this then for now?

**Comment by RonnyPfannschmidt** [comment]
this pr is fine for now, we just should take a look at doing a followup

**Pull request merged**
