### PR TITLE
fix #510 by adding a describing skip marker on empty parameterize

### LINKED ISSUE #510: Multiple calls to parametrize result in empty value lists not skipping the test
Originally reported by: **Alex Stapleton (BitBucket: [private](http://bitbucket.org/private), GitHub: [private](http://github.com/private))**

----------------------------------------

If you call parametrize on a test more than once for different arguments of the test it doesn't seem to combine the parameters correctly if some of them are empty. This results in tests that would normally get skipped because their parametisation is missing values receiving the internal `_notset` sentinel object for that fixture.

Examples here https://gist.github.com/public/e671a53b70fbb6fb6129

The last example is the simplest reproduction of the problem.

This does not get skipped and `fixP` is `_notset`.

```
@pytest.mark.parametrize(["fixP"], [(1,)])
@pytest.mark.parametrize(["fixQ"], [])
def test_fixA_fixB_bad2(fixP, fixQ):
    print fixP, fixQ
```

but if you swap the order of the calls to parametrize...

```
@pytest.mark.parametrize(["fixQ"], [])
@pytest.mark.parametrize(["fixP"], [(1,)])
def test_fixA_fixB_bad2(fixP, fixQ):
    print fixP, fixQ
```

it skips as you would expect from reading the documentation.

I've reproduced this on 2.5.2 and on the current master 2.6 branch.

----------------------------------------
- Bitbucket: https://bitbucket.org/pytest-dev/pytest/issue/510

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
this might need to go to features

also we might want to consider using a xfail marker with run=False instead of skip

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
also fml for formatting fixes

**Comment by nicoddemus** [comment]
LGTM

**Comment by RonnyPfannschmidt** [comment]
while working on the features branch, i noticed a correct skip that is checking for an apparently missing attribute

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt could you take a look at the failing AppVeyor build?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus it seems that one is related to the config filename on non-posix fix

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt could you rebase this and try again? This is fixed on `master` already.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i figured the underlying issue, the one on master was not composable

**Comment by RonnyPfannschmidt** [comment]
i removed the old hack and always use the marker

this has the upside of always composing and the downside of hiding one of the error in case of a double empty parametrize

**Comment by nicoddemus** [comment]
Thanks, the new code looks better indeed. :grin:

**Pull request merged**
