### PR TITLE
Clarify error message in case no collectors are found for a file

### PR DESCRIPTION
**Pull request by tobiasdiez**
In case no collector is found for a given file (e.g. if you run `pytest something.unrecognized`), then the somewhat cryptic error message
```
ERROR: not found: something.unrecognized
(no name 'something.unrecognized' in any of [])
``` 
With this PR, a more meaningful error message is displayed.

Not sure if such an almost-trivial change warrants an a changelog and authors entry.

### CODE REVIEW

**Review by nicoddemus — CHANGES_REQUESTED** [review]
Thanks for the PR!

> Not sure if such an almost-trivial change warrants an a changelog and authors entry.

I think so, improvements (however small) are worthy of note. 😁 

Plus we need a test for the change, specially to ensure it doesn't regress. 👍

**Comment by tobiasdiez** [comment]
Thanks for the feedback. I've now added a changelog and authors entry, and fixed the tests.

**Review by nicoddemus — APPROVED** [review]
Looks great, thank you!

**Comment by Zac-HD** [comment]
@tobiasdiez - you'll need to merge in `main` in order to fix the `jinja2` issue; then we should be ready to merge 🎉

**Comment by tobiasdiez** [comment]
Thanks, that worked like a charm!

**Comment by Zac-HD** [comment]
Thank *you* for the patch! Good error messages are enormously important to users, but so often neglected - it's a tricky form of "expert blindness" which makes contributions especially valuable 😍

**Pull request merged**
