### PR TITLE
Use multiple issue template types and mention Discussions

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Review by gnikonorov — APPROVED** [review]
This is awesome! Thanks @nicoddemus

**Review by asottile — APPROVED** [review]

**Comment by The-Compiler** [comment]
Wouldn't it make more sense to use GitHub's issue type selectors to point to discussions? Here's an example:

- https://github.com/qutebrowser/qutebrowser/issues/new/choose
- https://github.com/qutebrowser/qutebrowser/tree/master/.github/ISSUE_TEMPLATE

I'm -0.5 on this, as it doesn't seem to be the right mechanism and will lead to some people most likely just leaving this text inside their issues instead of deleting it.

**Comment by nicoddemus** [comment]
> Wouldn't it make more sense to use GitHub's issue type selectors to point to discussions?

Oh yeah I forgot a about that feature. I agree it is both much nicer as well as points people in the general direction!

Would you like to tackle that?

**Comment by nicoddemus** [comment]
@The-Compiler done, thanks!

**Review by asottile — APPROVED** [review]

**Comment by The-Compiler** [comment]
Looks great, thanks @nicoddemus and sorry for the delay!

**Pull request merged**
