### PR TITLE
Initial attempt at #7012; strip falsey values from strargs

### PR DESCRIPTION
**Pull request by symonk**
An attempt at fixing #7012, honestly I am not sure if this is the correct place to be doing this, the code base is completely new to me and pretty vast, feedback here is greatly appreciated by someone who knows the code base nicely.

I was able to recreate the issue of duplicate collection and my newly added tests confirms the fixed behaviour, regression suite remains passing.

Thanks for your time, have a great day and I look forward to your feedback.

- [X] Allow maintainers to push and squash when merging my commits. Please uncheck this if you prefer to squash the commits yourself.

### CODE REVIEW

**Comment by symonk** [comment]
ok looks not so simple, codecov is not very happy with the drop :) I'll await some feedback on the overall approach, likely its in the completely wrong place

**Comment by symonk** [comment]
"args" seems to have some immutability (provided by @attr (new to me)), should we do this check somewhere much sooner?

**Comment by symonk** [comment]
@bluetech excellent thanks for the feedback, I will go back and investigate :) any recommendations on the best place for handling it?

**Comment by bluetech** [comment]
> any recommendations on the best place for handling it?

Not out of hand, though I can look if needed.

> I am not so sure its truly a bug, but rather expected behaviour, for example:

Right, good find! According to #1187, this is expected behavior, though it does seem a little odd to me. On the other hand, if you don't want to run a test more than once, don't specify it more than once :smiley:

Perhaps the right move for now is for the reporter to move to reopen the issue.

**Comment by bluetech** [comment]
Actually, it seems like that decision was overturned in #1609 and the behavior was changed to remove duplicate tests by default, with a `--keep-duplicates` flag to disable it. So it does seem like a bug.

My suggestion would be to look at `--keep-duplicates` (or rather what it *disables*) and find the bug there.

**Comment by symonk** [comment]
Looking at something else right now then i will have a look at this again, would there be any merit in converting strargs to a set() ? will spend some time digging after.  I am having terrible trouble being able to debug the codebase using pycharm.  pdb is OK for now, but not ideal! it complains 'pytester' plugin is already registered with the pluginmanager when running from pycharm for me

**Comment by symonk** [comment]
Free up again, will investigate a better solution. did some reading on the links provided - thanks again

**Pull request closed without merging**
