### PR TITLE
Release 3.0.4

### PR DESCRIPTION
**Pull request by nicoddemus**
Builds:
* [Travis](https://travis-ci.org/nicoddemus/devpi-cloud-tester/builds/174613785)
* [AppVeyor](https://ci.appveyor.com/project/nicoddemus/devpi-cloud-tester/build/1.0.26)

### CODE REVIEW

**Comment by nicoddemus** [comment]
Two Travis failures:

* `py35-trial`: #1989
* `doctesting`: recently re-enabled (37dcdfbc58441a266272d8ab4a8cc985ca51fb84), it seems testing the package using `devpi test` doesn't work because of the `MismatchImportError` (#2042).

IMHO those are not release-blocking.

**Comment by nicoddemus** [comment]
Same `doctesting` failure on AppVeyor.

**Comment by The-Compiler** [comment]
The diff LGTM

**Comment by nicoddemus** [comment]
Any thoughts on the failures? Are they release blocking or should we move on with the release? 😁

**Comment by The-Compiler** [comment]
After having a closer look, I think they're "fine" as well.

**Comment by nicoddemus** [comment]
@hpk42, @RonnyPfannschmidt any opinions here?

**Comment by hpk42** [comment]
i am fine -- too busy with pluggy, tox and other releases to check in any detail.  but i wouldn't know what speaks against it :)

**Pull request merged**
