### PR TITLE
Merge master into features

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by blueyed** [comment]
Azure down?

**Comment by nicoddemus** [comment]
Not sure... weird that `master` has just passed on Azure. Seems to be a fluke.

Want me to push this again or can we trust on Travis? (I'm in for the latter)

**Comment by blueyed** [comment]
No, please re-run / just wait.

**Comment by blueyed** [comment]
(it is useful for later coverage comparison etc, based on this commit)

**Comment by nicoddemus** [comment]
Pushed again, let's see

**Comment by nicoddemus** [comment]
There it goes. 👍

**Comment by nicoddemus** [comment]
Thanks for the heads-up, fixed.

**Pull request merged**
