### PR TITLE
Simplify Argument.__repr__

### PR DESCRIPTION
**Pull request by blueyed**
I have came across this when noticing that universal-ctags fails to parse
this correctly (https://github.com/universal-ctags/ctags/issues/997).

### CODE REVIEW

**Comment by blueyed** [comment]
Rong - will add a test.

**Comment by nicoddemus** [comment]
> Rong - will add a test.

You plan to write a test for this first @blueyed?

**Comment by nicoddemus** [comment]
> Rong - will add a test.

You plan to write a test for this first @blueyed?

**Comment by blueyed** [comment]
@nicoddemus 
Yep, done.  Let's see if now still passes.

**Comment by nicoddemus** [comment]
Failed apparently, could you take a look please?

**Comment by nicoddemus** [comment]
Thanks! :grin:

**Pull request merged**
