### PR TITLE
python: a few cleanups

### PR DESCRIPTION
**Pull request by bluetech**
This PR contains a few code cleanups/improvements. Please see the commits.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
I believe the intent for make item was to be truely last, for which it should use a tryfirst hookwrapper

Lovely changes, going to take a closer look at the computer later

**Comment by bluetech** [comment]
> I believe the intent for make item was to be truely last, for which it should use a tryfirst hookwrapper

Right, the hookwrapper would guarantee that this hookimpl would go after even another hook which uses `trylast=True`. But the question is why? We don't try to do it for other hooks. In fact, for `firstresult` hooks we usually provide a default impl without even `trylast`. The external plugins would normally win because they are registered after the builtin plugin. Or they could use `tryfirst=True`.

So maybe it shouldn't be `trylast=True` either..

**Comment by nicoddemus** [comment]
> So maybe it shouldn't be trylast=True either..

I'm guessing it might be because `unittest`'s and `python`'s `pytest_pycollect_makeitem` hooks might match the same match object, but we want `unittest` to always take precedence regardless of the order of the plugins listed as builtin?

**Comment by bluetech** [comment]
> I'm guessing it might be because unittest's and python's pytest_pycollect_makeitem hooks might match the same object, but we want unittest to always take precedence regardless of the order of the plugins listed as builtin?

I think it's reasonable to rely on builtin plugins' registration order, but let's keep the `trylast=True` to be safe.

**Comment by nicoddemus** [comment]
> I think it's reasonable to rely on builtin plugins' registration order, but let's keep the trylast=True to be safe.

Agree on both accounts. 😁

**Pull request merged**
