### PR TITLE
Fix the "setup.py test" command for updated src/ layout

### PR DESCRIPTION
**Pull request by felixonmars**
Addresses #3536

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks @felixonmars,

I did try your branch in fresh virtual environment, but it doesn't seem to work:

```
λ python setup.py  test
C:\Users\Bruno\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)
running test
Traceback (most recent call last):
  File "src/pytest.py", line 9, in <module>
    from _pytest.config import main, UsageError, cmdline, hookspec, hookimpl
  File "c:\pytest\src\_pytest\config.py", line 9, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

Is the command supposed to install dependencies? If it is, then `setup.py test` has been broken for quite some time.

**Comment by felixonmars** [comment]
I did not rely on the dependency resolver AFAIK, it was used in Arch Linux's packaging of pytest. I have switched to a manual call to pytest.py on 3.6.1 for now (see below), so if you have decided to discontinue support for the old style, I‘ll continue use that in the future.

```
PYTHONPATH="$PWD"/build/lib python src/pytest.py
```

**Comment by RonnyPfannschmidt** [comment]
the test command su supposed to test the local package at least in terms of setuptools

testing the build folder is kind of wrong in any case

from the full context i beleive we should remove the command as its not applicable to pytest as is

**Comment by nicoddemus** [comment]
Everything I asked in https://github.com/pytest-dev/pytest/issues/3536#issuecomment-395116847 has been answered here, thanks @felixonmars and @RonnyPfannschmidt!

**Comment by nicoddemus** [comment]
Thanks everyone for the discussion. Closing in favor of #3536.

**Pull request closed without merging**
