### PR TITLE
Docs: Fix link anchor

### PR DESCRIPTION
**Pull request by hugovk**
- [x] Target the `master` branch for bug fixes, documentation updates and trivial changes.

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks @hugovk!

**Comment by asottile** [comment]
@nicoddemus should we backport this? or is it less important that the 4.6.x docs are perfectly up to date?

**Comment by nicoddemus** [comment]
>  is it less important that the 4.6.x docs are perfectly up to date?

It is, I don't think we will publish separate docs for the 4.6.X series: new 5.0+ features will be marked clearly as such, same as we have been doing with the previous releases. What do yuo think?

**Comment by asottile** [comment]
sg2m

**Pull request merged**
