### PR TITLE
doctest: lazily import bdb

### PR DESCRIPTION
**Pull request by blueyed**
Follow-up to 63d517645.

### CODE REVIEW

**Comment by The-Compiler** [comment]
Why? Is there a downside to importing it globally?

**Comment by blueyed** [comment]
A bit faster I assume?

**Comment by The-Compiler** [comment]
The same could be said about all the imports in all files - I don't really see the point of deviating from what's being done everywhere else.

**Comment by blueyed** [comment]
Sure, but that showed in the diff between master and features (recently added, I've linked the commit).  Therefore I've thought it would be better to be faster.
Feel free to closeit, I have no strong opinion about it.

**Comment by blueyed** [comment]
Closing - please speak up if you care for quality.

**Pull request closed without merging**
