### PR TITLE
Add good talk by Andrew Svetlov

### PR DESCRIPTION
**Pull request by gyermolenko**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks!

**Comment by blueyed** [comment]
Well, this is in Russion, without (non-automatic) subscripts.
It's mentioned in parenthesis, but I am not sure how big the audience is after all.
+0 from me.

**Comment by blueyed** [comment]
Thanks! :)

**Comment by blueyed** [comment]
(+1 +0 is still +1) ;)

**Pull request merged**
