### PR TITLE
Rename the default plugin "pdb" into "debugging"

### PR DESCRIPTION
**Pull request by aostr**
The pdb module name conflicts with the python debugger module.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
i wonder what problem that solves (this has been working since years, and its a name change)

**Comment by nicoddemus** [comment]
Problem is that depending where the current directory is, `import pdb` might import `_pytest.pdb` instead of builtin `pdb`. I think this should go in.

@aostr the only thing missing is a changelog entry, because the internal plugin was renamed to `debugging` as well (although I doubt anybody depends on this).

**Comment by RonnyPfannschmidt** [comment]
i did a quick github search and it matched only in copies/forks of pytest

**Comment by RonnyPfannschmidt** [comment]
i discussed the need of this with @nicoddemus and @blueyed - arrived at the conclusion that its a good idea to rename to support debugging while using the common pdb shortcuts :+1:

**Comment by nicoddemus** [comment]
Thanks @aostr!

**Pull request merged**
