### PR TITLE
fix issue #2920

### PR DESCRIPTION
**Pull request by rpuntaie**
See issue #2920 for details.

### CODE REVIEW

**Comment by nicoddemus** [comment]
@rpuntaie thanks for tackling this!

We need to add a new test for it though. I suggest writing a test in `test_config.py` or `acceptance_test.py`; take a look at other tests using the `testdir` fixture, it should be straightforward to prepare an integration test which triggers the bug.

**Comment by rpuntaie** [comment]
`test_addopts_before_initini` fails, but I think, that has no relation to my changes. The changed test fails without my fix and it succeeds with my fix.

**Comment by nicoddemus** [comment]
Thanks @rpuntaie! I verified locally that your test reproduces the problem and also improved it a bit to ensure all the mechanisms that we are mocking in that test work as expected when we don't use the `-p no:` flag.

**Comment by The-Compiler** [comment]
Thanks @rpuntaie and @nicoddemus!

**Pull request merged**
