### PR TITLE
Report correct reason when using multiple skip/xfail markers

### LINKED ISSUE #863: Wrong skipif reason for multiple markers
Hi there!

I noticed that `pytest` would show the reason of the very first `skipif` marker regardless of whose condition evaluates to `True`. I was able to reproduce the problem with the following snippet:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import pytest

first_condition = False
second_condition = True


@pytest.mark.skipif(first_condition, reason='first_condition')
@pytest.mark.skipif(second_condition, reason='second_condition')
def test_foobar():
    assert False
```

```
(pytest)[raphael@hackebook tmp]$ py.test test_foo.py -rs
========= test session starts =========
platform darwin -- Python 2.7.6 -- py-1.4.30 -- pytest-2.7.2
rootdir: /Users/raphael/hackebrot/tmp, inifile: 
collected 1 items 

test_foo.py s
========= short test summary info =========
SKIP [1] test_foo.py:7: first_condition

========= 1 skipped in 0.00 seconds =========
(pytest)[raphael@hackebook tmp]$
```

This may be related to #666.

Right now I am using Mac OS X 10.10, Python 2.7.6 along with a fresh `virtualenv` that only has `pytest`. I experienced the same issue with Ubuntu 14.04 and Python 2.

```
py==1.4.30
pytest==2.7.2
wheel==0.24.0
```

Raphael

### PR DESCRIPTION
**Pull request by nicoddemus**
Fixes #863

### CODE REVIEW

**Comment by nicoddemus** [comment]
CC @hackebrot

**Comment by hackebrot** [comment]
Hmm *appveyor* points to #861

**Comment by nicoddemus** [comment]
Yes, no idea why all PRs for `pytest-2.7` point to the same appveyor build... :disappointed:

**Comment by nicoddemus** [comment]
Apparently it has solved itself. :smile:

**Comment by bubenkoff** [comment]
@nicoddemus  :)

**Pull request merged**
