### PR TITLE
return non-zero exit code if no tests are collected

### LINKED ISSUE #500: Warn if `py.test -k foo` finds no tests.
Originally reported by: **Thomas Güttler (BitBucket: [thomas-guettler](http://bitbucket.org/thomas-guettler), GitHub: [thomas-guettler](http://github.com/thomas-guettler))**

----------------------------------------

I think it would be a good useability improvement, if py.test would
warn me, if `py.test -k foo` finds no test at all.

I use version 2.5.2 and I see a green line, which indicates that all is good.

But if no tests was found, at least for me (interactive usage), it is a fault.

It would be nice to see a different color (not green) if no test was selected.

----------------------------------------
- Bitbucket: https://bitbucket.org/pytest-dev/pytest/issue/500

### LINKED ISSUE #812: Exit non-zero if no tests were run
[Split out of https://github.com/pytest-dev/pytest/issues/500#issuecomment-112204804 into a separate issue]

If no tests were run, pytest should exit with a non-zero status.

### PR DESCRIPTION
**Pull request by nicoddemus**
Fix #812
Fix #500

### CODE REVIEW

**Comment by nicoddemus** [comment]
The xdist jobs will fail as they depend on this PR on `pytest-xdist` itself: https://bitbucket.org/pytest-dev/pytest-xdist/pull-request/16/update-collected-tests-from-slaves-into/diff

**Comment by bubenkoff** [comment]
looks fine, but we should wait for xdist pr to be merged and released?

**Comment by nicoddemus** [comment]
> Looks fine, but we should wait for xdist pr to be merged and released?

Yes, otherwise `master` will appear broken until then.

**Comment by The-Compiler** [comment]
This also fixes #662.

**Comment by untitaker** [comment]
The xdist seems to be merged (even if accidentally). Could somebody give this another shot?

**Comment by nicoddemus** [comment]
Waiting for a new `pytest-xdist` release. @RonnyPfannschmidt is working on it! :smile:

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus `pytest-xdist 1.13` was just released

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt could you publish `1.13` on devpi as well?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus which index?
im not sure i have access there

**Comment by nicoddemus** [comment]
Hmm `.travis.yml` is configured to use `https://devpi.net/hpk/dev`... @hpk42, could you please include `1.13` in your release?

**Comment by RonnyPfannschmidt** [comment]
we should perhaps create a aggregate index to begin with

**Comment by nicoddemus** [comment]
Perhaps the default for `travis` should be just use `pypi` packages? That's how `AppVeyor` is configured at the moment, and branches that want to test against packages in `devpi` can specify so in the `travis.yaml` file before being merged.

**Comment by RonnyPfannschmidt** [comment]
good point

**Comment by nicoddemus** [comment]
Weird, I can't reproduce the failures locally... :disappointed:

**Comment by RonnyPfannschmidt** [comment]
those failures are relates to xdist 1.13 - moving boxed into the xdist.boxed plugin broke the code that imported the plugin that way

**Comment by nicoddemus** [comment]
I couldn't reproduce that on my machine before because those tests are skipped on Windows, as it doesn't have a `fork()` function. :blush: 

I fixed the import, and all is green again.

**Comment by RonnyPfannschmidt** [comment]
i hope we can have a funeral for boxed as is soonish ^^

**Comment by nicoddemus** [comment]
Nice. That would be a pytest-xdist 2.0 then?

Also, any other comments before merging this in?

**Comment by RonnyPfannschmidt** [comment]
roughly after cache and looponfail land in core, there will be a xdist 2.0 that does only the distributed/multicpu testing

**Comment by bubenkoff** [comment]
great job!

**Pull request merged**
