### PR TITLE
Don't fail if imp can't find the source for a .pyc file. #2038

### PR DESCRIPTION
**Pull request by nedbat**
Thanks for submitting a PR, your contribution is really appreciated!

Here's a quick checklist that should be present in PRs:

- [x] Target: for bug or doc fixes, target `master`; for new features, target `features`;

Unless your change is trivial documentation fix (e.g.,  a typo or reword of a small section) please:

- [x] Make sure to include one or more tests for your change;
- [x] Add yourself to `AUTHORS`;
- [x] Add a new entry to `CHANGELOG.rst`
  * Choose any open position to avoid merge conflicts with other PRs.
  * Add a link to the issue you are fixing (if any) using RST syntax.
  * The pytest team likes to have people to acknowledged in the `CHANGELOG`, so please add a thank note to yourself ("Thanks @user for the PR") and a link to your GitHub profile. It may sound weird thanking yourself, but otherwise a maintainer would have to do it manually before or after merging instead of just using GitHub's merge button. This makes it easier on the maintainers to merge PRs.

### CODE REVIEW

**Comment by nicoddemus** [comment]
Fixes #2038 right?

Thanks a lot @nedbat for the PR. 👍

**Comment by nicoddemus** [comment]
The `linting` env failed because of `flake8-3.1.1`, which is fixed by #2071.

**Comment by nicoddemus** [comment]
Anybody still wants more time to take a look at this?

**Comment by RonnyPfannschmidt** [comment]
its :+1:

**Pull request merged**
