### PR TITLE
Preparing release version 3.7.4

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks @asottile!

**Comment by asottile** [comment]
@nicoddemus the [steps](https://github.com/pytest-dev/pytest/blob/master/HOWTORELEASE.rst) don't indicate when I should merge this PR / when I should create the tag (I'll fix them!) -- at what point should those things happen?

**Comment by nicoddemus** [comment]
Ahh right.

After all tests have passed, push the tag to `upstream` with the PR still open. After the Travis job finishes and the deploy is complete, we merge the PR and make the announcements. 

We can update the HOWTORELEASE after `3.7.4` is out to avoid having to wait for the CI all over again.

**Comment by asottile** [comment]
also I think I need to run `git tag 3.7.4` myself as well? I can add that to the steps as well

**Comment by nicoddemus** [comment]
> also I think I need to run git tag 3.7.4 myself as well? I can add that to the steps as well

Yes, that is not very explicit there. Thanks!

**Comment by asottile** [comment]
@nicoddemus lol, do you wait for appveyor?

**Comment by nicoddemus** [comment]
Oh this is running already... just need to wait a bit then.

**Comment by wimglenn** [comment]
appveyor

**Comment by asottile** [comment]
I once had an appveyor build finish before travis-ci -- I restarted it since I assumed something was wrong

**Comment by blueyed** [comment]
Maybe we should trim down the matrix for AV?

**Comment by asottile** [comment]
could also crowdfund, their paid plan has better parallelism iirc

**Comment by RonnyPfannschmidt** [comment]
hmm, neo would disapprove of a low res matrix

**Comment by nicoddemus** [comment]
Just realized that we can configure Travis to skip the stages and go directly to deploy when it is building a tag... what do you guys think about that?

**Comment by nicoddemus** [comment]
Awesome, thanks @asottile!

**Comment by asottile** [comment]
> Your message has been rejected, probably because you are not
> subscribed to the mailing list and the list's policy is to prohibit
> non-members from posting to it.

awkward, I'll subscribe and send that out in a bit!

**Comment by nicoddemus** [comment]
hehehe. Don't forget the tweet as well! 👍

**Comment by blueyed** [comment]
Thanks, @asottile !

> Just realized that we can configure Travis to skip the stages and go directly to deploy when it is building a tag... what do you guys think about that? 

:+1: 

Just did this for pytest-django: https://github.com/pytest-dev/pytest-django/commit/b1f1b26

I think it should run one test job before though.

**Comment by nicoddemus** [comment]
it is easier to skip an entire stage, how about skipping the `test` staging and only run `baseline` and `deploy` when in a tag?

**Comment by blueyed** [comment]
Sounds good!

**Comment by nicoddemus** [comment]
OK, cool: #3908. 👍

**Pull request merged**
