### PR TITLE
Improve output for missing required plugins

### PR DESCRIPTION
**Pull request by ssbarnea**
Partial-of: https://github.com/pytest-dev/pytest/pull/7572

### CODE REVIEW

**Review by nicoddemus — APPROVED** [review]

**Comment by nicoddemus** [comment]
@The-Compiler do you mind we merge this, then go back to #7572 to investigate the issue with `--strict-config` separately?

**Review by gnikonorov — APPROVED** [review]

**Comment by gnikonorov** [comment]
> @The-Compiler do you mind we merge this, then go back to #7572 to investigate the issue with `--strict-config` separately?

Bump @The-Compiler

**Comment by The-Compiler** [comment]
Sorry for the delay and thanks! Fine by me. I'm adding the "needs backport" label here as well given that #7572 had one, but I'm a bit confused (after reading the [contribution docs](https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst#backporting-bug-fixes-for-the-next-patch-release)) - who is expected to do the backporting?

**Comment by nicoddemus** [comment]
> who is expected to do the backporting?

Hmmm that's not crystal clear. Usually when I merge the PR I go ahead and do the backporting myself, but others may do differently.

**Comment by nicoddemus** [comment]
Backport: https://github.com/pytest-dev/pytest/pull/7765

**Pull request merged**
