### PR TITLE
Merge master into features (about to prepare 4.0)

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Another build interrupted on AppVeyor due to a codecov connection failure... rebuilding.

**Comment by RonnyPfannschmidt** [comment]
do we have a command retry tool to make it try more than once?

**Comment by blueyed** [comment]
On Travis I've switched to codecov-bash, which retries automatically.
No Idea for Windows.. could be just a simple loop + sleep?!

It is unfortunate that you have to rebuild everything on AppVeyor.

**Comment by blueyed** [comment]
Heh.. you got my :+1: into here automatically.. :D

**Comment by nicoddemus** [comment]
Follow up for the retry script idea: 4387

**Pull request merged**
