### PR TITLE
WIP: #9298 - add testing and debugging for the pycache_prefix 

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
adding debugging first, then potentially a xfail for the affected combination (python 3.9 + windows)

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
@The-Compiler accrording to the output, it seems like for some reason the complete set of path parents is replicated

@nicoddemus any idea/suggestion (its potentially a windows flag thats enabled in the CI and not enabled on normal systems)

**Comment by nicoddemus** [comment]
Here's the output paths, cleaned up:

```
C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw0/test_sys_pycache_prefix_integr0
C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw0/test_sys_pycache_prefix_integr0/my
C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw0/test_sys_pycache_prefix_integr0/my/pycs
C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw0/test_sys_pycache_prefix_integr0/my/pycs/Users
C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw0/test_sys_pycache_prefix_integr0/my/pycs/Users/runneradmin
C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw0/test_sys_pycache_prefix_integr0/my/pycs/Users/runneradmin/AppData
C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw0/test_sys_pycache_prefix_integr0/my/pycs/Users/runneradmin/AppData/Local
C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw0/test_sys_pycache_prefix_integr0/my/pycs/Users/runneradmin/AppData/Local/Temp
C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw0/test_sys_pycache_prefix_integr0/my/pycs/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin
C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw0/test_sys_pycache_prefix_integr0/my/pycs/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0
C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw0/test_sys_pycache_prefix_integr0/my/pycs/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw0
C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw0/test_sys_pycache_prefix_integr0/my/pycs/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw0/test_sys_pycache_prefix_integration0
C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw0/test_sys_pycache_prefix_integr0/my/pycs/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw0/test_sys_pycache_prefix_integration0/src
C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw0/test_sys_pycache_prefix_integr0/my/pycs/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/popen-gw0/test_sys_pycache_prefix_integration0/src/bar
```

> it seems like for some reason the complete set of path parents is replicated

You mean the full path is being appended to the original path? That's the expected behavior of `get_cache_dir`:

https://github.com/pytest-dev/pytest/blob/cd49075ad704eebdb2e43ceecd472c5dbf28d624/src/_pytest/assertion/rewrite.py#L1131

The path after `/my/pycs` is a version of the original path to avoid pyc clashes.

Let me push a commit to this branch to further try to isolate the problem.

**Comment by nicoddemus** [comment]
Ahh interesting, running that test in isolation still fails on CI.

**Comment by nicoddemus** [comment]
Interesting, here are the paths in which version:

**py38**

```
C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/test_sys_pycache_prefix_integr0/my/pycs/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/test_sys_pycache_prefix_integration0/src/test_foo.cpython-38-pytest-7.0.0.dev322+ga1bc34860.pyc
C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/test_sys_pycache_prefix_integr0/my/pycs/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/test_sys_pycache_prefix_integration0/src/bar/__init__.cpython-38.pyc
```

**py39**

No files at all.

**py310**

```
C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/test_sys_pycache_prefix_integr0/my/pycs/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/test_sys_pycache_prefix_integration0/src/test_foo.cpython-310-pytest-7.0.0.dev322+ga1bc34860.pyc
C:/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/test_sys_pycache_prefix_integr0/my/pycs/Users/runneradmin/AppData/Local/Temp/pytest-of-runneradmin/pytest-0/test_sys_pycache_prefix_integration0/src/bar/__init__.cpython-310.pyc
```

So the problem is not some file name mismatching, we are not writing `.pyc` at all in the cache dir.

**Comment by nicoddemus** [comment]
Ahh OK got to the actual error!

It is happening in `_write_pyc`:

```
write_pyc: error! [WinError 3] The system cannot find the path specified.
```

I suspect long paths.

**Comment by nicoddemus** [comment]
```
  write_pyc: parent exists? True
  write_pyc: error! [WinError 3] The system cannot find the path specified.
```

Yep! The parent folder exists, but we can't write the file. Pretty sure that's to long paths not working there. Will try a quick hack to confirm this.

**Comment by nicoddemus** [comment]
Yes, the problem is long paths, and is related to Python 3.9.8:

https://github.com/actions/setup-python/issues/267

Seems this will solve itself next week with Python 3.9.9.

**Comment by nicoddemus** [comment]
I suggest we keep the xfail but add `strict=True`, so it starts to fail when the image is updated, meaning we can then remove that xfail.

**Comment by RonnyPfannschmidt** [comment]
closing this as we learned it was a python deployment issue

**Pull request closed without merging**
