### PR TITLE
ci: harden github actions according to "zizmor" recommendations

### PR DESCRIPTION
**Pull request by bluetech**
"zizmor" is a new tool to statically analyze github actions files for security issues. See See: https://woodruffw.github.io/zizmor/.

Fix all issues reported by zizmor 0.9.2 running locally.

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
👍

**Review by webknjaz — APPROVED** [review]

**Comment by nicoddemus** [comment]
Nice!

Should we also run zizmor itself on CI?

**Comment by bluetech** [comment]
Running a CI security check in CI :) I suppose it can be helpful for finding unintentional weaknesses. I see there is a pre-commit hook here https://github.com/woodruffw/zizmor-pre-commit so I'll send a PR adding it.

**Comment by nicoddemus** [comment]
> Running a CI security check in CI :) I suppose it can be helpful for finding unintentional weaknesses. I see there is a pre-commit hook here https://github.com/woodruffw/zizmor-pre-commit so I'll send a PR adding it.

Hehehe

A pre-commit hook sounds even better!

**Pull request merged**
