### PR TITLE
Release 3.2.5

### PR DESCRIPTION
**Pull request by nicoddemus**
Going ahead and opening this PR as a possible solution to #2926.

### CODE REVIEW

**Comment by nicoddemus** [comment]
I will skip testing the actual package using `devpi-cloud-test` given the small changes.

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt feel free to push the package from [my devpi channel](https://devpi.net/nicoddemus/dev/pytest/3.2.5) to PyPI if you agree with this approach (I will wake up some hours after you due to our timezone difference).

**Comment by RonnyPfannschmidt** [comment]
for correct implementation of this one we should ensure the py 1.5.0 release is pulled after a py 1.5.1 release with the python version flags is done

**Comment by nicoddemus** [comment]
> for correct implementation of this one we should ensure the py 1.5.0 release is pulled after a py 1.5.1 release with the python version flags is done

Will release this and open a PR on `py` shortly.

**Comment by RonnyPfannschmidt** [comment]
👍

**Pull request merged**
