### PR TITLE
Fix misimport

### PR DESCRIPTION
**Pull request by flying-sheep**

### CODE REVIEW

**Comment by flying-sheep** [comment]
Superseded by #12208

**Comment by nicoddemus** [comment]
This fix is actually interesting to have, as it simplifies the code a bit.

Perhaps we can reopen it after #12208 gets merged.

**Comment by flying-sheep** [comment]
Reopened, I left it as draft for now

**Comment by nicoddemus** [comment]
With the new code this patch now breaks a bunch of tests.

I think we can close this for now, or would you like to investigate more @flying-sheep ?

**Comment by flying-sheep** [comment]
No, that’s fine. If there’s more issues coming up, maybe we should remember that an avenue like this might fix these.

**Pull request closed without merging**
