### PR TITLE
[Docs] remove semi-colon punctuation mark

### PR DESCRIPTION
**Pull request by finn0**
@gnikonorov now can you take a look into this PR? I've made suggested change.

### CODE REVIEW

**Review by gnikonorov — CHANGES_REQUESTED** [review]
Thank you for the PR @finn0!

You are right, semicolons are probably not the best punctuation to use here. Can you please remove the punctuation altogether.

**Review by The-Compiler — APPROVED** [review]
Looks good, thanks! :+1:

**Comment by finn0** [comment]
Usually, we name `doc` folder as `docs`. Isn't it a good idea, we also rename `doc` folder to `docs`?

**Comment by The-Compiler** [comment]
> Usually, we name `doc` folder as `docs`. Isn't it a good idea, we also rename `doc` folder to `docs`?

I've seen both. Various projects I'm involved in ([qutebrowser](https://github.com/qutebrowser/qutebrowser), [herbstluftwm](https://github.com/herbstluftwm/herbstluftwm/)) or use ([pylint](https://github.com/pycqa/pylint), [pygments](https://github.com/pygments/pygments), [coverage.py](https://github.com/nedbat/coveragepy), ...) use "doc" as well. Thus I'm -1 on that change, as it will introduce friction for no clear benefit :slightly_smiling_face:

**Comment by gnikonorov** [comment]
> Usually, we name `doc` folder as `docs`. Isn't it a good idea, we also rename `doc` folder to `docs`?

My opinion is similar to @The-Compiler's above. I think that given convention `doc` is a valid folder name

**Review by gnikonorov — APPROVED** [review]
Thank you @finn0!

**Comment by finn0** [comment]
@The-Compiler @gnikonorov Thanks for the reply, and example project which uses `doc` as folder name.

**Comment by nicoddemus** [comment]
Thanks @finn0!

**Pull request merged**
