### PR TITLE
Add CHANGELOG for 4.6.5 (#5696)

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by blueyed** [comment]
Will you do 5.0.2 then also?

**Comment by nicoddemus** [comment]
I'm planning on doing `5.1` after https://github.com/pytest-dev/pytest/pull/5605 gets merged.

**Comment by blueyed** [comment]
> I'm planning on doing `5.1` after #5605 gets merged.

Ok, left some remarks there.

I've expected the 5.x series to have priority over 4.6 though - i.e. a bugfix release (5.0.2) there before / (or at least) together with 4.6.x.

**Comment by nicoddemus** [comment]
> I've expected the 5.x series to have priority over 4.6 though - i.e. a bugfix release (5.0.2) there before / (or at least) together with 4.6.x.

I was expecting to release 5.1 (which still had one pending issue) right after 4.6 (which had no other pending issues), but that plan didn't realize as I hoped. 😕

**Pull request merged**
