### PR TITLE
Replace reorder-python-imports by isort due to black incompatibility

### PR DESCRIPTION
**Pull request by nicoddemus**
Unfortunately black and reorder-python-imports are no longer compatible, and from the looks of it probably will not be compatible anytime soon:

https://github.com/asottile/reorder-python-imports/issues/367
https://github.com/asottile/reorder-python-imports/issues/366
https://github.com/psf/black/issues/4175

This replaces `reorder-python-imports` by `isort` configured in a way to yield roughtly the same results.

Closes #11885

### CODE REVIEW

**Review by Pierre-Sassoulas — COMMENTED** [review]
LGTM. ruff is a drop in replacement for isort, but also for autoflake, flake8, flake8-typing-imports,  (flake8-docstrings I don't think so, but I don't know what's inside, maybe it's done by other checks), and pyupgrade, maybe something to consider instead ? I can do it and provide a configuration if you want.

**Review by Pierre-Sassoulas — APPROVED** [review]
(Approving in case ruff is not desirable)

**Comment by nicoddemus** [comment]
I'm also leaning towards trying out `ruff`, but would like to know what others think first.

**Comment by nicoddemus** [comment]
I'm merging this for now regardless, given otherwise our auto-updates are stuck.

But @Pierre-Sassoulas feel free to open a PR replacing other commit hooks with `ruff`. :+1:

**Pull request merged**
