### PR TITLE
Add support for Python 3.10

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Review by RonnyPfannschmidt — APPROVED** [review]
:+1:

**Comment by nicoddemus** [comment]
Thanks for the review!

1. Should we merge as is and deal with the problems later?
2. Wait until the failures are fixed?

I ask because I might not be able to take a look at it soon, and in the past we had added upcoming Python versions in a "allow failures" mode (in GitHub actions, the closest they have seems to be no marking the build as required).

**Comment by RonnyPfannschmidt** [comment]
there is a distutils warning we need to filter, lets do that at least, all other problems are for later

**Comment by nicoddemus** [comment]
It turned out to be simple. 🎉

**Pull request merged**
