### PR TITLE
tests: mark test_meta as slow

### PR DESCRIPTION
**Pull request by blueyed**
This moves it to the end of tests during collection.  Takes ~7s for me.

### CODE REVIEW

**Comment by asottile** [comment]
for optimal packing, shouldn't slow tests be run first?

also the individual parametrized tests here aren't slow -- just the collective group of them

**Comment by blueyed** [comment]
> for optimal packing, shouldn't slow tests be run first?

The idea is to run `pytest -x` to see where relevant tests are, for example.

> also the individual parametrized tests here aren't slow -- just the collective group of them

Yeah.  Could mark the module instead.

It is also a bit about "those are tests that should be run on CI, but are not really required / expected to fail usually".  But I do not feel like we should have an extra mark for them.

**Comment by blueyed** [comment]
Can we just merge this for now?

**Comment by nicoddemus** [comment]
I'm +0 on this, so unless @asottile prefers otherwise, I'm OK with merging it.

**Pull request merged**
