### PR TITLE
[pytest 7.0] Make --version write to stdout rather than stderr 

### LINKED ISSUE #8246: `--version` writes to stderr
Hello,
When calling `pytest --version`, Pytest writes the version to stderr, which should be stdout I think. This is a problem to create automation tooling around it.

Example : 
```python
import subprocess
res = subprocess.run(["pytest", "--version"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
res

> CompletedProcess(args=['pytest', '--version'], returncode=0, stdout=b'', stderr=b'pytest 6.1.2\r\n')
```

Context : 
```
Pytest  6.1.2
Python  3.9.0
Windows 10 20H2
```

### PR DESCRIPTION
**Pull request by nicoddemus**
Fix #8246

### CODE REVIEW

**Review by bluetech — APPROVED** [review]
We *might* want to keep this until pytest 7? In case someone already relies on the stderr behavior, which will break now, and there isn't really any way to provide backward compat.

Anyway, either decision is fine by me.

**Comment by nicoddemus** [comment]
> We might want to keep this until pytest 7? In case someone already relies on the stderr behavior, which will break now, and there isn't really any way to provide backward compat.

Hmm good point. I'm fine on waiting for pytest 7. @RonnyPfannschmidt ?

**Comment by RonnyPfannschmidt** [comment]
i agree

**Comment by nicoddemus** [comment]
Done, thanks!

**Comment by nicoddemus** [comment]
Just bumped into this.

@The-Compiler what do you think about getting this into `7.0.0rc1`?

**Comment by The-Compiler** [comment]
Seems fine to me, given that it's been reviewed and is simple enough. Maybe rebase though, so that the CI can run against it again?

**Comment by nicoddemus** [comment]
Sure, rebased! 👍

**Comment by nicoddemus** [comment]
oops ignore that, I got it wrong.

**Comment by The-Compiler** [comment]
Looks like you rebased before pulling my lastest changes in `main` or something :wink:

**Comment by nicoddemus** [comment]
Done now. 😁

**Comment by nicoddemus** [comment]
> Looks like you rebased before pulling my lastest changes in main or something

The classic "origin/main" vs "upstream/main" hehehe 😉

**Comment by h-vetinari** [comment]
Bit of a nit, but this shows up as having been done in the 8.0 milestone, instead of 7.0 (the version with which it now will be released). Same for #7870.

**Comment by nicoddemus** [comment]
Thanks @h-vetinari, fixed!

**Comment by The-Compiler** [comment]
Me: Huh, that seems quite exotic, why would someone rely on this behavior?

Also me: [Relies on that behavior](https://github.com/qutebrowser/qutebrowser/runs/2995052038?check_suite_focus=true#step:5:281) in integration tests for a coverage checking script :rofl:

**Pull request merged**
