### PR TITLE
Store terminal width on config

### PR DESCRIPTION
**Pull request by helenst**
Ref #162

### CODE REVIEW

**Comment by flub** [comment]
I'm not sure I understand the travis failures, I do get them locally as well though.

**Comment by helenst** [comment]
@flub I am getting them too but it's not immediately obvious why. I will take a look.

**Comment by RonnyPfannschmidt** [comment]
@helenst can you take a look at rebasing this one? the conflicts made it un-mergable, and i hope recent changes fix the 2 failed builds

**Comment by helenst** [comment]
Hmm, still failing. I tried to investigate this the first time round, but it was quite hard to debug. Can have another look when i get some more time.

**Comment by RonnyPfannschmidt** [comment]
thank you for rebasing and fixing the conflicts - its a big help for anyone else wanting to try

the next time i can iterate i#ll also take a look again

cheers

**Comment by blueyed** [comment]
I've only skimmed this, but it reminded me of https://github.com/pytest-dev/py/pull/92.

So a) there is a way to get it already in plugins (pytest-sugar does so), but probably requires to use a hook that provides the terminal writer, and b) it should not be static (that is what https://github.com/pytest-dev/py/pull/92 is about).

**Comment by nicoddemus** [comment]
Anyone still wants to give this one a try?

**Comment by nicoddemus** [comment]
Closing due to lack of follow up. Please feel free to reopen if there's still interest.

**Pull request closed without merging**
