### PR TITLE
add FixtureManager to docs

### LINKED ISSUE #3420: [docs] FixtureManager documentation not included in reference
I wanted to link to `_pytest.FixtureManager.getfixtureclosure` in my documentation and noticed that this class is not included in the `reference.rst`.  I would ordinarily submit a pull request, but

1. I wasn't sure if this is exactly where the documentation should go.
2. I cannot get class signatures to compile.  I had to comment out the usage of `'sphinxcontrib_trio'` in `extensions` of `conf.py`, otherwise I kept getting errors from that extension.  But without it no class signatures are rendered locally.

Anyway, I just stuck it at the end of the `Fixtures` section, the following diff should achieve the desired result **but** since I cannot get the docs to compile locally, I'm not sure :/

```diff
--- a/doc/en/reference.rst
+++ b/doc/en/reference.rst
@@ -496,6 +496,14 @@ tmpdir_factory
 .. automethod:: TempdirFactory.mktemp
 .. automethod:: TempdirFactory.getbasetemp
 
+FixtureManager
+~~~~~~~~~~~~~~
+
+.. currentmodule:: _pytest.fixtures
+
+.. autoclass:: _pytest.fixtures.FixtureManager
+    :members:
+
 
 .. _`hook-reference`:
```

### PR DESCRIPTION
**Pull request by svenevs**
Fixes #3420.

@nicoddemus encouraged me to submit a PR, but please understand I have not been able to render the docs locally to verify that this documentation links / finds the class correctly (error in third party docs extension).

Commits from maintainers can be done on that fork, as well as I'm happy to move it to another location on the docs etc.  Thanks for `pytest`, the learning curve was totally worth it :heart:

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks a lot for following up with the PR @svenevs, we appreciate it!

Glad to know you are enjoying working/learning pytest! 👍

**Comment by nicoddemus** [comment]
Uh oh, sorry to only realize this now: the `FixtureManager` is not really part of the public API, so it should not go to the docs. The reference docs is meant only for public API the user calls directly or is accessible from public objects, but the `FixtureManager` is an implementation detail that we reserve the right to change in the future as part of an internal refactoring or implementation of a new feature.

I'm really sorry I answered to your question in https://github.com/pytest-dev/pytest/issues/3420#issuecomment-383741515 in haste and made you waste your time preparing this PR. 😞 

Again thanks for the PR, totally my fault for suggesting to write a PR, but please do stick around to work on something else if you feel like. Thanks for understanding!

**Comment by svenevs** [comment]
No problem, creation of the PR took maybe 5 minutes since I saved the diff :smile:

**Comment by nicoddemus** [comment]
Hehehe great, thanks!

**Pull request closed without merging**
