### PR TITLE
Fix exception causes all over the codebase

### PR DESCRIPTION
**Pull request by cool-RR**
This is a continuation of #7351 

- [X] Allow maintainers to push and squash when merging my commits. Please uncheck this if you prefer to squash the commits yourself.
- [X] Create a new changelog file in the `changelog` folder, with a name like `<ISSUE NUMBER>.<TYPE>.rst`. See [changelog/README.rst](https://github.com/pytest-dev/pytest/blob/master/changelog/README.rst) for details.
- [X] Add yourself to `AUTHORS` in alphabetical order.

### CODE REVIEW

**Comment by cool-RR** [comment]
@bluetech Nudge

**Comment by bluetech** [comment]
Thanks @cool-RR! I do hope you won't be angry if at some point we change a bunch of these to `from None` :)

**Comment by cool-RR** [comment]
@bluetech Hey, I'm happy that my opinion against `from None` is respected, that's the best I can ask for.

**Comment by cool-RR** [comment]
I just made a blog post about this change here: https://blog.ram.rachum.com/post/621791438475296768/improving-python-exception-chaining-with

**Pull request merged**
