### PR TITLE
Config.getini returns none

### PR DESCRIPTION
**Pull request by TanyaAgarwal28**
PR Description:
This PR addresses the issue described in #11282 (replace with the issue number) where the `pytest.config.getini()` method returns an empty list instead of `None` when an INI option is not provided. This change ensures that `None` is returned as the default value when an INI option is not found or has no default value provided by the developer.

Changes Made:
- Modified the `getini` method in `config.py` to return `None` as the default value when an INI option is not found or has no default value.
- Added tests to cover this behavior, ensuring that `None` is returned when appropriate.

Testing:
- Added unit tests to verify the expected behavior of the `getini` method.
- Ran the test suite to ensure that existing functionality is not affected by this change.

Changelog:
- Added a new feature to the `config.py` module: `getini` now returns `None` as the default value when an INI option is not provided or has no default value.

Checklist:
- [x] The code changes have been tested locally and work as expected.
- [x] Documentation has been updated to reflect the changes.
- [x] New tests have been added to cover the updated behavior.
- [x] Maintain the ability to push and squash commits when merging.

This PR addresses issue #11282.

### CODE REVIEW

**Comment by nicoddemus** [comment]
Seems like this PR contains bits from #11489?

**Comment by TanyaAgarwal28** [comment]
Ohh let me remove that one file thanks

**Comment by nicoddemus** [comment]
> Ohh let me remove that one file thanks

Thanks, but I didn't mean only that file, there are other changes there which seem related to the other PR, for example the tests for duplicated ids and the changes in `python.py`.

**Comment by nicoddemus** [comment]
Also, is this related to an open issue? In that direction, a description on the PR is important to have.

**Comment by TanyaAgarwal28** [comment]
Sorry actually I forgot to remove the changes of my previous PR and now I have added comment as well

**Comment by TanyaAgarwal28** [comment]
Will make a new pull request

**Pull request closed without merging**
