### PR TITLE
use travis containers

### PR DESCRIPTION
**Pull request by bubenkoff**

### CODE REVIEW

**Comment by nicoddemus** [comment]
You beat me to it! :smile:

**Comment by nicoddemus** [comment]
Can you also update the README file with a proper badge from travis or shields.io?

**Comment by bubenkoff** [comment]
see another PR :)

**Comment by nicoddemus** [comment]
Cool. :+1:

**Comment by bubenkoff** [comment]
can you merge?

**Comment by nicoddemus** [comment]
I can, but the build is failing right now... I think it would be better to fix it before merging.

**Pull request merged**
