### PR TITLE
ci: few security/permissions improvements

### LINKED ISSUE #8599: Restrict GitHub Actions permissions
There is now some functionality for restricting workflow permissions: https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/

Given the recent CodeCov trouble this sounds like a good idea.

I suggest we enable this setting for the repository, and specify needed permissions for specific workflow files. It might cause some failed runs initially but should be easily fixed.

Another thing we can do is to [specify](https://github.com/actions/checkout#usage) `persist-credentials` for the `actions/checkout` action when it's not needed.

### PR DESCRIPTION
**Pull request by bluetech**
This fixes #8599, and couple other improvements -- please see the commits.

This is entirely untested, and probably would require debugging until nothing breaks, so marking as draft for now, but would appreciate others taking a look.

If the second commits looks good, we should change the default permissions in the repo settings from read-write to read-only.

If the third commit looks good, we should remove the `chatops` and `release_notes` secrets in the repo settings.

### CODE REVIEW

**Review by nicoddemus — COMMENTED** [review]
Thanks a lot @bluetech for tackling this!

> If the second commits looks good, we should change the default permissions in the repo settings from read-write to read-only.

Mostly on what I understand from that second commit is that it disables all permissions by default, granting adequate permissions on a step basis, which looks great. 

> If the third commit looks good, we should remove the chatops and release_notes secrets in the repo settings.

My question is what you mean by "default permissions in repo settings", and how is that settings related to the above? 


👍

**Comment by bluetech** [comment]
Thanks for taking a look.
 
> My question is what you mean by "default permissions in repo settings", and how is that settings related to the above?

The setting I'm referring to is under Settings -> Actions -> Workflow permissions. It would act as an extra bit of safety when a new workflow is added but forgets to set the permissions.

**Comment by nicoddemus** [comment]
> The setting I'm referring to is under Settings -> Actions -> Workflow permissions. It would act as an extra bit of safety when a new workflow is added but forgets to set the permissions.

Got it, thanks!

**Comment by bluetech** [comment]
I did some testing on my fork for what I could, and what I was able to test seems good (after a syntax fix). So marking as ready.

**Review by RonnyPfannschmidt — APPROVED** [review]

**Comment by bluetech** [comment]
Trying a fix for ancient macos bash version.

**Comment by nicoddemus** [comment]
> I did some testing on my fork for what I could, and what I was able to test seems good (after a syntax fix). So marking as ready.

Good enough for me! As you said, we can always fix things later when/if they come up. 👍

**Comment by bluetech** [comment]
Argh, `sha256sum` doesn't exist on macos, `shasum` doesn't exist on windows... Maybe should just use python for this. Will try it later.

**Comment by RonnyPfannschmidt** [comment]
@bluetech @nicoddemus by now im in favour of just dropping codecov until they get their act together and just providing a small minimal github action one can use instead of  this fetch shell from web mess they have

**Comment by RonnyPfannschmidt** [comment]
@bluetech i just stumbled on https://github.com/codecov/codecov-action - i wonder if we could/should use it

**Pull request merged**
