### PR TITLE
TracebackEntry.statement: keep raising AttributeError

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/blueyed/pytest/commit/eaa34a9df0#r35995547.

### CODE REVIEW

**Comment by bluetech** [comment]
If I understand correctly, you have a patch in your fork that started triggering this condition (`source` is `None` in `source.getstatement(...)`). Previously, it raised an `AttributeError`, and you handled it by catching it in the caller. But I changed it to an assert which broke your code. Did I get it right?

**Comment by blueyed** [comment]
Yes, have not really verified it, but the repr/str-test I have there inlcuded the "AssertionError()" then.

**Comment by bluetech** [comment]
What do you think about this diff instead (untested)? I think that if the condition can happen, and is not exceptional, it is better to be explicit. `AttributeError` is not something I'd expect from an innocent-looking property.

```diff
diff --git a/src/_pytest/_code/code.py b/src/_pytest/_code/code.py
index a8f117366..94231497b 100644
--- a/src/_pytest/_code/code.py
+++ b/src/_pytest/_code/code.py
@@ -203,10 +203,11 @@ class TracebackEntry:
         return "<TracebackEntry %s:%d>" % (self.frame.code.path, self.lineno + 1)
 
     @property
-    def statement(self) -> "Source":
+    def statement(self) -> Optional["Source"]:
         """ _pytest._code.Source object for the current statement """
         source = self.frame.code.fullsource
-        assert source is not None
+        if source is None:
+            return None
         return source.getstatement(self.lineno)
 
     @property
@@ -273,11 +274,15 @@ class TracebackEntry:
         except py.error.Error:
             fn = "???"
         name = self.frame.code.name
-        try:
-            line = str(self.statement).lstrip()
-        except KeyboardInterrupt:
-            raise
-        except:  # noqa
+        statement = self.statement
+        if statement is not None:
+            try:
+                line = str(statement).lstrip()
+            except KeyboardInterrupt:
+                raise
+            except:  # noqa
+                line = "???"
+        else:
             line = "???"
         return "  File %r:%d in %s\n  %s\n" % (fn, self.lineno + 1, name, line)
 
```

Walrus operator would have been nice here :)

**Comment by blueyed** [comment]
Your diff looks ok to me, but it changes the behavior still.
Fine for me, but @RonnyPfannschmidt might disagree?

> AttributeError is not something I'd expect from an innocent-looking property.

I've interpreted it as "there's no statement".

**Comment by blueyed** [comment]
Closing this for now.
@bluetech 
Please consider creating a PR from your patch.

@RonnyPfannschmidt 
Is this relevant / public API?  (if so it was broken in 5.3)

**Comment by RonnyPfannschmidt** [comment]
It's public api

**Pull request closed without merging**
