### PR TITLE
Skip test_source_mtime_long_long on 32bit and lower platforms

### PR DESCRIPTION
**Pull request by mimi1vx**
- [ ] Create a new changelog file in the `changelog` folder, with a name like `<ISSUE NUMBER>.<TYPE>.rst`. See [changelog/README.rst](https://github.com/pytest-dev/pytest/blob/master/changelog/README.rst) for details.
- [x] Target the `master` branch for bug fixes, documentation updates and trivial changes.
- [ ] Target the `features` branch for new features and removals/deprecations.
- [ ] Include documentation when adding new features.
- [ ] Include new tests or update existing tests when applicable.

Unless your change is trivial or a small documentation fix (e.g.,  a typo or reword of a small section) please:

- [x ] Add yourself to `AUTHORS` in alphabetical order;

### CODE REVIEW

**Comment by blueyed** [comment]
Thanks!

The test was added for #4903 - /cc @bmwiedemann 

Just for future reference: you should use "Fixes …" in commit message, especially given that you have created an issue already.

**Comment by bmwiedemann** [comment]
hmm. Wasnt there this `size & 0xffffffff` that is supposed to handle overly large files? If something is broken there, there should be a better fix than this.

**Comment by mimi1vx** [comment]
@bmwiedemann  python Integer bigger that `2^31-1` can't be converted to 'int' on a platform where `sys.maxsize` is `2^31-1` .. so this test is wrong on this platforms, and proprely cast `OverflowError` Exception

**Comment by bmwiedemann** [comment]
The test is not doing a cast to int. And the code specifically uses "L" for unsigned to have a 0..2^32-1 range. Maybe including a backtrace would make the problem clearer.

**Comment by nicoddemus** [comment]
The traceback was included in https://github.com/pytest-dev/pytest/issues/5046#issue-429215667:

```
[  348s]         timestamp = 2 ** 32 + offset
[  348s] >       os.utime(str(p), (timestamp, timestamp))
[  348s] E       OverflowError: Python int too large to convert to C long
```

And seems to be failing for both `-1` and `+1` offsets.

Strangely, this passes for me on 32-bit Python 2.7 on Windows:

```
λ python -c "import platform;print platform.architecture()"
('32bit', 'WindowsPE')

λ pytest testing\ -k test_source_mtime_long_long -v
======================== test session starts ========================
platform win32 -- Python 2.7.13, pytest-4.4.1.dev51+g1ed4ae863, py-1.6.0, pluggy-0.9.0
...

testing/test_assertrewrite.py::test_source_mtime_long_long[-1] PASSED [ 50%]
testing/test_assertrewrite.py::test_source_mtime_long_long[1] PASSED [100%]

============= 2 passed, 2383 deselected in 3.30 seconds =============
```

On 64-bits Python I get, as expected:

```
λ py -3.6 -c "import platform;print(platform.architecture())"
('64bit', 'WindowsPE')
```

I would expect to be able to reproduce this...

**Comment by nicoddemus** [comment]
@mimi1vx any updates on this? Can you please post the output of:

```
λ python -c "import platform;print platform.architecture()"
('32bit', 'WindowsPE')
```

In your system?

**Comment by mimi1vx** [comment]
@nicoddemus 
```
[    3s] + python2 -c 'import platform;print platform.architecture()'
[    3s] ('32bit', 'ELF')
```

**Comment by nicoddemus** [comment]
@mimi1vx interesting, thanks. Which OS is that?

**Comment by mimi1vx** [comment]
@nicoddemus  ELF - > linux 

btw>

```
abuild@penguin:~> python2 
Python 2.7.16 (default, Mar 04 2019, 07:13:50) [GCC] on linux2
>>> timestamp = 2 ** 32 +1
>>> import os
>>> os.utime(str("/etc/os-release"), (timestamp, timestamp))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python int too large to convert to C long
```

```
abuild@penguin:~> python3
Python 3.7.2 (default, Dec 30 2018, 16:18:15) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> timestamp = 2 ** 32 +1
>>> os.utime(str("/etc/os-release"), (timestamp, timestamp))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: timestamp out of range for platform time_t
>>> 
```

**Comment by nicoddemus** [comment]
I see, thanks!

Well now that's been clarified, I think it is harmless to merge this, otherwise the test blows up anyway. 👍

**Pull request merged**
