### PR TITLE
port the rest of the scripts/docs over to the main branch

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**

### CODE REVIEW

**Review by asottile — APPROVED** [review]

**Comment by RonnyPfannschmidt** [comment]
waiting for @nicoddemus to ack as well ^^

**Review by nicoddemus — APPROVED** [review]
👍

**Review by bluetech — APPROVED** [review]

**Comment by RonnyPfannschmidt** [comment]
i somehow managed not to press merge last week ^^

**Pull request merged**
