### PR TITLE
Merge master into features

### PR DESCRIPTION
**Pull request by nicoddemus**
Continuing after #1236

### CODE REVIEW

**Comment by bukzor** [comment]
@nicoddemus Could you post `git show 8b61a33` please?

Github doesn't represent merge commits very weill imho.

**Comment by nicoddemus** [comment]
```diff
commit 8b61a332ba6e7a1ce07cf4ab5611b6434e18761e
Merge: 6351e28 5ccb7b1
Author: Bruno Oliveira <nicoddemus@gmail.com>
Date:   Thu Dec 10 19:03:55 2015 -0200

    Merge remote-tracking branch 'bukzor/features-merge-master' into features

diff --cc CHANGELOG
index dec050d,d504e7a..1da8638
--- a/CHANGELOG
+++ b/CHANGELOG
@@@ -11,12 -11,86 +11,91 @@@
  * `pytest_enter_pdb` now optionally receives the pytest config object.
    Thanks Bruno Oliveira for the PR.

 +* New `-rp` and `-rP` reporting options give the summary and full output
 +  of passing tests, respectively. Thanks to David Vierra for the PR.
 +
 +2.8.2.dev
 +---------
+ 2.8.5.dev0
+ ----------

+ - fix #1074: precompute junitxml chunks instead of storing the whole tree in objects
+   Thanks Bruno Oliveira for the report and Ronny Pfannschmidt for the PR
+
+
+ 2.8.4
+ -----
+
+ - fix #1190: ``deprecated_call()`` now works when the deprecated
+   function has been already called by another test in the same
+   module. Thanks Mikhail Chernykh for the report and Bruno Oliveira for the
+   PR.
+
+ - fix #1198: ``--pastebin`` option now works on Python 3. Thanks
+   Mehdy Khoshnoody for the PR.
+
+ - fix #1219: ``--pastebin`` now works correctly when captured output contains
+   non-ascii characters. Thanks Bruno Oliveira for the PR.
+
+ - fix #1204: another error when collecting with a nasty __getattr__().
+   Thanks Florian Bruhin for the PR.
+
+ - fix the summary printed when no tests did run.
+   Thanks Florian Bruhin for the PR.
+ - fix #1185 - ensure MANIFEST.in exactly matches what should go to a sdist
+
+ - a number of documentation modernizations wrt good practices.
+   Thanks Bruno Oliveira for the PR.
+
+ 2.8.3
+ -----
+
+ - fix #1169: add __name__ attribute to testcases in TestCaseFunction to
+   support the @unittest.skip decorator on functions and methods.
+   Thanks Lee Kamentsky for the PR.
+
+ - fix #1035: collecting tests if test module level obj has __getattr__().
+   Thanks Suor for the report and Bruno Oliveira / Tom Viner for the PR.
+
+ - fix #331: don't collect tests if their failure cannot be reported correctly
+   e.g. they are a callable instance of a class.
+
+ - fix #1133: fixed internal error when filtering tracebacks where one entry
+   belongs to a file which is no longer available.
+   Thanks Bruno Oliveira for the PR.
+
+ - enhancement made to highlight in red the name of the failing tests so
+   they stand out in the output.
+   Thanks Gabriel Reis for the PR.
+
+ - add more talks to the documentation
+ - extend documentation on the --ignore cli option
+ - use pytest-runner for setuptools integration
+ - minor fixes for interaction with OS X El Capitan
+   system integrity protection (thanks Florian)
+
+
+
+
+ 2.8.2
+ -----
+
+ - fix #1085: proper handling of encoding errors when passing encoded byte
+   strings to pytest.parametrize in Python 2.
+   Thanks Themanwithoutaplan for the report and Bruno Oliveira for the PR.
+
+ - fix #1087: handling SystemError when passing empty byte strings to
+   pytest.parametrize in Python 3.
+   Thanks Paul Kehrer for the report and Bruno Oliveira for the PR.
+
+ - fix #995: fixed internal error when filtering tracebacks where one entry
+   was generated by an exec() statement.
+   Thanks Daniel Hahler, Ashley C Straw, Philippe Gauthier and Pavel Savchenko
+   for contributing and Bruno Oliveira for the PR.
+
+ - fix #1100 and #1057: errors when using autouse fixtures and doctest modules.
+   Thanks Sergey B Kirpichev and Vital Kudzelka for contributing and Bruno
+   Oliveira for the PR.

  2.8.1
  -----
```

**Comment by nicoddemus** [comment]
Thanks @bukzor, I fixed the CHANGELOG and merged with the latest master as well while I was at it. :smile:

**Comment by bukzor** [comment]
@nicoddemus you actually want to remove these lines, they don't make sense after the merge:

```#!diff
 +2.8.2.dev
 +---------
```

**Comment by nicoddemus** [comment]
Yes, I did it in 8f880e1. :grin:

**Comment by bukzor** [comment]
Thanks, all!

**Pull request merged**
