### PR TITLE
Replace py.std with stdlib imports

### PR DESCRIPTION
**Pull request by asottile**
Thanks for submitting a PR, your contribution is really appreciated!

Here's a quick checklist that should be present in PRs:

- [x] Add a new news fragment into the changelog folder
  * name it `$issue_id.$type` for example (588.bugfix)
  * if you don't have an issue_id change it to the pr id after creating the pr
  * ensure type is one of `removal`, `feature`, `bugfix`, `vendor`, `doc` or `trivial`
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."
- [x] Target: for `bugfix`, `vendor`, `doc` or `trivial` fixes, target `master`; for removals or features target `features`;
- [x] Make sure to include reasonable tests for your change if necessary

Unless your change is a trivial or a documentation fix (e.g.,  a typo or reword of a small section) please:

- [x] Add yourself to `AUTHORS`, in alphabetical order;

### CODE REVIEW

**Comment by asottile** [comment]
The xdist failure appears to be happening on master as well.  Seems to be introduced between pytest-xdist 1.20.1 and pytest-xdist 1.21

**Comment by asottile** [comment]
Seems related (?) to https://github.com/pytest-dev/pytest-xdist/pull/242

**Comment by asottile** [comment]
I've rebased this

**Comment by asottile** [comment]
@nicoddemus can you click retry on `doctesting` for me :)

**Comment by nicoddemus** [comment]
@asottile done! Strange, Travis is failing quite frequently with errors like that...

**Comment by asottile** [comment]
Thanks!  I think this is ready for review now 🎉

**Comment by RonnyPfannschmidt** [comment]
finally 👍

**Pull request merged**
