### PR TITLE
AttributeError chaining bug #1944 fix

### PR DESCRIPTION
**Pull request by axil**
Thanks for submitting a PR, your contribution is really appreciated!

Here's a quick checklist that should be present in PRs:

- [x] Target: for bug or doc fixes, target `master`; for new features, target `features`;
- [x] Make sure to include one or more tests for your change;
- [x] Add yourself to `AUTHORS`;
- [x] Add a new entry to `CHANGELOG.rst`
  * Choose any open position to avoid merge conflicts with other PRs.
  * Add a link to the issue you are fixing (if any) using RST syntax.
  * The pytest team likes to have people to acknowledged in the `CHANGELOG`, so please add a thank note to yourself ("Thanks @user for the PR") and a link to your GitHub profile. It may sound weird thanking yourself, but otherwise a maintainer would have to do it manually before or after merging instead of just using GitHub's merge button. This makes it easier on the maintainers to merge PRs.

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks, I've seen this happen on occasion but never took the time to properly look it up.

Would you mind add a CHANGELOG entry as well?

**Comment by axil** [comment]
@nicoddemus done

**Comment by The-Compiler** [comment]
Thanks! Maybe it'd make sense to include a test which creates a file like the one in the issue, runs pytest over it, and checks that "AttributeError" isn't in the output? Should be really straightforward to add and prevent regressions for this in the future.

**Comment by axil** [comment]
Added a test, rebased against master.

**Comment by nicoddemus** [comment]
Can you please take a look at the failing builds?

**Comment by axil** [comment]
All passed now.

**Comment by The-Compiler** [comment]
Thanks!

**Pull request merged**
