### PR TITLE
Fixture split 2nd attempt

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**

### CODE REVIEW

**Comment by nicoddemus** [comment]
I see this also fixes #1125

**Comment by RonnyPfannschmidt** [comment]
oh, i didn't notice ^^ i'll need some more code moves tho

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt you think it is worth doing it now, since this PR is moving a lot of code around anyway? :grin:

**Comment by RonnyPfannschmidt** [comment]
doing a second one helped getting faster with it
i feel the need to do the split as a base for moving more around

but i wouldn't mind deferring should it turn necessary

**Comment by nicoddemus** [comment]
Oh my this completely broke my invocation-scope branch... I thought Git would keep track better of those things. :sob:

**Comment by The-Compiler** [comment]
@nicoddemus a `git rebase features` doesn't fix it with minimal/no conflicts?

**Comment by nicoddemus** [comment]
Nope, that's what I meant with "broke my branch"... Git didn't track my changes at all :(

**Comment by RonnyPfannschmidt** [comment]
i only moved code, please show the failure

**Comment by nicoddemus** [comment]
No worries, I will try to figure it out tomorrow

**Comment by nicoddemus** [comment]
Found the problem, by mistake I missed some lines when applying the patch. :sweat_smile:

**Pull request merged**
