### PR TITLE
Preparing release version 4.6.2

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Pushed the tag already 😁 

Want to take it from here @asottile ?

**Comment by asottile** [comment]
oh I see, you've got the tag already :laughing: -- I'll let you do the rest :)

**Comment by asottile** [comment]
lol oops, I'll finish this off within an hour :+1:

**Comment by asottile** [comment]
finished it off -- thanks for the assist!

**Pull request merged**
