### PR TITLE
Make 'warnings' and 'deselected' in assert_outcomes optional

### LINKED ISSUE #9471: [prerelease] `deselected` addition to `assert_outcomes()` is backwards-incompatible
#9133 added a new `deselected` parameter to `assert_outcomes()`, cc @okken.

However, this actually is an incompatible change: Doing e.g. `result = testdir.runpytest("-k", "test_not_found_by_ini")` followed by `result.assert_outcomes(passed=2)` worked fine before, but now fails because the now included `'deselected': ...` does not equal `'deselected': 0`.

This breaks pytest-bdd: https://github.com/pytest-dev/pytest-bdd/issues/466 - I could swear I also saw another project in #9415 fail after fixing the initial issue it had, but then Christmas and stuff came along and now I don't remember which one it was, and of course can't find it anymore.

A (quite) [rough search](https://sourcegraph.com/search?q=context:global+%28testdir%7Cpytester%29%5C..*-k+lang:python+-file:.*/%3Ftesting/%28test_terminal%7Cacceptance_test%7Ctest_runner%7Ctest_collection%7Ctest_pytester%7Ctest_debugging%7Ctest_mark%7Cdeprecated_test%7Ctest_terminal%7Cpython/%29.*+-repo:pytest-dev/pytest-bdd&patternType=regexp) reveals that more projects might be affected by this (excludes to avoid matches in copies of pytest's source code).

Some examples I could dig up (but haven't verified):

- [test_parametrization.py - schemathesis/schemathesis - Sourcegraph](https://sourcegraph.com/github.com/schemathesis/schemathesis/-/blob/test/test_parametrization.py?L445:14)
- [test_ipa_run_tests.py - freeipa/freeipa - Sourcegraph](https://sourcegraph.com/github.com/freeipa/freeipa/-/blob/ipatests/test_ipatests_plugins/test_ipa_run_tests.py?L117:17) (maybe)
- [test_parametrized.py - pytest-dev/pytest-play - Sourcegraph](https://sourcegraph.com/github.com/pytest-dev/pytest-play/-/blob/tests/test_parametrized.py?L94:14)

I think the change in itself makes sense, but at the same time fixes like https://github.com/pytest-dev/pytest-bdd/pull/470 are a bit cumbersome.

Two questions:

- What should we do about this for 7.0? (even if the answer just is "live with it and document it as backwards-incompatible in the changelog)
- What (if anything) should we do about this so that it doesn't happen again for future releases? I guess not much we can do, as long as we want to assume 0 for outcomes which have not been given...

### PR DESCRIPTION
**Pull request by nicoddemus**
Fix #9471

I don't think we need a CHANGELOG here, as this has not really been officially released yet.

### CODE REVIEW

**Comment by The-Compiler** [comment]
I'm not sure if I like the approach to be honest... while it is indeed convenient, I fear the asymmetry could lead to a silent mode of failure, where people expect e.g. warnings to be checked, but that does not happen.

**Comment by nicoddemus** [comment]
I was trying to fix the regression... should we keep the regression then? Fix this some other way?

**Comment by The-Compiler** [comment]
Agreed that this would fix the regression - but I'm not sure if it's the right way forward. I think I personally would prefer documenting this as a breaking change instead.

However it sounded like @RonnyPfannschmidt was in favor of this approach in #9471, so I might be overridden on that. :wink: 

Maybe @okken has an opinion on this?

**Comment by RonnyPfannschmidt** [comment]
I totally agree with the sentient of @TheCompiler

My personal preference is to fix the regression first, then think about warning and /or plannable breaking changes

The problem is that the api initially was incomplete, and likely still is incomplete, so we ought to consider the states explicitly and implicitly checked for

**Comment by nicoddemus** [comment]
OK, closing this then. 👍

**Comment by RonnyPfannschmidt** [comment]
reopening as its preferable not to break users while we figure the correct long term solution

**Comment by The-Compiler** [comment]
Let me note that we [already had](https://docs.pytest.org/en/latest/changelog.html#id112) breaking changes to this API (without any kind of deprecation period) in pytest 6, via #6505. I've seen some version checks to account for that in the wild, but don't remember where.

So I guess the question is whether we'd rather:

1) Avoid additional breakage, but in return have an API which is inconsistent and could silently hide problems, especially with warnings (yes, they have been hidden before #8952 I think - but it seems like a good thing to make pytester tests fail if the subprocess has warnings by default, no)?
2) Have another breaking change there, accept the breakage, but of course document it.

I'd prefer 2) over an inconsistent API - but then again 1) would probably mean that if we clean this up in form of some kind of different API, plugins then need to account for *four* different ways of doing the same thing, which isn't ideal either...

Thoughts? I'm fine with merging this and defer a better API to another release, but I feel like there is a trade-off...

also cc-ing @symonk

**Comment by The-Compiler** [comment]
Bump? I feel like we need a decision here to avoid blocking the 7.0.0 final. As said, I'm fine with being overridden on this, I just hope it won't paint us into a corner.

**Review by RonnyPfannschmidt — APPROVED** [review]

**Comment by nicoddemus** [comment]
The safest one, feature wise, is 2: close this PR and accept the breakage. But I don't have strong feelings either, so what you folks decide it is fine.

**Comment by The-Compiler** [comment]
ok, let's go for this then to get things unstuck, and hope we can come up with a better API altogether in the future...

**Pull request merged**
