### PR TITLE
minor: fix grammar with help for --setup-{only,show}

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks @blueyed!

**Comment by blueyed** [comment]
@nicoddemus 
Thanks for merging and all your energy with pushing pytest forward! :)

**Comment by nicoddemus** [comment]
> Thanks for merging and all your energy with pushing pytest forward! :)

🍺 my friend! 😁

**Comment by blueyed** [comment]
@nicoddemus 
🍻 🤗

**Pull request merged**
