### PR TITLE
WIP/RFC: add failing test_capture_with_testdir_parseconfig  [ci skip]

### LINKED ISSUE #4329: TypeError: '>' not supported between instances of 'NoneType' and 'float'
```
% pytest 'testing/test_collection.py::TestCollector::()::test_getcustomfile_roundtrip' -s --tb=short
_________________________________________________________________ TestCollector.test_getcustomfile_roundtrip _________________________________________________________________
…/Vcs/pytest/testing/test_collection.py:98: in test_getcustomfile_roundtrip
    node = testdir.getpathnode(hello)
…/Vcs/pytest/src/_pytest/pytester.py:737: in getpathnode
    res = session.perform_collect([x], genitems=False)[0]
…/Vcs/pytest/src/_pytest/main.py:430: in perform_collect
    items = self._perform_collect(args, genitems)
…/Vcs/pytest/src/_pytest/main.py:455: in _perform_collect
    self.ihook.pytest_collectreport(report=rep)
…/Vcs/pluggy/pluggy/hooks.py:284: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
…/Vcs/pluggy/pluggy/manager.py:67: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
…/Vcs/pluggy/pluggy/manager.py:61: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
…/Vcs/pytest/src/_pytest/terminal.py:491: in pytest_collectreport
    self.report_collect()
…/Vcs/pytest/src/_pytest/terminal.py:500: in report_collect
    if self._collect_report_last_write > t - 0.5:
E   TypeError: '>' not supported between instances of 'NoneType' and 'float'
```

### PR DESCRIPTION
**Pull request by blueyed**
Fails with:

> OSError: reading from stdin while output is captured

Also tests https://github.com/pytest-dev/pytest/pull/4330 (i.e. fails
without #4330 earlier already).

Closes #4329.

### CODE REVIEW

**Comment by blueyed** [comment]
@nicoddemus 
Seems to be related to capturing being done, although it should stay resumed.

**Comment by blueyed** [comment]
This is also a problem when trying to step over:

    > …/src/_pytest/pytester.py(882)

     873         def runpytest_inprocess(self, *args, **kwargs):                                                                                                                  
     874             """Return result of running pytest in-process, providing a similar                                                                                           
     875             interface to what self.runpytest() provides.                                                                                                                 
     876                                                                                                                                                                          
     877             """                                                                                                                                                          
     878             if kwargs.get("syspathinsert"):                                                                                                                              
     879                 self.syspathinsert()                                                                                                                                     
     880             now = time.time()                                                                                                                                            
     881             capture = MultiCapture(Capture=SysCapture)                                                                                                                   
     882  ->         capture.start_capturing()                                                                                                                                    

I guess `MultiCapture.start_capturing` should honor some global state (which
remembers if there is capturing in place already), or the debugging plugin
needs to be able to interfere when capturing is suspended via it already.

Maybe this should use the CaptureManager in the first place here, instead of
`MultiCapture` directly?

**Comment by blueyed** [comment]
Failure can be seen at https://travis-ci.org/pytest-dev/pytest/jobs/454881133#L539.

@nicoddemus 
Any pointers/ideas how to fix this?
Should there be an internal level/stacking for this?

**Comment by nicoddemus** [comment]
Hi @blueyed, 

It has been a long time since it has last seen activity, plus we have made sweeping changes on `master` to drop Python 2.7 and 3.4 support, so this PR has some conflicts which require attention.

In order to clear up our queue and let us focus on the active PRs, I'm closing this PR for now.

Please don't consider this a rejection of your PR, we just want to get this out of sight until you have the time to tackle this again. If you get around to work on this in the future, please *don't hesitate* in re-opening this!

Thanks for your work, the team definitely appreciates it!

**Pull request closed without merging**
