### PR TITLE
The "ids" argument to "parametrize" again accepts unicode strings in Python 2

### LINKED ISSUE #1905: Cannot pass unicode string in parameterized ids with pytest 3.0.2 and python 2
Hi, since https://github.com/pytest-dev/pytest/pull/1861 we cannot pass python 2 unicode object to `parametrize()`:

sample code:

```python
import pytest

@pytest.mark.parametrize('p', ['v'], ids=[u'v'])
def test_foo(p):
    pass
```

Error is:

```
v/local/lib/python2.7/site-packages/_pytest/python.py:105: in pytest_generate_tests
    metafunc.parametrize(*marker.args, **marker.kwargs)
v/local/lib/python2.7/site-packages/_pytest/python.py:837: in parametrize
    raise ValueError(msg % (saferepr(id_value), type(id_value).__name__))
E   ValueError: ids must be list of strings, found: 'v' (type: unicode)
```

Will this be fixed or should I encode my string only with python 2 (or both) ?

Thanks !

### PR DESCRIPTION
**Pull request by nicoddemus**
Fixes #1905

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
unicode support on python 2 got removed for some specific reason/regression - i think we want test id#s tobe native strings ins *all* cases

**Comment by RonnyPfannschmidt** [comment]
i think i recalled the reason, environmental reasons may make python fail to print/output the unicode id's

i think we need to absolutely ensure the ids are native strings
please lets verify that and add a test

**Comment by The-Compiler** [comment]
> unicode support on python 2 got removed for some specific reason/regression

No, the check was added (by @nicoddemus) in response to #1857 to improve the error message when someone passes e.g. integers to parametrize.

**Comment by nicoddemus** [comment]
Yep

**Comment by flub** [comment]
So we can merge this anyway?

**Comment by nicoddemus** [comment]
From my POV yes :grin:

**Comment by The-Compiler** [comment]
Well then, I dared to click the button :wink:

**Pull request merged**
