### PR TITLE
Remove some python2.5 compatibility code

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by asottile** [comment]
Here's references to keep me honest:
- https://docs.python.org/2/reference/datamodel.html#index-37
- https://docs.python.org/2/whatsnew/2.6.html#pep-3112-byte-literals
- https://pythonhosted.org/six/#module-six.moves

**Comment by nicoddemus** [comment]
You think it would be worth adding a `trivial` changelog entry for those changes?

**Comment by RonnyPfannschmidt** [comment]
im seeing failures on all python versions for `__self__`

**Comment by asottile** [comment]
seems there's a slight difference in the `py` code, I can replace it with `getattr(..., '__self__', None)`

**Comment by asottile** [comment]
After fixing that and re-triggering travis-ci this is green -- another review for good measure?

**Comment by nicoddemus** [comment]
LGTM, I will let @RonnyPfannschmidt take a second look and merge. 👍

**Comment by hugovk** [comment]
http://doc.pytest.org/en/latest/changelog.html links to issue number 3629, which is a 404, not this 3529.

I guess it's from the typo in changelog/3629.trivial.rst. 

I would PR it, but can't find the file in that directory.

**Comment by asottile** [comment]
oops, shoot let me fix this (my bad)

**Comment by asottile** [comment]
Here's a PR to fix the link there: https://github.com/pytest-dev/pytest/pull/3544

**Pull request merged**
