### PR TITLE
Revert unrolling of `all()`

### LINKED ISSUE #5370: Assertions on nested comprehensions can give NameError
This test:

```
def test_nested_comprehension():
    s = [[True, True], [True, True]]
    assert all(e for row in s for e in row)
```
works fine in pytest 4.4.1 and 4.5.0.  In pytest 4.6.1 it produces a NameError:

```
$ pytest
===================================================== test session starts =====================================================
platform darwin -- Python 3.7.3, pytest-4.6.1, py-1.8.0, pluggy-0.12.0
collected 1 item                                                                                                              

test_it.py F                                                                                                            [100%]

========================================================== FAILURES ===========================================================
__________________________________________________ test_nested_comprehension __________________________________________________

    def test_nested_comprehension():
        s = [[True, True], [True, True]]
>       assert all(e for row in s for e in row)
E       NameError: name 'e' is not defined

test_it.py:3: NameError
================================================== 1 failed in 0.06 seconds ===================================================
```

Pip list gives:
```
$ pip list
Package            Version
------------------ -------
atomicwrites       1.3.0  
attrs              19.1.0 
importlib-metadata 0.17   
more-itertools     7.0.0  
packaging          19.0   
pip                19.1.1 
pluggy             0.12.0 
py                 1.8.0  
pyparsing          2.4.0  
pytest             4.6.1  
setuptools         41.0.1 
six                1.12.0 
wcwidth            0.1.7  
wheel              0.33.4 
zipp               0.5.1  
```

### LINKED ISSUE #5371: Unexpected behaviour for generator expressions in python 3.7
When running the following example with pytest 4.6.1 with python 3.6 from conda, the test passes, however when running with the same pytest version with python 3.7 the second assert statement fails
```python
def test_example():
    assert all(list(x for x in [True, False] if x))
    assert all(x for x in [True, False] if x)
```
```
    def test_example():
        assert all(list(x for x in [True, False] if x))
>       assert all(x for x in [True, False] if x)
E       assert False

pytest_example.py:4: AssertionError
```

Conda requirements file:
```
name: pytest_test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pytest
```

### LINKED ISSUE #5372: all(...) rewrite produces incorrect results
this is boiled down from a more complicated case

```python
def test():
    y = range(5)
    assert not all(x for x in y)
```

```console
$ pytest t.py
============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-4.6.1, py-1.8.0, pluggy-0.12.0
rootdir: /tmp
collected 1 item                                                               

t.py F                                                                   [100%]

=================================== FAILURES ===================================
_____________________________________ test _____________________________________

    def test():
        y = range(5)
>       assert not all(x for x in y)
E       assert 0

t.py:3: AssertionError
=========================== 1 failed in 0.04 seconds ===========================
$ pytest t.py --assert=plain
============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-4.6.1, py-1.8.0, pluggy-0.12.0
rootdir: /tmp
collected 1 item                                                               

t.py .                                                                   [100%]

=========================== 1 passed in 0.01 seconds ===========================```

### PR DESCRIPTION
**Pull request by asottile**
Resolves #5370 
Resolves #5371
Resolves #5372

### CODE REVIEW

**Comment by asottile** [comment]
I can handle backporting of this one as well :+1: (the revert didn't apply cleanly so I imagine it'll have similar issues in 4.6-maintenance)

**Comment by blueyed** [comment]
Oh... I've thought you reverted this _only_ for 4.6.

**Comment by RonnyPfannschmidt** [comment]
I propose never bringing this back at the ast level, there should be a difference approach

**Comment by Tadaboody** [comment]
So sorry about the fallout this created 🙏 I'll go back to the drawing board to see if this can be reintroduced in a better way. Reverting this was definitely the right decision, sorry I couldn't be more readily available to help with this

**Comment by RonnyPfannschmidt** [comment]
@Tadaboody still thanks for trying, we now know that the approach as is isn't viable

since quite a while there si the idea of assertion helper objects around, perhpas we should elaborate on it and its rammifications

**Comment by nicoddemus** [comment]
@Tadaboody not at all, as @RonnyPfannschmidt said, we appreciate you taking the time to implement this anyways! We should also have caught this earlier during review, but those things happen. 👍

**Comment by Sup3rGeo** [comment]
@nicoddemus @asottile It seems that the `all` unrolling was interfering with the feature #3479 I was working on, basically because this lines of code are still on the features branch:

https://github.com/pytest-dev/pytest/blob/4f57d40a43e0c27d82b8996d70e170ba9c879ee9/src/_pytest/assertion/rewrite.py#L920-L921

Was there any other PR merged on features with this `all()` unrolling or it was forgotten for removal in the features branch?

**Comment by asottile** [comment]
ah yeah it's a little confusing, for the 5.x release we're just going to release from `master` since there's no reason to split up the work for now -- so for now target master 👍

**Comment by nicoddemus** [comment]
Yep, sorry for the confusion!

**Pull request merged**
