### PR TITLE
[4.6] Distribution.files is None in some packages

### PR DESCRIPTION
**Pull request by nicoddemus**
Backport of #5389

**Question**: when backporting, should we squash commits? I vote yes.

### CODE REVIEW

**Comment by blueyed** [comment]
> Question: when backporting, should we squash commits? I vote yes.

Yeah.
On / for the PR already, or when merging (i.e. squash-merging then)?

**Comment by nicoddemus** [comment]
> On / for the PR already, or when merging (i.e. squash-merging then)?

I think it is up to the person creating the PR: they can open the PR without squashing, but squashing before merging.

I think it is easier to just open the PR with commits already squashed.

**Comment by nicoddemus** [comment]
Let's see what @asottile says then. 👍

**Comment by asottile** [comment]
the command I was using was `git cherry-pick -m1 <themergecommit>`, this looks like 3 cherry picks?

I documented the procedure I used in https://github.com/pytest-dev/pytest/issues/5275 -- it ~should end up as a single commit on the backport branch

**Comment by nicoddemus** [comment]
Closing in favor of #5401

**Pull request closed without merging**
