### PR TITLE
Handle python_files correctly in assertion rewrite

### PR DESCRIPTION
**Pull request by pelme**
This PR solves #2121.

Before merging this, https://github.com/pytest-dev/py/pull/99 and a new release of `py` is required.

### CODE REVIEW

**Comment by pelme** [comment]
I've updated the PR with a fix and changelog. The fix in py must land before merging this, though!

**Comment by nicoddemus** [comment]
Very nice, thanks @pelme!

**Comment by nicoddemus** [comment]
We should also add a requirement for `py>=1.4.33` to `setup.py`, otherwise users will get this error when upgrading:

```
  File "C:\pytest\_pytest\assertion\rewrite.py", line 97, in find_module
    if not self._should_rewrite(name, fn_pypath, state):
  File "C:\pytest\_pytest\assertion\rewrite.py", line 169, in _should_rewrite
    if fn_pypath.fnmatch(pat):
  File "C:\pytest\.env35\lib\site-packages\py\_path\common.py", line 209, in fnmatch
    return FNMatcher(pattern)(self)
  File "C:\pytest\.env35\lib\site-packages\py\_path\common.py", line 402, in __call__
    return py.std.fnmatch.fnmatch(name, pattern)
  File "C:\pytest\.env35\lib\site-packages\py\_apipkg.py", line 125, in __makeattr
    result = importobj(modpath, attrname)
  File "C:\pytest\.env35\lib\site-packages\py\_apipkg.py", line 48, in importobj
    module = __import__(modpath, None, None, ['__doc__'])
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 892, in _find_spec
  File "<frozen importlib._bootstrap>", line 873, in _find_spec_legacy
  File "C:\pytest\_pytest\assertion\rewrite.py", line 97, in find_module
    if not self._should_rewrite(name, fn_pypath, state):
  File "C:\pytest\_pytest\assertion\rewrite.py", line 169, in _should_rewrite
    if fn_pypath.fnmatch(pat):
  File "C:\pytest\.env35\lib\site-packages\py\_path\common.py", line 209, in fnmatch
    return FNMatcher(pattern)(self)
  File "C:\pytest\.env35\lib\site-packages\py\_path\common.py", line 402, in __call__
    return py.std.fnmatch.fnmatch(name, pattern)
  File "C:\pytest\.env35\lib\site-packages\py\_apipkg.py", line 125, in __makeattr
    result = importobj(modpath, attrname)
  File "C:\pytest\.env35\lib\site-packages\py\_apipkg.py", line 48, in importobj
    module = __import__(modpath, None, None, ['__doc__'])
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Hmm pinning a requirement for a different version of `py` could cause any problems that we are not foreseeing here?

**Comment by pelme** [comment]
I'm will update this PR as soon as 1.4.33 is available, then the builds should pass (they do locally with patched py for me).

I was thinking about copy/pasting the fnmatch code (which is not huge) from py but that did not seem very nice either. :/

**Comment by nicoddemus** [comment]
@pelme `1.4.33` has been released for some time now, would you like to continue this PR?

**Comment by pelme** [comment]
I've rebased the PR on the current master and adapted the changelog to be towncrier friendly! Anything missing?

**Comment by nicoddemus** [comment]
Sorry @pelme this went under the radar, I will review/merge it tomorrow!

**Comment by pelme** [comment]
No worries @nicoddemus, I was slow to update the PR.

I'm very very grateful for all the work you put into pytest and excited to see all the progress happening! 🍻

**Comment by nicoddemus** [comment]
Awesome, thanks @pelme! 😁

**Comment by RonnyPfannschmidt** [comment]
oh my goodness, i just have seen that right above in the comment we explicitly have a warning about importing fnmatch too late

**Comment by nicoddemus** [comment]
Ouch indeed. And we all missed that.

**Pull request merged**
