### PR TITLE
Kill memoized call

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**

### CODE REVIEW

**Comment by The-Compiler** [comment]
I think you'll also need to rebase and `push --force` your local branch.

**Comment by RonnyPfannschmidt** [comment]
yikes, and we need to merge master into features

**Comment by The-Compiler** [comment]
Why? @nicoddemus just did so a few days ago, and nothing too big happened since then :wink:

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt I think it would be better to rebase this branch... could you also include a description and reasoning for the change? From the diff alone I can't really tell what's the purpose...

**Pull request merged**
