### PR TITLE
Remove all py.test-X* entry points.

### PR DESCRIPTION
**Pull request by obestwalter**
These entry points were not documented, so no doc changes are necessary.

### CODE REVIEW

**Comment by The-Compiler** [comment]
I think it should still be mentioned in the changelog.

**Comment by nicoddemus** [comment]
Agreed, also make sure to mention the rationale behind the change (they were introduced at a time when virtual environments where not available and are not really necessary anymore, plus it generated broken entry points in wheels).

**Comment by hpk42** [comment]
this definitely needs a changelog entry along the lines nicoddemus suggests.

**Comment by obestwalter** [comment]
I added the changelog entry.

**Comment by nicoddemus** [comment]
Thanks @obestwalter!

**Pull request merged**
