### PR TITLE
Fix spurious ResourceWarning stderr in testsuite again

### PR DESCRIPTION
**Pull request by asottile**
See #5088

### CODE REVIEW

**Comment by blueyed** [comment]
So the second part of the test is also affected then/now?
Do you have some output from where it failed?

It might make sense to output/log the filtered lines - after all it might still indicate some issue that could be fixed instead, and being aware of it (in build logs etc) would be useful then / in general.

**Comment by asottile** [comment]
yes same failure, I clicked retry so it's gone now

**Comment by blueyed** [comment]
Was it pypy3?
Happended in https://travis-ci.org/pytest-dev/pytest/jobs/595069644#L5358:
```
_________________________ test_pytest_exit_returncode __________________________
[gw0] linux -- Python 3.6.1 /home/travis/build/pytest-dev/pytest/.tox/pypy3-xdist/bin/python
testdir = <Testdir local('/tmp/pytest-of-travis/pytest-0/popen-gw0/test_pytest_exit_returncode0')>
    def test_pytest_exit_returncode(testdir):
        testdir.makepyfile(
            """
            import pytest
            def test_foo():
                pytest.exit("some exit msg", 99)
        """
        )
        result = testdir.runpytest()
        result.stdout.fnmatch_lines(["*! *Exit: some exit msg !*"])
        # Assert no output on stderr, except for unreliable ResourceWarnings.
        # (https://github.com/pytest-dev/pytest/issues/5088)
        assert [
            x
            for x in result.stderr.lines
            if not x.startswith("Exception ignored in:")
            and not x.startswith("ResourceWarning")
        ] == [""]
        assert result.ret == 99
    
        # It prints to stderr also in case of exit during pytest_sessionstart.
        testdir.makeconftest(
            """
            import pytest
    
            def pytest_sessionstart():
                pytest.exit("during_sessionstart", 98)
            """
        )
        result = testdir.runpytest()
        result.stdout.fnmatch_lines(["*! *Exit: during_sessionstart !*"])
>       assert result.stderr.lines == ["Exit: during_sessionstart", ""]
E       assert ['Exit: durin...name=17>', ''] == ['Exit: durin...ionstart', '']
E         At index 1 diff: "Exception ignored in: <_io.FileIO name=17 mode='wb' closefd=True>" != ''
E         Left contains 2 more items, first extra item: 'ResourceWarning: unclosed file <_io.BufferedWriter name=17>'
E         Use -v to get the full diff
/home/travis/build/pytest-dev/pytest/testing/test_runner.py:601: AssertionError
----------------------------- Captured stdout call -----------------------------
============================= test session starts ==============================
platform linux -- Python 3.6.1[pypy-7.1.1-beta], pytest-5.2.2.dev11+g7f80b24e8, py-1.8.0, pluggy-0.13.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/travis/build/pytest-dev/pytest/.hypothesis/examples')
rootdir: /tmp/pytest-of-travis/pytest-0/popen-gw0/test_pytest_exit_returncode0
plugins: forked-1.0.2, hypothesis-4.39.0, xdist-1.30.0
collected 1 item
test_pytest_exit_returncode.py 
============================ no tests ran in 0.96s =============================
!!!!!!!!!!!!!!!!!!!!! _pytest.outcomes.Exit: some exit msg !!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!! _pytest.outcomes.Exit: during_sessionstart !!!!!!!!!!!!!!!!!!
----------------------------- Captured stderr call -----------------------------
Exit: during_sessionstart
Exception ignored in: <_io.FileIO name=17 mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedWriter name=17>
=============================== warnings summary ===============================
testing/test_warnings.py:610
  /home/travis/build/pytest-dev/pytest/testing/test_warnings.py:610: PytestExperimentalApiWarning: testdir.copy_example is an experimental api that may change over time
    testdir.copy_example("warnings/test_group_warnings_by_message.py")
```

**Comment by asottile** [comment]
yes, same as before

**Pull request merged**
