### PR TITLE
 deprecate the pytest.collect module

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
- [x] test
- [x] changelog
- [x] fix docs

### CODE REVIEW

**Comment by blueyed** [comment]
This causes a test failure with xdist:
```
___________________ ERROR collecting example_pkg/test_one.py ___________________
ImportError while importing test module '/tmp/pytest-of-daniel/pytest-524/test_distribution_rsyncdirs_example0/dest/example_pkg/test_one.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
__init__.py:5: in <module>
    from . import collect
E   ImportError: cannot import name 'collect' from partially initialized module 'dest' (most likely due to a circular import) (/tmp/pytest-of-daniel/pytest-524/test_distribution_rsyncdirs_example0/dest/__init__.py)
```

**Comment by blueyed** [comment]
https://travis-ci.org/github/pytest-dev/pytest-xdist/jobs/669139507#L255

**Comment by RonnyPfannschmidt** [comment]
@blueyed https://github.com/pytest-dev/pytest-xdist/blob/master/src/xdist/workermanage.py#L92  had this broken since it was turned into a package, now its finally breaking

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt can you explain what's the relation between this PR and https://github.com/pytest-dev/pytest/pull/6981#issuecomment-606496652?

I ask because of https://github.com/pytest-dev/pytest/pull/7459/files#r451198510, I'm trying to figure out if this should be a breaking change instead of a deprecation.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus the breaking change was when pytest got turned into a package, xdist has a hack in place that expects it to be a module, which needs a fix in xdist

**Comment by nicoddemus** [comment]
I see, thanks!

> xdist has a hack in place that expects it to be a module, which needs a fix in xdist

Can you explain that in more details? We should definitely fix/release this before pytest 6.0 comes out.

**Comment by RonnyPfannschmidt** [comment]
For _pytest it goes for the folder, for pytest itself only for the file

**Comment by nicoddemus** [comment]
PR opened at https://github.com/pytest-dev/pytest-xdist/pull/558

**Pull request merged**
