### PR TITLE
Remove mention of --assert=reinterp in documentation

### PR DESCRIPTION
**Pull request by rjprins**
Related to #1940

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
thanks for working on this long overdue patch

for completeness please add an entry to changelog

**Comment by The-Compiler** [comment]
I agree, no point in cluttering the changelog with stuff which likely isn't relevant to people reading it :wink:

**Comment by rjprins** [comment]
Also updated the first paragraphs on assertion introspection which mentioned "re-evaluating".
I don't think this warrants an entry in the changelog.
Tests failed because GitHub was down.

**Comment by nicoddemus** [comment]
Many thanks @rjprins!

**Comment by RonnyPfannschmidt** [comment]
👍

**Pull request merged**
