### PR TITLE
capture: do not set logging.raiseExceptions = False

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/pytest-dev/pytest/issues/4942

### CODE REVIEW

**Comment by nicoddemus** [comment]
Sorry for the delay!

Hmmm are you getting an error because of this code? We want to add a CHANGELOG error explaining in detail why we are reverting this code, and get a fix back quickly if this issue comes back.

**Comment by blueyed** [comment]
> Hmmm are you getting an error because of this code?

No, just found it confusing - likely when looking at coverage reports.

I'll add a changelog.

**Comment by blueyed** [comment]
Maybe related to https://github.com/pytest-dev/pytest/pull/4988.

**Comment by nicoddemus** [comment]
Would you like to include this one in 4.4 @blueyed?

**Comment by blueyed** [comment]
Rather not.. too  much in there already.. ;)

**Comment by nicoddemus** [comment]
Gentle ping in case you want to pick this up again. 👍

**Comment by blueyed** [comment]
Added changelog, and rebased it.

**Comment by nicoddemus** [comment]
I noticed you added this to the 5.0 milestone, is that correct?

**Comment by blueyed** [comment]
Yes, before - but only since it was the next after 4.4.

**Comment by nicoddemus** [comment]
OK to move to 4.5 then?

**Comment by blueyed** [comment]
Sure, I'd just merge it already.

**Pull request merged**
