### PR TITLE
Add explicit flag names for failed first and last failed

### PR DESCRIPTION
**Pull request by MichaelAquilina**
The title pretty much says it all, full name flags make it obvious what the flags are doing.

### CODE REVIEW

**Comment by adamchainz** [comment]
+!

**Comment by RonnyPfannschmidt** [comment]
thanks for noticing and implementing :+1: ,
please rebase/retarget onto the features branch

**Comment by nicoddemus** [comment]
:+1:

**Comment by MichaelAquilina** [comment]
It seems I need to open a new pull request to specify a different branch to rebase onto so I'm closing this one.

**Pull request closed without merging**
