### PR TITLE
Remove nullcontext + parametrize recommendation

### LINKED ISSUE #11556: Remove/update recommendation about using nullcontext + parametrize
As discussed in https://github.com/pytest-dev/pytest/issues/11555#issuecomment-1780749198, we should no longer recommend that approach in our documentation.

### PR DESCRIPTION
**Pull request by ziadk**
- Closes #11556.
- Removed recommendation about using nullcontext + parametrize in the documentation.

### CODE REVIEW

**Comment by kalekundert** [comment]
I know I'm not a big contributor to pytest, but for what it's worth, I don't agree with this change.  Real-world parametrized tests often have a lot of setup and teardown code, and writing separate test functions for the "should raise" and "shouldn't raise" cases is hard to do without duplicating this code.  I wrote about this a bit more extensively [here](https://stackoverflow.com/questions/67552586/pytest-mixing-exception-testing-using-pytest-mark-parametrize/67562035#67562035).

IMO, the documentation example could be improved by adding a way to specify an expected value in the case that no exception is raised, similar to what I show in the link above.  But removing the example altogether is a step in the wrong direction.

**Comment by Pierre-Sassoulas** [comment]
I agree with @kalekundert, that it's nice to know it's possible to use context manager this way. It's probably more intuitive to do two tests functions one for each behavior I certainly did that a lot in the past without reading a doc to give me the idea, I also named fixture a particular way ``if "boom" in fixture_name`` to handle both use case in the same function. I think it's a neat idea about how to possibly design tests that one can follow -- or not. It's not linked to the pytest framework though, as it could be used with unittest's ``self.assertRaises`` instead of ``pytest.raises`` and a list of context manager instead of ``parametrize``. So maybe it's more suited to a blog post about unit test design than the pytest's doc ?

**Comment by nicoddemus** [comment]
I'm OK with improving that section with some examples and alternatives, rather than just deleting it.

**Comment by nicoddemus** [comment]
Should we close this and update the issue to mean to improve the example? If so suggestions would be good.

**Review by nicoddemus — CHANGES_REQUESTED** [review]
Seems we do not have consensus this section should be removed from the docs. Waiting to see if others would like to comment on it, otherwise we should close this.

**Comment by nicoddemus** [comment]
Closing this then.

Thanks @ziadk, sorry for wasting time on this, but in the end is important to have consensus here. 👍

**Pull request closed without merging**
