### PR TITLE
Add --no-trace option, overrides pytrace=True for pytest.fail

### PR DESCRIPTION
**Pull request by GPery**
Hey, I just opened [this issue](https://github.com/pytest-dev/pytest/issues/6651) to open a PR for the fork I'll be using for my automated exercise testing.
Hoping this change can be useful to others as well :smile:

### CODE REVIEW

**Comment by blueyed** [comment]
Another idea that comes to mind is enforcing `pytrace=False` in `OutcomeException` always when the option is enabled.

**Comment by GPery** [comment]
That's where I started, but the session isn't available there in a clear manner.
The `_repr_failure_py` is a relatively nice place for it, but perhaps it should be organised a bit more nicely.

**Comment by nicoddemus** [comment]
> Note that _repr_failure_py is bad already (with regard to typing) to return a str here in some cases - this should not get extended.

Not sure I agree... I don't think the method is being extended; it used to return `str` in some instances, and continues to return `str` in an additional condition... is that what you mean by "extended"?

I agree that `_repr_failure_py` is a bit messy, but this is not making it worse than already is.

**Comment by blueyed** [comment]
> > Note that _repr_failure_py is bad already (with regard to typing) to return a str here in some cases - this should not get extended.
> 
> Not sure I agree... I don't think the method is being extended; it used to return `str` in some instances, and continues to return `str` in an additional condition...

I've looked into making it not return `str` anymore, so this would make that a bit more difficult.


@GPery 
> btw: have you tried `--tb=line`?

**Comment by GPery** [comment]
> @GPery
> 
> > btw: have you tried `--tb=line`?

I have not.
This will do nicely, thank you!

**Comment by nicoddemus** [comment]
So I think `--tb=line` is sufficient and we can close this @GPery?

**Comment by GPery** [comment]
No, I was mistaken on the last comment, `--tb=line` still outputs the file path, which doesn't work for me. `--tb=none` also wouldn't do, because it doesn't output the failure message. I'll keep using the fork, but I'm not sure if my use case is common enough that anyone would find it necessary.

I would appreciate the merge, it's a minor change that'll make things easier for me (keeping up to date with upstream).

**Comment by bluetech** [comment]
My opinion is that this need is not common enough to deserve a configuration option, so I propose we close this PR. The issue can remain open in case someone comes up with another suggestion for satisfying this need.

**Comment by bluetech** [comment]
Now that #7100 is merged, we have a better avenue for resolving this issue, as mentioned here: https://github.com/pytest-dev/pytest/pull/7100#pullrequestreview-415533577, so I'm closing this PR.

**Pull request closed without merging**
