### PR TITLE
Remove setup.py test now that it's broken

### PR DESCRIPTION
**Pull request by asottile**
See #3543

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks @asottile!

**Comment by nicoddemus** [comment]
Oh just realized we would need a `trivial` changelog entry for that...

**Comment by asottile** [comment]
on it! I always forget 😕

**Comment by RonnyPfannschmidt** [comment]
as far as external api is concerned, taking away setup.py test is a breaking change, even if it was broken by accient ^^

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt I agree, but the problem is that it seems to be broken for a few major releases now without people noticing, so I think it is OK to just remove it.

**Comment by RonnyPfannschmidt** [comment]
The SRC move made things apparent, that was recent

**Comment by nicoddemus** [comment]
Indeed

**Pull request merged**
