### PR TITLE
Explain a bad scope value to the user

### PR DESCRIPTION
**Pull request by tgoodlet**
Might be a bit friendlier for newbs and typos.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
good thinking and well done 

can you please add a test as well so we can avoid regressions?

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt sure will do!

**Comment by nicoddemus** [comment]
Thanks, please don't hesitate on posting here if you have questions. :grin:

**Comment by tgoodlet** [comment]
@nicoddemus I'm assuming I can stick the new test(s) in `testing/python/colllect.py` since the error should be raised during the collection phase?

**Comment by nicoddemus** [comment]
About the test, I think `testing/python/collect.py` would be OK. I think being more specific about the message would be fine as well.

**Comment by RonnyPfannschmidt** [comment]
i think its important to check the specific value, after all the initial exception is a ValueError as well and a test without the new specifics would add no value

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt @nicoddemus sorry about the delay with this. I added a unit test. Let me know if this is up to snuff :)

**Comment by nicoddemus** [comment]
Thanks! 

The py26 tests failed due to your usage of `{}` in the string formatting, for py26 you have to number it: `{0}` and `{1}` respectively. Could you fix it? Thanks!

**Comment by tgoodlet** [comment]
@nicoddemus will do. 
Are you guys still supporting py26; it's been EOL for 3 years?

**Comment by The-Compiler** [comment]
Yes - a test runner is a bit in a special position here, and we agreed to support Python versions as long as pip does.

**Comment by nicoddemus** [comment]
Hey @tgoodlet, thanks for the fix.

I just noticed (sorry, only now I had some time to look at the code) that we also have a similar code in the [`parametrize` function](https://github.com/pytest-dev/pytest/blob/master/_pytest/python.py#L802):

```python
        if scope is None:
            scope = _find_parametrized_scope(argnames, self._arg2fixturedefs, indirect)
        scopenum = scopes.index(scope)
        valtypes = {}
        for arg in argnames:
            if arg not in self.fixturenames:
```

Would you mind extracting your try/except to a function and reuse that in both places? Sorry for not noticing this earlier.

**Comment by nicoddemus** [comment]
Also, please add yourself to `AUTHORS` and a `CHANGELOG` entry. 😁

**Comment by tgoodlet** [comment]
@nicoddemus I think that should do it.
Let me know if there's anything else.

**Comment by RonnyPfannschmidt** [comment]
@tgoodlet for the first addition you also need to put an actual link in, please take a look down in the file

**Comment by RonnyPfannschmidt** [comment]
fabulous work, thanks for your patience

**Comment by nicoddemus** [comment]
> fabulous work, thanks for your patience

I second that! Thanks again @tgoodlet!

**Pull request merged**
