### PR TITLE
Fix Capfd From Fixtures After Test Teardown

### PR DESCRIPTION
**Pull request by trrichard**
Resolves https://github.com/pytest-dev/pytest/issues/3033
 
@nicoddemus

### CODE REVIEW

**Comment by nicoddemus** [comment]
Hi @trrichard, sorry for the delay.

Unfortunately this causes the tests which ensure `capsys` and `capfd` can be used for other fixtures to break, so I'm not sure this will be enough...

**Comment by trrichard** [comment]
Hummm. Well I'm not sure I know how to fix it then. 

Could you take a look?

**Comment by nicoddemus** [comment]
@trrichard will do, thanks!

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus ping?

**Comment by nicoddemus** [comment]
Thanks for the ping @RonnyPfannschmidt; this is on my radar, I will definitely get to it when I get a chance.

**Comment by nicoddemus** [comment]
Sorry again for the delay @trrichard.

I opened #3830 instead of pushing to this one because I had to rebase on `master` and did not want to force-push to your fork.

**Pull request closed without merging**
