### PR TITLE
tests: conftest: handle tests using runpytest_subprocess as "slowest"

### PR DESCRIPTION
**Pull request by blueyed**
This handles e.g. the faulthandler tests then.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
i like the change,, its a lovely tweak, can you sort out the spurious merge commit

**Comment by blueyed** [comment]
> can you sort out the spurious merge commit

There is none: https://github.com/pytest-dev/pytest/pull/6076/commits

This is from my fork (from this page):

> blueyed added a commit to blueyed/pytest that referenced this pull request yesterday
￼> Merge branch 'runpytest_subprocess-slowest' into my-master ￼… 9514d6c

**Comment by blueyed** [comment]
Assuming this to be ACKed, thanks!

**Comment by RonnyPfannschmidt** [comment]
indeed, that was bad ux from github

**Comment by blueyed** [comment]
nah, not really - it is good for cross-linking.  it also clearly says "1" next to commits without having to look there.

**Pull request merged**
