### PR TITLE
Allow marking fixtures as always-indirect

### LINKED ISSUE #10101: Marking fixtures as always-indirect
#### What's the problem this feature will solve?
I'm developing a pytest plugin that allows users to easily configure their fixtures: https://pypi.org/project/pytest-paramark/

One of the things I need for the plugin to be useful, is making all parametrizations of a given fixture indirect by default, so that users don't need to add `parametrize(..., indirect=[...])` to all their tests.

I think such a feature would be also useful on its own.

#### Describe the solution you'd like
Add an optional parameter, so that one can write `@pytest.fixture(indirect=True)`. This would:
 * make all parametrizations of this fixture indirect
 * disallow non-parametrized usage, unless the fixture provides defaults for all its arguments
 
#### Alternative Solutions
I've tried monkeypatching pytest inside the plugin to add this argument, but this is brittle, as I needed to dig deep into pytest's internals.
I'd rather have this included upstream, if possible.

#### Additional context
I'm happy to work on a PR if this is something you find interesting/useful.

### PR DESCRIPTION
**Pull request by michallowasrzechonek-silvair**
closes #10101

- [x] Include documentation when adding new features.
- [x] Include new tests or update existing tests when applicable.
- [x] Allow maintainers to push and squash when merging my commits. Please uncheck this if you prefer to squash the commits yourself.

- [x] Create a new changelog file in the `changelog` folder, with a name like `<ISSUE NUMBER>.<TYPE>.rst`. See [changelog/README.rst](https://github.com/pytest-dev/pytest/blob/main/changelog/README.rst) for details.

- [x] Add yourself to `AUTHORS` in alphabetical order.

### CODE REVIEW

**Comment by mrzechonek** [comment]
@RonnyPfannschmidt is there anything I could do to improve this and get it merged? :)

**Comment by michallowasrzechonek-silvair** [comment]
@RonnyPfannschmidt ping?

**Comment by RonnyPfannschmidt** [comment]
I haven't been able to allocate some time to understand the exact implications,

As I m surprisingly going to be a father again today i won't be able to look at this timel

@nicoddemus can you give it a look

**Comment by michallowasrzechonek-silvair** [comment]
Congratulations!

**Comment by nicoddemus** [comment]
Sorry for the delay.

@RonnyPfannschmidt **[you mentioned](https://github.com/pytest-dev/pytest/issues/10101#issuecomment-1174642674)** that you wanted to brainstorm a better name for the parameter.

@michallowasrzechonek-silvair you said you didn't want to require users to add `@parametrize` to all their tests, but they still need to do that in order to give the parameters, correct?

**Comment by RonnyPfannschmidt** [comment]
The more I think about it, the more this is a spooky action at a distance

I'd like to find a more explicit way to sort this out

**Comment by michallowasrzechonek-silvair** [comment]
Not really. This is about the need to add `indirect=["foo"]` to all *usages* of `parametrize`, if fixture `foo` is meant to be indirectly parametrized.

I think "indirect" is rather a property of the fixture (part of its API) than a property of the invocation.

**Comment by RonnyPfannschmidt** [comment]
It ought to be a part of the parameterization as its telling whether its OK to pass something to a fixtures or if it should be used directly

**Comment by michallowasrzechonek-silvair** [comment]
Did you have a chance to assess if this is a good idea? If it isn't, I'm OK with closing.

**Comment by RonnyPfannschmidt** [comment]
I believe the naming requires some bikeshedding

What we want is a fixture that always needs a parameter

Indirect is barely comprehensible for Parametrize, but for fixtures it's mind-boggling

First ideas for the name are `require_parameters`, but I'm sure we can do better with some brainstorming 

Im under the impression that it is necessary to **follow up** with a bad integration of lazy fixtures in core with a way to spell out fixture dependencies with parameters

**Comment by michallowasrzechonek-silvair** [comment]
> What we want is a fixture that always needs a parameter
Yes! Thanks for spelling it out like that, it's much clearer.

**Pull request closed without merging**
