### PR TITLE
Remove pre-2.6 support code and docs (including obsolete oldinterpret module)

### LINKED ISSUE #1226: Remove support code and docs for Python 2.5 or lower
While fixing #1224 I realized we only support Python >= 2.6 now, so the example which doesn't use a class decorator can be removed. That reminds me that we should review code and docs to remove features and tests which are supposed to support 2.5 or lower; this perhaps can clean up the code a bit.

### PR DESCRIPTION
**Pull request by nicoddemus**
Fix #1226

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
:+1:

**Comment by nicoddemus** [comment]
Should we take the opportunity to rename `newinterpret` to, `interpret`, or even better, just merge `newinterpret` into `reinterpret.py`?

**Comment by RonnyPfannschmidt** [comment]
I think that should follow up after merge

**Comment by nicoddemus** [comment]
Fair enough, merging then!

**Comment by nicoddemus** [comment]
I had the commit already on my local repository. :smile:

See #1268

**Comment by RonnyPfannschmidt** [comment]
I didn't mean to cause extra intermediate work

**Comment by nicoddemus** [comment]
Oh no worries, a simple rebase took care of that

**Pull request merged**
