### PR TITLE
permit node to warn with any warning type, not just PytestWarning

### PR DESCRIPTION
**Pull request by symonk**
Hi all, as per #7615 This pr enabled the item `node.warn` to handle any subclass of Warning rather than be explicitly locked to instances / subclass of PytestWarning.  I am not entirely sure on the 'use-case' for this but I'm just working on contributions and came across the issue.  Normally I wouldn't be a fan of isinstance checking and raising a ValueError under such scenario(s) but I kept the same internals as previously here because otherwise a generic TypeError is raised which offers little benefit to the  caller.

Thanks!

### CODE REVIEW

**Review by RonnyPfannschmidt — APPROVED** [review]

**Comment by symonk** [comment]
@nicoddemus can you advise on merge guidelines? Im unsure if it requires atleast 2 approvals :)

**Review by nicoddemus — APPROVED** [review]
Thanks @symonk!

Took the liberty of adding links to the CHANGELOG and a `..versionchanged` notice to the docstring. 👍

**Comment by nicoddemus** [comment]
> @nicoddemus can you advise on merge guidelines? Im unsure if it requires atleast 2 approvals :)

We don't have a hard rule here... I think if you got at least one approval, you're free to merge the PR yourself, but often is good to get at least two or more approvals to make sure people can make further suggestions (like I just did here). Also helps to leave a quick notice like: "I will merge this later/tomorrow unless someone would like to give this another look", and see if anybody manifests. 😁 

Either way don't hesitate to ask. 👍

**Comment by nicoddemus** [comment]
A quick hint: leave a phrase like "Closes #7615" in the PR description so GitHub will close the issue automatically for us when the PR gets merged. 👍

**Pull request merged**
