### PR TITLE
Merge master into features

### PR DESCRIPTION
**Pull request by nicoddemus**
Supersedes #6457

### CODE REVIEW

**Comment by nicoddemus** [comment]
Trying a workaround for py35-win in 04d5b56

**Comment by nicoddemus** [comment]
Disabling cov entirely on py35-win to make sure it is coverage related

**Comment by nicoddemus** [comment]
Oh OK, it is not coverage related then:

```
Traceback (most recent call last):

  File "c:\hostedtoolcache\windows\python\3.5.4\x64\Lib\multiprocessing\connection.py", line 132, in __del__

  File "c:\hostedtoolcache\windows\python\3.5.4\x64\Lib\multiprocessing\connection.py", line 277, in _close

OSError: [WinError 6] The handle is invalid
```

**Comment by blueyed** [comment]
I'd say to a) skip the test there, or b) use the simplified/mocked version (without multiprocessing).

**Comment by nicoddemus** [comment]
> simplified/mocked version (without multiprocessing).

Yeah that is what I was thinking, I will get to this later.

**Pull request merged**
