### PR TITLE
merge features into master to begin the 2.9 line

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**

### CODE REVIEW

**Comment by nicoddemus** [comment]
:+1: (I didn't actually read all the diff, but I assume it was just a merge so I think we are good to go :grin:)

**Comment by RonnyPfannschmidt** [comment]
the merges where mostly about the changelog

**Comment by The-Compiler** [comment]
It looks like `---` titles were changed to `===` in the changelog, but in the merged version it's one `===` title and the others are `---` again.

**Comment by nicoddemus** [comment]
@The-Compiler that's weird, they they all show as ==== to me on the different...

**Comment by nicoddemus** [comment]
*diff, sorry for auto correct :grin:

**Pull request merged**
