### PR TITLE
fix bug with nonskipped first test in package

### PR DESCRIPTION
**Pull request by zefirior**
Issue #5830 
Fix fail skipping the first test in package marked as ``skip``

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
great job at sorting this one aout and creating a working first implementation

at first glance it would still create duplicate markers on the module

the problem here is that the package object really should be the parent of the tests collected by the module
so other tests would also inherit the packages mark

however as things are, we have a package and a module, and the  module has the markers

so while the collection node tree structure is as it is now,
we need to introduce a `_PackageModule` that has `ALLOW_OWN_MARKERS = False` on top of your correction to ensure the module of `__init__.py` wont get duplicate marker objects

**Comment by zefirior** [comment]
If I understand correctly, you talked about the case when `__init__.py` is a test module. This module should not have its own markers, because the module inherits the markers from the parent package

**Comment by blueyed** [comment]
@zefirior 
Thanks for this.  I've went ahead and rebased it to get CI results (pytest-CI was missing).  Old HEAD: 6e5538b.

@RonnyPfannschmidt 
Please see the comment above.

**Comment by zefirior** [comment]
Thanks for review! I will be happy to help you in the future.

**Comment by asottile** [comment]
just a heads up, I'm looking to revert this in #6197 (at least temporarily) as it caused some regressions

**Pull request merged**
