### PR TITLE
Constrain more_itertools for Python 2.7 compatibility

### LINKED ISSUE #4772: more_itertools throws SyntaxError when pytest installed via setuptools
I have the following minimal `setup.py`:

```python
    import setuptools
    
    setuptools.setup(
        setup_requires=['pytest-runner'],
        tests_require=['mock', 'pytest'],
        test_suite='tests',
        python_requires='>=2.7',
    )
```

when running it with 

```bash
    python setup.py test
```

I keep getting the following error:

```
Traceback (most recent call last):   File "setup.py", line 8, in

    <module>
        python_requires='>=2.7',   File "/Users/project/tmp/env/lib/python2.7/site-packages/setuptools/__init__.py",
    line 145, in setup
        return distutils.core.setup(**attrs)   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py",
    line 151, in setup
        dist.run_commands()   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py",
    line 953, in run_commands
        self.run_command(cmd)   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py",
    line 972, in run_command
        cmd_obj.run()   File "/Users/project/tmp/.eggs/pytest_runner-4.2-py2.7.egg/ptr.py",
    line 176, in run
        return self.run_tests()   File "/Users/project/tmp/.eggs/pytest_runner-4.2-py2.7.egg/ptr.py",
    line 187, in run_tests
        result_code = __import__('pytest').main()   File "/Users/project/tmp/.eggs/pytest-4.2.0-py2.7.egg/pytest.py",
    line 14, in <module>
        from _pytest.fixtures import fillfixtures as _fillfuncargs   File "/Users/project/tmp/.eggs/pytest-4.2.0-py2.7.egg/_pytest/fixtures.py",
    line 16, in <module>
        from more_itertools import flatten   File "build/bdist.macosx-10.13-x86_64/egg/more_itertools/__init__.py", line
    1, in <module  File
    "/Users/project/tmp/.eggs/more_itertools-6.0.0-py2.7.egg/more_itertools/more.py",
    line 329
        def _collate(*iterables, key=lambda a: a, reverse=False):
                                   ^ SyntaxError: invalid syntax
```

The problem appears also in the tests of more_itertools that are executed during first run, when setup tools installs test dependencies:

```
    Downloading
    https://files.pythonhosted.org/packages/dd/f4/cdfbb6f07f767e0cd8a11b16adfecc735b6eb87dbebda026ce8898e1cc22/more-itertools-6.0.0.tar.gz#sha256=590044e3942351a1bdb1de960b739ff4ce277960f2425ad4509446dbace8d9d1
    Best match: more-itertools 6.0.0 Processing
    more-itertools-6.0.0.tar.gz Writing
    /var/folders/lq/c1ll7pqx7rb28p7m_8wz3h2d0r0mws/T/easy_install-Auek5Z/more-itertools-6.0.0/setup.cfg
    Running more-itertools-6.0.0/setup.py -q bdist_egg --dist-dir
    /var/folders/lq/c1ll7pqx7rb28p7m_8wz3h2d0r0mws/T/easy_install-Auek5Z/more-itertools-6.0.0/egg-dist-tmp-I3ic_t
    warning: no files found matching 'fabfile.py'   File
    "build/bdist.macosx-10.13-x86_64/egg/more_itertools/tests/test_more.py",
    line 892
        print(item, file=f)
                        ^ SyntaxError: invalid syntax
    
      File "build/bdist.macosx-10.13-x86_64/egg/more_itertools/more.py",
    line 329
        def _collate(*iterables, key=lambda a: a, reverse=False):
                                   ^ SyntaxError: invalid syntax
    
    zip_safe flag not set; analyzing archive contents... Copying
    more_itertools-6.0.0-py2.7.egg to /Users/project/tmp/.eggs
    
    Installed /Users/project/tmp/.eggs/more_itertools-6.0.0-py2.7.egg
```

The problem does not happen when I install more_itertools with

```bash
    pip install more_itertools
```

My environment

```bash
(env) MBP-OK-32:tmp maciej.gawinecki$ pip list
Package    Version
---------- -------
pip        19.0.2
setuptools 40.8.0
wheel      0.33.0
(env) MBP-OK-32:tmp maciej.gawinecki$ Python --version
Python 2.7.15
```

MacOS HighSierra version 10.13.6

### PR DESCRIPTION
**Pull request by sambrightman**
Fixes #4772, #4770.

There was some discussion in #4770 that maybe this can be written slightly differently but it worked for me like this.

I assume this doesn't require a changelog entry.

### CODE REVIEW

**Comment by nicoddemus** [comment]
> I assume this doesn't require a changelog entry.

Oh I believe it does, as definitely the Python 2 users which are facing this problem would like to know about it in the CHANGELOG. 👍

**Comment by sambrightman** [comment]
Ok, changelog entry added.

**Comment by hugovk** [comment]
> Fixes #4772, #4770.

GitHub tip: when this is merged, only the first issue will be autoclosed. Repeat the keyword to autoclose both:

> Fixes #4772, fixes #4770.

Docs: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by sambrightman** [comment]
Thanks! In this case #4772 is already closed.

**Pull request merged**
