### PR TITLE
Merge master into features

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
looks like the tox setup is now broken

**Comment by RonnyPfannschmidt** [comment]
@blueyed can you take a look, it seems related to that coverage hack not working as "expected"

**Comment by nicoddemus** [comment]
Actually this just seems like a conflicting test now that we merged #3912 into `features`. I will take a look. 👍

**Comment by nicoddemus** [comment]
Should be working now. 👍

**Comment by dhirensr** [comment]
@nicoddemus : do I need to improve the tests there? is there any problem?

**Comment by nicoddemus** [comment]
@dhirensr no need, I already did it in 2256f2f 👍

**Pull request merged**
