### PR TITLE
Add deprecation module to centralize deprecation messages and bits of…

### PR DESCRIPTION
**Pull request by nicoddemus**
As discussed in the mailing list, add a new module to centralize warning messages and bits of the code of features that we plan to deprecate in the next release.

The idea is to make it easy to glance what's deprecated and remove the features when the time comes around.

I opted for a simple module instead of a plugin because we can't completely move all deprecated code to it, only a few bits (for example, the logic that deals with `pytest_funcargs__` fixtures can't be completely extracted from `fixtures.py`). Because of this I don't think adding yet another core plugin is worth it and prefer to keep things simple.

### CODE REVIEW

**Comment by nicoddemus** [comment]
Oh, about the "bits of the code" I mentioned there's none yet, but I plan to add a simple proxy class to this module in order to issue deprecation warnings on `pytest.config` usages, as discussed in the mailing list.

**Comment by RonnyPfannschmidt** [comment]
idea - instead of just calling it `deprecated` how about having a plugin/module like `removedin40`
the usage of constants/functions from such modules will make really clear when something will be gone

**Comment by nicoddemus** [comment]
As we discussed on GTalk, I'm not a big fan of adding version numbers to module names, but that's just personal preference.

If nobody else has anything to say on this matter I will go with @RonnyPfannschmidt's suggestion, but I prefer to use "deprecate" or "deprecated" instead because that's a more natural name for this IMO.

**Comment by RonnyPfannschmidt** [comment]
my preference for `removedin...` is based purely on the naming expressing very exactly what will happen

**Comment by The-Compiler** [comment]
I'm for `deprecated` or so too, having a bunch of `removedin40`, `removedin50` etc. modules lying around seems quite ugly to me.

**Comment by RonnyPfannschmidt** [comment]
its intentinally ugly and to the point

**Comment by RonnyPfannschmidt** [comment]
also if we put it all into one module, we wont know what to remove when easyly

**Comment by nicoddemus** [comment]
> also if we put it all into one module, we wont know what to remove when easyly

Hmm what do you mean @RonnyPfannschmidt? Could you elaborate? I thought the idea was to remove everything from `_pytest.deprecated` before releasing **4.0**.

**Comment by flub** [comment]
current PR looks good to me, +1 for merging as-is

**Comment by flub** [comment]
After seeing this was 5 days old I went ahead and merged it... shout at me if I shouldn't do that

**Pull request merged**
