### PR TITLE
[WIP/RFC] fixtures: register finalizers with all previous fixtures in the stack (take 2)

### PR DESCRIPTION
**Pull request by blueyed**
Picking up https://github.com/pytest-dev/pytest/pull/6438 again.

TODO:

- [x] test for fix using tuple  (https://github.com/pytest-dev/pytest/pull/6554)
- [x] test for #6504 (integrated)
- [ ] investigate other issues
- [x] typing?

/cc @SalmonMode 

NOTES:

- Sphinx was also affected (https://github.com/sphinx-doc/sphinx/pull/7037), but worked with this PR here.

### CODE REVIEW

**Comment by blueyed** [comment]
@SalmonMode any idea/plan to test #6504 (83349d7011)?

**Comment by SalmonMode** [comment]
@blueyed I have an idea. I was working on a test for #6492 / #6551 but I just saw you beat me to the punch :joy: 

I'll put together the test for #6504 now

**Comment by SalmonMode** [comment]
@blueyed added the test case and also cleaned up the logic a bit by putting it into its own function so the code reads a little easier.

**Comment by SalmonMode** [comment]
@blueyed is there a reason to not include typing in this?

**Comment by blueyed** [comment]
> @blueyed is there a reason to not include typing in this?

No, would be good to have here also, of course.

**Comment by timc13** [comment]
Not sure if this is related, but I'm seeing that `indirect` fixtures are not getting cleaned up when being stacked.

e.g.
```
import pytest


@pytest.fixture
def x(): pass


@pytest.fixture
def y(): pass


@pytest.mark.parametrize("x", [0, 1], indirect=['x'])
@pytest.mark.parametrize("y", [2, 3], indirect=['y'])
def test_foo(x, y):
    pass

```

**Comment by blueyed** [comment]
@timc13 with this branch I assume?

**Comment by timc13** [comment]
no, sorry - this is in 5.3.5.  I was wondering if this PR is related.  I can also create another ticket otherwise

**Comment by blueyed** [comment]
@timc13 
> I was wondering if this PR is related.

Test it? :)

> I can also create another ticket otherwise

Yes, but information if this here helps would be useful there then also.

**Comment by SalmonMode** [comment]
any update on this?

I also wanted to link this related fix for pytest-django https://github.com/pytest-dev/pytest-django/pull/807

@timc13 were you able to run your tests using this branch to see if it solved your issue?

**Comment by SalmonMode** [comment]
@RonnyPfannschmidt @nicoddemus any thoughts on moving this forward? If I get the chance, I'll resolve the merge conflict later today (and I'm guessing that's the cause of the failed build). But I think it's a pretty solid fix at this point.

**Comment by SHxKM** [comment]
I'm pretty sure this is affecting me in [Inconsistent results for a test when running in-suite](https://github.com/pytest-dev/pytest-django/issues/842). Is there at least a temporary workaround that once can use?

**Comment by SalmonMode** [comment]
@SHxKM would you be able to try this branch in combination with the branch for pytest-django [here](https://github.com/pytest-dev/pytest-django/pull/807)?

I believe both changes will provide the solution, because the original fix I made for this caused some issues to be revealed in pytest-django that line up with what you described in the issue you linked.

**Comment by SHxKM** [comment]
@SalmonMode - Thanks for responding. So I ran:

```
pip install git+https://github.com/blueyed/pytest@fixture-stack
pip install git+https://github.com/SalmonMode/pytest-django@cnejame-fix-pytest-5-3-3-compatibility
```

I hope that's what you meant. The test still fails when running together with the whole suite.

**Comment by SalmonMode** [comment]
Hmmm are you able to provide a minimal set of tests to recreate it?

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt could you help reviewing this one as well?

**Comment by RonnyPfannschmidt** [comment]
at best by the weekend

**Comment by blueyed** [comment]
Closing as per https://github.com/blueyed/pytest/issues/365#issuecomment-651738385.

**Comment by SalmonMode** [comment]
As mentioned [here](https://github.com/blueyed/pytest/issues/365#issuecomment-660322067), I'll be remaking this branch under my repo again to continue the work.

**Comment by blueyed** [comment]
@SalmonMode Thanks!

**Pull request closed without merging**
