### PR TITLE
Release 4.6.6

### PR DESCRIPTION
**Pull request by nicoddemus**
I also cherry-picked 065773aa97a02731e5eec05e29204b50850d9248 and 1c5efffd904e0068a3e7b4090d94bbe589be66bf for this release.

### CODE REVIEW

**Comment by asottile** [comment]
did we backport the attrs fix? the tests aren't failing so maybe that's already handled 🤔

**Comment by asottile** [comment]
I cleaned out the `[needs backport]` label, only #5446 seemed to be missing but I didn't look too hard 👍

**Comment by nicoddemus** [comment]
> I cleaned out the [needs backport] label, only #5446 seemed to be missing but I didn't look too hard

Oops already pushed the tag... I guess we can backport this to 4.6.7 then

**Comment by asottile** [comment]
all good :)

**Pull request merged**
