### PR TITLE
Merge master into features

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
this was done as series of merge commits to ease conflict resolution

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
the py26 failures seem to stem from the recent pip update

**Comment by The-Compiler** [comment]
Yep, looks like https://bitbucket.org/hpk42/tox/issues/332/ / https://github.com/pypa/pip/issues/3667

**Comment by nicoddemus** [comment]
Should we just remove that comment from the `tox` file then?

**Comment by The-Compiler** [comment]
We can also set `VIRTUALENV_DOWNLOAD=no` on Travis like I did in https://github.com/The-Compiler/qutebrowser/commit/b634b051c8bd87df02a9e412468c9a32743f25b8 as a workaround - then virtualenv will use the vendored older pip (where this happens to work) instead of download the newest one.

**Comment by nicoddemus** [comment]
Hey @RonnyPfannschmidt, could you please get the new changes from `master` so we can merge this in? :grin:

**Comment by RonnyPfannschmidt** [comment]
done, pushing after local tox

**Comment by nicoddemus** [comment]
Hmm strange, it seems `test_absolute_win32_path` is failing on Windows...

**Comment by nicoddemus** [comment]
Please check solution for `test_absolute_win32_path` in #1566

**Comment by nicoddemus** [comment]
Thanks @RonnyPfannschmidt!

**Pull request merged**
