### PR TITLE
py36+: remove _pytest.compat.order_preserving_dict

### PR DESCRIPTION
**Pull request by asottile**
See #7808

### CODE REVIEW

**Review by Zac-HD — APPROVED** [review]

**Comment by bluetech** [comment]
I thought it was only since 3.7?

**Comment by asottile** [comment]
> 
> 
> I thought it was only since 3.7?

implemented and provisional in cpython 3.6 (pypy since 3.5), and permanently specified in 3.7

**Review by bluetech — APPROVED** [review]
Huh so that should cover it.

**Comment by nicoddemus** [comment]
> Huh so that should cover it.

Yep, seems like it, PyPy has that since 2015 so it should be covered there as well (in fact CPython borrowed the implementation IIRC).

**Review by nicoddemus — APPROVED** [review]

**Pull request merged**
