### PR TITLE
Avoid ast deprecation warnings on Python 3.12

### LINKED ISSUE #10977: [Python 3.12] Assertion rewriting triggers DeprecationWarning
#### What's the problem this feature will solve?
As of pytest 7.3.1, the classes `ast.Str` and `ast.NameConstant` are used in assertion rewriting. Their use has been [deprecated in Python 3.8](https://docs.python.org/3.8/library/ast.html#node-classes). These classes will [emit a _DeprecationWarning_](https://github.com/python/cpython/pull/104199) starting with Python 3.12.

When a user runs pytest 7.3.1 on Python 3.12and pytest collects a test with an `assert` statement, the test will show deprecation warnings.

#### Describe the solution you'd like
Pytest does not trigger a _DeprecationWarning_ when running tests on Python 3.12.

<!-- Provide examples of real-world use cases that this would enable and how it solves the problem described above. -->

Tested with pytest 7.3.1 on Python 3.12 (commit 0aeda29793):

`test_anything.py`
```
def test_a():
    assert True
```

```
$ pytest
===== test session starts =====
platform linux -- Python 3.12.0a7+, pytest-7.3.1, pluggy-1.0.0
rootdir: /tmp/test-cpython-next
collected 1 item                                                                                                                                                                                                                                                             

test_anything.py .                                                                                                                                                                                                                                                     [100%]

===== warnings summary =====
../venv-next/lib/python3.12/site-packages/_pytest/assertion/rewrite.py:927
../venv-next/lib/python3.12/site-packages/_pytest/assertion/rewrite.py:927
  /tmp/venv-next/lib/python3.12/site-packages/_pytest/assertion/rewrite.py:927: DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
    assertmsg = ast.Str("")

../venv-next/lib/python3.12/site-packages/_pytest/assertion/rewrite.py:929
  /tmp/venv-next/lib/python3.12/site-packages/_pytest/assertion/rewrite.py:929: DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
    template = ast.BinOp(assertmsg, ast.Add(), ast.Str(explanation))

../venv-next/lib/python3.12/site-packages/_pytest/assertion/rewrite.py:817
  /tmp/venv-next/lib/python3.12/site-packages/_pytest/assertion/rewrite.py:817: DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
    keys = [ast.Str(key) for key in current.keys()]

../venv-next/lib/python3.12/site-packages/_pytest/assertion/rewrite.py:941
../venv-next/lib/python3.12/site-packages/_pytest/assertion/rewrite.py:941
  /tmp/venv-next/lib/python3.12/site-packages/_pytest/assertion/rewrite.py:941: DeprecationWarning: ast.NameConstant is deprecated and will be removed in Python 3.14; use ast.Constant instead
    clear = ast.Assign(variables, ast.NameConstant(None))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
===== 1 passed, 6 warnings in 0.01s ====
```

<!-- #### Alternative Solutions -->
<!-- Have you tried to workaround the problem using a pytest plugin or other tools? Or a different approach to solving this issue? Please elaborate here. -->

<!-- #### Additional context -->
<!-- Add any other context, links, etc. about the feature here. -->

### PR DESCRIPTION
**Pull request by bluetech**
Fix #10977.

Marking as draft until we can verify the fix on next py312 alpha/beta release.

### CODE REVIEW

**Review by Zac-HD — APPROVED** [review]
Looks good to me!

Alternatively, we might just wait for the [Python 3.7 end of life in June](https://devguide.python.org/versions/), and then refactor to use the new nodes only since we'll presumably want to do that eventually.

**Comment by RonnyPfannschmidt** [comment]
Wondering if early drop of 3.7 makes sense

We could probably anhilate quite some support code

**Comment by nicoddemus** [comment]
> Wondering if early drop of 3.7 makes sense

I would rather not having to "justify" that decision within the community... whenever we drop a version we get some flak for it, I think we would get even more flak by just dropping a Python version which is still supported.

I think we can wait until it is officially dropped before going forward with pytest itself dropping it.

**Comment by Zac-HD** [comment]
It's also against policy, per https://docs.pytest.org/en/stable/backwards-compatibility.html#python-version-support

(though it might be nice to link from that page to https://devguide.python.org/versions/ ...)

**Comment by A5rocks** [comment]
Hi, the Python 3.12 beta is now out! https://blog.python.org/2023/05/python-3120-beta-1-released.html

**Comment by bluetech** [comment]
Tried it but still not available in github actions. Seems like we need to wait until it shows up here: https://github.com/actions/python-versions/releases

**Comment by bluetech** [comment]
I'm going to fold this PR into #10894 to make things easier to test and backport later.

**Pull request closed without merging**
