### PR TITLE
WIP: ci: Travis: revisit/fix coverage reporting

### PR DESCRIPTION
**Pull request by blueyed**
This should bring coverage back that got missing with 9dcd6f2.

Continuation of https://github.com/pytest-dev/pytest/pull/4839.

### CODE REVIEW

**Comment by blueyed** [comment]
After 1st commit:

> increase coverage by 0.99%.

**Comment by blueyed** [comment]
Now without windows:

> will increase coverage by 0.31%.

**Comment by blueyed** [comment]
Now:

> will increase coverage by 0.46%.

Need to investigate/compare coverage again.

**Comment by blueyed** [comment]
btw: so apparently tests are failing with `PYTEST_ADDOPTS=-vv` on Travis.. :/

**Comment by nicoddemus** [comment]
> btw: so apparently tests are failing with `PYTEST_ADDOPTS=-vv` on Travis.. :/

😞

**Comment by blueyed** [comment]
codecov/patch link still times out, with only 5 uploads now.. https://codecov.io/gh/pytest-dev/pytest/commit/11b531be0a38e3c9ce9e43e52fbc3c56fb72b6a5/build
So the base might also be relevant here.. :/

**Comment by blueyed** [comment]
@nicoddemus 
But we can see that only ~5 build jobs are necessary to have ~current coverage.

**Comment by blueyed** [comment]
The diff status is pretty much expected, since I've added comments where coverage regressed due to #4839.

**Comment by nicoddemus** [comment]
> codecov/patch link still times out, with only 5 uploads now.. [codecov.io/gh/pytest-dev/pytest/commit/11b531be0a38e3c9ce9e43e52fbc3c56fb72b6a5/build](https://codecov.io/gh/pytest-dev/pytest/commit/11b531be0a38e3c9ce9e43e52fbc3c56fb72b6a5/build)
So the base might also be relevant here.. :/

Not sure how to proceed then. Can we reach out to them perhaps? Or even drop the current base and start fresh, if that's the issue?

**Comment by blueyed** [comment]
I'm slacking with them since September last year about this at least.. :/

I will compare this manually again, clean it up, and then we should merge it.

I will bring back the jobs as before, but only ~5 then with coverage reporting.

I also plan to e.g. replace py37 with py37-pexpect (to get one less job) etc.

**Comment by nicoddemus** [comment]
> I'm slacking with them since September last year about this at least.. :/

Bummer. They have no idea why our coverage report view times out?

**Comment by blueyed** [comment]
Yeah, not really apparently..  the suggested it might be flags, or combinations in general.
I've also seen it with other projects though (awesome/awesomeWM), where using less flags appeared to help.. there are less jobs though.

**Comment by blueyed** [comment]
@nicoddemus 
FWIW I could invite you on the slack conversation they've created with me, but it would not really help I guess.

**Comment by nicoddemus** [comment]
Yeah, I agree.

Feel free to merge this then when you clean it up and deem it good enough.

**Comment by blueyed** [comment]
Just for reference: current state:

> 95.04% (+0.75%) compared to 55b78ff

**Comment by blueyed** [comment]
Nearly there - will hopefully finish it tomorrow or on the weekend then.

**Comment by blueyed** [comment]
With master being merged here this also now does not time out anymore on codecov.io.

**Comment by nicoddemus** [comment]
So in summary `flags` were to blame then?

**Comment by blueyed** [comment]
> So in summary `flags` were to blame then?

Looks like it, yes.

**Comment by nicoddemus** [comment]
Good, I'm sure they would like to know that. 👍

**Comment by blueyed** [comment]
It is something they suspect already.  But it is not the only factor apparently.

**Comment by blueyed** [comment]
Continued / restarted in https://github.com/pytest-dev/pytest/pull/4865.

**Pull request closed without merging**
