### PR TITLE
add flake8-pytest-style to plugin_list.rst

### LINKED ISSUE #10709: Docs request: inclusion of flake8-pytest-style
#### What's the problem this feature will solve?

I have been a long time `pytest` user and think it's is amazing.

I discovered [`flake8-pytest-style`](https://pypi.org/project/flake8-pytest-style/) ([repo](https://github.com/m-burst/flake8-pytest-style)) and was quite impressed with it.  I found it makes a lot of quality suggestions on how to better leverage the `pytest` library.  Also, it has good docs on the rationale behind each suggestion.

#### Describe the solution you'd like

There is the [Plugin List](https://docs.pytest.org/en/stable/reference/plugin_list.html) page that lists `pytest` plugins to help one test better with `pytest`.

I think it would be cool to list tools that helps users use the `pytest` library itself better.  `flake8-pytest-style` is one of those tools, I am not sure if there are others.  Perhaps this could be done on the same docs page, or in a new one.

Thanks for entertaining this!  I made this issue because, if I knew about this flake8 plugin, I would have used it much sooner!

### PR DESCRIPTION
**Pull request by sergkim13**
Hello! This is my first PR in opensource project. Please, don't judge me harshly.

This PR closes #10709 by adding `flake8-pytest-style` to `plugin_list.rst`.

### CODE REVIEW

**Review by RonnyPfannschmidt — CHANGES_REQUESTED** [review]
this file is autogenerated, unless you we add a extra condition to the script that creates it, the weekly update will just drop it out again

**Comment by RonnyPfannschmidt** [comment]
i recommend waiting a little with the script as i'm about to fixup and merge #10927

**Comment by The-Compiler** [comment]
To me, this seems like the wrong place entirely for this anyways - after all, this is not a pytest plugin, it's a plugin for the flake8 linter. As I suggested in #10709 already, I think the [Good Practices](https://docs.pytest.org/en/latest/explanation/goodpractices.html) page in the docs would be the perfect place for this.

**Comment by sergkim13** [comment]
So should I remove it from `plugin_list.rst` and add short description about `flake8-pytest-style` to the bottom of `goodpractices.rst`, right?

**Comment by sergkim13** [comment]
Added mention about `flake8-pytest-style` to the `goodpractices.rst`. I would appreciate a review!

**Review by bluetech — COMMENTED** [review]
Thanks @sergkim13, I think this can help users better use pytest.

However, since this appears in the official "good practices" doc, I think it's necessary to add a note like this:

Disclaimer: flake8-pytest-style is not an official pytest project.

**Comment by bluetech** [comment]
cc @m-burst, author of flake8-pytest-style, if you have any comments let us know!

**Comment by sergkim13** [comment]
@bluetech, done!

**Review by bluetech — APPROVED** [review]
Thanks @sergkim13. I hope your first open source contribution went well and won't be your last :)

**Comment by m-burst** [comment]
I want to add my 2 cents as the author of `flake8-pytest-style`.
There is a common caveat: one of the rules enforces a code style that differs from examples in pytest docs (namely `@pytest.fixture()` vs `@pytest.fixture`) unless the plugin is explicitly configured otherwise.
Maybe this should be mentioned here.

**Comment by bluetech** [comment]
@m-burst @sergkim13  What do you think about the following?

flake8-pytest-style is an official pytest project. Some of the rules enforce certain style choices, such as using `@pytest.fixture()` over `@pytest.fixture`, but you can configure the plugin to fit your preferred style.

**Pull request merged**
