### PR TITLE
adapt Pre commit hook and black

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
prepare #3464

### CODE REVIEW

**Comment by blueyed** [comment]
Where/how is this config used?

**Comment by RonnyPfannschmidt** [comment]
@blueyed by the pre-commit tool - its generalized pre commit hooks a dev can opt into

**Comment by blueyed** [comment]
Ah.. for reference: https://pre-commit.com/

**Comment by nicoddemus** [comment]
The CI failures seem related to #3480. Merging `master` into `features` in #3490, after that is merged we can try to rebase this.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus this is consistent with the pinned black versions - else we get failing pre-commit on black upgradeds - i wil upgrade to the latest stable version however

having black in the linting env creates a double failure point as its in need of version syncing

i pan to set up a travis stage for the linting checks however

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus after reiterating and going back to the older black version due to flake8 errors being introduced i reformatted a missing file and would like to get it merged including history for later comprehension

**Comment by RonnyPfannschmidt** [comment]
in that case we will have to defer and possibly rebase this one due to investigating sane caching for pre-commit on travis

**Comment by nicoddemus** [comment]
> in that case we will have to defer and possibly rebase this one due to investigating sane caching for pre-commit on travis

Why, do you think it will take a long time to install the pre-commit hooks? It takes less than a minute in my computer the first time, I don't think that's something to worry about.

**Comment by nicoddemus** [comment]
Nice! It seems to have worked wonderfully!

Please update our `linting` tox env to run `pre-commit` instead and run `tox -e linting` in the `linting` stage for completeness. 👍 

After that I think we are in excellent shape, excellent work!

**Comment by RonnyPfannschmidt** [comment]
i'd prefer to jsut drop the linting then - i'll take a look at getting ti to be pre-commit only as well

@obestwalter it would be nice to have tox plugin for certain kinds of envs there

**Comment by nicoddemus** [comment]
> i'd prefer to jsut drop the linting then - i'll take a look at getting ti to be pre-commit only as well

You are right, dropping it is fine. If you do, please update CONTRIBUTING because we mention `linting` in there.

A small note: I just noticed that the `linting` stage has `TOXENV=coveralls`; I know it doesn't matter but it would be nice to get rid of that as it might be confusing.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i just moved it to use pre-commit

**Comment by obestwalter** [comment]
Hi @RonnyPfannschmidt, best might be to open a "plugin request issue" in tox repo (would be the first, I guess) explaining what you imagine.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i want the linting stage to be fast, whats missing now is a cache for pre-commit

**Comment by nicoddemus** [comment]
> @nicoddemus i want the linting stage to be fast, whats missing now is a cache for pre-commit

It went from `50s` to `2m30s`. While this is a significant increase, it is not really relevant considering that the full build takes `>30m`.

Just saying I'm not particularly concerned with it, but if you really want to improve that timing then go for it. 👍

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i'd also like to put pypy into a own stage in some way

**Comment by nicoddemus** [comment]
Just so we keep track, I think the only thing missing is:

> Shouldn't the linting stage just run tox -e linting for consistency then?

Right?

> @nicoddemus i'd also like to put pypy into a own stage in some way

Not sure why, but feel free to do this in another PR.

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt gentle ping in case you didn't see my last comment. 👍

**Comment by obestwalter** [comment]
You might want to add the code style badge to the README also?

    .. image:: https://img.shields.io/badge/code%20style-black-000000.svg
      :target: https://github.com/ambv/black
      :alt: Code style: black

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i dont want to use tox for the linting since its an extra nesting i dont want to have

**Comment by nicoddemus** [comment]
OK, I fixed the two conflicts, if I done everything correctly we should be able to merge it after all is green.

**Pull request merged**
