### PR TITLE
Various cleanups of the vendored pprint module

### PR DESCRIPTION
**Pull request by BenjaminSchubert**
After vendoring and refactoring how we use the pprint module, there is quite a lot of code that can be simplified.

This is a first stab at it for various simple cleanups.

I was not sure if that's worth adding a changelog entry for it, please let me know what category it should be if you think it is

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
At first glance this looks lovely

Makes me wonder if the writes could be replaced with yield/yield from at a later point

**Review by bluetech — APPROVED** [review]
Nice!

**Comment by BenjaminSchubert** [comment]
@bluetech I updated the branch which "fixed" the issue.

Do you usually prefer to merge or squash? I could not find this in the contributing guide :)

**Comment by bluetech** [comment]
When the PR has nice commits like in this PR, prefer to merge, it's great to preserve atomic commits. In this case, if there are any fixup commits (not in this PR) or merge commits (one in this PR), do a rebase first to remove them - only the clean commits should end up in `main`.

Otherwise, if you don't want to preserve the commits, do a squash.

**Comment by BenjaminSchubert** [comment]
Seems good, thanks!

**Pull request merged**
