### PR TITLE
Merge master into features

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by nicoddemus** [comment]
/me waiting for GitHub Actions to try to do this automatically 😁

**Comment by blueyed** [comment]
> /me waiting for GitHub Actions to try to do this automatically ￼

How would this work?

In this case probably not anyway, since there were conflicts in tox.ini.

**Comment by nicoddemus** [comment]
> How would this work?

I didn't use GitHub Actions yet, but I think it could, after every merge to `master`, merge to features and open a PR.

> In this case probably not anyway, since there were conflicts in tox.ini.

Oh yeah in that case we need to do it by hand.

**Comment by blueyed** [comment]
> I didn't use GitHub Actions yet, but I think it could, after every merge to master, merge to features and open a PR.

A bit too much probably, no?
I think it is good to just do it after releases etc.

**Comment by nicoddemus** [comment]
> A bit too much probably, no?

Possibly, but I suppose we can try to do that daily for example (if there are changes), but also we can try a few frequencies until we find the right spot.

**Comment by blueyed** [comment]
Hmm, no codecov status/comment.. the site says that their service is partially degraded.

**Pull request merged**
