### PR TITLE
Use pip and tox from py27 in appveyor

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by bubenkoff** [comment]
so it will use only 64 bit version from now on?

**Comment by nicoddemus** [comment]
From my understanding it will still use the python version found in `%PATH`, just `tox` itself will be installed in `py27`, which seems ok to me.

**Comment by bubenkoff** [comment]
ok thanks

**Comment by nicoddemus** [comment]
Thanks for the quick turn around!

**Pull request merged**
