### PR TITLE
Fix staticmethod tests

### LINKED ISSUE #3466: staticmethod tests fail when declared in a superclass
`staticmethod` test fails if you declare it in a superclass:

```
@pytest.fixture
def fixture():
    return True

class TestFoo:
    @staticmethod
    def test_me(fixture):
        assert fixture

class TestBar(TestFoo):
    ...
```

`TestBar.test_me` fails due to the `TypeError: test_me() missing 1 required positional argument: 'fixture'`.

`TestFoo.test_me` passes correctly.

### PR DESCRIPTION
**Pull request by radzak**
Fix #3466

### CODE REVIEW

**Comment by radzak** [comment]
@RonnyPfannschmidt nice catch, you're absolutely right! Let me know which of the below you like more:

```
def is_static_method(klass, func):
    assert getattr(klass, func.__name__) == func

    return isinstance(
        next(
            filter(
                bool, (cls.__dict__.get(func.__name__) for cls in inspect.getmro(klass))
            ),
            None
        ),
        staticmethod
    )
```


```
def is_static_method(klass, func):
    assert getattr(klass, func.__name__) == func

    for cls in inspect.getmro(klass):
        method = cls.__dict__.get(func.__name__)
        if method is not None:
            return isinstance(method, staticmethod)
    return False
```

`assert` makes sure you can't call `is_static_method(B, A.static_lie)`, I wasn't sure what output should be desirable in that scenario. Tell me what you think about it.

**Comment by RonnyPfannschmidt** [comment]
good work, the second example is preferable as it  is more idiomatic python code

IMHO the deeply nested functional constructs are much harder to follow since python is not a first class functional language

**Comment by RonnyPfannschmidt** [comment]
oh, i missed that the fix wasnt dont yet, please discard my merge by rebasing later or force pushing

**Comment by nicoddemus** [comment]
@radzak gentle ping. 👍

**Comment by RonnyPfannschmidt** [comment]
closing due to staleness - i'm happy to reopen on revival

**Pull request closed without merging**
