### PR TITLE
Display number of different items with sequence/dict comparisons

### PR DESCRIPTION
**Pull request by blueyed**
TODO:

- [x] tests

### CODE REVIEW

**Comment by blueyed** [comment]
Wow, really no failing tests..

**Comment by nicoddemus** [comment]
> Wow, really no failing tests..

😞 

Well we should definitely add some then.

**Comment by nicoddemus** [comment]
Otherwise the code looks good! 👍

**Comment by blueyed** [comment]
Added tests, and improved the messages a bit more (for single items).

**Comment by nicoddemus** [comment]
LGTM, only missing CHANGELOG. 👍

**Comment by blueyed** [comment]
Added changelog, fixed branch coverage.

**Comment by nicoddemus** [comment]
Thanks!

**Pull request merged**
