### PR TITLE
Port CHANGELOG from 4.6.6 release

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by blueyed** [comment]
Shouldn't we merge the tag instead?
#5523 shows up 3 times in the changelog now.

**Comment by blueyed** [comment]
I think the changelog for 4.6 should not go into master / 5.x at all, no?

**Comment by blueyed** [comment]
As for #5523 in particular: it shows up with 5.0.1 and 5.1.0, probably because master was not merged into features before doing the release?

**Comment by asottile** [comment]
yes we should include the 4.6 changelog, otherwise it does not appear in the docs

**Comment by blueyed** [comment]
It appears with https://docs.pytest.org/en/4.6-maintenance/changelog.html.

**Comment by asottile** [comment]
yes but nobody is going to land on that

**Comment by blueyed** [comment]
If you are using 4.x you should look at the docs for it, no?

**Comment by asottile** [comment]
should? perhaps -- but I don't expect anyone to be able to find anything except latest from google, etc.

**Comment by blueyed** [comment]
Well, it might actually help Google etc if we would mention 4.6.x not within 5.x docs.

Apart from that, is googling for pytest changes/changelogs a common / valid use case after all?
(IMHO I think that is rather distracting to land on the changelog when you're interested in actual docs, but that's more an issue of (too verbose) changelogs in general - but it does not help to duplicate items there then additionally)

What about a clear note at the top that changes for 4.6.x are somewhere else? (with the above link)

**Comment by blueyed** [comment]
Also people using 5.x (the common use case) have to skip 4.6 entries when looking at the changelog.

**Comment by asottile** [comment]
the 4.6 changelog entries are already below 5.x ones, not sure how anyone would mistake the two

**Comment by blueyed** [comment]
I've not said that they could be mistaken.

**Comment by The-Compiler** [comment]
FWIW pylint does this (only having changelog in branches) and (at least when I followed its development a while back) it was a frequent source of confusion. IMHO, the changelog in the "main" docs should contain all versions.

**Comment by blueyed** [comment]
@The-Compiler 
Any references?  (I've tried to find something via https://github.com/PyCQA/pylint/issues?q=is%3Aissue+changelog+is%3Aclosed only quickly, but could not)

There's no such thing as "main" docs really.
I can see that the docs default to "latest", but then it should be made more clear (apart from the RTD version selector) maybe, that you are looking at docs for 5.x.

It makes sense to merge the current release branch into the development branch before doing a new major release (as we are doing with master => features before a new release from there in general), but here we have two separate release branches really (5.x (master), and 4.6.x (4.6-maintenance)).
Having to copy/add changelogs manually (instead of through a merge) is clearly an indicator that this might be wrong, isn't it?

**Pull request merged**
