### PR TITLE
ci: Travis: pin pip

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by blueyed** [comment]
Not merging it myself already since this was not wanted in https://github.com/pytest-dev/pytest/pull/6522 by 4 others.

**Comment by blueyed** [comment]
Seems to be fixed by just another update probably.

**Comment by nicoddemus** [comment]
I think the recommended practice is to update pip always, instead of pinning... why you think we should pin it? Please write a description when opening the PR.

**Comment by nicoddemus** [comment]
As before, I believe this can be closed.

**Comment by blueyed** [comment]
@nicoddemus 
It does not get upgraded since 58ef95ed4 anymore.

But since it usually fails within tox it is rather related to virtualenv anyway, and/or temporary hickups due to other unpinned dependencies (that last one was about zipp again).

**Pull request closed without merging**
