### PR TITLE
Change the default `tmp_path_retention_policy` to `all`

### PR DESCRIPTION
**Pull request by yusuke-kadowaki**
Partially addresses #10564.
In any case, we should set the default to `all`.

### CODE REVIEW

**Review by RonnyPfannschmidt — APPROVED** [review]
Thanks

**Comment by yusuke-kadowaki** [comment]
Can you rerun the test or just merge this please? I think the failing test is just flaky.

**Comment by RonnyPfannschmidt** [comment]
Restarted, thanks for the ping

**Comment by yusuke-kadowaki** [comment]
Thank you! Please merge if everything looks good for y'all. I'd like to add some more fixes on top of this for the issue.

**Review by nicoddemus — APPROVED** [review]

**Comment by nicoddemus** [comment]
Thanks @yusuke-kadowaki!

**Pull request merged**
