### PR TITLE
Prepare for 2.8.5: bump version, CHANGELOG, announce

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
looks good, any news on regendoc?

**Comment by nicoddemus** [comment]
Nope, still stuck at the same point as before. :disappointed: 

TBH there will be no regen doc changes from `2.8.4`, looking at the CHANGELOG. Perhaps let's just skip it this time? Also the package is on [devpi](https://devpi.net/nicoddemus/dev) but since I generated it on Windows sdist is in `zip` format. I assume that's OK?

**Comment by The-Compiler** [comment]
FWIW `tox -e regen` runs fine here (on Linux) - and indeed there are no relevant changes other than the version numbers.

**Comment by nicoddemus** [comment]
Thanks Florian, could you please push it somewhere so I can cherry pick it?
I would give you access to my fork but I'm not at my computer right now

Em sex, 11 de dez de 2015 21:23, Florian Bruhin <notifications@github.com>
escreveu:

**Comment by The-Compiler** [comment]
Pushed to https://github.com/The-Compiler/pytest/commit/78b0c2a8b4ebf82ee28399dc93d9f157e52eac33 (in the `2.8.5-regen` branch) - completely unreviewed/-edited as I need some sleep now :wink:

**Comment by nicoddemus** [comment]
Thanks @The-Compiler! :smile:

Release is done, thanks everyone!

**Comment by nicoddemus** [comment]
(I will build a new Ubuntu box from scratch to see if my problem with regendocs goes away)

**Pull request merged**
