### PR TITLE
Unpin `sphinx` upper bound

### PR DESCRIPTION
**Pull request by mxr**
CI fails with `ImportError: cannot import name 'environmentfilter' from 'jinja2'` ([example](https://github.com/pytest-dev/pytest/runs/5726444207)).

Bumping Sphinx as described in https://github.com/sphinx-doc/sphinx/issues/10291

### CODE REVIEW

**Comment by mxr** [comment]
The tox docs step fails with 

```
ERROR: InvocationError for command /home/runner/work/pytest/pytest/.tox/docs/bin/sphinx-build -W --keep-going -b html doc/en doc/en/_build/html -t changelog_towncrier_draft (exited with code 1)
```

I think this is from the below warning (since `-W` makes warnings into errors)

```
/home/runner/work/pytest/pytest/src/_pytest/pytester.py:docstring of _pytest.pytester.Pytester.TimeoutExpired:1: WARNING: duplicate object description of _pytest.pytester.Pytester.TimeoutExpired, other instance in reference/reference, use :noindex: for one of them
```

It seems there was some work to fix that in https://github.com/pytest-dev/pytest/issues/8730#issuecomment-860059789 but no change was merged

Beyond that, CI will still be red because of https://github.com/psf/black/issues/2964

**Comment by The-Compiler** [comment]
This seems like a duplicate of #9248.

**Comment by kshahaji166** [comment]
zxzxz

**Comment by bluetech** [comment]
Indeed, we're handling this in #9248.

**Pull request closed without merging**
