### PR TITLE
Release 3.0

### PR DESCRIPTION
**Pull request by nicoddemus**
Final adjustments for the 3.0 release :smile:

### CODE REVIEW

**Comment by nicoddemus** [comment]
devpi tests:

* [AppVeyor](https://ci.appveyor.com/project/nicoddemus/devpi-cloud-tester/build/1.0.17)
* [Travis](https://travis-ci.org/nicoddemus/devpi-cloud-tester/builds/153320203)

:sunglasses:

**Comment by The-Compiler** [comment]
LGTM, not sure if you intend to merge this yourself when actually doing the release or what the plan is :wink:

**Comment by nicoddemus** [comment]
Yep, I plan to merge it right after pushing to PyPI, possibly tomorrow if all goes well. :grin:

**Comment by RonnyPfannschmidt** [comment]
oh, there is an issue with this pull request, it should be against master ^^

**Comment by nicoddemus** [comment]
> oh, there is an issue with this pull request, it should be against master 

You are correct. I changed it though and GH got really unresponsive because then a ton of commits will be merged. I changed back the merge base to `features`, and will merge `master` and `features` locally later. :grin:

**Comment by RonnyPfannschmidt** [comment]
yikes ^^ pain, and gl

**Pull request merged**
