### PR TITLE
Display implicit args in header

### PR DESCRIPTION
**Pull request by blueyed**
Stalled in https://github.com/pytest-dev/pytest/pull/4938.

### CODE REVIEW

**Comment by blueyed** [comment]
Sorry, messed up by automation.

**Comment by RonnyPfannschmidt** [comment]
Out of curiosity, what's the goal of the automation and is it open source

**Comment by blueyed** [comment]
It's just "hub pull-request" (https://github.com/github/hub).
I am using it for https://github.com/blueyed/pytest/pull/2

**Comment by RonnyPfannschmidt** [comment]
I see, thanks

**Pull request closed without merging**
