### PR TITLE
pre-commit-hooks.yaml

### PR DESCRIPTION
**Pull request by MathersMax**
Hi :)

Sorry I'm not compliant with your contributing guidelines but this pr is not about the project itself, it's about being able to use it automatically with `pre-commit`.
I was looking for a way to run my tests before every commit and was surprised to discover that you use `pre-commit` for your own development workflow but do not provide a `pre-commit-hooks.yaml`

So here's one, I'm using it from my fork and it does the job.

I hope you'll accept this little change.

Regards

### CODE REVIEW

**Comment by blueyed** [comment]
Thanks for the PR, but we have `./.pre-commit-config.yaml` already.
Haven't looked at the diff, but you might want to revisit this one then.. :)

**Comment by blueyed** [comment]
Oh, this might be about something else?  https://github.com/pre-commit/pre-commit-hooks

**Comment by asottile** [comment]
👋 first thanks for the contribution!

I think there's a few reasons this won't work for the general case and often is better suited for a [`repo: local`](https://pre-commit.com/#repository-local-hooks) hook or in tox.in / etc. instead

First and foremost is the technical limitation.  since pre-commit creates isolated environments for each hook, they (usually) won't have access to your project and its dependencies (meaning this config would only really work out-of-the-box for a project which had no dependencies, no test dependencies, and was using a non-src layout).  Granted a consumer can ~kinda fix that by twiddling `additional_dependencies` but that's more of a square-peg-round-hole situation.

The second, and perhaps the more important (?) is the ergonomics of such a hook.  While I (and others) have been working a bit on [improving pytest startup / runtime](https://github.com/pytest-dev/pytest/pull/5063), it's still a pretty slow task to execute a full test suite.  Even if startup time were near zero, running a full test suite on every commit in the critical path adds up quickly (and will likely be the slowest part of that commit) -- if I find a hook is slower than others I tend to disable it, and others will outright disable the whole tool!

That said, there still are situations where I've reached for pytest as a hook in pre-commit, though it wasn't necessarily pretty to make it happen:

https://github.com/pre-commit/pygrep-hooks/blob/06d668d27d7b2db128838f83d31c6ab2bd852910/.pre-commit-config.yaml#L46-L52

**Comment by blueyed** [comment]
Ah, now I see what it is about.. :)

Might make sense with something like pytest-testmon (https://github.com/tarpas/pytest-testmon), diff-cover (https://github.com/Bachmann1234/diff-cover) or something similar only really.

But even if it only takes a few seconds I would still prefer to not have it on by default.

**Comment by MathersMax** [comment]
@asottile, @blueyed Thanks for having considered my pr!
Your explanations make perfect sense, I just thought that enabling pytest as a pre-commit repo would only give more freedom to the devs using both libs.
Anyway, I would totally understand if you'd rather keep it that way and I can perfectly accommodate with a local repo.

Best

**Comment by RonnyPfannschmidt** [comment]
i believe there is still some structural merit to those, but i cant quite put it into the right words yet

when pytest no longer uses pkg_resources, it may be sensible to run a core set of unit-tests on commit for example to prevent blunters - there is various small projects where this is entirely sensible

**Comment by nicoddemus** [comment]
Thanks @MathersMax for the contribution and understanding, and everyone else for the excellent discussion. 👍

**Pull request closed without merging**
