### PR TITLE
Add acceptance tests

### PR DESCRIPTION
**Pull request by Lothiraldan**
Following of https://github.com/pytest-dev/pytest/pull/2207 and https://github.com/pytest-dev/pytest/issues/2643, add some "examples" or "acceptance" test files in the acceptance directory.

They are not yet tested automatically.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
@Lothiraldan sorry for taking so long on this one, i am under the impression that it needs a bit of discussion but i'm currently swamped with other things

**Comment by Lothiraldan** [comment]
No problem, I needed them for my own plugin. Could we keep the pull-request open so we don't forget about it and plugins authors might find the pull-request and use them?

**Comment by RonnyPfannschmidt** [comment]
i#ll keep it open until i get to it

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt anything else needed here?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus this one follows up with an odea of another pr, but i need to detail handling it

**Comment by nicoddemus** [comment]
#3623 will probably take this one over or supersede this, correct?

**Comment by nicoddemus** [comment]
#3636 has also been merged.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i still need to make time to actually do this ^^

**Comment by nicoddemus** [comment]
Oh sure, just a gentle ping! 👍

**Comment by RonnyPfannschmidt** [comment]
now that we have the example dir and moved many more elaborate tests there, i wonder if the tests that helped to inspired the structural idea actually still make sense to move in

**Comment by nicoddemus** [comment]
I feel the same way, I'll leave up to you to decide. I'm OK with closing this now.

**Comment by RonnyPfannschmidt** [comment]
@Lothiraldan i want to thank you again from bringing this up and creating it, it had been a valuable source for sorting out the final  implementation

however a side-effect of the final implementation was, that it already includes quite a number of elements and thus this initial idea/demo has been superseded by that

**Pull request closed without merging**
