### PR TITLE
Utilize more_itertools to consolidate logic when collecting marks.

### PR DESCRIPTION
**Pull request by jaraco**

### CODE REVIEW

**Comment by jaraco** [comment]
While working on #10447, I noticed two areas for improvement in `structures.get_unpacked_marks`:

- The logic to convert "one or many" to a list was repeated in both `if isinstance(obj, type)` and `not`.
- Instead of utilizing a "flatten" operation (e.g. `itertools.chain.from_iterable` or `more_itertools.flatten`), the code imperatively constructs a list and selectively appends or extends the list, entangling the flattening operation with the "one or many" conversion.

This approach instead constructs `mark_lists` in a symmetrical way in each branch and then performs the flattening and "one or many" to list conversion on the result.

I believe this approach is safer because it avoids [unnecessary code duplication](https://blog.jaraco.com/code-duplication-how-much-is-too-much/), reduces mccabe complexity, and makes the code more symmetrical (and thus easier to interpret).

Please consider adopting it.

I did not create a changelog entry because this change is a pure internal refactor with no effect on tests or behavior. I can add a changelog entry linking to this PR if desired. I welcome other feedback as well.

**Comment by jaraco** [comment]
Note that there are potentially many more places where `always_iterable` could simplify the code:

```
diff --git a/src/_pytest/python.py b/src/_pytest/python.py
index 5f4ba3da6..e6318c411 100644
--- a/src/_pytest/python.py
+++ b/src/_pytest/python.py
@@ -29,6 +29,8 @@ from typing import Tuple
 from typing import TYPE_CHECKING
 from typing import Union
 
+from more_itertools import always_iterable
+
 import _pytest
 from _pytest import fixtures
 from _pytest import nodes
@@ -455,12 +457,7 @@ class PyCollector(PyobjMixin, nodes.Collector):
                 res = ihook.pytest_pycollect_makeitem(
                     collector=self, name=name, obj=obj
                 )
-                if res is None:
-                    continue
-                elif isinstance(res, list):
-                    values.extend(res)
-                else:
-                    values.append(res)
+                values.extend(always_iterable(res))
             dict_values.append(values)
 
         # Between classes in the class hierarchy, reverse-MRO order -- nodes
```

If you'd like me to explore a broader refactor, I can do that on request.

**Comment by RonnyPfannschmidt** [comment]
we had it in a while back and it got removed in #7587

**Comment by RonnyPfannschmidt** [comment]
personally i'm inclined a bit against it as some of those convenient helpers hide conceptual complexity that sometimes ought to be removed instead of being eased/hidden

for example the support for pytestmark being a single marker or a list is a sloppy convenience and that cost should be visible if not removed

**Comment by jaraco** [comment]
Fair enough.

**Pull request closed without merging**
