### PR TITLE
RFC Multiline logging

### PR DESCRIPTION
**Pull request by thisch**
This adds support for aligned multi-line log messages:

image

What this change is doing is inserting white-space to all lines except the first of the "message" part of the log msg.

### CODE REVIEW

**Comment by blueyed** [comment]
Interesting.
I wonder though why not `filename:lineno` is used (to make it more condense), but that appears to not have changed here, or has it?

**Comment by thisch** [comment]
I think we should rather make the current integration of the log formatter a bit more extensible. What I have in mind is that the default formatter should be easily replaceable by a custom log formatter. Ideally we could create a collection of predefined log formatters in a new pytest package that can then be selected by name.

**Comment by s0undt3ch** [comment]
Even better then :)

**Comment by nicoddemus** [comment]
Hi @thisch, 

It has been a long time since it has last seen activity, plus we have made sweeping changes on `master` to drop Python 2.7 and 3.4 support, so this PR has some conflicts which require attention.

In order to clear up our queue and let us focus on the active PRs, I'm closing this PR for now.

Please don't consider this a rejection of your PR, we just want to get this out of sight until you have the time to tackle this again. If you get around to work on this in the future, please *don't hesitate* in re-opening this!

Thanks for your work, the team definitely appreciates it!

**Pull request closed without merging**
