### PR TITLE
fix #3631 - don't store legacy markinfo when its impossible

### LINKED ISSUE #3631: "AttributeError: object has no attribute 'add_mark'" when marks clash with existing attributes
When running the following code with `python -m pytest foo.py`:

```python
import pytest


def assign_foo(f):
    f.foo = "Hi"
    return f


@pytest.mark.foo
@assign_foo
def test():
    pass
```

I get the following error:

```
foo.py:10: in <module>
    @assign_foo
v/lib/python3.6/site-packages/_pytest/mark/structures.py:213: in __call__
    store_legacy_markinfo(func, self.mark)
v/lib/python3.6/site-packages/_pytest/mark/structures.py:250: in store_legacy_markinfo
    holder.add_mark(mark)
E   AttributeError: 'str' object has no attribute 'add_mark'
```

This is on 3.6.0 with the following packages in the virtualenv (i.e. a clean install of pytest 3.6.2):

```
Package        Version
-------------- -------
atomicwrites   1.1.5
attrs          18.1.0
more-itertools 4.2.0
pip            10.0.1
pluggy         0.6.0
py             1.5.4
pytest         3.6.2
setuptools     39.2.0
six            1.11.0
wheel          0.31.1
```

We encountered this because someone was applying `@pytest.mark.hypothesis` to a `@given` decorated test (see https://github.com/HypothesisWorks/hypothesis/issues/1362), which broke when we added a `hypothesis` attribute on the decorated function. 

I believe this is only a problem with the legacy support and is not required for marks to work: we already apply a hypothesis mark to all `@given` decorated tests, and it is still working fine, so it seems likely that a fix that checked if the attribute was already present and did nothing if it was not a `MarkInfo` would be backwards compatible and fix this problem.

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus perhaps a candidate to rebase onto master?

**Comment by nicoddemus** [comment]
> perhaps a candidate to rebase onto master?

You mean cherry-pick this commit into master? Why not targeting `master` directly?

**Comment by RonnyPfannschmidt** [comment]
i simply first based it on features and by rebase i mean rebase form features onto master

**Comment by nicoddemus** [comment]
> i simply first based it on features and by rebase i mean rebase form features onto master

You want to rebase features onto master, but merge this branch in features still? Or you intend to merge this into master?

I think this is a bug fix and can go directly to `master` (this is what you might have been meaning since the beginning, I apologize for not getting it right away).

**Comment by RonnyPfannschmidt** [comment]
rebase onto master = take away from features and put onto master

 will do

**Comment by RonnyPfannschmidt** [comment]
`git rebase features --onto master` is surprisingly painless by now ^^

**Pull request merged**
