### PR TITLE
Add --report-passing option.

### PR DESCRIPTION
**Pull request by codewarrior0**
This is an alternative to `-s` for viewing the output of passing tests. This causes the captured stdout/stderr of passing tests to be output in the same way as that of failing tests.

Additional changes to `pytest_capturelog` are needed for this option to also output captured logs.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
I think this should use reportchars

**Comment by codewarrior0** [comment]
I thought about that but decided against it since the existing reportchars only add one line of output per test, while this new option could add several pages of output. If you want, I'll change it to `-rP` instead of `--report-passing`

**Comment by nicoddemus** [comment]
I see your reasoning @codewarrior0, but I also think this option fits with the idea of the reportchars command line option, which is to provide a summary at the end of the test runs. In this case is a summary of all the outputs captured of passing tests. That's my understanding, at least. :smile:

Could you also post an sample output showing case the new feature?

**Comment by codewarrior0** [comment]
Sure. I've also modified my pytest-capturelog plugin so the log output is shown, too:

```
============================= test session starts =============================
platform win32 -- Python 2.7.9, pytest-2.8.0, py-1.4.30, pluggy-0.3.1 -- c:\Users\Rio\Documents\src\pyinst1328\.env27\Scripts\python.exe
cachedir: .cache
rootdir: c:\Users\Rio\Documents\src\pyinst1328, inifile: setup.cfg
plugins: capturelog-0.7, timeout-0.5, xdist-1.13.1
collecting ... collected 222 items

tests/functional/test_basic.py::test_helloworld[onedir] PASSED

=================================== PASSES ====================================
___________________________ test_helloworld[onedir] ___________________________
---------------------------- Captured stdout call -----------------------------
RUNNING:  'c:\\users\\rio\\appdata\\local\\temp\\pytest-of-Rio\\pytest-5\\test_helloworld_onedir_0\\dist\\pyi_helloworld\\pyi_helloworld.exe' , args:  ['.\\pyi_helloworld.exe']
Hello Python!

---------------------------- Captured stderr call -----------------------------
c:\users\rio\documents\src\pyinst1328\PyInstaller\hooks\hook-encodings.py:11: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  from PyInstaller.utils.hooks import collect_submodules
PyInstaller Bootloader 3.x

LOADER: executable is c:\users\rio\appdata\local\temp\pytest-of-Rio\pytest-5\test_helloworld_onedir_0\dist\pyi_helloworld\pyi_helloworld.exe

-- [30 lines of LOADER output] --

LOADER: Done

LOADER: Cleaning up Python interpreter.

-------------------------------- Captured log ---------------------------------
analysis.py                430 INFO     Initializing module dependency graph...
analysis.py                 94 INFO     Looking for graph hooks ...
configure.py                28 DEBUG    Testing for UPX ...
configure.py                53 INFO     UPX is not available.
__main__.py                 89 INFO     PyInstaller: 3.0.dev3+81164ea-mod
__main__.py                 90 INFO     Python: 2.7.9
__main__.py                 91 INFO     Platform: Windows-7-6.1.7601-SP1

-- [200 lines of logging output] --

winmanifest.py            1006 INFO     Updating manifest in c:\users\rio\appdata\local\temp\pytest-of-Rio\pytest-5\test_helloworld_onedir_0\bincache00_py27_64bit\python27.dll
winresource.py             204 INFO     Updating resource type 24 name 2 language 1033
============= 221 tests deselected by '-ktest_helloworld[onedir]' =============
========= 1 passed, 221 deselected, 2 pytest-warnings in 9.33 seconds =========
```

**Comment by hpk42** [comment]
meta-comment: please retarget to "features" branch -- "master" is since today meant for bugfixes only. sorry for the inconvenience.

**Comment by RonnyPfannschmidt** [comment]
so what do we do with this one, close since it died down before being merge-able?

**Comment by nicoddemus** [comment]
Hmm why do you say it is no longer merge-able?

**Comment by RonnyPfannschmidt** [comment]
the requested changes went unaddressed

**Comment by nicoddemus** [comment]
Oh I see.

Well, don't know... @codewarrior0, do you still have interest on this?

**Comment by codewarrior0** [comment]
Oh, my bad. It looks like I did change it to `-rP` in my local branch but never got around to updating the PR. Just a sec...

**Comment by codewarrior0** [comment]
All right, I'll send another PR against `features` instead.

**Pull request closed without merging**
