### PR TITLE
Add the PyPI classifier for Python 3.11

### PR DESCRIPTION
**Pull request by bryant1410**

### CODE REVIEW

**Comment by bryant1410** [comment]
Should I update this as well?

https://github.com/pytest-dev/pytest/blob/a17d3b0c44f9434e34f2fecf02f97f3e866cae05/.pre-commit-config.yaml#L2

**Comment by RonnyPfannschmidt** [comment]
That one is better left for now

**Comment by nicoddemus** [comment]
Thanks @bryant1410!

**Review by nicoddemus — APPROVED** [review]

**Comment by The-Compiler** [comment]
Should we backport this to 7.2.x?

**Comment by nicoddemus** [comment]
Yes, thanks for the reminder.

**Pull request merged**
