### PR TITLE
Switch to new API

### LINKED ISSUE #3653: Avoid deprecated attrs feature `convert`
https://github.com/pytest-dev/pytest/commit/37793d4cdbf71f597a3c69c827e0c010528d53a5 introduced a use of the `convert` keyword argument to `attr.ib`.  This is deprecated in attrs:

> DeprecationWarning: The `convert` argument is deprecated in favor of `converter`.  It will be removed after 2019/01.                                 

The replacement should be used instead.

### PR DESCRIPTION
**Pull request by exarkun**
Fixes #3653

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks @exarkun!

**Comment by nicoddemus** [comment]
Btw, we don't catch that warning because unfortunately we don't yet capture deprecation warnings at import time.

**Comment by exarkun** [comment]
Thanks for the quick turn-around on this.  My CI was failing but the fixed release came out so quickly I didn't even have time to implement a work-around on my side.  Much appreciated. :)

**Comment by nicoddemus** [comment]
No worries, thanks again for the PR! 👍

**Pull request merged**
