### PR TITLE
[6.1.x] Merge pull request #8540 from hauntsaninja/assert310

### PR DESCRIPTION
**Pull request by erikkemperman**
(cherry picked from commit af31c60db1dc4e513f47aabf8f6e844b23afd35f)

### CODE REVIEW

**Comment by asottile** [comment]
sorry, we don't backport to releases prior to the latest minor version -- this has been released in 6.2.4

**Comment by erikkemperman** [comment]
Fair enough. I thought I’d give it a shot — I’m running into this bug with mypy’s unit tests, and I expect they will want to continue supporting python 3.5 and thus depend on pytest<6.2.0...

**Comment by asottile** [comment]
presumably you only need pytest<6.2.0 for python3.5 and can use modern pytest elsewhere?

**Comment by erikkemperman** [comment]
Thanks for taking a look!

**Pull request closed without merging**
