### PR TITLE
Report the right package name for nested packages

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks @s0undt3ch! 

Not sure this is wanted though... the name of all other nodes are only the leaf names, not the full name.

**Comment by s0undt3ch** [comment]
Hmm, sure, but it just reads wrong.
Do you suggest another attribute?

**Comment by nicoddemus** [comment]
To elaborate a bit more, I believe we should be consistent:

```
<Package tests>
  <Module __init__.py>
    <Function test_init>
  <Module test_foo.py>
    <Function test_foo>
<Package tests.pkg>
  <Module test_foo.py>
    <Function test_foo>
```

Note that `Module` does not contain the full name, so `Package` should follow suit.

I believe we can introduce a new `@property` in `Node` that gives the `full_name` or `qual_name` in Python terms, which would iterate over all parent nodes constructing the proper full qualified name:

```python
assert tests_pkg.name == "pkg"
assert tests_pkg.qual_name == "tests.pkg"
```

And would even work for any node:

```python
assert test_foo_func.name == "test_foo"
assert test_foo_func.qual_name == "tests.pkg.test_foo.test_foo"
```

What do you think?

**Comment by nicoddemus** [comment]
@s0undt3ch gentle ping. 😁

**Comment by s0undt3ch** [comment]
Sorry, totally missed your comment.
Yes, I believe `qual_name` is indeed a better solution.
Is the above "pseudo-code" or you actually worked on it and this PR should just be closed?

**Comment by nicoddemus** [comment]
> Is the above "pseudo-code" or you actually worked on it and this PR should just be closed?

Pseudo-code 😁 

Feel free to close this PR and re-open another one with my suggestion, or create an issue if you feel you won't have to tackle it. 👍

**Comment by s0undt3ch** [comment]
I don't mind tackling it, and since it's not a high priority, ie, no one else needs it right away, I can try and squeeze it on my free time slots.
Obrigado pela sugestão da direção a tomar ;)

**Comment by nicoddemus** [comment]
Sure thing, let's close this for now then, I've created https://github.com/pytest-dev/pytest/issues/7365 to track the new feature suggested here. 

> Obrigado pela sugestão da direção a tomar ;)

Claro, sem problemas, valeu! 😁

**Comment by symonk** [comment]
@nicoddemus  gonna grab this if its ok

**Pull request closed without merging**
