### PR TITLE
Support @pytest.mark.usefixture in fixtures

### PR DESCRIPTION
**Pull request by youtux**
- [x] Target the `master` branch for bug fixes, documentation updates and trivial changes.
- [x] Target the `features` branch for new features, improvements, and removals/deprecations.
- [ ] Include documentation when adding new features.
- [ ] Include new tests or update existing tests when applicable.
- [ ] Create a new changelog file in the `changelog` folder, with a name like `<ISSUE NUMBER>.<TYPE>.rst`. See [changelog/README.rst](https://github.com/pytest-dev/pytest/blob/master/changelog/README.rst) for details.
- [ ] Add yourself to `AUTHORS` in alphabetical order;

Followup from https://github.com/pytest-dev/pytest/issues/3664#issuecomment-524557400.
I am trying to get the @pytest.mark.usefixture marker to work with fixtures as well.

### CODE REVIEW

**Comment by bluetech** [comment]
Hi @youtux,

We've recently stopped using the `features` branch, and use the `master` branch instead ([rationale](https://github.com/pytest-dev/pytest/pull/6571)). We're asking open PRs against `features` to be rabased on `master`. You can do it as follows:

- `git checkout master && git pull origin` - sync the latest code.
- `git checkout usefixtures-in-fixtures` - checkout the branch of this PR.
- `git rebase -i master` - leave only your own commits, and delete everything else.
- `git push --force` - update the PR.
- Click `Edit` in the PR GitHub UI and change the base branch from `features` to `master`.

Let us know if you have any issues.

Thanks!

**Comment by nicoddemus** [comment]
(Revisiting this)

The PR looks well written for a first draft, thanks! (Sorry for not commenting on it previously, missed the notification most likely).

---
I wonder though if people use `@pytest.mark.usefixtures`, they will probably also expect `@pytest.mark.skipif` to work too?

Also it probably is a good idea to eventually support `@pytest.mark.skipif` (and the others) in fixtures? I think it makes sense and there's no confusion involved.

@RonnyPfannschmidt what do you think?

--- 

btw the discussion above is out of scope for this PR, just me thinking aloud to get feedback.

**Comment by nicoddemus** [comment]
Hmmm just realized that this technically might be a challenge, because marks usually are applied during collection, and fixtures are lazily evaluated during test call...

**Comment by RonnyPfannschmidt** [comment]
its technically incredibly hard to correctly transfer markers from fixtures to nodes,
making one mark magically special is not going to be good in any way,

until we have a sound solution for markers on fixtures, its not acceptable to have some of them a little bit magically

a sound solution is hard  to impossible right now as the fixture system has various features that make this more tricky (like replacing vs enhancing fixtures, dynamic fixture requests and a few more details) as  well as the fact that the current internals of fixtures are rather frickly and fragile as the result of their development history

revisiting the original issue i have to note that while we improved some parts of marks, the parts that make it fundamentally  a bad choice to support them on fixtures is still the same

**Comment by bluetech** [comment]
> We've recently stopped using the features branch

(I've changed the base on my own now).

**Comment by nicoddemus** [comment]
> revisiting the original issue i have to note that while we improved some parts of marks, the parts that make it fundamentally a bad choice to support them on fixtures is still the same

Agree completely. 👍

**Comment by youtux** [comment]
I soon realized after digging a little bit into pytest internals that indeed this would require a major architectural change, not just a small patch.
Closing this PR as I am not continuing this development.

**Comment by nicoddemus** [comment]
Thanks @youtux for trying! We appreciate it.

**Comment by jamt9000** [comment]
> I think once people notice that they can use @pytest.mark.usefixtures, they will probably also expect @pytest.mark.skipif to work too.

Does the mechanism to use fixtures need to be a mark? How about defining `@pytest.usefixtures` that works for both fixtures and tests.

**Pull request closed without merging**
