### PR TITLE
Add missing ref docs to tmp_path and tmp_path_factory

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Docs passed already, so merging. 👍

**Comment by blueyed** [comment]
@nicoddemus 
btw: at least with Travis we could skip jobs/stages based on commit message content, e.g. `skip tests`.

**Comment by blueyed** [comment]
(OTOH that is bad then when merging, where the base coverage might be missing then)

**Comment by nicoddemus** [comment]
> we could skip jobs/stages based on commit message content, e.g. `skip tests`

I guess you mean we could implement this logic in our `.travis.yml` file.

I'm not sure it will save us much because the builds now are quite faster, plus I guess most people contributing docs won't know about the `skip tests` trick... I don't know. 🤷‍♂️

**Pull request merged**
