### PR TITLE
Making conftest import failures easier to debug

### LINKED ISSUE #1516: pytest rethrows Exception poorly. losing traceback information.
In [config.py](https://github.com/pytest-dev/pytest/blob/6a3c943ce26de52737eac083fb692610bf1fce35/_pytest/config.py#L322) pytest catches all Exceptions and rethrows them (poorly) as conftestImportFailure, losing the original traceback. this makes bug hunting rather tricky since the traceback pytest gives doesn't point at all to the cause of the error.

either throwing the original exception or rethrowing properly would be a good solution.

### PR DESCRIPTION
**Pull request by txomon**
We had problems at the office debugging a conftest error, so I am submitting this patch to close #1516

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
this is a nice start but would also need a accompanying test, and perhaps using the more detailed printing thats already supported by the excinfo class

**Comment by txomon** [comment]
@RonnyPfannschmidt I have made tests, and about the excinfo class, I have no idea on how to use it nor if it makes sense in this case. I would leave it as it is because it makes clear what the exception is.

**Comment by txomon** [comment]
I think I am doing something wrong in the testing because the coverage is not increasing, but I don't know what.

**Comment by nicoddemus** [comment]
Hey @txomon, I tried your PR using these files:

```python
# conftest.py
def foo():
    raise ValueError('oh noes')

def bar():
    foo()

bar()

# test_f.py
def test():
    pass
```

And this is what I get:

```
Traceback (most recent call last):
  File "x:\pytest\_pytest\config.py", line 327, in _importconftest
    mod = conftestpath.pyimport()
  File "X:\pytest\.env27\lib\site-packages\py-1.4.31-py2.7.egg\py\_path\local.py", line 650, in pyimport
    __import__(modname)
  File "x:\pytest\_pytest\assertion\rewrite.py", line 182, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "X:\pytest\.env27\lib\site-packages\py-1.4.31-py2.7.egg\py\_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "X:\pytest\tmp\conftest.py", line 7, in <module>
    bar()
  File "X:\pytest\tmp\conftest.py", line 5, in bar
    foo()
  File "X:\pytest\tmp\conftest.py", line 2, in foo
    raise ValueError('oh noes')
ValueError: oh noes
ERROR: could not load X:\pytest\tmp\conftest.py
```

That looks OK, but trying it using latest `master` (cc0920ceb10) it shows me this:

```
Traceback (most recent call last):
  File "x:\pytest\_pytest\config.py", line 320, in _importconftest
    mod = conftestpath.pyimport()
  File "X:\pytest\.env27\lib\site-packages\py-1.4.31-py2.7.egg\py\_path\local.py", line 650, in pyimport
    __import__(modname)
  File "X:\pytest\tmp\conftest.py", line 7, in <module>
    bar()
  File "X:\pytest\tmp\conftest.py", line 5, in bar
    foo()
  File "X:\pytest\tmp\conftest.py", line 2, in foo
    raise ValueError('oh noes')
ValueError: oh noes
ERROR: could not load X:\pytest\tmp\conftest.py
```

Could you please test against the latest `master` and see if the output looks OK to you? We might not need your PR after all. Thanks!

**Comment by nicoddemus** [comment]
Btw, I'm using Python 2.7 on that example because I understand your original issue happened in Python 2.7 as well.

**Comment by txomon** [comment]
@nicoddemus have you tried raising the value error from somewhere else not in conftest?

I still get the output, just in case, this is my environment:
```
-e git+github:pytest-dev/pytest@cc0920ceb105b832cef1aec6d4422226ffbaf473#egg=pytest
pytest-capturelog==0.7
pytest-cov==2.2.1
pytest-mock==1.1
pytest-xdist==1.14
```

**Comment by nicoddemus** [comment]
Hi @txomon, sorry for not coming back to this earlier. Could you provide a minimal case with the problem? As I commented earlier, I tried a few combinations but couldn't reproduce the problem.

**Comment by nicoddemus** [comment]
Nevermind, I was able to reproduce the problem and indeed it improves the message. :sweat_smile: 

I will rebase and merge this later. 

Thanks!

**Comment by txomon** [comment]
Oh nice!!! I was wondering how to do it =)

**Comment by txomon** [comment]
@nicoddemus how did this go?

**Comment by nicoddemus** [comment]
Didn't have time to merge yet, I will get to it this week.

**Pull request merged**
