### PR TITLE
Release 4.0.0

### PR DESCRIPTION
**Pull request by nicoddemus**
🎉

### CODE REVIEW

**Comment by blueyed** [comment]
Why the rush?
I feel like we could wait a week more, to e.g. get the features/things I have cooking for pdb in here.
This includes https://github.com/pytest-dev/pytest/pull/4280 (#4292 / #4299).

I think 4.0 is a better opportunity to break/change things than 4.1 after it.

**Comment by blueyed** [comment]
Also https://github.com/pytest-dev/pytest/pull/4381 (merged to master later) would be nice to have.

**Comment by RonnyPfannschmidt** [comment]
@blueyed there will be a few more majors to come after this one that wont have long delays

**Comment by nicoddemus** [comment]
> Why the rush?
I feel like we could wait a week more, to e.g. get the features/things I have cooking for pdb in here.

Good points. Let me explain the reasons why we would like to release 4.0 right away:

In the past all our major releases (well, the two major releases) introduced sweeping and large changes, which makes users nervous to upgrade and makes it hard to pinpoint regressions when there are too many changes in place at the same time. 4.0 is a backward compatibility breakage already because all warnings are now errors, so we should reduce the "moving parts" in the release, that's why I would like to have a 4.0 release with as few things as possible, preferably only warnings changing into errors would be ideal IMO.

Also, with 4.0 released, we are free to cleanup and remove the old deprecated functionality in `features`, as they will be removed in 4.1. This will open the path for us to start some internal refactorings (@RonnyPfannschmidt's initialization revamp) and new features (#4091).

Finally, as @RonnyPfannschmidt mentions, nothing prevents us to have a 4.1 release soon (like next week) if we want to: frequent minor releases means features reaching users faster. Of course minor releases also often mean unintended regressions, but as we improve our processes and codebase, my feeling is that those will tend to diminish and disappear (hopefully).

Let me know if you still would like to see a 4.0 next week with the pdb features you are cooking up (which are awesome btw), but I would rather we stick to having a small 4.0 release.

> I think 4.0 is a better opportunity to break/change things than 4.1 after it.

Actually, we ideally should only break things if we can deprecate first for two minor releases. Small changes which are not API breakages are fine between minor releases. 😁

**Pull request merged**
