### PR TITLE
[WIP] py36 plus

### PR DESCRIPTION
**Pull request by asottile**
still TODO:
- audit `TYPE_CHECKING`

### CODE REVIEW

**Comment by The-Compiler** [comment]
I know this is WIP, but FWIW I think you can also remove `.travis.yml` entirely.

**Comment by Zac-HD** [comment]
> * `# type: ` comments

https://pypi.org/project/com2ann/ might help.

**Comment by asottile** [comment]
> 
> 
> > * `# type: ` comments
> 
> https://pypi.org/project/com2ann/ might help.

yeah the problem is a good percentage of them have some things that need manual attention (I started with com2ann and then said "maybe later"):
- a lot of them are forward annotations
- some can be refactored as follows:
```
x: VeryLongTypeNameHere = (
    expression_here
)
```
=>
```
x: VeryLongTypeNameHere
x = expression_here
```

**Review by nicoddemus — APPROVED** [review]

**Comment by asottile** [comment]
I'm going to be splitting this out into a bunch of PRs so this is easier to merge -- right now it's going to be a real pain to keep rebasing / managing conflicts as I finish things up 👍

**Review by ssbarnea — CHANGES_REQUESTED** [review]
This change seems to combine lots of unrelated changes, but overall it seems that most of it is around adding fstrings and type checking.

I would totally support smaller steps of atomic changes, like remove py35 jobs and update python_requires, followed by  update pre-commit linters.

**Comment by asottile** [comment]
@ssbarnea did you not read my last comment?

**Comment by ssbarnea** [comment]
> @ssbarnea did you not read my last comment?

Yep, but after I added the comment.

**Pull request closed without merging**
