### PR TITLE
ExceptionInfo.from_current: pass through exprinfo

### PR DESCRIPTION
**Pull request by blueyed**
This was lost in 11f1f79222.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
Good find, got a idea for a test?

**Comment by blueyed** [comment]
@RonnyPfannschmidt 
Not from the top of my head - do you have one?

**Comment by blueyed** [comment]
I do not fully grasp the API there btw, I think something more explicit like https://github.com/pytest-dev/pytest/pull/6003 makes sense here.

**Comment by RonnyPfannschmidt** [comment]
@blueyed should we add a follow-up task to make a test for this one, i have no idea myself off hand

**Comment by blueyed** [comment]
@RonnyPfannschmidt not really necessary AFAICS.
But feedback on #6003 / the idea from there might be good.

**Pull request merged**
