### PR TITLE
remove pytest internal usage of the namespace hook

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
reopening of the prior pr #2280 

- [ ] investigate the source of the errors as they dont happen when there is at least one namspace hook

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
the xdist failure is most interesting

**Comment by RonnyPfannschmidt** [comment]
#2331 could be considered a blocker, a decission is needed

**Comment by RonnyPfannschmidt** [comment]
the xfail is probably a bad idea, for now i do not want to merge it, its no longer sane to try this for 3.1

**Comment by nicoddemus** [comment]
Hmm sorry, just now I saw your comment @RonnyPfannschmidt... should I revert this merge?

**Comment by RonnyPfannschmidt** [comment]
Its fine, i dir put in a workaround that works by kerping a single hook in pytest

**Pull request merged**
