### PR TITLE
[WIP] raise exception when fixture is applied to marked function

### LINKED ISSUE #3664: Generate an error when a mark is applied to a fixture
Follow up from #1014.

We should generate an error if a `@pytest.mark` is applied to a fixture.

There is a warning in `doc/en/fixture.rst` about this problem which should be updated once this issue is dealt with.

### PR DESCRIPTION
**Pull request by avirlrma**
sorry I the original PR got closed as I removed the commit from the master.

Ed: closes #3664, once finished.

### CODE REVIEW

**Comment by nicoddemus** [comment]
No problem!

**Comment by nicoddemus** [comment]
(I've added "WIP" to the title to make it explicit that this is not ready for review/merge)

**Comment by avirlrma** [comment]
oh makes sense! thanks.
I will keep it in mind from the next time.

**Comment by nicoddemus** [comment]
Hi @avirlrma, 

It has been a long time since it has last seen activity, plus we have made sweeping changes on `master` to drop Python 2.7 and 3.4 support, so this PR has some conflicts which require attention.

In order to clear up our queue and let us focus on the active PRs, I'm closing this PR for now.

Please don't consider this a rejection of your PR, we just want to get this out of sight until you have the time to tackle this again. If you get around to work on this in the future, please *don't hesitate* in re-opening this!

Thanks for your work, the team definitely appreciates it!

**Pull request closed without merging**
