### PR TITLE
4.6: Run pyupgrade without --py3-plus

### PR DESCRIPTION
**Pull request by hugovk**
- [ ] Target the `master` branch for bug fixes, documentation updates and trivial changes.
- [ ] Target the `features` branch for new features and removals/deprecations.
- [ ] Include documentation when adding new features.
- [ ] Include new tests or update existing tests when applicable.

Unless your change is trivial or a small documentation fix (e.g.,  a typo or reword of a small section) please:

- [ ] Create a new changelog file in the `changelog` folder, with a name like `<ISSUE NUMBER>.<TYPE>.rst`. See [changelog/README.rst](https://github.com/pytest-dev/pytest/blob/master/changelog/README.rst) for details.
- [ ] Add yourself to `AUTHORS` in alphabetical order;

To help with backports, and related to #5275, this runs `pyupgrade` _without_ `--py3-plus` on the `4.6-maintenance` branch, to minimise the difference between it and the master branch, where `pyupgrade` has been run (with `--py3-plus`).

(And run Black.)

### CODE REVIEW

**Comment by hugovk** [comment]
Ah, tests are failing, if this isn't a quick win it's probably not worth the effort.

By the way, I did test this on my fork before creating the PR, but tests all fail on forks (also for clean `master` and `4.6-maintenance`) maybe due to the `repo = pytest-dev/pytest` restrictions.

Sorry for the noise, feel free to close!

**Comment by nicoddemus** [comment]
I will let @asottile comment/handle this one. 😁

**Comment by asottile** [comment]
Yeah we can't quite do this as pytest 2.7 code isn't quite unicode clean (which is why it was running with --skip-percent-format)

**Comment by asottile** [comment]
Note that we're already running pyupgrade as well, just with the format fixer disabled

**Pull request closed without merging**
