### PR TITLE
code: drop Experimental API label from ExceptionInfo.from_exc_info

### PR DESCRIPTION
**Pull request by bluetech**
This API is OK, I don't think we're going to change something about it at this point.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
The only caveat this poses is that it may be harder to drop exception info as is (it's one of the inheritances from pylib that's unfortunately very intertwined

**Review by RonnyPfannschmidt — APPROVED** [review]
Since modern exceptions carry the traceback /context, maybe we can directly deprecate this

**Comment by RonnyPfannschmidt** [comment]
thanks for the clarification on python version ranges

indeed, raises is raising some serious future work ^^

**Comment by nicoddemus** [comment]
> The only caveat this poses is that it may be harder to drop exception info as is (it's one of the inheritances from pylib that's unfortunately very intertwined

Curious, drop it in favor of what? As of now, it is inside pytest and it seems to do its role OK-ish -- perhaps it exposes other internals like `ReprExceptionInfo`, is that what you mean?

**Pull request merged**
