### PR TITLE
[6.1.x] Merge pull request #7979 from nicoddemus/metafunc-ref

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Weird, I don't see how my patch could break with `os.PathLike` not existing in Python 3.5. 🤔

**Comment by bluetech** [comment]
Happens on my backport PR as well, so not related to this specifically. Since our code on 6.1.x doesn't have any mention of `PathLike`, it must be coming from some dependency. Unless someone wants to debug this I suggest we ignore it :)

**Comment by bluetech** [comment]
@nicoddemus WDYT re. ignoring the `PathLike` error on older Python 3.5 for 6.1.x? Since we don't use `PathLike` in that branch I don't think it's caused by us.

**Comment by nicoddemus** [comment]
> @nicoddemus WDYT re. ignoring the PathLike error on older Python 3.5 for 6.1.x? Since we don't use PathLike in that branch I don't think it's caused by us.

Agreed. Should we hit the merge button then?

**Pull request merged**
