### PR TITLE
Merge master into features

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Hmm linting fail for some reason

**Comment by blueyed** [comment]
No, docs:

```
docs create: /home/travis/build/pytest-dev/pytest/.tox/docs
docs installdeps: -r/home/travis/build/pytest-dev/pytest/doc/en/requirements.txt
docs develop-inst: /home/travis/build/pytest-dev/pytest
ERROR: invocation failed (exit code 1), logfile: /home/travis/build/pytest-dev/pytest/.tox/docs/log/docs-2.log
================================== log start ===================================
Obtaining file:///home/travis/build/pytest-dev/pytest
ERROR: Error installing 'file:///home/travis/build/pytest-dev/pytest': editable mode is not supported for pyproject.toml-style projects. This project is being processed as pyproject.toml-style because it has a pyproject.toml file with a "build-backend" key in the "build_system" value. See PEP 517 for the relevant specification.
```

Likely due to new pip release.

**Comment by nicoddemus** [comment]
Oh my. This is definitely a huge problem now.

**Comment by nicoddemus** [comment]
Just reading about this, with pip 19.1 develop installs do not work anymore, which of course is a problem for us (https://github.com/pypa/pip/pull/6370).

There are a few workarounds:

* https://github.com/ansible/molecule/pull/2009/files
* https://github.com/jaraco/skeleton/commit/123b0b2

but none of them are pretty.

Not sure how to proceed overall... this mean develop installs don't work at all anymore in the pytest tree.

**Comment by blueyed** [comment]
Not looked into this really now, but enabling isolated builds just because a pyproject.toml is present was a bad idea to begin with.  IIRC the PEP was even clarified to not do this, but yeah..  an old comment from me: https://github.com/pypa/pip/issues/5416#issuecomment-398635268

**Comment by blueyed** [comment]
Here is a workaround/fix: https://github.com/pypa/pip/issues/6433#issuecomment-486875540

**Comment by nicoddemus** [comment]
Oh just now I saw this, and I already merged the other one (as master was broken otherwise) 😬 

Anyway, the `--no-use-pep517` does not work for us because we have a `build_meta` section in our `pyproject.yml`:

```
λ pip install -e . --no-use-pep517
Obtaining file:///C:/pytest
ERROR: Disabling PEP 517 processing is invalid: project specifies a build backend of setuptools.build_meta in pyproject.toml
```

(FTR I have tried that before falling back to comment the `usedevelop` sections in our `tox.ini`)

**Comment by blueyed** [comment]
Ok, pulled in here.

**Pull request merged**
