### PR TITLE
document autouse scope fixture priority 

### LINKED ISSUE #3404: Can't override an autouse fixture ordering
pytest 3.5.0 on Python 3.6.5 (macOS).  This result surprised me:

```python
import pytest

d = {'k': 'v_init'}

@pytest.fixture(autouse=True)
def fixauto(monkeypatch):
    monkeypatch.setitem(d, 'k', 'v_auto')

@pytest.fixture
def fix(monkeypatch):
    monkeypatch.setitem(d, 'k', 'v_fix')

def test_auto():
    assert d['k'] == 'v_auto'

def test_fix(fix):
    assert d['k'] == 'v_fix'

def test_fixauto_fix(fixauto, fix):
    assert d['k'] == 'v_fix'

def test_fix_fixauto(fix, fixauto):
    assert d['k'] == 'v_auto'
```

To be clear, first 3 tests are passing OK but the `test_fix_fixauto` fails.  I would have expected that explicitly injecting an autouse fixture could be used to override the usual order.  Feature or bug?

### PR DESCRIPTION
**Pull request by symonk**
Hi team, added some brief documentation explaining that autouse fixtures will be prioritized even when declared after non auto use fixtures in a test signature.  closes #3404

### CODE REVIEW

**Comment by symonk** [comment]
Whoops seems the tests in there get actually ran, will address (on mobile right now)

**Comment by bluetech** [comment]
Hi @symonk, isn't that sufficiently covered a few lines above? Specifically by this line:

> a1: is a function-scoped autouse fixture: it will be instantiated before other fixtures within the same scope.

**Comment by symonk** [comment]
Thanks @bluetech I do see `a1` now which outlines it,  I will defer to you on this one.  I think:

- An example in code can help articulate the example nicely

But yep, that a1 line basically covers it

**Comment by bluetech** [comment]
It's also mentioned in the paragraph introducing the existing example:

> Autouse fixtures will be instantiated before explicitly used fixtures.

So I don't think another emphasis is needed.

**Comment by symonk** [comment]
Yes sir, closing 👍

**Pull request closed without merging**
