### PR TITLE
7018: Use internal version of make_numbered_dir

### LINKED ISSUE #7018: Replace usage of py.path.local().make_numbered_dir
There are two places where `make_numbered_dir` is used from pylib, although there is also `_pytest.pathlib.make_numbered_dir`:

`testdir.runpytest_subprocess`:
https://github.com/pytest-dev/pytest/blob/e01dcbf3235188c64d8aa3b9cdc014efbc29e15d/src/_pytest/pytester.py#L1242-L1244

In a test - likely to prepare it for use via `runpytest_subprocess`:
https://github.com/pytest-dev/pytest/blob/e01dcbf3235188c64d8aa3b9cdc014efbc29e15d/testing/test_assertrewrite.py#L835-L837

Ref: https://github.com/pytest-dev/pytest/issues/3810

### PR DESCRIPTION
**Pull request by kerizane**
Fixes #7018

No changelog as it's trivial, but happy to add if you like. 
e.g.
"Replace usage of py.path.local.make_numbered_dir with version from _pytest.pathlib"

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
Hmm, on second thought, let me take a look on a real computer in about 30

**Comment by kerizane** [comment]
Fixed.

**Comment by kerizane** [comment]
Removed strpath.

**Comment by nicoddemus** [comment]
Thanks a lot @kerizane!

**Pull request merged**
