### PR TITLE
Do not rewrite assertion if a message is present

### LINKED ISSUE #12360: Assertions are rewritten even if a message is present
As stated in [documentation](https://docs.pytest.org/en/7.1.x/how-to/assert.html#asserting-with-the-assert-statement), assertion should not be rewritten when raised by an assert statement in the extended form (with the optional message):

 > However, if you specify a message with the assertion like this:
 >
 > `assert a % 2 == 0, "value was odd, should be even"`
 >
 > then no assertion introspection takes places at all and the message will be simply shown in the traceback.

This is not the case actually as we can see with the following example:
```shell
$ cat test_assertionrewrite.py 
def test_a():
    a = 3
    assert a % 2 == 0, "value was odd, should be even"


$ pytest
================================== test session starts ==================================
platform linux -- Python 3.11.6, pytest-0.1.dev15936+gcbf6bd9.d20240523, pluggy-1.5.0
rootdir: /home/ed/tools/pytest-reports
plugins: anyio-4.1.0
collected 1 item                                                                        

test_assertionrewrite.py F                                                        [100%]

======================================= FAILURES ========================================
________________________________________ test_a _________________________________________

    def test_a():
        a = 3
>       assert a % 2 == 0, "value was odd, should be even"
E       AssertionError: value was odd, should be even
E       assert (3 % 2) == 0

test_assertionrewrite.py:3: AssertionError
================================ short test summary info ================================
FAILED test_assertionrewrite.py::test_a - AssertionError: value was odd, should be even
=================================== 1 failed in 0.04s ===================================
```
see the difference when disabling assertion rewrite with the command line option:
```shell
$ pytest --assert=plain
================================== test session starts ==================================
platform linux -- Python 3.11.6, pytest-0.1.dev15936+gcbf6bd9.d20240523, pluggy-1.5.0
rootdir: /home/ed/tools/pytest-reports
plugins: anyio-4.1.0
collected 1 item                                                                        

test_assertionrewrite.py F                                                        [100%]

======================================= FAILURES ========================================
________________________________________ test_a _________________________________________

    def test_a():
        a = 3
>       assert a % 2 == 0, "value was odd, should be even"
E       AssertionError: value was odd, should be even

test_assertionrewrite.py:3: AssertionError
================================ short test summary info ================================
FAILED test_assertionrewrite.py::test_a - AssertionError: value was odd, should be even
=================================== 1 failed in 0.04s ===================================
```

### PR DESCRIPTION
**Pull request by edhinard**
- [X] Allow maintainers to push and squash when merging my commits.

closes #12360

### CODE REVIEW

**Comment by The-Compiler** [comment]
It doesn't make sense to disable assertion introspection there, as it's actually very useful. The docs have already been updated in the newest version, so I don't think there's anything that should be changed here.

**Comment by edhinard** [comment]
Too bad. Can the decision be argued?
On the contrary, I think it makes a lot of sense. When I add a message it is because I know what information needs to be reported and I do not need it to be enriched. I can also display information that I know is relevant in the message using an f-string. Some examples:

`assert alpn in alpns, f"Accepting deprecated protocol {alpn!r}"`
`assert n < NMAX, "Unlimited number of concurrent connections"`
`assert isinstance(sighashalgo, allowedalgos), f"algo={sighashalgo.name} is not from SHA256 nor SHA384 family"`
`assert "ECDSA" in algoname.upper() or "RSA" in algoname.upper(), \
        f"expecting RSA or ECDSA signature algorithm, not {algoname}"`

**Comment by edhinard** [comment]
Forgot my Mood gap @The-Compiler
This was discussed in #549. It is like that from release 7.4. 😏 

I should have been there at the time and give my arguments when the decision was made to always rewrite assertion even with message (that said,  I still don't agree). The recent documentation change only reflects what has been around for 10 years.

Thank you for your work.

**Comment by nicoddemus** [comment]
@edhinard it is very useful to be able to complement pytest's assertion with some helper message, because often the pytest message is complex/detailed (for example the diff between two dicts). 

If you want to get rid of the message completely, you can skip using the `assert` statement:

```python
if x != 10:
    pytest.fail("my custom message")
``` 

Of course not as succinct, but seems reasonable as this is relatively rare to the other use cases.

**Pull request closed without merging**
