### PR TITLE
changed the fixture for spam function

### PR DESCRIPTION
**Pull request by erjan**
head-fork: erjan/pytest
compare: improving-small-test-foo-function

base-fork: pytest-dev/pytest
base: main

improved the return with print statement

### CODE REVIEW

**Comment by erjan** [comment]
adding some improvement

**Comment by nicoddemus** [comment]
Thanks, but can you elaborate why is this an improvement?

**Review by nicoddemus — CHANGES_REQUESTED** [review]
Thanks, but can you elaborate why is this an improvement?

**Comment by erjan** [comment]
> Thanks, but can you elaborate why is this an improvement?

the function needs to print out info before returning.

**Comment by The-Compiler** [comment]
There's no reason this needs to print anything (even more so given that the print wouldn't even be shown anywhere).

**Pull request closed without merging**
