### PR TITLE
contact.rst: Added github discussions.

### PR DESCRIPTION
**Pull request by guettli**
Trival change: Added github discussions to contact.rst

### CODE REVIEW

**Review by nicoddemus — APPROVED** [review]
Thanks!

**Comment by guettli** [comment]
There are flaky tests on windows-py310:

```
=========================== short test summary info ============================
FAILED testing/test_pytester.py::test_run_result_repr - AssertionError: asser...
FAILED testing/python/metafunc.py::TestMetafunc::test_idmaker_enum - Assertio...
```

**Review by nicoddemus — APPROVED** [review]

**Comment by The-Compiler** [comment]
This should probably go to `main` too?

**Comment by nicoddemus** [comment]
Ahh good catch, didn't realize it wasn't going to `main` already. I will follow up with a port.

**Comment by nicoddemus** [comment]
https://github.com/pytest-dev/pytest/pull/8937

Thanks again!

**Pull request merged**
