### PR TITLE
record_property is no longer experimental

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**

### CODE REVIEW

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt there's a deprecation test which needs to be removed as well. 😉

**Comment by RonnyPfannschmidt** [comment]
yikes, thats what i get for a quick late night fix ^^

**Comment by RonnyPfannschmidt** [comment]
first thing after first coffee is also no good, i#ll do the next one in a sane manner ^^

**Comment by nicoddemus** [comment]
Thanks

**Pull request merged**
