### PR TITLE
Nomore py26

### LINKED ISSUE #2812: finally drop python2.6 support
i just verified with @dstufft that pip master no longer supports python2.6 and we can drop it for all purposes

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
fixes #2812

### CODE REVIEW

**Comment by nicoddemus** [comment]
LGTM, just have to fix the linting issue.

**Comment by hugovk** [comment]
What's the difference between the features and master branches?

**Comment by RonnyPfannschmidt** [comment]
@hugovk features is where we do feature/majore releases from, after a release from features it will be merged to master

**Comment by The-Compiler** [comment]
Please also adjust the README and maybe other documentation that refers to Python 2.6 / 3.3.

**Comment by RonnyPfannschmidt** [comment]
@hugovk just graciously did that 👍

**Pull request merged**
