### PR TITLE
Add hint of Issue #478 to error text

### PR DESCRIPTION
**Pull request by DuncanBetts**
- [ master ] Target: for bug or doc fixes, target `master`; for new features, target `features`;

Tried  to resolve 3 way merge (with help) but it kept recurring, subsequently accidentally closed previous pull request in process of trying to resolve.

Same as [Pull #2081 ](https://github.com/pytest-dev/pytest/pull/2081)

### CODE REVIEW

**Comment by lwm** [comment]
:rocket:

**Comment by nicoddemus** [comment]
Will merge as soon as #2092 passes.

**Comment by nicoddemus** [comment]
Thanks again @DuncanBetts!

**Comment by enkore** [comment]
> Tried to resolve 3 way merge (with help) but it kept recurring

The ways of git sometimes escape even the most experienced developers :)

**Pull request merged**
