### PR TITLE
ci: Travis: add pypy3 to allowed failures temporarily

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/pytest-dev/pytest/pull/5334
Ref: https://github.com/pytest-dev/pytest/issues/5317

### CODE REVIEW

**Comment by blueyed** [comment]
Let's try to fix it instead first.

**Comment by blueyed** [comment]
Re-opening: https://github.com/pytest-dev/pytest/pull/5334#issuecomment-497527688

**Comment by nicoddemus** [comment]
@asottile we're all set for 4.6. Want to make that release? 😁

**Comment by blueyed** [comment]
JFI: this causes Travis builds to become even slower, since it now gets run as the last job: https://travis-ci.org/pytest-dev/pytest/builds/539900223

**Pull request merged**
