### PR TITLE
Preparing release version 4.6.5

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by blueyed** [comment]
Sorry, I've pushed https://github.com/pytest-dev/pytest/commit/b71f8731893c4e4b4c7d3ca97e17738519318006 directly accidentally.

AFAICS it will be included in the release then, but files should be regenerated?

**Comment by nicoddemus** [comment]
> AFAICS it will be included in the release then, but files should be regenerated?

Not automatically, but I will update the branch.

**Comment by blueyed** [comment]
Thanks!

**Comment by nicoddemus** [comment]
Updated. 👍

**Pull request merged**
