### PR TITLE
Testcase reports with a url attribute will now properly write this to…

### PR DESCRIPTION
**Pull request by fushi**
Thanks for submitting a PR, your contribution is really appreciated!

Here's a quick checklist that should be present in PRs:

- [*] Target: for bug or doc fixes, target `master`; for new features, target `features`;
- [*] Make sure to include one or more tests for your change;
- [*] Add yourself to `AUTHORS`;
- [*] Add a new entry to `CHANGELOG.rst`
  * Choose any open position to avoid merge conflicts with other PRs.
  * Add a link to the issue you are fixing (if any) using RST syntax.
  * The pytest team likes to have people to acknowledged in the `CHANGELOG`, so please add a thank note to yourself ("Thanks @user for the PR") and a link to your GitHub profile. It may sound weird thanking yourself, but otherwise a maintainer would have to do it manually before or after merging instead of just using GitHub's merge button. This makes it easier on the maintainers to merge PRs. 

… junitxml

### CODE REVIEW

**Comment by fushi** [comment]
Just triggering a rerun of travis with the close/open routine

**Comment by nicoddemus** [comment]
Thanks! According to the [junit-plugin schema](https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd#L88) this is valid on Jenkins, but could you explain your use case better? Do you have custom hooks that add that attribute to test reports?

**Comment by fushi** [comment]
I do! We're using this to point to where our test artifacts are, so that when you see a failure in phabricator, you can be linked directly to the artifacts in jenkins

**Comment by nicoddemus** [comment]
@fushi I see, thanks. This seems like a new feature (albeit small), so perhaps this should go into the `features` branch and be released on `3.1.0`? Let's see what others have to say.

Also I wonder how to better document that.

**Comment by The-Compiler** [comment]
I agree this should go to `features`.

**Comment by nicoddemus** [comment]
@fushi could you change the target of this PR to `features` then?

**Comment by flub** [comment]
Apparently we can change the target ourselves using the edit button at the top of the page :-)

**Pull request merged**
