### PR TITLE
Merge master into features

### PR DESCRIPTION
**Pull request by nicoddemus**
@RonnyPfannschmidt I resolved two conflicts on `code.py` in `ExceptionInfo`: in those cases I kept the code from features because I believe that's the one we want to keep. 👍

### CODE REVIEW

**Comment by nicoddemus** [comment]
😢

**Comment by blueyed** [comment]
I'd rather like to find the root cause, but in any case we have an issue already to track this: https://github.com/pytest-dev/pytest/issues/4346.

**Comment by nicoddemus** [comment]
Agreed, trying to improve the situation a bit in #4457

**Comment by RonnyPfannschmidt** [comment]
:+1:

**Pull request merged**
