### PR TITLE
runner: inline helpers into runtestprotocol

### PR DESCRIPTION
**Pull request by bluetech**
`runtestprotocol()` is an important function which calls all of `pytest_runtest_*` hooks for a single test item.

Previously it was broken up into several helper functions, to avoid some duplication and add some abstraction. But I think it makes the code a bit harder to follow, due to indirection and having to jump around, adds stackframes and makes things harder to grep for.

Let's inline them all so there is one straight function which can be read in all its glory.

Interesting take in the context of game programming if interested:
http://number-none.com/blow/john_carmack_on_inlined_code.html

### CODE REVIEW

**Comment by bluetech** [comment]
In the corpus of plugins I have locally I could not find any usage of the removed functions.

**Comment by bluetech** [comment]
I'm fine closing this but will just try again :smile:

- `call_runtest_hook` is not very useful IMO - in this PR the hook calls become direct and the reraise is done once.

- `call_and_report` - I find it more direct to just `call` and `report` in sequence.

- `show_test_item` - I don't think it stands on its own and is only called from one place. But can be kept separate if wanted.

**Comment by nicoddemus** [comment]
I'm leaving this for you guys to decide. 😁

**Comment by RonnyPfannschmidt** [comment]
i agree with in-lining `call_runtest_hook`

i think `show_test_item` should be separate since it purely ux code

i think `call_and_report` should stay condensed, but there may be some merit to restructuring the hooks

also i would like to call to attention that a future removal of the test protocol hook would benefit by coordinating some details here (in order to loose nextitem eventually)

**Comment by bluetech** [comment]
I've noticed that this plugin https://github.com/box/flaky/blob/master/flaky/flaky_pytest_plugin.py seems to rely on the details here, and this PR or similar changes would break it and possibly others. It's probably not worth breaking them just to make things slightly cleaner, so I'll close this.

**Pull request closed without merging**
