### PR TITLE
Optimize appveyor build

### PR DESCRIPTION
**Pull request by nicoddemus**
- AppVeyor does not run matrix builds in parallel, so creating a matrix with the intent to
  speed up the build will actually result in longer build times, as each matrix will execute
  in a brand new VM.

- `tox` does not detect 64 bit installations in AppVeyor as [these logs show](https://ci.appveyor.com/project/nicoddemus/pytest/build/1.0.2), so there's no point to have 64bit builds (`tox` always installs interpreters from [C:\PythonX.Y](https://bitbucket.org/hpk42/tox/src/4a8b2093838fdaeea640a49be9b3df87190b4fdc/tox/interpreters.py?at=default&fileviewer=file-view-default#interpreters.py-140)).
- No need for the auxiliary script `"install.ps1"` because all python versions we are interested
  in are already pre-installed in AppVeyor.

### CODE REVIEW

**Comment by nicoddemus** [comment]
Can I merge this?

Seems like a no brainer, the scripts are simpler and AppVoyer builds now takes less than half the time it took before (plus I also added `flakes` check for good measure).

**Comment by RonnyPfannschmidt** [comment]
i was wondering if we want to keep the script around to install certain kinds of python,
but this is just to ensure it still works on windows, so i think we are fine

**Comment by nicoddemus** [comment]
Hmmm your remark about the script made me realize that we should perhaps install `pypy` into AppVeyor and test against it.

Also note that there's no need for that script to be written in Powershell... since we already have some Python versions installed we can use a plain Python script instead. That's the approach I used in [pytest-qt](https://github.com/pytest-dev/pytest-qt/blob/master/scripts/install-qt.py) to install PyQt, borrowed from [qutebrowser](https://github.com/The-Compiler/qutebrowser). :smile:

If you think this is worthwhile I can create a task for it.

**Comment by RonnyPfannschmidt** [comment]
a pip installable lib would be nice for that purpose, so we dont litter the pytest repo :)

**Comment by nicoddemus** [comment]
PyQt's a little more complicated than pypy... `pypy` should be just a download/zip extract, with a few lines of code.

**Comment by nicoddemus** [comment]
Created the issue at #1254

**Comment by RonnyPfannschmidt** [comment]
we still should have a tool that all projects can use - we want the interpreters for a few plugins as well,
also own windows boxes could use a auto tool

**Pull request merged**
