### PR TITLE
Fix TypeError

### PR DESCRIPTION
**Pull request by linchiwei123**
can only concatenate str (not "bytes") to str

- [x] Target the `master` branch for bug fixes, documentation updates and trivial changes.
- [ ] Target the `features` branch for new features, improvements, and removals/deprecations.
- [ ] Include documentation when adding new features.
- [ ] Include new tests or update existing tests when applicable.

Unless your change is trivial or a small documentation fix (e.g.,  a typo or reword of a small section) please:

- [x] Create a new changelog file in the `changelog` folder, with a name like `<ISSUE NUMBER>.<TYPE>.rst`. See [changelog/README.rst](https://github.com/pytest-dev/pytest/blob/master/changelog/README.rst) for details.
- [ ] Add yourself to `AUTHORS` in alphabetical order;

### CODE REVIEW

**Comment by linchiwei123** [comment]
@nicoddemus thanks for your information, and i have added the file changelog/5782.bugfix.rst.

**Comment by nicoddemus** [comment]
We still need a test. You can test the actual function directly. It is OK if you don't have the time to do it, let me know and I can take it over in that case.

**Comment by linchiwei123** [comment]
@nicoddemus sorry, i'm new to test, it would be great if you can help!

**Comment by nicoddemus** [comment]
No worries, I will take this on later or tomorrow! 😁

**Comment by nicoddemus** [comment]
Thanks again @linchiwei123!

**Comment by linchiwei123** [comment]
@nicoddemus You’re welcome! And thank you, too.🙂

**Pull request merged**
