### PR TITLE
Release 2.8.5

### PR DESCRIPTION
**Pull request by nicoddemus**
I took the opportunity to review the `HOWTORELEASE` docs with the most up-to-date information, mainly how to handle `features` and `master` branches before and after the release, and relying on the C.I servers we have setup to ensure the release is solid instead of manually running checks in various platforms.

### CODE REVIEW

**Comment by nicoddemus** [comment]
I'm trying to run `tox -e regen` on a Ubuntu 14.04 box, but it gets stuck at this point:

```
  ======= 1 passed in 0.12 seconds ========
#[ 13/ 88] faq.rst
#[ 14/ 88] feedback.rst
#[ 15/ 88] fixture.rst
```

Any idea why?

**Comment by RonnyPfannschmidt** [comment]
The howtorelease is getting more and more like a script, 
I'd prefer if it had a separate pr

The last time I skipped a devpi step there where errors in the release (2.8.3)
So I'm def opposed to just changing that as part of a release branch

**Comment by The-Compiler** [comment]
I agree there are some gotchas there, so it'd be better to do the `HOWTORELEASE` update in a separate PR.

**Comment by nicoddemus** [comment]
Hmm IMHO the natural way to update this document **is** during the release, because at this point you are effectively using it, so you are noticing shortcomings, encountering problems, etc.

But I'm fine doing the doc changes in a separate PR of you guys insist. 

Ronny, do you remember the error you had? I changed that part because controlled CI testing beats manual checking of the package IMHO.

**Comment by The-Compiler** [comment]
Relevant discussion from IRC recently:

```
hpk     ronny: you didn't use "devpi upload", did you?  That would have avoided pyc files irrespective of manifest.in 
hpk     ronny: 2.8.3 is also 20% bigger than 2.8.2 's tar.gz
hpk     so i guess a 2.8.4 is due 
ronny   hpk: i can do it around 19:00 when im back home
hpk     ronny: relying on manifest.in is very brittle which is the reason devpi upload does the vcs-copying
hpk     in the rare cases where that doesn't work one can still do a manifest.in 
ronny   hpk: our manifest.in is also rather bad
ronny   (it uses grafr insted of includes)
ronny   hpk: per design one is supposed to use a setuptools file finder (which is a different kind of special mess)
hpk     i am using the devpi-upload logic for the last 20-30 releases of various projects and never had any issue
hpk     it's also what we have in howtorelease.txt
hpk     also bruno, floris and others used that approach without problems 
ronny   i accidentially skipped the step after a email exchange with bruno
hpk     sure, not a super-big deal -- the wheel should be fine i guess and is what is most often used i guess
ronny   yup
ronny   hpk: btw, for 2.9 can we switch to a src folder using layout?
hpk     suggest to suggest it on ML 
ronny   k
ronny   hpk: btw, i also wonder, if we could push the upload process of docs/releases to a ci system
hpk     ronny: we can try -- but we haven't got full automation on pytest regen docs, have we? 
ronny   hpk: true, release preparation is tricky :/
ronny   hpk: woud regendoc update commits *after* the tag be acceptable?
hpk     not really, they should be part of the release tarball 
ronny   hpk: the basic process would be something like on tag run regendoc, create the release tarball, upload the docs, commit the changes
hpk     ronny: i'd work from the howtorelease.txt and PRs to it
hpk     too easy to miss details and several people have thought about howtorelease 
ronny   hpk: there is a few detail problem tho, howtorelease puts tagging atthe wrong place for automation
hpk     ronny: tagging is the last worry IMO 
ronny   hpk: for complete automation, you do the tag *before* automation is applied on the tag
ronny   hpk: im going to investigate using zest.releaser for automation next
hpk     ronny: disagree. tagging is done when all else succeeded 
hpk     i don't see the point in overwriting tags if automation goes wrong or results in "not ready" 
ronny   hpk: the system is unable to know the target release if its not indicated by something like a tag
The-Compiler    why not just something like a   python release.py 2.8.4
ronny   The-Compiler: means it would run on my box and i would need credentials for uploads 
The-Compiler    ronny: and what's the problem with that?
ronny   The-Compiler: it should be possible to release by just creating a tag in the github ui
The-Compiler    I disagree
The-Compiler    (and I'm also somewhat against e.g. Travis having the permissions to deploy stuff)
ronny   The-Compiler: in the end i want to see a system where i can tag a release and it will happen including all needed steps
hpk     ronny: if we want this we can trigegr it by all kinds of things, tag is not the only possibility 
hpk     we should run the release machinery i guess on every commit
hpk     on the default branch and with PRs
hpk     anyway, it's best to discuss this wrt to a PR to howtorelease 
ronny   k
```

**Comment by RonnyPfannschmidt** [comment]
also never change a process while executing it

btw, the removal of numbers is bad, we dont format this for consumption we open it in the editor, and the ordered markdown lists are harder to read

**Comment by nicoddemus** [comment]
No problem guys, I will remove my changes from `HOWTORELEASE` and push-force only the actual release changes later today.

@The-Compiler thanks for that transcript!

About `devpi`, I skipped it in the doc because I think we should rely in our current CI platforms since we use them on a daily basis. I thought `setup.py sdist` and `devpi upload` generated the same package, so that's why I changed the docs to skip it entirely.

Does it make sense to use `devpi` for packaging and pushing to `PyPI`, but relying on our current CI servers (Travis and AppVeyor) for testing a release?


@RonnyPfannschmidt any idea why my `tox -e regen` is getting stuck? Any options I use to give any hints perhaps?

**Comment by nicoddemus** [comment]
I decided to close this instead of pushing forcing the changes. I will open a separate PR.

**Comment by RonnyPfannschmidt** [comment]
im not sure why the regen is stuck, it would take a while to add propper tracing

**Comment by RonnyPfannschmidt** [comment]
wrt ci and release automation, thats one of the topics i want to push forward differently, because thats exactly one of the topics where i'd like the ci to manage everything from pushing docs to pypi uploading

**Comment by nicoddemus** [comment]
Agreed

**Pull request closed without merging**
