### PR TITLE
Adjust stacklevel of "config" warnings

### PR DESCRIPTION
**Pull request by nicoddemus**
Related to #4439

### CODE REVIEW

**Comment by nicoddemus** [comment]
Yeah it is kind of a pain... decided to get this out quickly though because our warnings as they are point to totally arbitrary locations. Perhaps as a future improvement?

**Comment by RonnyPfannschmidt** [comment]
lets add it as a easy help wanted issue - perhaps with a reference to this one

**Comment by nicoddemus** [comment]
Good idea, done: #4445

**Comment by RonnyPfannschmidt** [comment]
awesome thanks :+1:

**Pull request merged**
