### PR TITLE
small mypy fixes

### PR DESCRIPTION
**Pull request by asottile**
mypy is very far from passing, but it did point out a few small cleanups that were doable

### CODE REVIEW

**Comment by blueyed** [comment]
Great.
Would be nice to have some mypy config already in setup.cfg maybe, or share it here.

**Comment by asottile** [comment]
agreed, but even with no config there's 1000+ errors right now, I hope to reduce them slowly, eventually

I was using `pre-commit try-repo https://github.com/pre-commit/mirrors-mypy` and then fixing the crashes

**Comment by blueyed** [comment]
`mypy --check-untyped-defs --ignore-missing-imports src/` has 275 issues "only".. ;)

**Comment by asottile** [comment]
I was also looking at `testing` since it's useful to validate those calls as well, I might've also had `--check-untyped-defs` as well I forget

**Pull request merged**
