### PR TITLE
use `if not TYPE_CHECKING` on `pytest.__getattr__` to prevent type checkers from using it

### LINKED ISSUE #11325: `pytest.__getattr__` disables type checker errors on invalid imports
```py
from pytest import asdfasdf
```
no error from mypy:
```
>mypy main.py
Success: no issues found in 1 source file
```

i'm not sure what the purpose of this `__getattr__` method is, but it should probably be inside an `if not TYPE_CHECKING` block to avoid this issue:
```py
from typing import TYPE_CHECKING:

if not TYPE_CHECKING:
    def __getattr__(name: str) -> object:
        if name == "Instance":
            # The import emits a deprecation warning.
            from _pytest.python import Instance
    
            return Instance
        raise AttributeError(f"module {__name__} has no attribute {name}")
```

### PR DESCRIPTION
**Pull request by DetachHead**
fixes #11325

### CODE REVIEW

**Review by bluetech — COMMENTED** [review]
LGTM, thanks. Just needs a fix to the mypy error in `testing/deprecated_test.py`.

**Comment by The-Compiler** [comment]
I suppose something like

```python
if TYPE_CHECKING:
    from _pytest.python import Instance
else:
    def __getattr__(name: str) -> object:
        ...
```

would work so mypy still knows that it's there?

**Review by RonnyPfannschmidt — COMMENTED** [review]
I believe a else clause with the import is needed

I wonder if literal can be used to narrow the input for the type checking

**Comment by Zac-HD** [comment]
> I suppose something like <snip> would work so mypy still knows that it's there?

I _deliberately_ omit type annotations for deprecated functionality, to emphasize that while we haven't (yet) broken backwards-compatibility anyone working on this code should probably update it.

**Review by Zac-HD — APPROVED** [review]
Thanks again @DetachHead!

**Pull request merged**
