### PR TITLE
[WIP][RFC][NOMERGE] Node nomore smart init

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
in this pr i experiment with breaking changes to node structure in order to get rid of the construction patterns that make things hard

as a starting point i removed instance, however so far that just broke fixture finding

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
i currently suspect that i cant make removing instance feasible without removing nodeid splitting and introducing per directory nodes which connect conftests to direct nodes

**Comment by RonnyPfannschmidt** [comment]
leaving this sit for feedback and cringeing

**Comment by blueyed** [comment]
Nice, reminded me of https://github.com/pytest-dev/pytest/pull/4357 - cannot provide much more help currently though.

**Comment by RonnyPfannschmidt** [comment]
im canceling this one  again as well, i will have to do a small series of breaking changes to get this sorted, this mess is just too interconnected

**Pull request closed without merging**
