### PR TITLE
Merge master into features (with regen)

### PR DESCRIPTION
**Pull request by blueyed**
Includes #5037.

### CODE REVIEW

**Comment by blueyed** [comment]
@nicoddemus 
You are right: we should merge https://github.com/pytest-dev/pytest/pull/5037 also (re-opened).
It is included here already.

**Comment by nicoddemus** [comment]
Should we close this then?

**Comment by blueyed** [comment]
No, we can merge it now also.

**Comment by blueyed** [comment]
Oh, I got the base branch wrong.. :)

**Comment by blueyed** [comment]
The version issue is not so minor anymore.. ;)

> pluggy.manager.PluginValidationError: Plugin 'xdist' could not be loaded: (pytest 4.3.2.dev225+gebe8169 (/home/travis/build/pytest-dev/pytest/.tox/py36-xdist/lib/python3.6/site-packages), Requirement.parse('pytest>=4.4.0'))!

(from another PR against features)

**Comment by nicoddemus** [comment]
> The version issue is not so minor anymore.. ;)

Indeed. Should be fixed now though. 👍

**Pull request merged**
