### PR TITLE
Preparing release version 3.7.4

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Decided to cut `3.7.4` now because of #3888, but I forgot that @RonnyPfannschmidt was scheduled for the next release, sorry! @RonnyPfannschmidt will you do the honors please? 😁

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus for personal reasons im a bit swamped, please do it ^^

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt just let me know he swamped with some personal matters so he won't be able to do this release anytime soon.

@blueyed, @asottile, anyone of you want to do the honors? It is really quick, should take no longer than five minutes. The steps are explained in [HOWTORELEASE.rst](https://github.com/pytest-dev/pytest/blob/master/HOWTORELEASE.rst).

**Comment by asottile** [comment]
I can take a stab at it, seems simple enough

**Comment by nicoddemus** [comment]
Cool, let me know if you encounter problems. 👍

**Pull request closed without merging**
