### PR TITLE
New-style classes implemented for python 2.7 - #2147

### PR DESCRIPTION
**Pull request by MichalTHEDUDE**
Added `(object)` inheritance for all classes as per #2147.
All tests are green.

All feedback appreciated :).

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks a ton @MichalTHEDUDE, you are the dude! 👍 

LGTM, we should merge as soon as CI passes.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus wait, this changed pluggy?

**Comment by nicoddemus** [comment]
Ouch right, my bad! I will fix this in a PR.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus it was also merged in pluggy, perhaps we can do a full update

**Comment by nicoddemus** [comment]
But we didn't make a new pluggy release yet, right?

**Comment by nicoddemus** [comment]
Regardless, fixed in #2263. 😅

**Pull request merged**
