### PR TITLE
Add same environments to Azure, except py37-freeze

### PR DESCRIPTION
**Pull request by nicoddemus**
PyPy needs a little more work I suspect

### CODE REVIEW

**Comment by nicoddemus** [comment]
Failing on two envs because apparently that Windows image does not contain the build tools for Python 2.7 (fails to build xfreeze and twisted). All other envs passed, the entire build took 17 minutes which, even we are missing PyPy, is very promising.

**Comment by nicoddemus** [comment]
I'm really excited about the timings we are getting:

```
Queued
37m ago
Started after 1m 57s in queue
35m ago
Completed after 15m 54s
19m ago
```

And at this moment both Travis and AppVeyor have not even started. 👍

**Comment by blueyed** [comment]
Nice.

Would be good btw to not trigger AppVeyor/Travis from here.

I'm not sure if they support "[skip …]" from the PR title, but then you could add it to commits, or manually cancel them after pushing.

**Comment by nicoddemus** [comment]
> Would be good btw to not trigger AppVeyor/Travis from here.

My bad, should have added `[skip travis] [skip appveyor]` to the commits

**Comment by nicoddemus** [comment]
Ready for review. Let's please squash all changes during merging.

Only standing issue https://github.com/pytest-dev/pytest/issues/4807

**Comment by nicoddemus** [comment]
Nice, took 15 minutes, even faster than Travis. 👍

**Comment by blueyed** [comment]
> Let's please squash all changes during merging.

You have to force-push yourself.. but could be done after review / before merging.
Not time for it myself currently though.

Is it meant to replace AppVeyor in the long run?

**Comment by nicoddemus** [comment]
> Is it meant to replace AppVeyor in the long run?

Yep! So far it looks promising. Still need coverage though.

**Comment by nicoddemus** [comment]
Rebased. 👍

**Comment by nicoddemus** [comment]
> Yep! So far it looks promising. Still need coverage though.

**Comment by nicoddemus** [comment]
@blueyed @asottile, gentle ping. 👍 

I'm anxious to see this live to see how it behaves on daily basis.

**Pull request merged**
