### PR TITLE
Add new flag to CLI: `--config-file`

### PR DESCRIPTION
**Pull request by chrimaho**
## Add new flag to CLI: `--config-file`

There is already an exiting flag in the CLI for importing a custom config file: `-c`. This change does not change the behaviour of that flag, but simply adds a new flag to execute the same process: `--config-file`.

This change is also in-line with other large Python packages which use the same behaviour:

- MyPy uses the command: `--config-file CONFIG_FILE`. See [here][mypy_cli_flag_--config-file].
- Black uses the command: `--config FILE`. See [here][black_cli_flag_--config].

---

- Closes: #11031

[mypy_cli_flag_--config-file]: https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-config-file
[black_cli_flag_--config]: https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#:~:text=version%20and%20exit.-,%2D%2Dconfig,-FILE%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Read%20configuration

### CODE REVIEW

**Review by nicoddemus — CHANGES_REQUESTED** [review]
Hi @chrimaho, thanks for the contribution!

However please check your Git settings, both `main.py` and `test_config.py` have changed entirely.

**Comment by RonnyPfannschmidt** [comment]
it seems like the newline convention was changed, wen setting ignore whitespace it gets down to a reasonable diff

please fix the newline convention

**Comment by chrimaho** [comment]
Thank you @nicoddemus and @RonnyPfannschmidt.
This should be fixed now. All tests are passing 👍 
Please check it.

**Review by nicoddemus — APPROVED** [review]
LGTM, thanks!

Reminder: we should squash this before merging.

**Comment by nicoddemus** [comment]
(Small tip @chrimaho: you can add "Fix #11036" to your PR description to automatically close when it gets merged: https://github.blog/2013-05-14-closing-issues-via-pull-requests/).

**Review by RonnyPfannschmidt — APPROVED** [review]

**Pull request merged**
