### PR TITLE
Preparing release version 3.3.1

### PR DESCRIPTION
**Pull request by nicoddemus**
Builds: 

- [Travis](https://travis-ci.org/nicoddemus/devpi-cloud-test-pytest/builds/311588611)
- [AppVeyor](https://ci.appveyor.com/project/nicoddemus/devpi-cloud-test-pytest/build/1.0.30)

### CODE REVIEW

**Comment by nicoddemus** [comment]
Created a new `3.3.1` package with the latest changes on `master` (specifically the `pytest-capturelog` blacklisting).

If this gets approved and the builds finish until bed time tonight, I can push the package later today, otherwise we will publish this tomorrow. 👍

**Comment by nicoddemus** [comment]
Builds:

- [Travis](https://travis-ci.org/nicoddemus/devpi-cloud-test-pytest/builds/311588611)
- [AppVeyor](https://ci.appveyor.com/project/nicoddemus/devpi-cloud-test-pytest/build/1.0.31)

**Comment by The-Compiler** [comment]
LGTM FWIW!

**Comment by RonnyPfannschmidt** [comment]
is the metadata correct in the generated wheel?

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus should be in PKG-INFO at best, but usually setup.py itself

**Comment by RonnyPfannschmidt** [comment]
also 👍 yay

**Comment by nicoddemus** [comment]
> should be in PKG-INFO at best, but usually setup.py itself

Ahh OK, I see it in `PKG-INFO`:

```
Requires-Python: >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
```

So if all is well with you @RonnyPfannschmidt I will push the package to PyPI once the `devpi` builds pass. 👍

**Pull request merged**
