### PR TITLE
Added .so files to doctest.py for testing C extension modules (targeted to features branch)

### PR DESCRIPTION
**Pull request by lgpage**
Also See:
Issue: #1498
Closed PR (targeted to master branch): #1499

Comments by @nicoddemus from #1499 copied here for convenience:
> Thanks for the PR.
> 
> I have a few comments:
> 
> - I think we should think more carefully about this. For pytest to start to assume that all .so modules should be collected as doctest files seems dangerous to me, they might not be even a python extension after all, but just a standard .so file... could you check what happens when that's the case?
> 
> - It must also consider .dll and .pyd files on Windows.
> 
> - Perhaps this should be a separate option? I mean besides --doctest-modules.
> 
> - This change definitely should go into features branch. Unfortunately for that you have to close this PR, rebase into features and open an new PR because GitHub doesn't allow you to change the target branch after creating a PR.

### CODE REVIEW

**Comment by lgpage** [comment]
I'll have a look at what happens with standard ``.so`` files and post back here

I have a few ideas on how to approach this:
- Only consider Cython extension modules
  - look for ``.pyx`` files and only doctest  ``.so`` files if both filenames (``file.pyx``, ``file.so``) are present

- Added a separate option:
  - E.g. ``py.test --doctest-modules --doctest-c-ext=.ext``
  - And test all given ``.ext`` files
  - This would rely on the user to ensure ``.ext`` files are C extension modules
  - However @nicoddemus's comment still applies, if a ``.ext`` file is not actually a C extension module it could be dangerous and cause un-stable behaviour

With regards to windows ``.dll`` and ``.pyd`` files, I am at a bit of a loss. I have never looked into building C extensions for windows.

**Comment by lgpage** [comment]
A standard .so (dynamic shared C lib) that is not a Python extension causes pyimport to raise an ImportError:

> ______________ ERROR collecting proj/lib/libjulia.so ______________
> .tox/py27/local/lib/python2.7/site-packages/py/_path/local.py:650: in pyimport
>      __import__(modname)
> E   ImportError: dynamic module does not define init function (initlibjulia)
> ...
> ______________ summary ______________
> ERROR:   py27: commands failed

**Comment by lgpage** [comment]
Skipping .so files that can't be imported be pyimport

```
$ py.test -ra --verbose --doctest-modules
========================================= test session starts ==========================================
platform linux2 -- Python 2.7.6, pytest-2.10.0.dev1, py-1.4.31, pluggy-0.3.1 -- /.../bin/python
cachedir: .cache
rootdir: /.../cython-template-project, inifile: 
collected 3 items / 1 skipped 

proj/sub_package/some_module.so::proj.sub_package.some_module.SomeClass PASSED
proj/sub_package/some_module.so::proj.sub_package.some_module.__test__.SomeClass.norm (line 35) PASSED
tests/test_some_thing.py::test_some_thing PASSED
======================================= short test summary info ========================================
SKIP [1] /.../local/lib/python2.7/site-packages/pytest-2.10.0.dev1-py2.7.egg/_pytest/doctest.py:202: unable to import module local('/.../cython-template-project/proj/lib/libjulia.so') (probably not a Python extension module)

================================= 3 passed, 1 skipped in 0.10 seconds ==================================
```

**Comment by The-Compiler** [comment]
IMHO it'd be nice to have tests for this in pytest's repo (at least with ` .so` which can be imported, and one which can't), but I'm not sure how complex that could get. Maybe just include prebuilt binaries for testing?

**Comment by nicoddemus** [comment]
> IMHO it'd be nice to have tests for this in pytest's repo (at least with .so which can be imported, and one which can't), but I'm not sure how complex that could get. Maybe just include prebuilt binaries for testing?

Certainly tests would be nice. I'm sure it should be simple to write some simple Cython modules and compile them, specially in Linux (although AppVeyor already contains all C compilers necessary so should be simple as well).

We have a [separate environment](https://github.com/pytest-dev/pytest/blob/master/tox.ini#L125) which cx_freezes pytest and tests it, so perhaps we could take the same approach for those Cython tests. In this approach, the tests for this feature are not part of the official test suite which is usually executed by contributors (`linting,py27,py35`) so it doesn't disrupt the usual workflow. I think this would be the best approach.

**Comment by nicoddemus** [comment]
@lgpage 
> * Only consider Cython extension modules
>   + look for .pyx files and only doctest .so files if both filenames (file.pyx, file.so) are present

I think this is the safest approach. Sure it is specific to Cython for now, but we can always add support for other extension forms later. What others think?

**Comment by lgpage** [comment]
I've started adding tests for this as requested.
I however have no idea how to work with ``cx_freeze`` and will need some guidance.
For now I have created a ``py27-cython`` test environment in the ``tox.ini`` file.

**Comment by nicoddemus** [comment]
Sorry, I meant we should have a separate environment for the cython test(s), exactly like you did, so we're in the right idea. 

I'm not so fan of adding `cmake` as dependency for pytest's tests thought... isn't there a simpler way to build a cython extension?

**Comment by lgpage** [comment]
Busy looking into it atm.

I included ``.so`` files that were not Python extensions in the tests and used ``cmake`` to compile these. For cross-platform compiling cmake is the easiest as it self configures for both unix (Travis) and windows (AppVeyor). The other option it to simple manually add them to git and not worry about recompiling them.

With regards to actually building the Cython extensions:
This is proving to be a pain, at least for AppVeyor. I need to make quite a few changes to the CI config files.

**Comment by RonnyPfannschmidt** [comment]
can we make this a pytest plugin instead of a part of pytest core, this is not about normal python

**Comment by nicoddemus** [comment]
> can we make this a pytest plugin instead of a part of pytest core, this is not about normal python

That crossed my mind as well... specially with the difficulty involved in testing this. What do you say @lgpage?

**Comment by lgpage** [comment]
A pytest plugin makes more sense.
Again something new I will have to look into :)

**Comment by nicoddemus** [comment]
Please take a look at [cookiecutter-pytest-plugin](https://github.com/pytest-dev/cookiecutter-pytest-plugin). It makes this much easier.

**Comment by lgpage** [comment]
Cool. Will work on this.

**Pull request closed without merging**
