### PR TITLE
prioritize outputting relative paths

### PR DESCRIPTION
**Pull request by dongfangtianyu**
- ~~[ ] Include documentation when adding new features.~~
- [x] Include new tests or update existing tests when applicable.
- [X] Allow maintainers to push and squash when merging my commits. 
- [x] Add text like ``closes #XYZW`` to the PR description and/or commits.
- [X] Create a new changelog file in the `changelog` folder

Implementation of #12973

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
perhaps we want a concept of a "display path that collapss details

it would render cwd relative paths to  - but also perhaps `${SITE}/somepacke/broken.py` instead of the exact folder to the current python site

this could also be expanded with $TMP_PATH and some more

**Review by pyuscherbakov — APPROVED** [review]

**Comment by dongfangtianyu** [comment]
This is a classic pytest output, with most of its paths being relative paths:
```
================================================ test session starts =================================================
platform win32 -- Python 3.12.2, pytest-8.3.3, pluggy-1.5.0
rootdir: D:\git\github\dongfangtianyu\tmp_py312
configfile: pytest.ini
collected 1 item                                                                                                      

a\b\c\test_demo.py F                                                                                            [100%]

====================================================== FAILURES ====================================================== 
_____________________________________________________ test_demo ______________________________________________________ 

    def test_demo():
>       funcs.my_func()

a\b\c\test_demo.py:4:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  

    def my_func():

>       1/0
E       ZeroDivisionError: division by zero

a\b\c\funcs.py:5: ZeroDivisionError
============================================== short test summary info =============================================== 
FAILED a/b/c/test_demo.py::test_demo - ZeroDivisionError: division by zero
================================================= 1 failed in 0.17s ================================================== 
```


This is the output for some scenarios (FixtureLookupError, skip, warnings): the absolute path (warnings summary) is output
```
================================================ test session starts =================================================
platform win32 -- Python 3.12.2, pytest-8.3.3, pluggy-1.5.0
rootdir: D:\git\github\dongfangtianyu\tmp_py312
configfile: pytest.ini
collected 1 item                                                                                                      

a\b\c\test_demo.py F                                                                                            [100%]


====================================================== FAILURES ====================================================== 
_____________________________________________________ test_demo ______________________________________________________ 

    def test_demo():
        import warnings
        warnings.warn('yyy', UserWarning)
>       funcs.my_func()

a\b\c\test_demo.py:8:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  
a\b\c\funcs.py:4: in my_func
    json.loads("xxxxx")
C:\Users\administrator\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py:348: in loads
    return _default_decoder.decode(s)
C:\Users\administrator\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py:337: in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  

self = <json.decoder.JSONDecoder object at 0x000002661F54C920>, s = 'xxxxx', idx = 0

    def raw_decode(self, s, idx=0):
        """Decode a JSON document from ``s`` (a ``str`` beginning with
        a JSON document) and return a 2-tuple of the Python
        representation and the index in ``s`` where the document ended.

        This can be used to decode a JSON document from a string that may
        have extraneous data at the end.

        """
        try:
            obj, end = self.scan_once(s, idx)
        except StopIteration as err:
>           raise JSONDecodeError("Expecting value", s, err.value) from None
E           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

C:\Users\administrator\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py:355: JSONDecodeError
================================================== warnings summary ================================================== 
a/b/c/test_demo.py::test_demo
  D:\git\github\dongfangtianyu\tmp_py312\a\b\c\test_demo.py:7: UserWarning: yyy
    warnings.warn('yyy', UserWarning)

a/b/c/test_demo.py::test_demo
C:\Users\administrator\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py:334
  C:\Users\administrator\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py:334: UserWarning: xxx
    warnings.warn('xxx', UserWarning)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================== short test summary info =============================================== 
FAILED a/b/c/test_demo.py::test_demo - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
=========================================== 1 failed, 3 warnings in 0.13s ============================================
```

---


This is the output of this PR: the relative paths of the files within the project are outputted, while the libraries and traceback maintain their original outputs
```
================================================ test session starts =================================================
platform win32 -- Python 3.12.2, pytest-8.3.3, pluggy-1.5.0
rootdir: D:\git\github\dongfangtianyu\tmp_py312
configfile: pytest.ini
collected 1 item                                                                                                      

a\b\c\test_demo.py F                                                                                            [100%]


====================================================== FAILURES ====================================================== 
_____________________________________________________ test_demo ______________________________________________________ 

    def test_demo():
        import warnings
        warnings.warn('yyy', UserWarning)
>       funcs.my_func()

a\b\c\test_demo.py:8:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  
a\b\c\funcs.py:4: in my_func
    json.loads("xxxxx")
C:\Users\administrator\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py:348: in loads
    return _default_decoder.decode(s)
C:\Users\administrator\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py:337: in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  

self = <json.decoder.JSONDecoder object at 0x000001CF1412C920>, s = 'xxxxx', idx = 0

    def raw_decode(self, s, idx=0):
        """Decode a JSON document from ``s`` (a ``str`` beginning with
        a JSON document) and return a 2-tuple of the Python
        representation and the index in ``s`` where the document ended.

        This can be used to decode a JSON document from a string that may
        have extraneous data at the end.

        """
        try:
            obj, end = self.scan_once(s, idx)
        except StopIteration as err:
>           raise JSONDecodeError("Expecting value", s, err.value) from None
E           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

C:\Users\administrator\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py:355: JSONDecodeError
================================================== warnings summary ================================================== 
a/b/c/test_demo.py::test_demo
  a\b\c\test_demo.py:7: UserWarning: yyy
    warnings.warn('yyy', UserWarning)

a/b/c/test_demo.py::test_demo
C:\Users\administrator\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py:334
  C:\Users\administrator\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py:334: UserWarning: xxx
    warnings.warn('xxx', UserWarning)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================== short test summary info =============================================== 
FAILED a/b/c/test_demo.py::test_demo - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
=========================================== 1 failed, 3 warnings in 0.12s ============================================ 


```

**Comment by dongfangtianyu** [comment]
@nicoddemus Yes. These contents are copied from the actual output.

In this example, the PR converts `D:\git\github\dongfangtianyu\tmp_py312\a\b\c\test_demo.py` to a relative path because the file is part of the project and output by pytest:
- https://github.com/pytest-dev/pytest/blob/72f17d10d76e5260906c17f279c5fa6bd29b5a8d/src/_pytest/warnings.py#L83
- https://github.com/pytest-dev/pytest/blob/72f17d10d76e5260906c17f279c5fa6bd29b5a8d/src/_pytest/terminal.py#L558
- https://github.com/pytest-dev/pytest/blob/72f17d10d76e5260906c17f279c5fa6bd29b5a8d/src/_pytest/terminal.py#L1046

The traceback content is not processed for several reasons:
1. Most standard libraries and third-party libraries in venv have paths that differ from cwd, and converting them to relative paths doesn't work well.
2. In complex call stacks, traceback content can be large, and processing it would be resource-intensive.
3. Many file paths in exception messages are strings, making them harder to process.

**Comment by nicoddemus** [comment]
> The traceback content is not processed for several reasons

Oh no I agree we should not touch the traceback content, I was just making sure the post was correct.

**Review by Tusenka — APPROVED** [review]

**Pull request closed without merging**
