### PR TITLE
Pdbcls without pdb on fail

### LINKED ISSUE #1948: --pdbcls implies --pdb
is this intentional?

(my use case is setting pdbcls in my pytest.ini so that whenever i _do_ invoke pdb it uses a custom pdb class)

### PR DESCRIPTION
**Pull request by davidszotten**
fixes #1948 

i tried to add a final test for using `pdb.set_trace()`, but couldn't get it to work. any advice appreciated

```python
    def test_pdb_custom_cls_with_settrace(self, testdir, custom_pdb_calls):
        testdir.makepyfile(custom_pdb="""
            class CustomPdb:
                def __init__(self, *args, **kwargs):
                    called.append("init")

                def reset(self):
                    called.append("reset")

                def interaction(self, *args):
                    called.append("interaction")
         """)
        p1 = testdir.makepyfile("""
            import pytest

            def test_foo():
                pytest.set_trace()
        """)
        child = testdir.spawn_pytest("--pdbcls=custom_pdb:CustomPdb %s" % str(p1))
        child.expect("interaction")
        child.send('c\n')
        child.sendeof()
        if child.isalive():
            child.wait()
        assert custom_pdb_calls == ["init", "reset", "interaction"]
```

### CODE REVIEW

**Comment by nicoddemus** [comment]
The patch looks good to me, although it should go into `features` instead.

About your test, what is the error you are getting? Also, I don't see the connection between the `custom_pdb_calls` fixture and the `CustomPdb` class you define in the test(the `custom_pdb` module) which is accessing an undeclared module level variable named `called`.

**Comment by davidszotten** [comment]
ah yes, the content of the `CustomPdb` is broken (leftover from the tests that use a similar class) but i don't think we get there `INTERNALERROR> ImportError: No module named custom_pdb`. unless i'm misunderstanding, i take that to mean that the pytest invocation `spawn_pytest` can't even find the custom module

**Comment by davidszotten** [comment]
ok, think i got it working

**Comment by davidszotten** [comment]
@nicoddemus is "it should go into `features` instead." something you need from me or just a reply to @RonnyPfannschmidt ?

**Comment by flub** [comment]
@davidszotten you need to click edit next to the PR title which will give you a drop down list where you can choose between master and features.  After changing to features you'll probably have to fix merge-conflicts for the changelog file and then it should be good to go

**Comment by davidszotten** [comment]
ah, "be raised against the `features` branch". apologies for not catching on.

**Pull request merged**
