### PR TITLE
docs: generate index and add it to globaltoc sidebar

### PR DESCRIPTION
**Pull request by blueyed**
2020-02-24-160334_999x701_escrotum

### CODE REVIEW

**Comment by blueyed** [comment]
2020-02-24-160334_999x701_escrotum

**Comment by blueyed** [comment]
@nicoddemus WDYT?

**Comment by blueyed** [comment]
Might be worth checking why it was explicitly not enabled.

**Comment by nicoddemus** [comment]
> @nicoddemus WDYT?

Looks good, thanks; I don't see myself using it (I use the search box), but I don't see how it can hurt either. 👍 

> Might be worth checking why it was explicitly not enabled.


Seems to have been added in e7c8fc7db9b02921889ddc8ec1b930ec95991661, so it might be related to PDF generation (although I don't think that's relevant anymore?).

**Pull request merged**
