### PR TITLE
Async result warn

### PR DESCRIPTION
**Pull request by graingert**
- [ ] Target the `master` branch for bug fixes, documentation updates and trivial changes.
- [ ] Target the `features` branch for new features and removals/deprecations.
- [ ] Include documentation when adding new features.
- [ ] Include new tests or update existing tests when applicable.

Unless your change is trivial or a small documentation fix (e.g.,  a typo or reword of a small section) please:

- [ ] Create a new changelog file in the `changelog` folder, with a name like `<ISSUE NUMBER>.<TYPE>.rst`. See [changelog/README.rst](https://github.com/pytest-dev/pytest/blob/master/changelog/README.rst) for details.
- [ ] Add yourself to `AUTHORS` in alphabetical order;

### CODE REVIEW

**Comment by nicoddemus** [comment]
Follow up to https://github.com/pytest-dev/pytest/pull/5734 I assume? Can you please rebase given that https://github.com/pytest-dev/pytest/pull/5734 was merged already? Thanks

**Comment by nicoddemus** [comment]
Do we really need this? I mean, Python itself already issues a warning which is clear enough IMHO:

```python
async def foo():
    pass

def test_foo():
    return foo()
```

```
====================== warnings summary ======================
test_async.py::test_foo
  c:\users\bruno.esss.co\pytest\src\_pytest\python.py:165: RuntimeWarning: coroutine 'foo' was never awaited
    testfunction(**testargs)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

**Comment by nicoddemus** [comment]
Oh for the future: new warnings should target `features`, because they might break test suites. No need to change this now because we are about to release 5.1.0. 👍

**Comment by graingert** [comment]
I'm experiencing the problem with twisted Deferreds, however. Where they are awaitable but no error is thrown if you do not await them and there is no way to determine if a function will return one statically like inspect.iscoro...

**Comment by nicoddemus** [comment]
Oh I see, thanks!

**Pull request merged**
