### PR TITLE
9202 Update codecov uploader

### LINKED ISSUE #9202: Codecov bash uploader is deprecated
The Codecov bash uploader that the CI is using is deprecated and will stop working on Feb 1, 2022, with brownouts before then.

https://about.codecov.io/blog/introducing-codecovs-new-uploader/

We should update to their new uploader.

The relevant file is https://github.com/pytest-dev/pytest/blob/5fc7b21391c959bb5a54174d9084ad55131b8fdb/scripts/upload-coverage.sh

Called in CI from here: https://github.com/pytest-dev/pytest/blob/5fc7b21391c959bb5a54174d9084ad55131b8fdb/.github/workflows/main.yml#L168-L172

Note: the `scripts/upload-coverage.sh` script itself can stay in bash; just the codecov file it downloads should be changed to the new one.

### PR DESCRIPTION
**Pull request by cristianMeli**
- [ ] Include documentation when adding new features.
- [ ] Include new tests or update existing tests when applicable.
- [X] Allow maintainers to push and squash when merging my commits. Please uncheck this if you prefer to squash the commits yourself.

Closes #9202

### CODE REVIEW

**Comment by cristianMeli** [comment]
This PR absolutely needs a squash and merge 😅.

**Review by bluetech — COMMENTED** [review]
This seems to work, thanks @cristianMeli!

Two things:

- We can remove the `scripts/upload-coverage.sh` file now - can you do it?

- Any particular reason you added the explicit `use_coverage: false` lines? I think they were omitted intentionally so the jobs that are reporting coverage stand out.

**Comment by cristianMeli** [comment]
Hi @bluetech 

- Yes I can remove it.

- First I added because I had coverage errors in some steps, but maybe it was that the `if` was wrong. Besides that, I think that is better to explicitly set `use_coverage: false` for those steps that the coverage report is not generated.

**Comment by bluetech** [comment]
> What do you think?

I think, let's try to remove the explicit `use_coverage: false` and see if it works; if not, we can keep them.

**Comment by cristianMeli** [comment]
@bluetech yeah, it works. Thanks!

**Review by bluetech — APPROVED** [review]

**Pull request merged**
