### PR TITLE
Update release procedure

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by nicoddemus** [comment]
>  just tag the release via GitHub (on master), which also triggers a build then already.

This is fine, but I would prefer to tag exactly the same commit that was approved on the PR. If this is possible to do via GitHub's UI, then great!

**Comment by blueyed** [comment]
> This is fine, but I would prefer to tag exactly the same commit that was approved on the PR. If this is possible to do via GitHub's UI, then great!

Sure.. you can specify a commit, and/or browse them via "recent commits" on https://github.com/pytest-dev/pytest/releases/new.

Maybe we should update the document according to this instead?
Or wait for the next iteration/release?

**Comment by blueyed** [comment]
Might be good to have some script to fill in the release notes then also (copy'n'paste via some towncrier output/command).

**Comment by nicoddemus** [comment]
> Might be good to have some script to fill in the release notes then also (copy'n'paste via some towncrier output/command).

The release notes are generated from `tox -e release` 😉

**Pull request merged**
