### PR TITLE
adding contact and badge for pytest-dev discord server

### PR DESCRIPTION
**Pull request by symonk**
Short and sweet; adds a discord badge into the readme and updates the contacts docs to reference the **pytest-dev** discord server.

(Not sure on what is best for the text on these; so feel free to recommend any changes :) was a best guess!)

edit: It is possible to make a more 'interactive' discord badge; stating how many users online etc but it might require some admin permissions on the discord server itself - if anyone wants to pursue that

### CODE REVIEW

**Comment by The-Compiler** [comment]
If we're adding badges for social channels in the readme, might want to add other (more or less) active channels as well, such as IRC ([possible badge](https://img.shields.io/badge/irc-%23pytest%20on%20Libera-blue), [link to webchat](https://web.libera.chat/?channels=#pytest)) and perhaps GitHub discussions too?

**Comment by RonnyPfannschmidt** [comment]
i would consider a irc badge as a follow-up tho (we already have irc in the contact channels as well)

**Comment by The-Compiler** [comment]
I wouldn't. If we start promoting one chat platform prominently in the readme, I'd rather have the other there as well (especially considering that it's open and doesn't require an account to use).

**Comment by RonnyPfannschmidt** [comment]
@The-Compiler i understand the sentiment

@symonk can you add the proposed libera badge as well?

**Comment by symonk** [comment]
absolutely, will get to it asap

**Review by RonnyPfannschmidt — APPROVED** [review]

**Review by nicoddemus — APPROVED** [review]
Thanks!

(Reminder to squash on merge)

**Pull request merged**
