### PR TITLE
Do not claim copyright for future years

### PR DESCRIPTION
**Pull request by bmwiedemann**
When building today's python-pytest-doc openSUSE package
in the year 2033, the documentation .html files state
Copyright 2015-2033 , holger krekel and pytest-dev team.

That cannot be correct, because nobody did anything copyright-worthy
for this file in 2033.

See also https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

Additionally, this change makes the package build reproducible.
See https://reproducible-builds.org/ for why this is good.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
the point about being reproducible is important! , thanks

however i'd like to remove the need to update the end of the year range
anyone fluent with copyright up for providing  a idea

if i recall correct the start year can be used solely

**Comment by bmwiedemann** [comment]
As I understood it, copyright is automatic and the statement and year is just there to make proof easier in case you want to sue a violator for damages.

Expiry is usually 70 years after your death, so nothing you need to worry about.

**Comment by nicoddemus** [comment]
I have no idea as well. I will setup a calendar reminder to update this yearly, seems simple enough and will avoid this headaches. 😁

**Comment by RonnyPfannschmidt** [comment]
@asottile i'm wondering - would this be an interesting item for a pre-commit hook that autofixes?

**Comment by asottile** [comment]
@RonnyPfannschmidt I've had a similar idea since 2015 it seems 😆 https://github.com/pre-commit/pre-commit-hooks/issues/94

In this case though, it probably makes more sense as a "copyright year update bot" which swings by once a year to spruce up the comments / years (since you probably wouldn't want a pre-commit hook to suddenly start failing: happy new year 🎉)

**Comment by nicoddemus** [comment]
Automatize a once-a-year single-digit change (or 2 em 2 years) seems overkill to me TBH. 😁 

I see value though if this is a bot that open PRs for a bunch of projects once a year. Then it definitely would be nice.

**Comment by asottile** [comment]
oh yeah for sure, it would have to be something other people would use for it to be worth it 😆

**Comment by nicoddemus** [comment]
A repository which can people submit their repositories as PRs, and configure which files need updating.

A heroku account with a cron job once a year downloads that repository, and goes over all repositories opening PRs.

Heh sounds like a fun project. 😁

**Comment by bmwiedemann** [comment]
Except that you do not even have to update this yearly. Just every 70+ years.
So the bot task would be rather moot.

**Comment by blueyed** [comment]
The copyright year is not necessary, see http://www.contentious.com/2007/01/07/copyright-notice-is-the-year-really-necessary/ (via https://github.com/davidhalter/parso/pull/25).

**Comment by nicoddemus** [comment]
Thanks for the research @blueyed. If nobody opposes, I'm OK with changing it.

**Pull request merged**
