### PR TITLE
Preparing release version 3.8.2

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by asottile** [comment]
travis is confused :S

**Comment by RonnyPfannschmidt** [comment]
not really, distributed systems 101 is calling dibbs

**Comment by asottile** [comment]
:tada:

**Comment by nicoddemus** [comment]
🎉

**Comment by nicoddemus** [comment]
Don't forget the tweet! 😁

**Comment by asottile** [comment]
~o/ yep wouldn't forget that!  I think I finally got the mailing lists stuff sorted out.  I needed to _send_ from the same email I signed up with (including the `+pytest@` bit!)

**Comment by asottile** [comment]
https://twitter.com/codewithanthony/status/1047230193193037824 for that!

**Pull request merged**
