### PR TITLE
Issue: 3103 - Fix UsageError raised when specifying config override options followed by test path

### PR DESCRIPTION
**Pull request by arcoyle**
Thanks for submitting a PR, your contribution is really appreciated!

Here's a quick checklist that should be present in PRs:

- [x] Add a new news fragment into the changelog folder
  * name it `$issue_id.$type` for example (588.bugfix)
  * if you don't have an issue_id change it to the pr id after creating the pr
  * ensure type is one of `removal`, `feature`, `bugfix`, `vendor`, `doc` or `trivial`
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."
- [x] Target: for `bugfix`, `vendor`, `doc` or `trivial` fixes, target `master`; for removals or features target `features`;
- [x] Make sure to include reasonable tests for your change if necessary

Unless your change is a trivial or a documentation fix (e.g.,  a typo or reword of a small section) please:

- [x] Add yourself to `AUTHORS`, in alphabetical order;

### CODE REVIEW

**Comment by arcoyle** [comment]
https://github.com/pytest-dev/pytest/issues/3103

**Comment by nicoddemus** [comment]
Thanks @arcoyle for the PR!

Great work, just took the liberty of improving the test and changelog entry a bit.

**Comment by nicoddemus** [comment]
While playing with it I realized that the problem lies a little deeper.

The `-o` option is configured with `nargs='*'`, but this means that any argument after `-o` will be swallowed by it, even if it is a test path:

```
pytest -o foo=1 bar=1 /path/to/test
```

In this case `-o` will contain `["value=1", "bar=1", "/path/to/test"]` which is clearly not we want.

I don't see any way to fix this other than changing how the command line is parsed, so each option must be passed with `-o` as well:

```
pytest -o foo=1 -o bar=1 /path/to/test
```

I have some local changes that I intend to push to this branch to fix this, meanwhile let's keep it on hold.

**Comment by arcoyle** [comment]
@nicoddemus 
Well spotted i didn't take into account the affect of that. Lesson learned for me. I'll keep an eye out for other issues to help on where possible. Thanks for the help on this one!

**Comment by nicoddemus** [comment]
> Well spotted i didn't take into account the affect of that.

Not at all, that bug has always been there since the introduction of `-o`. 😬 

> I'll keep an eye out for other issues to help on where possible.

Awesome, thanks!

**Comment by nicoddemus** [comment]
Superseded by #3147: I had to rebase this on `features` and change the target so it seemed more appropriate to open a new PR, but I did keep the history intact.

Thanks @arcoyle and @atoolan for tackling this in the first place!

**Pull request closed without merging**
