### PR TITLE
pytest.mark in classes marks methods defined in the class body only

### LINKED ISSUE #725: Markers are transferred from subclasses to base class methods
Originally reported by: **BitBucket: [foobarbazquux](http://bitbucket.org/foobarbazquux), GitHub: [foobarbazquux](http://github.com/foobarbazquux)**

----------------------------------------

pytest transfers markers from subclasses to base class methods, which can result in incorrect test selection.

Example code:
```
#!python
import pytest

class BaseClass():
    def test_foo(self):
        pass

@pytest.mark.test1
class Test1(BaseClass):
    def test_test1(self):
        pass

@pytest.mark.test2
class Test2(BaseClass):
    def test_test2(self):
        pass
```

Example run showing the `test1` marker also being applied to the `Test2` base class:
```
$ py.test -v --collect-only -m test1
================================================================================ test session starts ================================================================================
platform darwin -- Python 2.7.8 -- py-1.4.26 -- pytest-2.6.4 -- /usr/local/opt/python/bin/python2.7
collected 4 items
<Module 'test_example.py'>
  <Class 'Test1'>
    <Instance '()'>
      <Function 'test_foo'>
      <Function 'test_test1'>
  <Class 'Test2'>
    <Instance '()'>
      <Function 'test_foo'>

======================================================================== 1 tests deselected by "-m 'test1'" =========================================================================
=========================================================================== 1 deselected in 0.01 seconds ===========================================================================
```

More detail from `ronny` via IRC:
```
1:52 ronny joesmith: ah, i figured the bug
1:52 ronny hpk: marker transfer to base class test methods fails
1:52 ronny joesmith: we have a mechanism that transfers test markers from the classes to the methods
1:53 ronny joesmith: due to a misstake they trasnfer subclass markers to base class methods
1:53 ronny can you report a issue, i think we can issue a fix this weekend
1:55 ronny hpk: markers on a subclass transfer to a base class method
1:57 ronny https://bitbucket.org/pytest-dev/pytest/src/tip/_pytest/python.py#cl-351 is the "bad" call site
1:58 ronny and https://bitbucket.org/pytest-dev/pytest/src/tip/_pytest/python.py#cl-437 is the implementation
2:01 ronny hpk: its not an easy fix ^^
2:02 ronny hpk: as far as i can tell marker transfer should be part of the marker plugin and the item marker set should be detached from the per object markers
2:03 ronny its a minor restructuring but it has external facing api implications
```

----------------------------------------
- Bitbucket: https://bitbucket.org/pytest-dev/pytest/issue/725

### PR DESCRIPTION
**Pull request by nicoddemus**
Fix #725

### CODE REVIEW

**Comment by nicoddemus** [comment]
Hmm didn't realize it but this change breaks the test case for #265 (as it is related to nose, I didn't have that installed when I ran in my virtual environment).

The test case which fails is this:

```python
import pytest

        class TestGeneric(object):
            def test_nothing(self):
                """Tests the API of the implementation (for generic and specialized)."""

        @pytest.mark.skipif("True", reason=
                    "Skip tests to check if teardown is skipped as well.")
        class TestSkipTeardown(TestGeneric):

            def setup(self):
                """Sets up my specialized implementation for $COOL_PLATFORM."""
                raise Exception("should not call setup for skipped tests")

            def teardown(self):
                """Undoes the setup."""
                raise Exception("should not call teardown for skipped tests")
```

Because this PR precisely changes the semantics of the markers applied to classes using decorators. 

I feel the behavior implemented in this PR is less surprising as #725 demonstrates, but it will certainly break test suites which rely on the previous behavior.

@hpk42 and @RonnyPfannschmidt, any thoughts?

**Comment by nicoddemus** [comment]
Btw, I just realized the original poster's example doesn't make sense, as because if a subclass decided to skip all its tests because `$COOL_PLATFORM` is not available, then all tests for all other subclasses would be skipped as well.

**Comment by RonnyPfannschmidt** [comment]
the fix makes the breakage worse

the problem is that markers are applied to a function object instead of being collected on the item

its absolutely correct that class scoped markers of a subclass get applied to inherited methods
however its absolutely incorrect that those get applied to the method thats located on the base class

**Comment by nicoddemus** [comment]
> its absolutely correct that class scoped markers of a subclass get applied to inherited methods
however its absolutely incorrect that those get applied to the method thats located on the base class

Hmm but that's what the PR does, it only applies the markers to the functions defined in the class dict (which does not take in account superclasses).

```python
    # transfer markers from class decorators only if the method is defined
    # in the class itself
    if cls is not None and funcobj.__name__ in cls.__dict__:
        transfer(cls)
```

Or am I missing something?

**Comment by RonnyPfannschmidt** [comment]
Inherited methods are collected on subclasses, those items must receive the markers even tho they are defined in subclasses

**Comment by RonnyPfannschmidt** [comment]
perhaps we could put a descriptor into the subclasses that will carry along the mark decorators and help invoking the original method

**Comment by nicoddemus** [comment]
I'm not sure I understand your points... :sweat_smile:

To clarify things, let's consider:

```python
class A:
    def test_A(): pass

@pytest.mark.M
class B(A):
    # inherits A.test_A
    def test_B1(): pass
    def test_B2(): pass

class C(B):
    # inherits A.test_A
    def test_B1(): pass # overrides B.test_B1
    # inherits B.test_B2
```

**Current behavior**

The following functions end up having `M` applied to them:

```
A
  .test_A

B
  .test_A
  .test_B1
  .test_B2

C
  .test_A
  .test_B2
```

So class markers apply the marks to all the functions found in a class during class creation, including functions defined in **upperclasses**.

**Behavior implemented in this PR**

The following functions end up having `M` applied to them:

``` 
B
  .test_B1
  .test_B2

C
  .test_B2
```

So class markers apply marks to all functions found in the class **body** at the time of class creation only. Subclasses which don't explicitly override functions will inherit the same markers (that's why `C.test_B1` doesn't have a mark, it is overwritten in `C`).

I find the behavior implemented in this PR much less surprising, as it follows usual python inheritance rules. Nobody expects that a change in a function in a subclass to affect functions in the upperclass, but it's natural for changes in superclasses to affect subclasses, don't you agree?

Or do you have something else in mind, like review how markers in general are handled? If that's the case, either way IMO the new behavior is less surprising anyway and a major overhaul of how makers are handled are the scope of another PR.

**Comment by RonnyPfannschmidt** [comment]
expected behavior should be:

```
B
  .test_A
  .test_B1
  .test_B2

C
  .test_A
  .test_B2
```

**Comment by nicoddemus** [comment]
I see what you mean, thanks.

Do you think this should be tackled in this PR, or should be a separate task? I prefer the former, because I think as it is the PR is an improvement already.

**Comment by RonnyPfannschmidt** [comment]
i think it should happen in this pr, however the current state of this pr is bound to break things for users

**Comment by nicoddemus** [comment]
As discussed, a better solution is proposed in #891.

**Pull request closed without merging**
