### PR TITLE
don`t parse compat properties as fixtures

### LINKED ISSUE #2701: warning filters incorrectly apply for conftests and collection in pytester
#2696 uncovered that pytest invocations with selected warning filters dont pass trough to the nested pytest correctly, in turn making tests even with the filter fail at importing a conftest and running a collection

CC @nicoddemus

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
Fix #2701 

its tricky to trigger those warnings under normal circumstances as they happen before pytest hooks into the warnings system

`python -W always -m pytest testing/test_tmpdir.py --collectonly` could be used to trigger them for example on the cli

### CODE REVIEW

**Comment by nicoddemus** [comment]
Hi @RonnyPfannschmidt, this seems to be working fine, why is it a RFC? Seems like it gets rid of the warnings about compat-properties during fixture collection quite nicely. 👍

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus mainly because i skipped on tests and the docs

**Comment by nicoddemus** [comment]
Oh OK, I was under an erroneous definition of what `RFC` meant. 😁

**Comment by RonnyPfannschmidt** [comment]
no, i was ^^

**Pull request merged**
