### PR TITLE
bugfix in ApproxNumpy initialisation, use keywords for arguments to fix

### PR DESCRIPTION
**Pull request by abrammer**
With respect to #3695 , flip the arguments in the initialization and also use keywords so it's more obvious and less likely to happen in future.  

Can add tests along the lines of the code in #3695 if desired but it seems like an obvious typo fix

### CODE REVIEW

**Comment by asottile** [comment]
Let's add a quick test since the current code doesn't actually ensure `ApproxNumpy` works

**Comment by abrammer** [comment]
You think add a test to check tolerances, or just make the current tests such that abs & rel tolerances aren't equivalent.  I can push a commit either way this eve.

**Comment by asottile** [comment]
Anything that fails before your change and passes afterwards. Either approach is fine though the "different params" one is what I'd probably go for.

**Comment by abrammer** [comment]
Something else is broken here.  I typo'd the last rel argument, so it's 10% instead of 1%.  
Fixing the typo means that it fails though, which doesn't make sense as 99 is obviously within 1% of 100.

**Comment by abrammer** [comment]
Justification for f0db64a:

currently pytest will calculate the tolerances against either value if it's a numpy array. 
`np.array(1e7) == pytest.approx(1, abs=1)`

The above will pass a test in 3.6.4.  With the earlier commits 
`np.array(1e7) == pytest.approx(1, rel=1)`
would still pass a test.  

Unless I'm missing something the approx should be 1±1 therefore it should be wrong. 
I have stripped out the repeat ApproxNumpy() initilsiation at 
https://github.com/pytest-dev/pytest/blob/b7419bd9bb2ad5b609532766ceb77e7b732e1dcf/src/_pytest/python_api.py#L214
to handle this.  This may not elegantly handle nans but should just fail.   All current tests pass.

**Comment by kalekundert** [comment]
The extra ``ApproxNumpy`` initialization was there to properly handle corner-cases involving ``nan`` and ``inf``.  In particular, the ``nan_ok`` option will be ignored without it.  That said, looking back at this code now, the extra ``ApproxNumpy`` initialization was also broken because it switched the "actual" and "expected" values, which would cause relative tolerances to be calculated incorrectly.

I think the best way to write this line would be like this:

        if _is_numpy_array(actual):
            return all(a == self for a in actual)

Thanks for the PR and the tests (clearly this code needs more tests)!

**Comment by nicoddemus** [comment]
Thanks @kalekundert for the suggestion! I implemented it myself, I think we can merge this for now, it has been waiting here long enough. I encourage others to open PRs later to improve the tests if needed! 👍

**Comment by abrammer** [comment]
I have changes and tests coming, away from my computer for a couple days so will update with respect to the @kalekundert and tests on Sunday.

**Comment by nicoddemus** [comment]
@abrammer sure think, let's wait for you to get around to this then! Thanks a lot for following up with this. 👍

**Comment by tadeu** [comment]
Just brainstorming, but it would be less errorprone to maintain if all corner cases are tested (it's hard to remember all corner cases when maintaining the code):

* 0-d, 1-d, 2-d
* common values, nan, inf
* check for `rel` only (equality and inequality); cases where `abs` would fail
* check for `abs` only (equality and inequality); cases where `rel` would fail
* no numpy array, numpy array on left-side, numpy array on right-side, numpy array on both sides
* pytest.approx on left-side, pytest.approx on right side
* relative tolerance that would fail if sides are switched

Perhaps an approach with `parametrize` would be helpful.
I could work on this if you think it's useful (would it be another issue?)

**Comment by abrammer** [comment]
@tadeu I think the tests I put in cover most of those cases.   Pulled logic from earlier tests, though maybe a decorator method could be better?

I was going to suggest np.at_least1d(actual) with respect to bf127a6, might be a little more memory efficient but probably doesn't matter for tests.

**Comment by kalekundert** [comment]
Looks good to me.  I think one of ``flat``, ``flatten()``, or ``ravel()`` is needed to handle comparisons with multidimensional arrays, and my understanding is that ``flat`` just makes an iterator and doesn't copy anything.  But I haven't really thought about it that carefully.

**Comment by abrammer** [comment]
Yeah you're right. Flatten copies, flat just iterates. Nice.

**Comment by tadeu** [comment]
@abrammer, awesome improvement on the tests ;)

**Pull request merged**
