### PR TITLE
fix #10447 - consider marks in reverse mro order to give base classes priority

### LINKED ISSUE #10447: Parent class marked fixture no longer reached with pytest 7.2
Starting with the release of pytest 7.2, the distutils tests started failing (https://github.com/pypa/distutils/issues/186).

I read the [changelog for 7.2](https://docs.pytest.org/en/stable/changelog.html#pytest-7-2-0-2022-10-23), but I don't see anything relevant.

The issue is likely due to some of these factors:

- the [test class is a subclass](https://github.com/pypa/distutils/blob/6c39b5053c17ec41690dab9d11399e2f39389892/distutils/tests/test_build_ext.py#L87) of [another class](https://github.com/pypa/distutils/blob/6c39b5053c17ec41690dab9d11399e2f39389892/distutils/tests/support.py#L15)
- both classes are marked with `usefixtures`
- The fixture on the subclass is reliant on the prior execution of the fixture in the parent class.

See the upstream bug for:

- [x] a detailed description of the bug or problem you are having
- [x] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions

For consideration:
- [x] minimal example if possible

I haven't put together a minimal example yet as I'm still triaging the issue. Is there a known change with pytest 7.2 that was expected to change this behavior?

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**

### CODE REVIEW

**Review by jaraco — APPROVED** [review]

**Comment by jaraco** [comment]
I've confirmed that this change also addresses the test failures originally encountered in pypa/distutils#186.

**Comment by suewonjp** [comment]
@RonnyPfannschmidt 
Thank you for the work from pytest team.

This fix was merged a long time ago, but has not been included in any of the latest releases.
Can you let us know when we can have the fix?

Thank you.

**Comment by nicoddemus** [comment]
Hi @suewonjp,

While this is a bug fix and it seems it was attempted to backport for 7.3.x (due to its label), it seems it never was ported in the end (not sure why).  

This will be released on pytest 7.5 or more likely 8.0 (#11126), but we don't have a timeline for that yet.

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt do you recall why this was not backported in the end? Just for recording purposes.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i believe i missed the failure of the back-porting process

**Comment by nicoddemus** [comment]
Oh in that case let's try to backport again, then it might go out in the next 7.4.x release.

**Comment by nicoddemus** [comment]
#11545 🎉

**Comment by nicoddemus** [comment]
7.4.3 released which includes this fix. 👍

**Pull request merged**
