### PR TITLE
make --doctest-glob multi-allowed

### PR DESCRIPTION
**Pull request by jab**
Tested manually and works like a charm. Still needs automated tests and docs updates, but wanted to get the ball rolling. Can I pass this back to a maintainer to get the rest landed? Thanks in advance.

#1242

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks! :smile:

I wonder if this should land into `features` thought. It is a minor change, but still it would be weird for users that need this feature to need to depend on `>=2.8.5`.

Opinions?

**Comment by jab** [comment]
(I don't know what your question means but maybe it was intended for fellow maintainers)

**Comment by nicoddemus** [comment]
Ops sorry @jab, yes, it was for other maintainers :grin:

**Comment by RonnyPfannschmidt** [comment]
at first glance this looks like it contains a few behavior changes for the single argument case
more deep review is needed, i suspect a few missing tests

**Comment by The-Compiler** [comment]
I agree it should go to `features`.

**Comment by RonnyPfannschmidt** [comment]
Closing as #1297 got merged

**Pull request closed without merging**
