### PR TITLE
replay initial warnings when terminalreporter is loaded

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
this will replay all early warnings using the pytest_logreport hook

that way warnings no longer can get lost (happens for the planned early cache warnings)

### CODE REVIEW

**Comment by nicoddemus** [comment]
Hmmm the patch seems strange to me, `PytestPluginManager.pytest_plugin_registered` has intimate knowledge about `terminalreporter`. 

Perhaps it would be better to just accumulate all warnings into a  `config.warnings` list instead? On `PytestPluginManager.pytest_plugin_registered` the warnings list would be passed over to the `pytestconfig` plugin and set to `None`. This way `terminalreporter` and `helpconfig` can easily access the list when appropriate.

**Comment by RonnyPfannschmidt** [comment]
The problem is properly invoking the logreport hook for all warnings

Perhaps it's best to make the hook itself historic

**Comment by nicoddemus** [comment]
> Perhaps it's best to make the hook itself historic

I'm not familiar on how historic hooks work, but if it will save you from implementing this "playback previous calls to the hook" yourself then certainly seems like the way to go! :smile:

**Comment by RonnyPfannschmidt** [comment]
the plugin-manager will now replay for each new registered plugin

**Comment by nicoddemus** [comment]
So basically you just have to mark `pytest_logwarning` as `historic`, right? Cool. :sunglasses:

**Comment by RonnyPfannschmidt** [comment]
i already did ^^ and adapted the calls

**Comment by nicoddemus** [comment]
Oh I didn't noticed. Looks :+1: to me! :smile:

**Pull request merged**
