### PR TITLE
Preparing release version 5.2.3

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Not sure, but travis seems to have missed my update, but the previous commit passed fine so I think we're good to go here.

**Comment by blueyed** [comment]
> Not sure, but travis seems to have missed my update

Because of "[skip ci]".. ;)

> but the previous commit passed fine so I think we're good to go here.

:+1:

**Comment by nicoddemus** [comment]
Rá duh

**Comment by nicoddemus** [comment]
Oh no, this will probably cause it to also skip the deploy when I push the tag... will have to ammend I'm afraid. 😓

**Pull request merged**
