### PR TITLE
Added Akhilesh Ramakrishnan to AUTHORS

### PR DESCRIPTION
**Pull request by akhilramkee**
#10337, #10338

### CODE REVIEW

**Comment by akhilramkee** [comment]
cc @nicoddemus. Thanks!

**Comment by The-Compiler** [comment]
Thanks @akhilramkee! While you're at it, could you fix a small typo in [changelog/10337.bugfix.rst](https://github.com/pytest-dev/pytest/pull/10338/files#diff-76599d2beebc52fab5b8cfed70b8e5c4d29552878ac6f74341e9fa92b078c9e5) please?

> Fixed **but** that fake intermediate modules generated by ``--import-mode=importlib`` would not include the child modules as attributes of the parent modules.

I don't think that "but" there makes sense.

**Comment by akhilramkee** [comment]
> could you fix a small typo in [changelog/10337.bugfix.rst](https://github.com/pytest-dev/pytest/pull/10338/files#diff-76599d2beebc52fab5b8cfed70b8e5c4d29552878ac6f74341e9fa92b078c9e5) please?

Sure!

**Review by The-Compiler — APPROVED** [review]

**Comment by The-Compiler** [comment]
Thank you!

**Pull request merged**
