### PR TITLE
Minor: help / direct usage of config

### PR DESCRIPTION
**Pull request by blueyed**
No changelog(s).

### CODE REVIEW

**Comment by blueyed** [comment]
btw: changed the GitHub setting for this repo to deleted head branches now.

> After pull requests are merged, you can have head branches deleted automatically.

> Automatically delete head branches  
> Deleted branches will still be able to be restored.

**Comment by nicoddemus** [comment]
Oh I was under the impression that was set already.

**Comment by blueyed** [comment]
No, but it is also new, isn't it?  (just noticed this the other day myself)

**Comment by nicoddemus** [comment]
Yeah, for a couple of weeks or so

**Pull request merged**
