### PR TITLE
Implement a linear algorithm in the `recursionindex` function

### PR DESCRIPTION
**Pull request by kri-k**
See https://github.com/pytest-dev/pytest/issues/8482#issuecomment-835841190

### CODE REVIEW

**Comment by bluetech** [comment]
Hmm, that's interesting.

If I understand correctly, the algorithm relies on the fact that the last frame is part of the loop:

> Finding beginning of the loop: such n that frames[n] equals to the last_frame

But I don't think this holds. Suppose the loop is:

    a -> b -> c -> a -> b -> c -> ....

Now suppose that `a`, before calling `b`, does some other work, i.e. the call stack progresses like this:

```
a
a -> aa
a -> aa -> aaa
a -> aa
a
a -> b
<loop>
```

Then it might happen that the recursion limit is hit right when we're at `aa` or `aaa` which are not part of the loop.

**Comment by kri-k** [comment]
> Now suppose that `a`, before calling `b`, does some other work
>...
> Then it might happen that the recursion limit is hit right when we're at `aa` or `aaa` which are not part of the loop.

If I understand correctly, you mean that if traceback will have the following frames `a -> aa -> aaa` when `RecursionError` happens, then the proposed algorithm will not be able to find the cycle.

It seems to me that this behavior is correct, because at the time of the exception raised, the program has not yet reached the execution of an infinite loop. So, we should not show warning `!!! Recursion detected (same locals & position)` (also, maybe we should clarify this message and write about _infinite_ recursion?)

And, in this situation, I believe, we can't predict existence of the loop `a -> b -> c -> a ...` without explicitly further code execution :)

**Comment by bluetech** [comment]
I'm thinking of something like this:

```py
def a():
  aaa(20)
  b()

def aaa(n):
   if n == 0:
       return
   aaa(n - 1)

def b():
   c()

def c():
   a()
```

The loop here is `a -> b -> c -> a`, but the `RecursionError` is very likely to hit at something like `a -> b -> c -> a -> ... -> a -> aaa -> aaa -> aaa -> aaa`, and the `last_frame` here is not part of the loop.

I didn't try it though so might be missing some detail.

**Comment by kri-k** [comment]
> The loop here is `a -> b -> c -> a`, but the `RecursionError` is very likely to hit at something like `a -> b -> c -> a -> ... -> a -> aaa -> aaa -> aaa -> aaa`, and the `last_frame` here is not part of the loop.

Oh, I get it, thanks.

This particular example will not work because algorithm will group all frames by [position](https://github.com/pytest-dev/pytest/pull/8651/files#diff-ac2099a172465905236568f8c175328fb75ebc1b80ce39f4799e61373d355418R422) first.

But you're right, here is another example that fails my code:
```python
def b(n):
    a(n)  # position A

def a(n):
    if n == 0:
        b(1)
        b(0)
    if n == 3:
        return
    b(n + 1)
```

Here, for position `A`, we can have the following list of frames: `a(0) -> a(0) -> ... -> a(0) -> a(1) -> a(2) -> a(3)`.

**Pull request closed without merging**
