### PR TITLE
Added logging-level link to logging level table

### PR DESCRIPTION
**Pull request by FIOpwK**
This PR adds a link to the log level table for quick look up of all logging options.

### CODE REVIEW

**Comment by FIOpwK** [comment]
Addresses Issue [9540](https://github.com/pytest-dev/pytest/issues/9540)

**Review by The-Compiler — CHANGES_REQUESTED** [review]
Thanks for the contribution! However, I don't think the location at the end of the file makes much sense: The preceding

> More details about the discussion that lead to this changes can be read in
￼issue #3013

Is referring to the "Incompatible changes in pytest 3.4" heading, while this is clearly unrelated to that. I doubt anyone reading the text and wondering about logging levels would find it there.

Further above under "Live Logs" (which is I think you were referring to in the issue) there are two places saying *This setting accepts the logging level names as seen in python's documentation*. What do you think about turning "in python's documentation" into a link instead?

Finally, it would be good if you could retarget this to the `main` branch instead - while docs are (currently) served from 6.2.x, we always fix things in `main` and then backport the changes to maintenance branches.

**Comment by FIOpwK** [comment]
#What do you think about turning "in python's documentation" into a link instead?

I must've overlooked that line. It does make more sense in that location. Thanks for pointing that out. Further, I didn't know opening a PR on main was how things were done in this project. Good to know.

**Comment by FIOpwK** [comment]
@The-Compiler, 'doubt' is measure there, sure. If  not the `python's documentation` then `logging level` or `logging level names` ? I moved before this discussion was truly resolved. Checking myself in for it.

**Comment by FIOpwK** [comment]
I say logging level to keep the theme of what the text is about. Yes, the link is specific to python's documentation and deserves to be included if mentioned I guess. The logging level text *is* what that documentation references.

**Comment by The-Compiler** [comment]
Closing this in favor of #9575 (which is against the correct branch) - let's continue this there!

**Pull request closed without merging**
