### PR TITLE
Remove duplicated changelog entry for 5.3.1

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by blueyed** [comment]
@nicoddemus 
Just out of curiousity: why haven't you amended the existing PR where I've pointed that out already?  (https://github.com/pytest-dev/pytest/pull/6277#discussion_r350439167)
(now the tag has the wrong changelog)

Also just re-generating the release-PR would have avoided conflicts with https://github.com/pytest-dev/pytest/pull/6272, which came before already  (which you now have to resolve manually).
I am just trying to understand your workflow there..

**Comment by nicoddemus** [comment]
Sorry @blueyed, my bad. As you said it probably would have been easier to just generate the release branch again. As per https://github.com/pytest-dev/pytest/pull/6272#issuecomment-559079746, I will open a new PR implementing your suggestion (it would be nice if you ressuciated this branch though: https://github.com/blueyed/pytest/tree/docs).

**Comment by blueyed** [comment]
@nicoddemus restored the branch (JFI: typically it should also work by restoring it using the commit hash, but not sure if that is fetchable for you etc)

**Comment by nicoddemus** [comment]
> JFI: typically it should also work by restoring it using the commit hash, but not sure if that is fetchable for you etc

Yeah I wasn't sure if it would be reachable for me, even if I fetched your fork. Thanks for restoring it. 👍

**Pull request merged**
