### PR TITLE
Temporarily pin pluggy on master

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by asottile** [comment]
> But we also appear to have new / flaky failures on features..?!

link? I haven't seen any

**Comment by blueyed** [comment]
Only https://travis-ci.org/pytest-dev/pytest/builds/537992776 apparently (via https://travis-ci.org/pytest-dev/pytest/branches).  That is the pypy3-spamming one, so might be unrelated then.

:shipit:

**Comment by asottile** [comment]
we'll need to make sure to revert this on features when we merge the two

**Comment by nicoddemus** [comment]
Thanks @asottile!

**Pull request merged**
