### PR TITLE
cache the pre-commit environment

### LINKED ISSUE #3502: optimize travis builds
followup to #3485

we should reduce the build time for travis builds,
il## investigate the speed for the linting env and various others as well

### PR DESCRIPTION
**Pull request by asottile**
Resolves #3502

### CODE REVIEW

**Comment by asottile** [comment]
note: this will change the job name so we'll need to adjust this in the repository settings

**Comment by nicoddemus** [comment]
IMOHO this is not really necessary... `linting` is always one of the first jobs to finish, as far as I see, since we moved to GitHub actions.

**Comment by asottile** [comment]
> 
> 
> IMOHO this is not really necessary... `linting` is always one of the first jobs to finish, as far as I see, since we moved to GitHub actions.

finishing quickly can open up another parallel runner.  also saves some bandwidth / flakiness with clones 🤷

**Comment by nicoddemus** [comment]
Yeah you got a point. 👍

**Pull request merged**
