### PR TITLE
Avoid installing incompatible more-itertools

### PR DESCRIPTION
**Pull request by ssbarnea**
Note: this needs backporting to latest version of pytest that supports
python2.7 in order to be of practical use.

Fixes: #5854

### CODE REVIEW

**Comment by Zac-HD** [comment]
It looks like [`more-itertools` already specifies its `python-requires` version](https://github.com/erikrose/more-itertools/blob/0d97c55616fb9563be69fdeeda13bf4038834b7c/setup.py#L32), so this should not be a problem if you first update `pip`!

I think "advise users to update `pip`" is a better solution, as they will need to do so anyway - or manually specify upper version bounds on more and more transitive dependencies, I guess.

**Comment by RonnyPfannschmidt** [comment]
its probably sensible to add this to the python2.7 version only,
we absolutely shouldn't have it in the python3 only version however

while updating pip is certainly a better solution, i believe that the people/projects stuck on old python are likely in a situation where a pip update may actually be delayed for similar strategic reasons

and while i don't agree with such strategy, we still can ease the life of those that are subject to it

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt the change proposed here is already on `4.6-maintenance`:

https://github.com/pytest-dev/pytest/blob/f2d87dcf6ce735796f06e70a66cc72a5e7a7a8ae/setup.py#L11-L12

**Comment by ssbarnea** [comment]
Thanks! Sadly we will see more of these in the future, with a big spike in January.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i see, thanks

**Pull request closed without merging**
