### PR TITLE
docs: enable Sphinx nitpicky mode

### PR DESCRIPTION
**Pull request by bluetech**
See:
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-nitpicky

This ensures we have no more broken references.

### CODE REVIEW

**Review by Pierre-Sassoulas — APPROVED** [review]
Just learned about something today 😄 The removal of ``_non_numeric_type_error`` seems unrelated to sphinx nitpickyness, right ?

**Comment by RonnyPfannschmidt** [comment]
some of the changes look like something that ought to be a correct link any idea if those are actually fixable?

**Comment by bluetech** [comment]
@Pierre-Sassoulas 

> The removal of _non_numeric_type_error seems unrelated to sphinx nitpickyness, right ?

Yep, it's unrelated.

@RonnyPfannschmidt 

> some of the changes look like something that ought to be a correct link any idea if those are actually fixable?

Which of the changes?

**Comment by RonnyPfannschmidt** [comment]
Apologies, upon reading again i realized those are the intentionally broken refs to local path details

**Review by nicoddemus — APPROVED** [review]

**Pull request merged**
