### PR TITLE
use the travis cache for pip

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**

### CODE REVIEW

**Comment by The-Compiler** [comment]
[The docs](https://docs.travis-ci.com/user/caching/#pip-cache) says it's `cache: pip` - are you sure this works as well?

**Comment by RonnyPfannschmidt** [comment]
as far as i know we need to add a few extra directories anyway, since the travis guys lag behind python cache folders

**Comment by nicoddemus** [comment]
Are you sure @RonnyPfannschmidt? Because the [build time](https://travis-ci.org/pytest-dev/pytest/builds/108355095) of your change is 13m7s, while the [build time](https://travis-ci.org/pytest-dev/pytest/builds/108494122) for `master` currently is 6m47s...

I think the problem is the second method suggested in the docs should be used instead:

```yaml
cache:
  directories:
    - $HOME/.cache/pip
```

because we do override the install section in the travis file.

**Comment by RonnyPfannschmidt** [comment]
will retry at a later point in time

**Pull request closed without merging**
