### PR TITLE
Document that Parser.addini() can take, and defaults to, 'string'

### PR DESCRIPTION
**Pull request by altendky**
- [X] Include documentation when adding new features.
- [x] Include new tests or update existing tests when applicable.
- [X] Allow maintainers to push and squash when merging my commits. Please uncheck this if you prefer to squash the commits yourself.

If this change fixes an issue, please:

- [x] Add text like ``closes #XYZW`` to the PR description and/or commits (where ``XYZW`` is the issue number). See the [github docs](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more information.

Unless your change is trivial or a small documentation fix (e.g., a typo or reword of a small section) please:

- [x] Create a new changelog file in the `changelog` folder, with a name like `<ISSUE NUMBER>.<TYPE>.rst`. See [changelog/README.rst](https://github.com/pytest-dev/pytest/blob/master/changelog/README.rst) for details.

  Write sentences in the **past or present tense**, examples:

  * *Improved verbose diff output with sequences.*
  * *Terminal summary statistics now use multiple colors.*

  Also make sure to end the sentence with a `.`.

- [x] Add yourself to `AUTHORS` in alphabetical order.

### CODE REVIEW

**Comment by altendky** [comment]
I'm going to changelog this as a doc change though it does touch on actual code in a spot too.  I'm glad to adjust that if it is felt it is appropriate.

**Comment by altendky** [comment]
For linkage, follows from https://github.com/python-trio/pytest-trio/pull/105/files/f2ab69293ce54a6b703a554b997576f965c1f9cc#r497969241.

**Review by nicoddemus — APPROVED** [review]
Thanks @altendky!

**Comment by saper** [comment]
It is not only a doc change, it actually makes the use of "string" possible. 

With pytest 6.1.2, using `string` causes an AssertionError like https://github.com/agronholm/anyio/issues/1028

**Pull request merged**
