### PR TITLE
Fail ignore xfail

### PR DESCRIPTION
**Pull request by cielavenir**
Thanks for submitting a PR, your contribution is really appreciated!

Here's a quick checklist that should be present in PRs (you can delete this text from the final description, this is
just a guideline):

- [x] Create a new changelog file in the `changelog` folder, with a name like `<ISSUE NUMBER>.<TYPE>.rst`. See [changelog/README.rst](/changelog/README.rst) for details.
- [ ] Target the `master` branch for bug fixes, documentation updates and trivial changes.
- [x] Target the `features` branch for new features and removals/deprecations.
- [x] Include documentation when adding new features.
- [x] Include new tests or update existing tests when applicable.

Unless your change is trivial or a small documentation fix (e.g.,  a typo or reword of a small section) please:

- [x] Add yourself to `AUTHORS` in alphabetical order;

### CODE REVIEW

**Comment by cielavenir** [comment]
The test architecture is like this (sorry for very pseudo code; we cannot show all):

```
def framework():
  framework = our_library.load_framework()
  yield framework
  our_library.destroy()

@pytest.mark.xfail
def test_computation1(framework):
  result,valueLists = framework.compute(EXPRESSION1)
  if result!='Success':
    pytest.fail(ignore_xfail=True) # we still need to make sure the result is Success
  for (valueList,check_func) in zip(valueLists,[checkA,checkB,checkC]):
    assert check_func(valueList) # not all asserts are passing currently, so we need xfail...

def test_computation2(framework):
  result,valueLists = framework.compute(EXPRESSION2)
  assert result=='Fail' # We expect EXPRESSION2 to Fail, so putting framework.compute into fixture is not our preference.
```

**Comment by cielavenir** [comment]
I have given you the use case @RonnyPfannschmidt ...

**Comment by RonnyPfannschmidt** [comment]
sorry for the delay and thanks for the ping

it got me thinking a bit further and i do wonder if pytest.xfail should respect outcome exceptions in all cases
(so a pytest.fail should pass into the test outcome even if there is a xfail mark in general

@nicoddemus please give some input on this as well

should we merge this i would like to set it as experimental for now

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt TBH I've been absent from this thread because I don't understand the requirement at all.

It seems like a bad idea because I can't even explain it easily:

> Pass `ignore_xfail=True` to pytest.xfail() to force tests marked with @pytest.mark.xfail to actually FAIL instead of XFAIL.

It might be just me, but this just feels weird to have that option in `pytest.xfail`. 

Since this is such an edge case, can't it be controlled from within the test instead?

```python
def test_computation1(framework):
    result,valueLists = framework.compute(EXPRESSION1)
    if result!='Success':
        pytest.fail() # we still need to make sure the result is Success
    try:  
        for (valueList,check_func) in zip(valueLists,[checkA,checkB,checkC]):
            assert check_func(valueList) # not all asserts are passing currently, so we need xfail...
    except AssertionError:
        pytest.xfail('flaky or something')     
```

**Comment by cielavenir** [comment]
The problem is actually the latter code is longer but the (shorter) former part executes longer.

Actually I solved the issue locally: https://github.com/cielavenir/pytest-forcefail/blob/master/pytest_forcefail.py

Removed potentially sensitive stuff and closing this. Thank you.

**Comment by nicoddemus** [comment]
Thanks @cielavenir for letting us know about your solution and plugin.

**Pull request closed without merging**
