### PR TITLE
ci: remove numpy/trial envs

### PR DESCRIPTION
**Pull request by blueyed**
Just test/install this with all envs.

Ref: https://github.com/pytest-dev/pytest/pull/4848#issuecomment-467909811

### CODE REVIEW

**Comment by blueyed** [comment]
@nicoddemus 
Forgot one, but would we need this for all envs then?
https://github.com/blueyed/pytest/blob/8f12ca7a40f00eda856cf27b45b98b27e43413a3/azure-pipelines.yml#L35

Maybe don't run it on Windows?

**Comment by nicoddemus** [comment]
Only for `py27` jobs; let's set `needs_vc=True` for all py27 jobs then and see how it goes.

**Comment by blueyed** [comment]
Is it about this?  (with py34)
https://pytest-dev.visualstudio.com/pytest/_build/results?buildId=184&view=logs&jobId=da09038e-f80f-5420-29e7-671c9d7f49f7&taskId=865deaf7-28e4-5d09-6c76-a4d537014f58&lineStart=2235&lineEnd=2236&colStart=1&colEnd=1

**Comment by blueyed** [comment]
Doesn't use a wheel for twisted?!
https://pytest-dev.visualstudio.com/pytest/_build/results?buildId=184&view=logs&jobId=9b6e0447-f9a7-5447-6cd8-875bc46ca01d&taskId=97bc4e87-a60f-5a2a-9d57-eef0cb8494e0&lineStart=60&lineEnd=61&colStart=1&colEnd=1

**Comment by blueyed** [comment]
There are none: https://pypi.org/project/Twisted/#files
You've only meant numpy then probably.
So let's keel trial, but rename it?

**Comment by blueyed** [comment]
numpy does not work with pypy-xdist: https://travis-ci.org/pytest-dev/pytest/jobs/499340143

**Comment by blueyed** [comment]
Nice try.. ;)
Closing for now.

**Comment by nicoddemus** [comment]
Heh, OK, thanks anyway!

**Pull request closed without merging**
