### PR TITLE
deprecate the public internal PyCollector.makeitem method

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
… a underscore

### CODE REVIEW

**Comment by nicoddemus** [comment]
Fixed the linting error, after that environment passes it should be safe to merge it.

**Comment by nicoddemus** [comment]
LGTM @RonnyPfannschmidt, still WIP?

**Comment by RonnyPfannschmidt** [comment]
i wanted to get feedback on the deprecation first, then fix the details myself in an ammed ^^ - but more around monday

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus i rebased your fixes along the merge - i#ll add a mocked integration test for the method invocation

**Comment by nicoddemus** [comment]
Thanks @RonnyPfannschmidt

**Pull request merged**
