### PR TITLE
Fixed how files are opened in capture.py to be compatible on Windows

### PR DESCRIPTION
**Pull request by Ahris**
My build system, which uses Pytest, was running into a file IO error on Windows. Specifically: 
```
  File "C:\jenkins\workspace\PR+name\.venv\lib\site-packages\_pytest\capture.py", line 337, in write
    self.buffer.write(obj)
IOError: [Errno 0] Error
```
_fdopen on Windows requires an intervening fflush, fsetpos, fseek, or rewind operation when switching between reading and writing. See: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fdopen-wfdopen

This fix is to circumvent this requirement by using io.open() instead.

### CODE REVIEW

**Comment by nicoddemus** [comment]
Hi @Ahris, the `test_dupfile` test that is failing on both platforms and the check according to git blame seems to have been added by @blueyed in 0603d1d500c14a67715e486568b50f15b2086616. @blueyed perhaps you can chime in here?

**Comment by nicoddemus** [comment]
Closing by lack of follow up, will happily reopen if requested. 👍

**Comment by Ahris** [comment]
@nicoddemus Thanks for following up, haha. And for posterity, we worked around this issue on our end by using `-s` to not capture the output.

**Comment by nicoddemus** [comment]
OK @Ahris thanks for responding. 😁

**Comment by blueyed** [comment]
Maybe this could be made specific for Windows?  (since having to use -s seems to be a bad workaround)

The test failure (https://travis-ci.org/pytest-dev/pytest/jobs/339631681#L622) caused by my earlier commit/test could be fixed also then - not sure what it was about exactly though, without seeing how it looks without this PR.

**Comment by nicoddemus** [comment]
I'm hesitant because the change breaks a test which seems design to prevent the change in the first place:

```
_________________________________ test_dupfile _________________________________
tmpfile = <_io.BufferedRandom name='/tmp/pytest-of-travis/pytest-0/test_dupfile0/test_dupfile.py'>
    @needsosdup
    def test_dupfile(tmpfile):
        flist = []
        for i in range(5):
            nf = capture.safe_text_dupfile(tmpfile, "wb")
            assert nf != tmpfile
            assert nf.fileno() != tmpfile.fileno()
            assert nf not in flist
            print(i, end="", file=nf)
            flist.append(nf)
    
        fname_open = flist[0].name
        assert fname_open == repr(flist[0].buffer)
    
        for i in range(5):
            f = flist[i]
            f.close()
        fname_closed = flist[0].name
        assert fname_closed == repr(flist[0].buffer)
>       assert fname_closed != fname_open
E       AssertionError: assert '<_io.BufferedWriter name=11>' != '<_io.BufferedWriter name=11>'
```

I might be wrong though

**Pull request closed without merging**
