### PR TITLE
[WIP] cacheprovider: add --cache-readonly option

### PR DESCRIPTION
**Pull request by blueyed**
Based on https://github.com/pytest-dev/pytest/issues/5033

### CODE REVIEW

**Comment by nicoddemus** [comment]
I'm unsure if this is the correct approach for the use case mentioned in #5033; seems strange to disable the entire cache (which a lot of plugins might be using) if you want to disable `--lf`.

On the other hand, this seems like a useful option for other situations, for example when people try to write to read-only file systems: #1029. This is more elegant than disabling the entire `cacheprovider` plugin, because in that case you don't have the `config.cache` object anymore which might break other plugins which use the cache.

So 👍 to this.

**Comment by nicoddemus** [comment]
Besides tests and changelog, we should also add this to the documentation, both in `cache.rst` as an example and to `reference.rst`.

**Comment by RonnyPfannschmidt** [comment]
i believe this breaks the expectations of the system in strange ways,
i consier it a breaking api change as it changes cache writes, that may be followed by cache reads a noop that generate a "dirty/outdated read" situation

**Comment by blueyed** [comment]
ok, closing for now.

**Comment by blueyed** [comment]
For reference: this allows for setting it read-only internally with failures (0e33845).
This turned out to be useful in tests when there are other plugins installed (before I've disabled them for inner runs), since the number of warnings then differs.

**Pull request closed without merging**
