### PR TITLE
Fix dependencies on 'terminal' plugin

### LINKED ISSUE #5139: notify_exception crashes with -p no:terminal
e.g. run with `pytest -p no:terminal test.py` where test.py is
```python
raise Exception
```

### PR DESCRIPTION
**Pull request by ikonst**
Fix #5139

### CODE REVIEW

**Comment by blueyed** [comment]
Thanks for working on this!

I wonder what @RonnyPfannschmidt has to say about the terminal plugin options being coupled like that - shouldn't only the terminal part/plugin itself know about it in the best case?

**Comment by ikonst** [comment]
I agree this coupling is not optimal. I only corrected the code with the assumption that this coupling is a necessary evil for now.

**Comment by blueyed** [comment]
@ikonst 
That good, yeah - just wondered myself how to improve this in the future.

**Comment by blueyed** [comment]
Since this is green on CI now, please squash-merge it (it does not need 7 commits, and we have the squash-merge button disabled here).

**Comment by blueyed** [comment]
Thank you!

**Pull request merged**
